tagData.push({
  "group": "汉服 (Hanfu)",
  "categories": [
    {
      "name": "风格 (Style)",
      "tags": [
        { "zh": "日常汉服", "en": "daily Hanfu" },
        { "zh": "华丽汉服", "en": "luxurious Hanfu" },
        { "zh": "素雅汉服", "en": "elegant and simple Hanfu" },
        { "zh": "仙气飘逸", "en": "ethereal and flowing" },
        { "zh": "武侠风", "en": "wuxia style" },
        { "zh": "江湖侠客", "en": "wandering swordsman style" },
        { "zh": "书生雅士", "en": "scholar style" },
        { "zh": "闺阁仕女", "en": "boudoir maiden style" },
        { "zh": "端庄大气", "en": "dignified and grand" },
        { "zh": "小家碧玉", "en": "delicate and demure" },
        { "zh": "清新淡雅", "en": "fresh and subtle" },
        { "zh": "端庄古朴", "en": "solemn and ancient" },
        { "zh": "明艳活泼", "en": "bright and lively" },
        { "zh": "端丽典雅", "en": "graceful and elegant" },
        { "zh": "飘逸灵动", "en": "flowing and dynamic" },
        { "zh": "写实风格", "en": "realistic style" },
        { "zh": "唯美风格", "en": "aesthetic style" },
        { "zh": "国风新韵", "en": "new Chinese style charm" },
        { "zh": "传统复原", "en": "traditional restoration" },
        { "zh": "改良创新", "en": "modernized Hanfu" },
        { "zh": "艺术化", "en": "artistic" },
        { "zh": "写真风格", "en": "portraiture style" },
        { "zh": "写意", "en": "freehand style" },
        { "zh": "浪漫主义", "en": "romanticism" },
        { "zh": "唯美主义", "en": "aestheticism" },
        { "zh": "工笔画风", "en": "gongbi painting style" },
        { "zh": "水墨画风", "en": "ink wash painting style" },
        { "zh": "仙侠风", "en": "xianxia style" },
        { "zh": "鬼怪志异", "en": "supernatural/folklore style" },
        { "zh": "宫廷风", "en": "palace style" },
        { "zh": "朴素简约", "en": "plain and minimalist" },
        { "zh": "繁复奢靡", "en": "intricate and extravagant" }
      ]
    },
    {
      "name": "朝代 (Dynasty)",
      "tags": [
        { "zh": "先秦时期", "en": "Pre-Qin period" },
        { "zh": "秦汉时期", "en": "Qin-Han Dynasty" },
        { "zh": "魏晋时期", "en": "Wei-Jin Dynasties" },
        { "zh": "南北朝时期", "en": "Southern and Northern Dynasties" },
        { "zh": "隋朝", "en": "Sui Dynasty" },
        { "zh": "唐朝", "en": "Tang Dynasty" },
        { "zh": "盛唐", "en": "High Tang" },
        { "zh": "晚唐", "en": "Late Tang" },
        { "zh": "五代十国", "en": "Five Dynasties and Ten Kingdoms" },
        { "zh": "宋朝", "en": "Song Dynasty" },
        { "zh": "宋明过渡", "en": "Song-Ming Transition" },
        { "zh": "元朝 (民族融合)", "en": "Yuan Dynasty (Ethnic integration)" },
        { "zh": "明朝", "en": "Ming Dynasty" },
        { "zh": "明初", "en": "Early Ming" },
        { "zh": "明中", "en": "Mid Ming" },
        { "zh": "明末", "en": "Late Ming" },
        { "zh": "特定年代", "en": "specific historical era" },
        { "zh": "历史考据", "en": "historically accurate" },
        { "zh": "古代中国", "en": "ancient China" }
      ]
    },
    {
      "name": "型制 (Form/Structure)",
      "tags": [
        { "zh": "襦裙", "en": "Ruqun (blouse and skirt)" },
        { "zh": "齐胸襦裙", "en": "Qixiong Ruqun (high-waisted, chest-length)" },
        { "zh": "齐腰襦裙", "en": "Qiyao Ruqun (waist-height)" },
        { "zh": "高腰襦裙", "en": "Gaoyao Ruqun (high-waisted)" },
        { "zh": "深衣", "en": "Shenyi (deep garment, single piece)" },
        { "zh": "曲裾深衣", "en": "Quju Shenyi (curved hem, wrap-around)" },
        { "zh": "直裾深衣", "en": "Zhiju Shenyi (straight hem)" },
        { "zh": "袍", "en": "Pao (long robe)" },
        { "zh": "圆领袍", "en": "Yuanlingpao (round-collared robe)" },
        { "zh": "交领袍", "en": "Jiaolingpao (cross-collared robe)" },
        { "zh": "大袖衫", "en": "Daxiusn (large-sleeved loose outer robe)" },
        { "zh": "半臂", "en": "Banbi (half-arm jacket/blouse)" },
        { "zh": "褙子", "en": "Beizi (long jacket/vest with front split)" },
        { "zh": "比甲", "en": "Bijia (sleeveless jacket/vest)" },
        { "zh": "道袍", "en": "Daopao (Taoist style robe)" },
        { "zh": "直身", "en": "Zhishen (straight-cut robe)" },
        { "zh": "贴里", "en": "Tieli (fitted riding robe)" },
        { "zh": "曳撒", "en": "Yisa (longer riding robe with pleats)" },
        { "zh": "襦袄", "en": "Ruao (short jacket)" },
        { "zh": "袄裙", "en": "Aoqun (jacket and skirt)" },
        { "zh": "短褐", "en": "Duanhe (short coarse garment)" },
        { "zh": "窄袖袍", "en": "Zhaixiu Pao (narrow-sleeved robe)" },
        { "zh": "披风", "en": "Pifeng (cloak)" },
        { "zh": "斗篷", "en": "Doupeng (cape)" },
        { "zh": "马面裙", "en": "Mamianqun (horse-face skirt, pleated and planar front/back)" },
        { "zh": "打褶裙", "en": "pleated skirt" },
        { "zh": "裋褐", "en": "Shuhe (commoner's short coarse clothes)" },
        { "zh": "旋裙", "en": "Xuanqun (twirling skirt)" },
        { "zh": "交领右衽", "en": "Jiaoling Youren (cross-collar, right overlap)" },
        { "zh": "对襟", "en": "Duijin (parallel lapel/front opening)" },
        { "zh": "通袖", "en": "Tongxiu (sleeves connected to the side seams)" },
        { "zh": "琵琶襟", "en": "Pipa Jin (pipa-shaped opening)" },
        { "zh": "坦领", "en": "Tanling (U-shaped bare collar)" },
        { "zh": "坦胸", "en": "Tanxiong (exposed chest style)" },
        { "zh": "袒胸", "en": "Tanxiong (more formal term for exposed chest)" },
        { "zh": "襕衫", "en": "Lanshan (formal scholar's robe with horizontal stripe)" },
        { "zh": "帽", "en": "hat" },
        { "zh": "冠", "en": "crown/cap" },
        { "zh": "发簪", "en": "hairpin" },
        { "zh": "步摇", "en": "hair ornament with dangling parts" },
        { "zh": "发冠", "en": "hair crown" },
        { "zh": "发带", "en": "hair ribbon" },
        { "zh": "腰带", "en": "belt" },
        { "zh": "玉佩", "en": "jade pendant" },
        { "zh": "璎珞", "en": "traditional necklace/body ornament" },
        { "zh": "流苏", "en": "tassels" },
        { "zh": "绣花鞋", "en": "embroidered shoes" },
        { "zh": "木屐", "en": "wooden clogs" },
        { "zh": "团扇", "en": "round fan" },
        { "zh": "折扇", "en": "folding fan" },
        { "zh": "荷包", "en": "embroidered purse" },
        { "zh": "香囊", "en": "fragrant sachet" },
        { "zh": "佩剑", "en": "sword" },
        { "zh": "笛子", "en": "flute" },
        { "zh": "古琴", "en": "guqin (zither)" },
        { "zh": "琴棋书画", "en": "music, chess, calligraphy, painting" },
        { "zh": "头饰", "en": "headwear" },
        { "zh": "耳饰", "en": "earrings" },
        { "zh": "项饰", "en": "necklaces" },
        { "zh": "手镯", "en": "bracelets" },
        { "zh": "佩饰", "en": "pendants/ornaments" },
        { "zh": "环佩", "en": "jingling ornaments" }
      ]
    },
    {
      "name": "上衣 (Tops)",
      "tags": [
        { "zh": "襦", "en": "Ru (blouse)" },
        { "zh": "短襦", "en": "Duanru (short blouse)" },
        { "zh": "长襦", "en": "Changru (long blouse)" },
        { "zh": "衫", "en": "Shan (unlined shirt/blouse)" },
        { "zh": "袄", "en": "Ao (lined/padded jacket)" },
        { "zh": "诃子", "en": "Hezi (bodice, typically Tang style undergarment)" },
        { "zh": "交领衫", "en": "Jiaoling Shan (cross-collared shirt)" },
        { "zh": "圆领衫", "en": "Yuanling Shan (round-collared shirt)" },
        { "zh": "对襟衫", "en": "Duijin Shan (parallel-lapel shirt)" },
        { "zh": "褙子", "en": "Beizi (long, open-front jacket/vest)" },
        { "zh": "半臂", "en": "Banbi (half-sleeved top)" },
        { "zh": "披袄", "en": "Piao (outer jacket)" },
        { "zh": "主腰", "en": "Zhuyuan (bodice)" },
        { "zh": "内搭", "en": "inner top" },
        { "zh": "中衣", "en": "Zhongyi (middle layer garment)" },
        { "zh": "外衫", "en": "outer shirt" },
        { "zh": "罩衫", "en": "overshirt/cover-up" },
        { "zh": "比甲", "en": "Bijia (sleeveless vest/jacket)" },
        { "zh": "霞帔", "en": "Xiapei (formal cape/stole for noblewomen)" },
        { "zh": "抹胸/裹胸", "en": "Moxiong/Guoxiong (tube top/bodice)" },
        { "zh": "坦领上衣", "en": "Tanling Top (U-collar top)" },
        { "zh": "立领上衣", "en": "Liling Top (mandarin collar top)" },
        { "zh": "琵琶衫", "en": "Pipa Shan (pipa-shaped opening shirt)" },
        { "zh": "袄子", "en": "Aozi (jacket)" },
        { "zh": "汗衫", "en": "Hanshan (undershirt)" },
        { "zh": "短袄", "en": "Duan'ao (short jacket)" },
        { "zh": "长袄", "en": "Chang'ao (long jacket)" }
      ]
    },
    {
      "name": "裙子 (Skirts)",
      "tags": [
        { "zh": "裙", "en": "Qun (skirt)" },
        { "zh": "马面裙", "en": "Mamianqun (horse-face skirt)" },
        { "zh": "破裙", "en": "Poqun (segmented skirt)" },
        { "zh": "百褶裙", "en": "Baizhequn (hundred-pleat skirt)" },
        { "zh": "褶裙", "en": "Zhequn (pleated skirt)" },
        { "zh": "一片式直裙", "en": "Yipianshi Zhijun (single-piece straight skirt)" },
        { "zh": "间色裙", "en": "Jiansequn (multi-colored striped skirt)" },
        { "zh": "提花裙", "en": "jacquard skirt" },
        { "zh": "刺绣裙", "en": "embroidered skirt" },
        { "zh": "印花裙", "en": "printed skirt" },
        { "zh": "旋裙", "en": "Xuanqun (swirling dance skirt)" },
        { "zh": "凤尾裙", "en": "Fengwei Qu (phoenix tail skirt)" },
        { "zh": "散褶裙", "en": "Sanzhequn (random pleated skirt)" },
        { "zh": "褶裥裙", "en": "Zhejianqun (accordion pleated skirt)" },
        { "zh": "长裙", "en": "long skirt" },
        { "zh": "半裙", "en": "half skirt" },
        { "zh": "高腰裙", "en": "high-waisted skirt" },
        { "zh": "齐腰裙", "en": "waist-height skirt" },
        { "zh": "齐胸裙", "en": "chest-height skirt" },
        { "zh": "明制裙", "en": "Ming style skirt" },
        { "zh": "宋制裙", "en": "Song style skirt" },
        { "zh": "唐制裙", "en": "Tang style skirt" }
      ]
    },
    {
      "name": "领子 (Collar)",
      "tags": [
        { "zh": "交领", "en": "Jiaoling (cross collar)" },
        { "zh": "圆领", "en": "Yuanling (round collar)" },
        { "zh": "坦领", "en": "Tanling (U-shaped collar)" },
        { "zh": "对襟", "en": "Duijin (parallel lapel/front opening)" },
        { "zh": "立领", "en": "Liling (stand-up collar/mandarin collar)" },
        { "zh": "直领", "en": "Zhi Ling (straight collar)" },
        { "zh": "曲领", "en": "Qu Ling (curved collar)" },
        { "zh": "凤领", "en": "Fengling (phoenix shaped collar)" },
        { "zh": "方领", "en": "Fangling (square collar)" },
        { "zh": "琵琶领", "en": "Pipa Ling (pipa-shaped opening/collar)" },
        { "zh": "方交领", "en": "Fang Jiaoling (square cross collar)" },
        { "zh": "大襟", "en": "Dajin (large front overlap)" },
        { "zh": "小襟", "en": "Xiaojin (small front overlap)" },
        { "zh": "翻领", "en": "lapel/turn-down collar" },
        { "zh": "无领", "en": "collarless" },
        { "zh": "系带", "en": "tie-front" }
      ]
    },
    {
      "name": "袖子 (Sleeve)",
      "tags": [
        { "zh": "广袖", "en": "Guangxiu (wide sleeve)" },
        { "zh": "大袖", "en": "Daxiu (oversized sleeve)" },
        { "zh": "窄袖", "en": "Zhaixiu (narrow sleeve)" },
        { "zh": "琵琶袖", "en": "Pipa Sleeve (pipa-shaped sleeve)" },
        { "zh": "直袖", "en": "Zhixiu (straight sleeve)" },
        { "zh": "箭袖", "en": "Jianxiu (arrow sleeve/fitted cuff)" },
        { "zh": "收袖", "en": "Shouxiu (cuffed sleeve)" },
        { "zh": "水袖", "en": "Shuixiu (water sleeve, long flowing for opera)" },
        { "zh": "半臂袖", "en": "Banbixiu (half-arm sleeve)" },
        { "zh": "短袖", "en": "short sleeve" },
        { "zh": "中袖", "en": "medium sleeve" },
        { "zh": "长袖", "en": "long sleeve" },
        { "zh": "无袖", "en": "sleeveless" },
        { "zh": "连袖", "en": "continuous sleeve" },
        { "zh": "灯笼袖", "en": "lantern sleeve" },
        { "zh": "泡泡袖", "en": "puff sleeve" },
        { "zh": "云肩袖", "en": "cloud shoulder sleeve" },
        { "zh": "宽大袖口", "en": "wide cuff" },
        { "zh": "束口", "en": "elasticized cuff" },
        { "zh": "破袖", "en": "segmented sleeve" },
        { "zh": "接袖", "en": "joined sleeve (multisectional)" }
      ]
    },
    {
      "name": "材质 (Material)",
      "tags": [
        { "zh": "丝绸", "en": "silk" },
        { "zh": "缎面", "en": "satin" },
        { "zh": "真丝", "en": "real silk" },
        { "zh": "素绉缎", "en": "crepe satin" },
        { "zh": "重磅真丝", "en": "heavy silk" },
        { "zh": "雪纺", "en": "chiffon" },
        { "zh": "乔其纱", "en": "georgette" },
        { "zh": "纱", "en": "sheer/gauze" },
        { "zh": "绡", "en": "raw silk gauze" },
        { "zh": "绫", "en": "gauze silk" },
        { "zh": "罗", "en": "luo silk (open-weave silk)" },
        { "zh": "锦", "en": "brocade" },
        { "zh": "织金", "en": "gold-woven" },
        { "zh": "妆花", "en": "Zhuanghua (elaborate tapestry satin)" },
        { "zh": "缂丝", "en": "Kesi (silk tapestry)" },
        { "zh": "棉", "en": "cotton" },
        { "zh": "麻", "en": "linen" },
        { "zh": "苎麻", "en": "ramie" },
        { "zh": "棉麻混纺", "en": "cotton-linen blend" },
        { "zh": "涤纶", "en": "polyester" },
        { "zh": "人造丝", "en": "rayon" },
        { "zh": "混纺", "en": "blend" },
        { "zh": "天丝", "en": "Tencel" },
        { "zh": "雪纺印花", "en": "printed chiffon" },
        { "zh": "提花棉", "en": "jacquard cotton" },
        { "zh": "肌理感面料", "en": "textured fabric" },
        { "zh": "刺绣工艺", "en": "embroidery craftsmanship" },
        { "zh": "机绣", "en": "machine embroidery" },
        { "zh": "手绣", "en": "hand embroidery" },
        { "zh": "盘金绣", "en": "couching embroidery with gold thread" },
        { "zh": "珠绣", "en": "bead embroidery" },
        { "zh": "亮片", "en": "sequins" },
        { "zh": "印花", "en": "printed pattern" },
        { "zh": "烫金", "en": "hot stamping" },
        { "zh": "手绘", "en": "hand-painted" },
        { "zh": "染色", "en": "dyed" },
        { "zh": "扎染", "en": "tie-dye" },
        { "zh": "苏绣", "en": "Suzhou embroidery" },
        { "zh": "湘绣", "en": "Hunan embroidery" },
        { "zh": "蜀绣", "en": "Sichuan embroidery" },
        { "zh": "粤绣", "en": "Guangdong embroidery" },
        { "zh": "绒面", "en": "velvet" },
        { "zh": "磨毛", "en": "brushed fabric" },
        { "zh": "轻薄", "en": "lightweight" },
        { "zh": "透气", "en": "breathable" },
        { "zh": "垂坠感", "en": "draping effect" },
        { "zh": "有光泽", "en": "lustrous" },
        { "zh": "哑光", "en": "matte" }
      ]
    },
    {
      "name": "颜色 (Color)",
      "tags": [
        { "zh": "红色", "en": "red" },
        { "zh": "正红", "en": "true red" },
        { "zh": "绯红", "en": "scarlet" },
        { "zh": "绛红", "en": "deep red" },
        { "zh": "朱红", "en": "vermilion" },
        { "zh": "妃色", "en": "rosy pinkish-red" },
        { "zh": "粉色", "en": "pink" },
        { "zh": "藕色", "en": "lotus root pink (muted pink-beige)" },
        { "zh": "橙色", "en": "orange" },
        { "zh": "橘黄", "en": "orangey yellow" },
        { "zh": "黄色", "en": "yellow" },
        { "zh": "鹅黄", "en": "goose yellow (pale yellow)" },
        { "zh": "明黄", "en": "bright yellow" },
        { "zh": "缃色", "en": "light yellow (often with green tint)" },
        { "zh": "绿色", "en": "green" },
        { "zh": "翠绿", "en": "emerald green" },
        { "zh": "墨绿", "en": "dark green" },
        { "zh": "湖蓝", "en": "lake blue" },
        { "zh": "蓝色", "en": "blue" },
        { "zh": "天蓝", "en": "sky blue" },
        { "zh": "宝蓝", "en": "royal blue" },
        { "zh": "靛蓝", "en": "indigo" },
        { "zh": "石青", "en": "stone blue (deep blue-green)" },
        { "zh": "紫色", "en": "purple" },
        { "zh": "藕荷色", "en": "light purplish-pink" },
        { "zh": "玄色", "en": "mysterious black (often with dark undertones)" },
        { "zh": "黑色", "en": "black" },
        { "zh": "白色", "en": "white" },
        { "zh": "月白", "en": "moon white (bluish-white)" },
        { "zh": "米色", "en": "beige" },
        { "zh": "灰色", "en": "grey" },
        { "zh": "黛色", "en": "dark grey/indigo_tinged black" },
        { "zh": "棕色", "en": "brown" },
        { "zh": "咖啡色", "en": "coffee brown" },
        { "zh": "金色", "en": "gold" },
        { "zh": "银色", "en": "silver" },
        { "zh": "青色", "en": "cyan/azure (broad term for blue-green)" },
        { "zh": "淡色系", "en": "light color palette" },
        { "zh": "暖色系", "en": "warm color palette" },
        { "zh": "冷色系", "en": "cool color palette" },
        { "zh": "莫兰迪色", "en": "Morandi colors (muted, earthy tones)" },
        { "zh": "纯色", "en": "solid color" },
        { "zh": "拼色", "en": "color block" },
        { "zh": "渐变色", "en": "gradient color" },
        { "zh": "撞色", "en": "contrasting colors" },
        { "zh": "多色", "en": "multi-color" },
        { "zh": "传统色谱", "en": "traditional Chinese color spectrum" },
        { "zh": "雅致色调", "en": "elegant color tones" },
        { "zh": "鲜艳", "en": "vibrant" },
        { "zh": "沉稳", "en": "subdued" },
        { "zh": "通透", "en": "translucent" },
        { "zh": "光泽", "en": "lustrous" }
      ]
    },
    {
      "name": "图案/纹样 (Patterns/Motifs)",
      "tags": [
        { "zh": "刺绣图案", "en": "embroidered patterns" },
        { "zh": "仙鹤纹", "en": "crane motif" },
        { "zh": "凤凰纹", "en": "phoenix motif" },
        { "zh": "龙纹", "en": "dragon motif" },
        { "zh": "祥云纹", "en": "auspicious cloud motif" },
        { "zh": "花卉纹", "en": "floral patterns" },
        { "zh": "牡丹", "en": "peony" },
        { "zh": "莲花", "en": "lotus" },
        { "zh": "梅花", "en": "plum blossom" },
        { "zh": "竹纹", "en": "bamboo motif" },
        { "zh": "几何纹", "en": "geometric patterns" },
        { "zh": "回字纹", "en": "key fret pattern" },
        { "zh": "团窠纹", "en": "roundel motif" },
        { "zh": "海水江崖纹", "en": "sea waves and cliffs motif" },
        { "zh": "飞鱼纹", "en": "flying fish motif" },
        { "zh": "麒麟纹", "en": "qilin motif" },
        { "zh": "蝙蝠纹", "en": "bat motif (for good fortune)" },
        { "zh": "暗纹", "en": "hidden/subtle pattern" },
        { "zh": "明纹", "en": "visible pattern" },
        { "zh": "提花纹样", "en": "jacquard pattern" },
        { "zh": "织锦纹样", "en": "brocade pattern" },
        { "zh": "山水画", "en": "landscape painting (motif)" },
        { "zh": "亭台楼阁", "en": "pavilions and towers motif" },
        { "zh": "人物故事", "en": "figure/story scenes" },
        { "zh": "动物纹", "en": "animal motifs" },
        { "zh": "植物纹", "en": "plant motifs" },
        { "zh": "八宝纹", "en": "Eight Treasures motif" },
        { "zh": "福寿纹", "en": "longevity and good fortune motif" },
        { "zh": "流云纹", "en": "flowing cloud pattern" },
        { "zh": "如意纹", "en": "ruyi scepter pattern" },
        { "zh": "卷草纹", "en": "scrollwork/foliate pattern" },
        { "zh": "锦鲤纹", "en": "koi fish pattern" },
        { "zh": "鱼纹", "en": "fish pattern" },
        { "zh": "蝶纹", "en": "butterfly pattern" },
        { "zh": "喜鹊纹", "en": "magpie pattern" },
        { "zh": "花鸟纹", "en": "flowers and birds pattern" },
        { "zh": "几何抽象", "en": "geometric abstraction" }
      ]
    },
    {
      "name": "场合 (Occasion)",
      "tags": [
        { "zh": "日常穿着", "en": "daily wear" },
        { "zh": "节日盛装", "en": "festival attire" },
        { "zh": "婚礼服", "en": "wedding attire" },
        { "zh": "成人礼", "en": "coming-of-age ceremony" },
        { "zh": "毕业典礼", "en": "graduation ceremony" },
        { "zh": "文化活动", "en": "cultural event" },
        { "zh": "摄影", "en": "photography" },
        { "zh": "影视剧", "en": "film and television drama" },
        { "zh": "舞台表演", "en": "stage performance" },
        { "zh": "茶艺", "en": "tea ceremony" },
        { "zh": "游园", "en": "garden stroll" },
        { "zh": "祭祀", "en": "sacrificial ceremony" },
        { "zh": "宴会", "en": "banquet" },
        { "zh": "雅集", "en": "literary gathering" },
        { "zh": "休闲场合", "en": "casual occasion" },
        { "zh": "正式场合", "en": "formal occasion" },
        { "zh": "户外活动", "en": "outdoor activity" },
        { "zh": "室内场景", "en": "indoor scene" }
      ]
    }
  ]
});