tagData.push({
  "group": "游戏设计 (Game Design)",
  "categories": [
    {
      "name": "游戏风格 (Game Style)",
      "tags": [
        // 游戏类型 (Genres)
        { "zh": "角色扮演游戏 (RPG)", "en": "Role-Playing Game (RPG)" },
        { "zh": "动作角色扮演游戏 (ARPG)", "en": "Action RPG (ARPG)" },
        { "zh": "大型多人在线角色扮演游戏 (MMORPG)", "en": "Massively Multiplayer Online RPG (MMORPG)" },
        { "zh": "第一人称射击 (FPS)", "en": "First-Person Shooter (FPS)" },
        { "zh": "第三人称射击 (TPS)", "en": "Third-Person Shooter (TPS)" },
        { "zh": "即时战略 (RTS)", "en": "Real-Time Strategy (RTS)" },
        { "zh": "回合制策略 (TBS)", "en": "Turn-Based Strategy (TBS)" },
        { "zh": "多人在线战术竞技 (MOBA)", "en": "Multiplayer Online Battle Arena (MOBA)" },
        { "zh": "冒险游戏", "en": "Adventure Game" },
        { "zh": "图形冒险", "en": "Point-and-Click Adventure" },
        { "zh": "平台游戏", "en": "Platformer" },
        { "zh": "格斗游戏", "en": "Fighting Game" },
        { "zh": "赛车游戏", "en": "Racing Game" },
        { "zh": "体育游戏", "en": "Sports Game" },
        { "zh": "模拟游戏", "en": "Simulation Game" },
        { "zh": "经营模拟", "en": "Management Simulation" },
        { "zh": "城市建设模拟", "en": "City-Building Simulation" },
        { "zh": "飞行模拟", "en": "Flight Simulation" },
        { "zh": "生活模拟", "en": "Life Simulation" },
        { "zh": "生存游戏", "en": "Survival Game" },
        { "zh": "恐怖游戏", "en": "Horror Game" },
        { "zh": "心理恐怖", "en": "Psychological Horror" },
        { "zh": "潜行游戏", "en": "Stealth Game" },
        { "zh": "节奏游戏", "en": "Rhythm Game" },
        { "zh": "卡牌对战游戏", "en": "Card Battle Game" },
        { "zh": "集换式卡牌游戏 (TCG)", "en": "Trading Card Game (TCG)" },
        { "zh": "数字卡牌游戏 (DCG)", "en": "Digital Card Game (DCG)" },
        { "zh": "益智游戏", "en": "Puzzle Game" },
        { "zh": "解谜游戏", "en": "Puzzle-Solving Game" },
        { "zh": "三消游戏", "en": "Match-3 Game" },
        { "zh": "文字冒险", "en": "Visual Novel" },
        { "zh": "互动小说", "en": "Interactive Fiction" },
        { "zh": "沙盒游戏", "en": "Sandbox Game" },
        { "zh": "建造游戏", "en": "Building Game" },
        { "zh": "开放世界", "en": "Open World" },
        { "zh": "Roguelike", "en": "Roguelike" },
        { "zh": "Roguelite", "en": "Roguelite" },
        { "zh": "银河战士恶魔城 (Metroidvania)", "en": "Metroidvania" },
        { "zh": "派对游戏", "en": "Party Game" },
        { "zh": "街机游戏", "en": "Arcade Game" },
        { "zh": "放置游戏", "en": "Idle Game / Clicker Game" },
        { "zh": "抽卡游戏 (Gacha Game)", "en": "Gacha Game" },
        { "zh": "虚拟现实 (VR)", "en": "Virtual Reality (VR) Game" },
        { "zh": "增强现实 (AR)", "en": "Augmented Reality (AR) Game" },
        { "zh": "独立游戏", "en": "Indie Game" },
        { "zh": "教育游戏", "en": "Educational Game" },
        { "zh": "健康游戏", "en": "Exergaming" },
        { "zh": "桌游改编", "en": "Board Game Adaptation" },
        { "zh": "非对称对抗", "en": "Asymmetric Multiplayer" },
        { "zh": "大逃杀", "en": "Battle Royale" },
        { "zh": "塔防", "en": "Tower Defense" },
        { "zh": "自动战斗", "en": "Auto Battler" },
        { "zh": "弹幕射击", "en": "Bullet Hell" },
        { "zh": "清版射击", "en": "Shoot 'em up" },
        { "zh": "跑酷游戏", "en": "Runner Game" },
        { "zh": "点击游戏", "en": "Clicker Game" },
        { "zh": "社交模拟", "en": "Social Simulation" },
        { "zh": "侦探推理", "en": "Detective / Deduction" },
        { "zh": "音乐游戏", "en": "Music Game" },
        { "zh": "烹饪游戏", "en": "Cooking Game" },
        { "zh": "乙女游戏", "en": "Otome Game" },
        { "zh": "女性向游戏", "en": "Otome / Joseimuke" },
        { "zh": "生存恐怖", "en": "Survival Horror" },
        { "zh": "叙事驱动", "en": "Narrative-driven" },
        { "zh": "互动电影", "en": "Interactive Movie" },

        // 艺术风格 (Art Styles)
        { "zh": "像素艺术", "en": "Pixel Art" },
        { "zh": "低多边形", "en": "Low Poly" },
        { "zh": "体素艺术", "en": "Voxel Art" },
        { "zh": "卡通风格", "en": "Cartoon Style" },
        { "zh": "动漫风格", "en": "Anime Style" },
        { "zh": "赛璐珞渲染", "en": "Cel-Shaded" },
        { "zh": "写实风格", "en": "Realistic Style" },
        { "zh": "超写实风格", "en": "Hyperrealistic Style" },
        { "zh": "风格化", "en": "Stylized" },
        { "zh": "手绘风格", "en": "Hand-drawn Style" },
        { "zh": "水彩风格", "en": "Watercolor Style" },
        { "zh": "油画风格", "en": "Oil Painting Style" },
        { "zh": "剪影风格", "en": "Silhouette Style" },
        { "zh": "漫画风格", "en": "Comic Book Style" },
        { "zh": "未来主义", "en": "Futuristic" },
        { "zh": "赛博朋克", "en": "Cyberpunk" },
        { "zh": "蒸汽朋克", "en": "Steampunk" },
        { "zh": "黑暗幻想", "en": "Dark Fantasy" },
        { "zh": "奇幻", "en": "Fantasy" },
        { "zh": "科幻", "en": "Sci-Fi" },
        { "zh": "历史题材", "en": "Historical Theme" },
        { "zh": "抽象", "en": "Abstract" },
        { "zh": "极简主义", "en": "Minimalist" },
        { "zh": "立体主义", "en": "Cubism" },
        { "zh": "巴洛克", "en": "Baroque" },
        { "zh": "哥特式", "en": "Gothic" },
        { "zh": "废土风格", "en": "Post-Apocalyptic Style" },
        { "zh": "复古", "en": "Retro" },
        { "zh": "街机复古", "en": "Arcade Retro" },
        { "zh": "Chibi", "en": "Chibi / Q-version" },
        { "zh": "可爱风格", "en": "Cute Style" },
        { "zh": "黑暗风格", "en": "Grimdark" },
        { "zh": "恐怖风格", "en": "Horror Style" },
        { "zh": "童话风格", "en": "Fairy Tale Style" },
        { "zh": "解构主义", "en": "Deconstructivism" },
        { "zh": "噪点美学", "en": "Glitch Art" },
        { "zh": "赛博哥特", "en": "Cybergothic" },
        { "zh": "普普艺术", "en": "Pop Art" },
        { "zh": "蒸汽波", "en": "Vaporwave" },
        { "zh": "故障艺术", "en": "Glitch Art" },
        { "zh": "国风", "en": "Chinese Style" },
        { "zh": "日式", "en": "Japanese Style" },
        { "zh": "韩式", "en": "Korean Style" },
        { "zh": "欧美", "en": "Western Style" },
        { "zh": "黑白", "en": "Black and White" },
        { "zh": "灰度", "en": "Grayscale" },
        { "zh": "高饱和度", "en": "High Saturation" },
        { "zh": "低饱和度", "en": "Low Saturation" },
        { "zh": "霓虹灯效", "en": "Neon Effect" },
        { "zh": "发光效果", "en": "Glow Effect" },
        { "zh": "粒子效果", "en": "Particle Effect" },
        { "zh": "布娃娃物理", "en": "Ragdoll Physics" },
        { "zh": "程序生成", "en": "Procedural Generation" },
        { "zh": "破坏性环境", "en": "Destructible Environments" },
        { "zh": "实时光线追踪", "en": "Real-time Ray Tracing" },
        { "zh": "物理渲染 (PBR)", "en": "Physically Based Rendering (PBR)" },
        { "zh": "非真实感渲染 (NPR)", "en": "Non-Photorealistic Rendering (NPR)" },
        { "zh": "镜头光晕", "en": "Lens Flare" },
        { "zh": "体积光", "en": "Volumetric Lighting" },
        { "zh": "环境光遮蔽", "en": "Ambient Occlusion" },
        { "zh": "景深", "en": "Depth of Field" },
        { "zh": "动态模糊", "en": "Motion Blur" },
        { "zh": "屏幕空间反射", "en": "Screen Space Reflection" },
        { "zh": "高动态范围 (HDR)", "en": "High Dynamic Range (HDR)" },
        { "zh": "全局光照", "en": "Global Illumination" },
        { "zh": "卡通阴影", "en": "Toon Shading" },
        { "zh": "边缘检测", "en": "Edge Detection" },
        { "zh": "图像着色器", "en": "Image Shaders" },
        { "zh": "后处理效果", "en": "Post-processing Effects" },
        { "zh": "粒子系统", "en": "Particle System" },
        { "zh": "视觉特效 (VFX)", "en": "Visual Effects (VFX)" },
        { "zh": "光栅化渲染", "en": "Rasterization" },
        { "zh": "路径追踪", "en": "Path Tracing" },
        { "zh": "卡通三维", "en": "Cartoon 3D" },
        { "zh": "概念艺术风格", "en": "Concept Art Style" },
        { "zh": "涂鸦风格", "en": "Graffiti Style" },
        { "zh": "极简画面", "en": "Minimalist Visuals" },
        { "zh": "超现实主义", "en": "Surrealism" },
        { "zh": "梦幻感", "en": "Dreamlike Atmosphere" },
        { "zh": "蒸汽波", "en": "Vaporwave" }
      ]
    },
    {
      "name": "职业划分 (Class/Profession)",
      "tags": [
        // 战斗职业 (Combat Classes)
        { "zh": "战士", "en": "Warrior" },
        { "zh": "骑士", "en": "Knight" },
        { "zh": "圣骑士", "en": "Paladin" },
        { "zh": "野蛮人", "en": "Barbarian" },
        { "zh": "斗士", "en": "Fighter" },
        { "zh": "武僧", "en": "Monk" },
        { "zh": "潜行者/盗贼", "en": "Rogue/Thief" },
        { "zh": "刺客", "en": "Assassin" },
        { "zh": "弓箭手", "en": "Archer" },
        { "zh": "猎人", "en": "Hunter" },
        { "zh": "游侠", "en": "Ranger" },
        { "zh": "法师", "en": "Mage" },
        { "zh": "巫师", "en": "Wizard" },
        { "zh": "术士", "en": "Warlock" },
        { "zh": "亡灵法师", "en": "Necromancer" },
        { "zh": "牧师", "en": "Priest" },
        { "zh": "神官", "en": "Cleric" },
        { "zh": "德鲁伊", "en": "Druid" },
        { "zh": "萨满", "en": "Shaman" },
        { "zh": "吟游诗人", "en": "Bard" },
        { "zh": "召唤师", "en": "Summoner" },
        { "zh": "枪手", "en": "Gunslinger" },
        { "zh": "工程师", "en": "Engineer" },
        { "zh": "狙击手", "en": "Sniper" },
        { "zh": "狂战士", "en": "Berserker" },
        { "zh": "守护者", "en": "Guardian" },
        { "zh": "冠军", "en": "Champion" },
        { "zh": "剑士", "en": "Blademaster" },
        { "zh": "魔剑士", "en": "Spellblade" },
        { "zh": "黑暗骑士", "en": "Dark Knight" },
        { "zh": "元素师", "en": "Elementalist" },
        { "zh": "驭兽师", "en": "Beastmaster" },
        { "zh": "流浪者", "en": "Vagrant" },
        { "zh": "角斗士", "en": "Gladiator" },
        { "zh": "圣武士", "en": "Crusader" },
        { "zh": "死灵法师", "en": "Lich" },
        { "zh": "诡术师", "en": "Trickster" },
        { "zh": "魔枪手", "en": "Arcane Gunner" },
        { "zh": "符文大师", "en": "Rune Master" },
        { "zh": "驭龙者", "en": "Dragon Tamer" },
        { "zh": "时间法师", "en": "Time Mage" },
        { "zh": "空间法师", "en": "Spatial Mage" },
        { "zh": "血法师", "en": "Blood Mage" },
        { "zh": "影舞者", "en": "Shadow Dancer" },
        { "zh": "武术家", "en": "Martial Artist" },
        { "zh": "突击兵", "en": "Commando" },
        { "zh": "爆破专家", "en": "Demolitionist" },
        { "zh": "重装机兵", "en": "Heavy Mech Pilot" },
        { "zh": "异能者", "en": "Psion" },
        { "zh": "改造人", "en": "Cyborg" },
        { "zh": "仿生人", "en": "Android" },
        { "zh": "克隆人", "en": "Clone" },
        { "zh": "生物兵器", "en": "Bio-weapon" },
        { "zh": "机械师", "en": "Mechanic" },
        { "zh": "黑客", "en": "Hacker" },
        { "zh": "赏金猎人", "en": "Bounty Hunter" },
        { "zh": "星际探险家", "en": "Stellar Explorer" },

        // 辅助/支援职业 (Support/Utility Classes)
        { "zh": "坦克", "en": "Tank" },
        { "zh": "治疗者", "en": "Healer" },
        { "zh": "辅助", "en": "Support" },
        { "zh": "加成者 (提供增益)", "en": "Buffer" },
        { "zh": "削弱者 (提供减益)", "en": "Debuffer" },
        { "zh": "控制者", "en": "Controller" },
        { "zh": "探路者", "en": "Pathfinder" },
        { "zh": "外交官", "en": "Diplomat" },
        { "zh": "学者", "en": "Scholar" },
        { "zh": "医护兵", "en": "Medic" },
        { "zh": "科学家", "en": "Scientist" },
        { "zh": "指挥官", "en": "Commander" },
        { "zh": "侦察兵", "en": "Scout" },
        { "zh": "信使", "en": "Messenger" },
        { "zh": "探险家", "en": "Explorer" },
        { "zh": "考古学家", "en": "Archaeologist" },
        { "zh": "商人", "en": "Merchant" },
        { "zh": "船长", "en": "Captain" },
        { "zh": "管理者", "en": "Administrator" },
        { "zh": "工匠", "en": "Crafter" },
        { "zh": "采集者", "en": "Gatherer" },
        { "zh": "炼金术士", "en": "Alchemist" },
        { "zh": "附魔师", "en": "Enchanter" },
        { "zh": "厨师", "en": "Cook" },
        { "zh": "矿工", "en": "Miner" },
        { "zh": "伐木工", "en": "Lumberjack" },
        { "zh": "农民", "en": "Farmer" },
        { "zh": "铁匠", "en": "Blacksmith" },
        { "zh": "裁缝", "en": "Tailor" },
        { "zh": "珠宝匠", "en": "Jeweler" },
        { "zh": "铭文师", "en": "Scribe" },
        { "zh": "制革师", "en": "Leatherworker" },
        { "zh": "渔夫", "en": "Fisherman" },
        { "zh": "园丁", "en": "Gardener" },
        { "zh": "建筑师", "en": "Architect" },
        { "zh": "训练师", "en": "Trainer" },
        { "zh": "驯兽师", "en": "Tamer" },

        // 复合职业 (Hybrid Classes)
        { "zh": "战斗法师", "en": "Battlemage" },
        { "zh": "影牧师", "en": "Shadow Priest" },
        { "zh": "魔武双修", "en": "Spellsword" },
        { "zh": "黑暗德鲁伊", "en": "Dark Druid" },
        { "zh": "秘术师", "en": "Arcanist" },
        { "zh": "掠夺者", "en": "Marauder" },
        { "zh": "恶魔猎手", "en": "Demon Hunter" },
        { "zh": "奥术弓箭手", "en": "Arcane Archer" },
        { "zh": "圣武士", "en": "Inquisitor" },
        { "zh": "瘟疫医生", "en": "Plague Doctor" },
        { "zh": "炼狱医师", "en": "Infernal Physician" },
        { "zh": "虚空使徒", "en": "Void Apostle" },
        { "zh": "混沌术士", "en": "Chaos Warlock" }
      ]
    },
    {
      "name": "角色设定 (Character Setting)",
      "tags": [
        // 种族 (Races)
        { "zh": "人类", "en": "Human" },
        { "zh": "精灵", "en": "Elf" },
        { "zh": "高等精灵", "en": "High Elf" },
        { "zh": "暗夜精灵", "en": "Night Elf" },
        { "zh": "血精灵", "en": "Blood Elf" },
        { "zh": "矮人", "en": "Dwarf" },
        { "zh": "侏儒", "en": "Gnome" },
        { "zh": "兽人", "en": "Orc" },
        { "zh": "地精", "en": "Goblin" },
        { "zh": "巨魔", "en": "Troll" },
        { "zh": "亡灵/不死族", "en": "Undead/Zombie" },
        { "zh": "牛头人", "en": "Tauren" },
        { "zh": "狼人", "en": "Werewolf" },
        { "zh": "狐人", "en": "Vulpera" },
        { "zh": "龙人", "en": "Dragonborn" },
        { "zh": "天使", "en": "Angel" },
        { "zh": "恶魔", "en": "Demon" },
        { "zh": "吸血鬼", "en": "Vampire" },
        { "zh": "狼人", "en": "Lycan" },
        { "zh": "巨人", "en": "Giant" },
        { "zh": "半兽人", "en": "Half-Orc" },
        { "zh": "半精灵", "en": "Half-Elf" },
        { "zh": "半身人/霍比特人", "en": "Halfling/Hobbit" },
        { "zh": "人鱼", "en": "Merfolk" },
        { "zh": "蜥蜴人", "en": "Lizardfolk" },
        { "zh": "蜘蛛人", "en": "Arachnid" },
        { "zh": "晶石人", "en": "Crystal Golem" },
        { "zh": "机器人", "en": "Robot" },
        { "zh": "仿生人", "en": "Android" },
        { "zh": "改造人", "en": "Cyborg" },
        { "zh": "外星人", "en": "Alien" },
        { "zh": "猫人", "en": "Catfolk/Khajiit" },
        { "zh": "兔子人", "en": "Rabbitfolk" },
        { "zh": "鸟人", "en": "Aarakocra" },
        { "zh": "树人/树怪", "en": "Treant" },
        { "zh": "元素体", "en": "Elemental" },
        { "zh": "魔像", "en": "Golem" },
        { "zh": "幽灵", "en": "Ghost" },
        { "zh": "妖精", "en": "Fairy" },
        { "zh": "哥布林", "en": "Goblin" },
        { "zh": "食人魔", "en": "Ogre" },
        { "zh": "独眼巨人", "en": "Cyclops" },
        { "zh": "美杜莎", "en": "Medusa" },
        { "zh": "斯芬克斯", "en": "Sphinx" },
        { "zh": "魅魔", "en": "Succubus" },
        { "zh": "梦魇", "en": "Incubus" },
        { "zh": "虚空生物", "en": "Void Creature" },

        // 性别 (Gender)
        { "zh": "男性角色", "en": "Male Character" },
        { "zh": "女性角色", "en": "Female Character" },
        { "zh": "中性角色", "en": "Androgynous Character" },
        { "zh": "非二元性别", "en": "Non-binary Character" },

        // 年龄/体型 (Age/Body Type)
        { "zh": "幼年角色", "en": "Child Character" },
        { "zh": "少年角色", "en": "Teen Character" },
        { "zh": "青年角色", "en": "Young Adult Character" },
        { "zh": "中年角色", "en": "Middle-aged Character" },
        { "zh": "老年角色", "en": "Elderly Character" },
        { "zh": "健壮体型", "en": "Muscular Body Type" },
        { "zh": "纤细体型", "en": "Slender Body Type" },
        { "zh": "丰腴体型", "en": "Curvy Body Type" },
        { "zh": "高大", "en": "Tall" },
        { "zh": "矮小", "en": "Short" },
        { "zh": "超重", "en": "Overweight" },
        { "zh": "骨瘦如柴", "en": "Skeletal" },

        // 职业/身份 (Occupation/Identity)
        { "zh": "英雄", "en": "Hero" },
        { "zh": "反派", "en": "Villain" },
        { "zh": "主角", "en": "Protagonist" },
        { "zh": "配角", "en": "Sidekick" },
        { "zh": "非玩家角色 (NPC)", "en": "Non-Player Character (NPC)" },
        { "zh": "国王/女王", "en": "King/Queen" },
        { "zh": "王子/公主", "en": "Prince/Princess" },
        { "zh": "贵族", "en": "Noble" },
        { "zh": "士兵", "en": "Soldier" },
        { "zh": "平民", "en": "Commoner" },
        { "zh": "学者", "en": "Scholar" },
        { "zh": "艺术家", "en": "Artist" },
        { "zh": "商人", "en": "Merchant" },
        { "zh": "探险家", "en": "Explorer" },
        { "zh": "科学家", "en": "Scientist" },
        { "zh": "罪犯", "en": "Criminal" },
        { "zh": "雇佣兵", "en": "Mercenary" },
        { "zh": "警察", "en": "Police Officer" },
        { "zh": "医生", "en": "Doctor" },
        { "zh": "老师", "en": "Teacher" },
        { "zh": "学生", "en": "Student" },
        { "zh": "运动员", "en": "Athlete" },
        { "zh": "明星", "en": "Celebrity" },
        { "zh": "偶像", "en": "Idol" },
        { "zh": "厨师", "en": "Chef" },
        { "zh": "农民", "en": "Farmer" },
        { "zh": "渔夫", "en": "Fisherman" },
        { "zh": "矿工", "en": "Miner" },
        { "zh": "工人", "en": "Worker" },
        { "zh": "管理者", "en": "Administrator" },
        { "zh": "研究员", "en": "Researcher" },
        { "zh": "间谍", "en": "Spy" },
        { "zh": "特工", "en": "Agent" },
        { "zh": "政治家", "en": "Politician" },
        { "zh": "宗教领袖", "en": "Religious Leader" },
        { "zh": "异教徒", "en": "Heretic" },
        { "zh": "流浪者", "en": "Vagabond" },
        { "zh": "奴隶", "en": "Slave" },
        { "zh": "叛军", "en": "Rebel" },
        { "zh": "革命者", "en": "Revolutionary" },
        { "zh": "古代人", "en": "Ancient Civilization Member" },
        { "zh": "中世纪人", "en": "Medieval Person" },
        { "zh": "未来人", "en": "Future Human" },
        { "zh": "赛博格", "en": "Cyborg" },
        { "zh": "改造人", "en": "Augmented Human" },
        { "zh": "克隆人", "en": "Clone" },

        // 人物特征 (Character Traits)
        { "zh": "勇敢", "en": "Brave" },
        { "zh": "胆怯", "en": "Cowardly" },
        { "zh": "善良", "en": "Kind" },
        { "zh": "邪恶", "en": "Evil" },
        { "zh": "狡猾", "en": "Cunning" },
        { "zh": "忠诚", "en": "Loyal" },
        { "zh": "背叛", "en": "Treacherous" },
        { "zh": "聪明", "en": "Intelligent" },
        { "zh": "愚蠢", "en": "Foolish" },
        { "zh": "乐观", "en": "Optimistic" },
        { "zh": "悲观", "en": "Pessimistic" },
        { "zh": "自信", "en": "Confident" },
        { "zh": "自卑", "en": "Insecure" },
        { "zh": "冲动", "en": "Impulsive" },
        { "zh": "冷静", "en": "Calm" },
        { "zh": "残忍", "en": "Cruel" },
        { "zh": "仁慈", "en": "Merciful" },
        { "zh": "神秘", "en": "Mysterious" },
        { "zh": "健谈", "en": "Talkative" },
        { "zh": "沉默寡言", "en": "Quiet" },
        { "zh": "自大", "en": "Arrogant" },
        { "zh": "谦逊", "en": "Humble" },
        { "zh": "幽默", "en": "Humorous" },
        { "zh": "严肃", "en": "Serious" },
        { "zh": "疯狂", "en": "Insane" },
        { "zh": "理智", "en": "Sane" },
        { "zh": "好奇", "en": "Curious" },
        { "zh": "厌世", "en": "World-weary" },
        { "zh": "天真", "en": "Naive" },
        { "zh": "世故", "en": "Sophisticated" },
        { "zh": "精神错乱", "en": "Deranged" },
        { "zh": "痴迷", "en": "Obsessive" },
        { "zh": "自我牺牲", "en": "Self-sacrificing" },
        { "zh": "复仇者", "en": "Avenger" },
        { "zh": "守护者", "en": "Guardian" },
        { "zh": "殉道者", "en": "Martyr" },
        { "zh": "苦行僧", "en": "Ascetic" },
        { "zh": "享乐主义者", "en": "Hedonist" },
        { "zh": "实用主义者", "en": "Pragmatist" },
        { "zh": "浪漫主义者", "en": "Romanticist" },
        { "zh": "理想主义者", "en": "Idealist" },
        { "zh": "虚无主义者", "en": "Nihilist" },
        { "zh": "实用型", "en": "Pragmatic" },
        { "zh": "梦想家", "en": "Dreamer" },
        { "zh": "悲剧英雄", "en": "Tragic Hero" },
        { "zh": "反英雄", "en": "Anti-Hero" },
        { "zh": "智谋型", "en": "Tactician" },

        // 核心设定 (Core Settings)
        { "zh": "背景故事丰富", "en": "Rich Backstory" },
        { "zh": "多种结局", "en": "Multiple Endings" },
        { "zh": "善恶选择", "en": "Good/Evil Choices" },
        { "zh": "阵营选择", "en": "Faction Choices" },
        { "zh": "道德系统", "en": "Morality System" },
        { "zh": "声望系统", "en": "Reputation System" },
        { "zh": "羁绊系统", "en": "Bond/Relationship System" },
        { "zh": "可定制", "en": "Customizable" },
        { "zh": "深度角色发展", "en": "Deep Character Development" },
        { "zh": "角色弧光", "en": "Character Arc" },
        { "zh": "家族/血统系统", "en": "Family/Lineage System" },
        { "zh": "人格分裂", "en": "Multiple Personalities" },
        { "zh": "失忆症", "en": "Amnesia" },
        { "zh": "秘密身份", "en": "Secret Identity" },
        { "zh": "双面间谍", "en": "Double Agent" },
        { "zh": "卧底", "en": "Undercover" },
        { "zh": "被诅咒的", "en": "Cursed" },
        { "zh": "被附身的", "en": "Possessed" },
        { "zh": "超能力", "en": "Superpowers" },
        { "zh": "魔法能力", "en": "Magical Abilities" },
        { "zh": "科技增强", "en": "Technologically Enhanced" },
        { "zh": "独特技能树", "en": "Unique Skill Tree" },
        { "zh": "技能组合", "en": "Skill Synergy" },
        { "zh": "弱点", "en": "Weaknesses" }
      ]
    },
    {
      "name": "特色服装 (Characteristic Costume)",
      "tags": [
        // 部位 (Parts)
        { "zh": "头盔", "en": "Helmet" },
        { "zh": "头饰", "en": "Headpiece" },
        { "zh": "发饰", "en": "Hair Accessory" },
        { "zh": "面具", "en": "Mask" },
        { "zh": "护肩", "en": "Shoulder Pads" },
        { "zh": "胸甲", "en": "Breastplate" },
        { "zh": "轻甲", "en": "Light Armor" },
        { "zh": "重甲", "en": "Heavy Armor" },
        { "zh": "布甲", "en": "Cloth Armor" },
        { "zh": "皮甲", "en": "Leather Armor" },
        { "zh": "外套", "en": "Coat" },
        { "zh": "斗篷", "en": "Cloak" },
        { "zh": "披风", "en": "Cape" },
        { "zh": "长袍", "en": "Robe" },
        { "zh": "上衣", "en": "Top" },
        { "zh": "衬衫", "en": "Shirt" },
        { "zh": "连衣裙", "en": "Dress" },
        { "zh": "裙子", "en": "Skirt" },
        { "zh": "裤子", "en": "Pants" },
        { "zh": "短裤", "en": "Shorts" },
        { "zh": "手套", "en": "Gloves" },
        { "zh": "护腕", "en": "Bracers" },
        { "zh": "腰带", "en": "Belt" },
        { "zh": "靴子", "en": "Boots" },
        { "zh": "鞋子", "en": "Shoes" },
        { "zh": "护腿", "en": "Greaves" },
        { "zh": "盾牌", "en": "Shield (as part of outfit)" },
        { "zh": "翅膀装饰", "en": "Wing Decoration" },
        { "zh": "尾巴装饰", "en": "Tail Decoration" },

        // 风格 (Styles)
        { "zh": "奇幻盔甲", "en": "Fantasy Armor" },
        { "zh": "科幻防护服", "en": "Sci-Fi Suit" },
        { "zh": "哥特式服装", "en": "Gothic Attire" },
        { "zh": "蒸汽朋克服饰", "en": "Steampunk Outfit" },
        { "zh": "赛博朋克服饰", "en": "Cyberpunk Attire" },
        { "zh": "和服", "en": "Kimono" },
        { "zh": "旗袍", "en": "Qipao" },
        { "zh": "欧洲中世纪服装", "en": "Medieval European Garb" },
        { "zh": "维多利亚时代服装", "en": "Victorian Era Clothing" },
        { "zh": "现代休闲装", "en": "Modern Casual Wear" },
        { "zh": "军装", "en": "Military Uniform" },
        { "zh": "制服", "en": "Uniform" },
        { "zh": "校服", "en": "School Uniform" },
        { "zh": "运动服", "en": "Sportswear" },
        { "zh": "泳装", "en": "Swimsuit" },
        { "zh": "礼服", "en": "Formal Wear" },
        { "zh": "晚礼服", "en": "Evening Gown" },
        { "zh": "燕尾服", "en": "Tuxedo" },
        { "zh": "民族服装", "en": "Ethnic Costume" },
        { "zh": "传统服饰", "en": "Traditional Dress" },
        { "zh": "睡衣", "en": "Pajamas" },
        { "zh": "内衣", "en": "Underwear" },
        { "zh": "朋克服饰", "en": "Punk Outfit" },
        { "zh": "摇滚服饰", "en": "Rock Outfit" },
        { "zh": "机车服", "en": "Biker Gear" },
        { "zh": "宇航服", "en": "Spacesuit" },
        { "zh": "潜水服", "en": "Diving Suit" },
        { "zh": "斗殴服装", "en": "Brawling Attire" },
        { "zh": "魔法师长袍", "en": "Mage Robes" },
        { "zh": "牧师长袍", "en": "Cleric Robes" },
        { "zh": "游侠服装", "en": "Ranger Outfit" },
        { "zh": "刺客服装", "en": "Assassin's Creed Style" },
        { "zh": "超人服", "en": "Superhero Suit" },
        { "zh": "反派制服", "en": "Villain Uniform" },
        { "zh": "战斗服", "en": "Combat Suit" },
        { "zh": "侦探大衣", "en": "Detective Coat" },
        { "zh": "牛仔装", "en": "Cowboy Outfit" },
        { "zh": "海盗装", "en": "Pirate Attire" },
        { "zh": "忍者服", "en": "Ninja Outfit" },
        { "zh": "武士甲", "en": "Samurai Armor" },
        { "zh": "武者服", "en": "Martial Arts Uniform" },
        { "zh": "神官服", "en": "Divine Robes" },
        { "zh": "猎装", "en": "Hunting Gear" },
        { "zh": "农民装", "en": "Farmer's Clothes" },
        { "zh": "王室服装", "en": "Royal Attire" },
        { "zh": "侍者/女仆装", "en": "Butler/Maid Outfit" },
        { "zh": "厨师装", "en": "Chef's Uniform" },
        { "zh": "赛车服", "en": "Racing Suit" },
        { "zh": "特工西装", "en": "Agent Suit" },
        { "zh": "法庭长袍", "en": "Court Robe" },
        { "zh": "防护服", "en": "Protective Suit" },
        { "zh": "实验室制服", "en": "Lab Coat" },
        { "zh": "囚犯服", "en": "Prison Uniform" },
        { "zh": "乞丐装", "en": "Rags" },
        { "zh": "婚纱", "en": "Wedding Dress" },
        { "zh": "浴袍", "en": "Bathrobe" },
        { "zh": "沙滩装", "en": "Beachwear" },
        { "zh": "睡裙", "en": "Nightgown" },
        { "zh": "比基尼", "en": "Bikini" },
        { "zh": "死库水", "en": "School Swimsuit" },
        { "zh": "猫女郎服饰", "en": "Catgirl Outfit" },
        { "zh": "兔女郎服饰", "en": "Bunny Suit" },
        { "zh": "女仆装", "en": "Maid Outfit" },
        { "zh": "水手服", "en": "Sailor Uniform" },
        { "zh": "啦啦队服", "en": "Cheerleader Uniform" },
        { "zh": "圣诞老人套装", "en": "Santa Claus Outfit" },
        { "zh": "万圣节服装", "en": "Halloween Costume" },
        { "zh": "破烂的服装", "en": "Tattered Clothing" },
        { "zh": "光鲜亮丽的服装", "en": "Pristine Clothing" },
        { "zh": "沾满泥土的服装", "en": "Mud-stained Clothing" },
        { "zh": "定制服装", "en": "Customized Outfit" },
        { "zh": "隐藏式服装", "en": "Concealing Outfit" },
        { "zh": "炫耀式服装", "en": "Showy Outfit" },
        { "zh": "透明服装", "en": "Transparent Outfit" },
        { "zh": "发光服装", "en": "Glowing Outfit" },
        { "zh": "紧身衣", "en": "Bodysuit" },
        { "zh": "开胸衣", "en": "Keyhole Top" },
        { "zh": "露背装", "en": "Backless Dress" },
        { "zh": "高开衩裙", "en": "High-slit Skirt" },
        { "zh": "露脐装", "en": "Crop Top" },
        { "zh": "皮革服装", "en": "Leather Attire" },
        { "zh": "丝绸服装", "en": "Silk Clothing" },
        { "zh": "棉质服装", "en": "Cotton Clothing" },
        { "zh": "毛皮服装", "en": "Fur Clothing" }
      ]
    },
    {
      "name": "人物装饰 (Character Accessories)",
      "tags": [
        // 头部 (Head)
        { "zh": "发带", "en": "Headband" },
        { "zh": "发夹", "en": "Hair Clip" },
        { "zh": "发圈", "en": "Hair Tie" },
        { "zh": "发箍", "en": "Hairband" },
        { "zh": "皇冠", "en": "Crown" },
        { "zh": "王冠", "en": "Tiara" },
        { "zh": "羽毛头饰", "en": "Feather Headpiece" },
        { "zh": "角饰", "en": "Horn Decoration" },
        { "zh": "耳环", "en": "Earrings" },
        { "zh": "耳夹", "en": "Ear Cuffs" },
        { "zh": "眼镜", "en": "Glasses" },
        { "zh": "墨镜", "en": "Sunglasses" },
        { "zh": "单片镜", "en": "Monocle" },
        { "zh": "眼罩", "en": "Eye Patch" },
        { "zh": "围巾", "en": "Scarf" },
        { "zh": "项链", "en": "Necklace" },
        { "zh": "项圈", "en": "Choker" },
        { "zh": "领结", "en": "Bow Tie" },
        { "zh": "领带", "en": "Tie" },

        // 身体 (Body)
        { "zh": "胸针", "en": "Brooch" },
        { "zh": "徽章", "en": "Badge" },
        { "zh": "臂章", "en": "Armband" },
        { "zh": "手镯", "en": "Bracelet" },
        { "zh": "手表", "en": "Watch" },
        { "zh": "戒指", "en": "Ring" },
        { "zh": "手链", "en": "Charm Bracelet" },
        { "zh": "纹身", "en": "Tattoo" },
        { "zh": "身体彩绘", "en": "Body Paint" },
        { "zh": "绷带", "en": "Bandages" },
        { "zh": "绷带缠绕", "en": "Wrapped in Bandages" },
        { "zh": "绷带固定", "en": "Bandage Secured" },
        { "zh": "披肩", "en": "Shawl" },
        { "zh": "围裙", "en": "Apron" },
        { "zh": "肩章", "en": "Epaulets" },
        { "zh": "吊袜带", "en": "Garter" },
        { "zh": "腰包", "en": "Fanny Pack" },
        { "zh": "腰链", "en": "Waist Chain" },
        { "zh": "链条装饰", "en": "Chain Decoration" },
        { "zh": "绳索装饰", "en": "Rope Decoration" },
        { "zh": "皮带", "en": "Leather Strap" },
        { "zh": "铆钉", "en": "Studs/Rivets" },
        { "zh": "扣子", "en": "Buckle" },
        { "zh": "徽章", "en": "Emblem" },

        // 其他 (Other)
        { "zh": "背包", "en": "Backpack" },
        { "zh": "挎包", "en": "Shoulder Bag" },
        { "zh": "手提包", "en": "Handbag" },
        { "zh": "钱包", "en": "Wallet" },
        { "zh": "钥匙串", "en": "Keychain" },
        { "zh": "护目镜", "en": "Goggles" },
        { "zh": "口罩", "en": "Face Mask" },
        { "zh": "面巾", "en": "Bandana" },
        { "zh": "臂铠", "en": "Gauntlet" },
        { "zh": "护膝", "en": "Knee Pads" },
        { "zh": "帽子", "en": "Hat" },
        { "zh": "头巾", "en": "Headscarf" },
        { "zh": "手帕", "en": "Handkerchief" },
        { "zh": "徽章", "en": "Insignia" },
        { "zh": "缎带", "en": "Ribbon" },
        { "zh": "铃铛", "en": "Bell" },
        { "zh": "丝带", "en": "Sash" },
        { "zh": "面纱", "en": "Veil" },
        { "zh": "袖章", "en": "Armband" },
        { "zh": "腿环", "en": "Leg Ring" },
        { "zh": "腿带", "en": "Thigh Harness" },
        { "zh": "纹身贴片", "en": "Temporary Tattoo" },
        { "zh": "伤疤", "en": "Scar" },
        { "zh": "眼线", "en": "Eyeliner" },
        { "zh": "口红", "en": "Lipstick" },
        { "zh": "美甲", "en": "Manicure" },
        { "zh": "穿刺", "en": "Piercings" },
        { "zh": "特殊隐形眼镜", "en": "Special Contact Lenses" },
        { "zh": "发色挑染", "en": "Hair Streaks" },
        { "zh": "假发", "en": "Wig" },
        { "zh": "美瞳", "en": "Colored Contacts" },
        { "zh": "假肢", "en": "Prosthetics" },
        { "zh": "机械义肢", "en": "Mechanical Prosthetics" },
        { "zh": "发簪", "en": "Hairpin (Chinese Style)" },
        { "zh": "折扇", "en": "Folding Fan" },
        { "zh": "烟斗", "en": "Pipe" },
        { "zh": "雪茄", "en": "Cigar" },
        { "zh": "香烟", "en": "Cigarette" },
        { "zh": "耳机", "en": "Headphones" },
        { "zh": "蓝牙耳机", "en": "Bluetooth Earpiece" },
        { "zh": "智能手表", "en": "Smartwatch" },
        { "zh": "全息投影", "en": "Holographic Projector" },
        { "zh": "机械手臂", "en": "Mechanical Arm" },
        { "zh": "机械腿", "en": "Mechanical Leg" },
        { "zh": "夜视仪", "en": "Night Vision Goggles" },
        { "zh": "通讯设备", "en": "Communication Device" },
        { "zh": "手持终端", "en": "Handheld Device" },
        { "zh": "无人机", "en": "Drone (companion)" },
        { "zh": "宠物伴侣", "en": "Pet Companion" },
        { "zh": "魔法符文", "en": "Magic Runes (on body)" },
        { "zh": "发光纹身", "en": "Glowing Tattoos" },
        { "zh": "神经接口", "en": "Neural Interface" },
        { "zh": "面部植入物", "en": "Facial Implants" },
        { "zh": "耳机麦克风", "en": "Headset Microphone" },
        { "zh": "可穿戴设备", "en": "Wearable Device" },
        { "zh": "赛博朋克植入物", "en": "Cyberpunk Implants" },
        { "zh": "数据线", "en": "Data Cable (integrated)" },
        { "zh": "发光带", "en": "LED Strips (on outfit)" },
        { "zh": "能量核心", "en": "Energy Core (visible)" },
        { "zh": "能量管", "en": "Energy Conduits" },
        { "zh": "机械骨骼", "en": "Exoskeleton" },
        { "zh": "生物发光", "en": "Bioluminescence" }
      ]
    },
    {
      "name": "游戏装备 (Game Equipment)",
      "tags": [
        // 武器 (Weapons)
        { "zh": "单手剑", "en": "One-handed Sword" },
        { "zh": "双手剑", "en": "Two-handed Sword" },
        { "zh": "匕首", "en": "Dagger" },
        { "zh": "长剑", "en": "Longsword" },
        { "zh": "短剑", "en": "Short Sword" },
        { "zh": "弯刀", "en": "Scimitar" },
        { "zh": "武士刀", "en": "Katana" },
        { "zh": "大刀", "en": "Greatsword" },
        { "zh": "斧头", "en": "Axe" },
        { "zh": "战斧", "en": "Battle Axe" },
        { "zh": "锤子", "en": "Hammer" },
        { "zh": "战锤", "en": "Warhammer" },
        { "zh": "法杖", "en": "Staff" },
        { "zh": "魔杖", "en": "Wand" },
        { "zh": "弓", "en": "Bow" },
        { "zh": "十字弓", "en": "Crossbow" },
        { "zh": "火枪", "en": "Musket" },
        { "zh": "手枪", "en": "Pistol" },
        { "zh": "步枪", "en": "Rifle" },
        { "zh": "冲锋枪", "en": "Submachine Gun (SMG)" },
        { "zh": "霰弹枪", "en": "Shotgun" },
        { "zh": "狙击步枪", "en": "Sniper Rifle" },
        { "zh": "机关枪", "en": "Machine Gun" },
        { "zh": "榴弹发射器", "en": "Grenade Launcher" },
        { "zh": "火箭发射器", "en": "Rocket Launcher" },
        { "zh": "激光枪", "en": "Laser Gun" },
        { "zh": "能量武器", "en": "Energy Weapon" },
        { "zh": "光剑", "en": "Lightsaber" },
        { "zh": "霰弹枪", "en": "Blaster" },
        { "zh": "近战武器", "en": "Melee Weapon" },
        { "zh": "远程武器", "en": "Ranged Weapon" },
        { "zh": "魔法武器", "en": "Magic Weapon" },
        { "zh": "科技武器", "en": "Tech Weapon" },
        { "zh": "矛", "en": "Spear" },
        { "zh": "长柄武器", "en": "Polearm" },
        { "zh": "戟", "en": "Halberd" },
        { "zh": "镰刀", "en": "Scythe" },
        { "zh": "拳套", "en": "Gauntlets" },
        { "zh": "爪刃", "en": "Claw Weapon" },
        { "zh": "链锤", "en": "Flail" },
        { "zh": "弹弓", "en": "Slingshot" },
        { "zh": "飞刀", "en": "Throwing Knife" },
        { "zh": "飞镖", "en": "Dart/Shuriken" },
        { "zh": "手榴弹", "en": "Grenade" },
        { "zh": "炸弹", "en": "Bomb" },
        { "zh": "C4炸弹", "en": "C4 Explosive" },
        { "zh": "地雷", "en": "Mine" },
        { "zh": "粘性炸弹", "en": "Sticky Bomb" },
        { "zh": "毒药瓶", "en": "Poison Vial" },
        { "zh": "烟雾弹", "en": "Smoke Grenade" },
        { "zh": "闪光弹", "en": "Flashbang" },
        { "zh": "燃烧瓶", "en": "Molotov Cocktail" },
        { "zh": "回旋镖", "en": "Boomerang" },
        { "zh": "鞭子", "en": "Whip" },
        { "zh": "盾牌", "en": "Shield" },
        { "zh": "塔盾", "en": "Tower Shield" },
        { "zh": "圆盾", "en": "Round Shield" },
        { "zh": "臂盾", "en": "Buckler" },
        { "zh": "魔法书", "en": "Spellbook" },
        { "zh": "圣物", "en": "Relic" },
        { "zh": "符文", "en": "Rune" },
        { "zh": "法器", "en": "Arcane Focus" },
        { "zh": "图腾", "en": "Totem" },
        { "zh": "乐器 (武器)", "en": "Musical Instrument (weapon)" },
        { "zh": "手术刀 (武器)", "en": "Scalpel (weapon)" },
        { "zh": "注射器 (武器)", "en": "Syringe (weapon)" },
        { "zh": "电锯", "en": "Chainsaw" },
        { "zh": "钻头", "en": "Drill" },
        { "zh": "激光切割机", "en": "Laser Cutter" },
        { "zh": "电击枪", "en": "Taser" },
        { "zh": "声波武器", "en": "Sonic Weapon" },
        { "zh": "生物武器", "en": "Bio-Weapon" },
        { "zh": "异形武器", "en": "Alien Weapon" },
        { "zh": "混沌武器", "en": "Chaos Weapon" },
        { "zh": "光明武器", "en": "Holy Weapon" },
        { "zh": "诅咒武器", "en": "Cursed Weapon" },
        { "zh": "传奇武器", "en": "Legendary Weapon" },
        { "zh": "史诗武器", "en": "Epic Weapon" },
        { "zh": "神话武器", "en": "Mythic Weapon" },
        { "zh": "独特武器", "en": "Unique Weapon" },
        { "zh": "稀有武器", "en": "Rare Weapon" },
        { "zh": "普通武器", "en": "Common Weapon" },
        { "zh": "消耗品武器", "en": "Consumable Weapon" },
        { "zh": "改装武器", "en": "Modified Weapon" },
        { "zh": "战术手电", "en": "Tactical Flashlight (weapon attachment)" },
        { "zh": "瞄准镜", "en": "Scope" },
        { "zh": "消音器", "en": "Silencer" },
        { "zh": "枪口制退器", "en": "Muzzle Brake" },
        { "zh": "加长弹匣", "en": "Extended Magazine" },
        { "zh": "握把", "en": "Grip" },
        { "zh": "枪托", "en": "Stock" },
        { "zh": "镭射瞄准", "en": "Laser Sight" },
        { "zh": "皮卡汀尼导轨", "en": "Picatinny Rail" },
        { "zh": "模块化武器", "en": "Modular Weapon" },
        { "zh": "可变形武器", "en": "Transforming Weapon" },
        { "zh": "生物附生武器", "en": "Bio-attached Weapon" },
        { "zh": "魔法符文雕刻", "en": "Magic Rune Engravings" },
        { "zh": "会说话的武器", "en": "Sentient Weapon" },
        { "zh": "武器外观", "en": "Weapon Skin" },
        { "zh": "武器特效", "en": "Weapon Effects" },
        { "zh": "附魔", "en": "Enchantment" },
        { "zh": "宝石镶嵌", "en": "Gem Inlay" },

        // 物品 (Items)
        { "zh": "血瓶", "en": "Health Potion" },
        { "zh": "蓝瓶", "en": "Mana Potion" },
        { "zh": "药水", "en": "Potion" },
        { "zh": "卷轴", "en": "Scroll" },
        { "zh": "炸药", "en": "Dynamite" },
        { "zh": "解毒剂", "en": "Antidote" },
        { "zh": "兴奋剂", "en": "Stimpack" },
        { "zh": "急救包", "en": "Medkit" },
        { "zh": "工具箱", "en": "Toolbox" },
        { "zh": "钥匙", "en": "Key" },
        { "zh": "地图", "en": "Map" },
        { "zh": "指南针", "en": "Compass" },
        { "zh": "手电筒", "en": "Flashlight" },
        { "zh": "打火机", "en": "Lighter" },
        { "zh": "绳索", "en": "Rope" },
        { "zh": "钩爪", "en": "Grappling Hook" },
        { "zh": "照明棒", "en": "Flare Stick" },
        { "zh": "陷阱", "en": "Trap" },
        { "zh": "诱饵", "en": "Lure" },
        { "zh": "信号弹", "en": "Signal Flare" },
        { "zh": "食物", "en": "Food" },
        { "zh": "水", "en": "Water" },
        { "zh": "治疗物品", "en": "Healing Item" },
        { "zh": "增益物品", "en": "Buff Item" },
        { "zh": "任务物品", "en": "Quest Item" },
        { "zh": "收藏品", "en": "Collectible" },
        { "zh": "生产材料", "en": "Crafting Material" },
        { "zh": "金币", "en": "Gold Coin" },
        { "zh": "珠宝", "en": "Jewel" },
        { "zh": "宝箱", "en": "Treasure Chest" },
        { "zh": "钱袋", "en": "Pouch of Coins" },
        { "zh": "装备箱", "en": "Equipment Crate" },
        { "zh": "弹药", "en": "Ammunition" },
        { "zh": "箭矢", "en": "Arrow" },
        { "zh": "魔法符文", "en": "Magic Runes (item)" },
        { "zh": "祭品", "en": "Sacrificial Offering" },
        { "zh": "宠物蛋", "en": "Pet Egg" },
        { "zh": "坐骑召唤物", "en": "Mount Summon Item" },
        { "zh": "传送卷轴", "en": "Teleport Scroll" },
        { "zh": "召唤符文", "en": "Summoning Rune" },
        { "zh": "回城卷轴", "en": "Town Portal Scroll" },
        { "zh": "复活卷轴", "en": "Resurrection Scroll" },
        { "zh": "技能书", "en": "Skill Book" },
        { "zh": "改造组件", "en": "Mod Component" },
        { "zh": "升级材料", "en": "Upgrade Material" },
        { "zh": "附魔材料", "en": "Enchanting Material" },
        { "zh": "合成配方", "en": "Crafting Recipe" },
        { "zh": "古董", "en": "Artifact" },
        { "zh": "圣物", "en": "Relic" },
        { "zh": "遗物", "en": "Heirloom" },
        { "zh": "情报文件", "en": "Intelligence Document" },
        { "zh": "数据芯片", "en": "Data Chip" },
        { "zh": "黑匣子", "en": "Black Box" },
        { "zh": "解密物品", "en": "Decryption Item" },

        // 交通工具/载具 (Vehicles/Mounts)
        { "zh": "马匹", "en": "Horse" },
        { "zh": "龙", "en": "Dragon (Mount)" },
        { "zh": "飞行坐骑", "en": "Flying Mount" },
        { "zh": "陆地坐骑", "en": "Land Mount" },
        { "zh": "海上坐骑", "en": "Sea Mount" },
        { "zh": "汽车", "en": "Car" },
        { "zh": "轿车", "en": "Sedan" },
        { "zh": "跑车", "en": "Sports Car" },
        { "zh": "越野车", "en": "Off-road Vehicle" },
        { "zh": "摩托车", "en": "Motorcycle" },
        { "zh": "自行车", "en": "Bicycle" },
        { "zh": "卡车", "en": "Truck" },
        { "zh": "坦克", "en": "Tank (Vehicle)" },
        { "zh": "机甲", "en": "Mech" },
        { "zh": "飞行器", "en": "Aircraft" },
        { "zh": "无人机", "en": "Drone (Vehicle)" },
        { "zh": "飞船", "en": "Spaceship" },
        { "zh": "星际飞船", "en": "Starship" },
        { "zh": "潜艇", "en": "Submarine" },
        { "zh": "船", "en": "Boat" },
        { "zh": "帆船", "en": "Sailboat" },
        { "zh": "快艇", "en": "Speedboat" },
        { "zh": "直升机", "en": "Helicopter" },
        { "zh": "喷气背包", "en": "Jetpack" },
        { "zh": "悬浮板", "en": "Hoverboard" },
        { "zh": "滑翔翼", "en": "Glider" },
        { "zh": "轨道车", "en": "Railcar" },
        { "zh": "蒸汽机车", "en": "Steam Locomotive" },
        { "zh": "武装载具", "en": "Armed Vehicle" },
        { "zh": "侦察载具", "en": "Recon Vehicle" },
        { "zh": "运输载具", "en": "Transport Vehicle" },
        { "zh": "定制载具", "en": "Customized Vehicle" },
        { "zh": "可升级载具", "en": "Upgradeable Vehicle" },
        { "zh": "破坏性载具", "en": "Destructible Vehicle" },
        { "zh": "赛车", "en": "Race Car" },
        { "zh": "未来载具", "en": "Futuristic Vehicle" },
        { "zh": "概念载具", "en": "Concept Vehicle" },
        { "zh": "生物载具", "en": "Organic Vehicle" }
      ]
    },
    {
      "name": "游戏特效 (Game Effects)",
      "tags": [
        // 视觉特效 (Visual Effects)
        { "zh": "爆炸效果", "en": "Explosion Effect" },
        { "zh": "火焰效果", "en": "Fire Effect" },
        { "zh": "冰霜效果", "en": "Ice Effect" },
        { "zh": "水波纹效果", "en": "Water Ripple Effect" },
        { "zh": "闪电效果", "en": "Lightning Effect" },
        { "zh": "烟雾效果", "en": "Smoke Effect" },
        { "zh": "灰尘效果", "en": "Dust Effect" },
        { "zh": "血液飞溅", "en": "Blood Splatter" },
        { "zh": "粒子飞溅", "en": "Particle Spray" },
        { "zh": "破碎效果", "en": "Shatter Effect" },
        { "zh": "溶解效果", "en": "Dissolve Effect" },
        { "zh": "扭曲效果", "en": "Distortion Effect" },
        { "zh": "传送效果", "en": "Teleportation Effect" },
        { "zh": "生成效果", "en": "Spawn Effect" },
        { "zh": "眩光", "en": "Glow" },
        { "zh": "发光", "en": "Luminescence" },
        { "zh": "辉光", "en": "Bloom" },
        { "zh": "闪烁", "en": "Flicker" },
        { "zh": "残影", "en": "Afterimage" },
        { "zh": "慢动作", "en": "Slow Motion" },
        { "zh": "时间扭曲", "en": "Time Distortion" },
        { "zh": "能量护盾", "en": "Energy Shield" },
        { "zh": "魔法阵", "en": "Magic Circle" },
        { "zh": "魔法光束", "en": "Magic Beam" },
        { "zh": "冲击波", "en": "Shockwave" },
        { "zh": "电光火石", "en": "Arcing Electricity" },
        { "zh": "环境特效", "en": "Environmental Effects" },
        { "zh": "天气特效", "en": "Weather Effects" },
        { "zh": "水墨特效", "en": "Ink Wash Effect" },
        { "zh": "程式化特效", "en": "Stylized Effect" },
        { "zh": "写实特效", "en": "Realistic Effect" },
        { "zh": "卡通特效", "en": "Cartoon Effect" },
        { "zh": "粒子系统", "en": "Particle System" },
        { "zh": "UV动画", "en": "UV Animation" },
        { "zh": "顶点动画", "en": "Vertex Animation" },
        { "zh": "着色器特效", "en": "Shader Effects" },
        { "zh": "屏幕着色器", "en": "Screen Shaders" },
        { "zh": "全屏特效", "en": "Full Screen Effects" },
        { "zh": "径向模糊", "en": "Radial Blur" },
        { "zh": "画面震动", "en": "Camera Shake" },
        { "zh": "屏幕滤镜", "en": "Screen Filter" },
        { "zh": "边缘发光", "en": "Edge Glow" },
        { "zh": "能量场", "en": "Force Field" },
        { "zh": "治疗光效", "en": "Healing Light Effect" },
        { "zh": "中毒光效", "en": "Poison Effect" },
        { "zh": "灼烧效果", "en": "Burning Effect" },
        { "zh": "冰冻效果", "en": "Freezing Effect" },
        { "zh": "石化效果", "en": "Petrification Effect" },
        { "zh": "魅惑效果", "en": "Charm Effect" },
        { "zh": "沉默效果", "en": "Silence Effect" },
        { "zh": "击飞效果", "en": "Knockback Effect" },
        { "zh": "击倒效果", "en": "Knockdown Effect" },
        { "zh": "浮空效果", "en": "Launch Effect" },
        { "zh": "流血效果", "en": "Bleeding Effect" },
        { "zh": "破甲效果", "en": "Armor Break Effect" },
        { "zh": "增益光环", "en": "Buff Aura" },
        { "zh": "减益光环", "en": "Debuff Aura" },
        { "zh": "等级提升特效", "en": "Level Up Effect" },
        { "zh": "拾取物品特效", "en": "Item Pickup Effect" },
        { "zh": "死亡特效", "en": "Death Effect" },
        { "zh": "复活特效", "en": "Resurrection Effect" },
        { "zh": "暴击特效", "en": "Critical Hit Effect" },
        { "zh": "格挡特效", "en": "Block Effect" },
        { "zh": "闪避特效", "en": "Dodge Effect" },
        { "zh": "技能衔接特效", "en": "Skill Chain Effect" },
        { "zh": "法术施法特效", "en": "Spell Cast Effect" },
        { "zh": "弹道视觉", "en": "Projectile Trail" },
        { "zh": "挥砍痕迹", "en": "Slash Marks" },
        { "zh": "激光轨迹", "en": "Laser Trace" },
        { "zh": "能量冲击", "en": "Energy Burst" },
        { "zh": "灵魂出窍", "en": "Soul Separation" },
        { "zh": "虚影", "en": "Ghosting" },
        { "zh": "扭曲空间", "en": "Warpping Space" },
        { "zh": "次元裂缝", "en": "Dimensional Rift" },
        { "zh": "黑洞", "en": "Black Hole Effect" },
        { "zh": "白洞", "en": "White Hole Effect" },
        { "zh": "时间倒流", "en": "Rewind Effect" },
        { "zh": "时间停止", "en": "Time Stop Effect" },
        { "zh": "幻觉", "en": "Hallucination Effect" },
        { "zh": "数据损坏", "en": "Data Corruption Effect" },
        { "zh": "电流", "en": "Electrical Effect" },
        { "zh": "能量吸取", "en": "Energy Drain" },
        { "zh": "光线穿透", "en": "Light Penetration" },
        { "zh": "蒸汽", "en": "Steam Effect" },
        { "zh": "酸液", "en": "Acid Effect" },
        { "zh": "腐蚀", "en": "Corrosion Effect" },
        { "zh": "晶体生长", "en": "Crystal Growth Effect" },
        { "zh": "尘埃", "en": "Dust Effect" },
        { "zh": "烟花", "en": "Fireworks Effect" },
        { "zh": "泡泡", "en": "Bubble Effect" },
        { "zh": "光晕", "en": "Halo Effect" },
        { "zh": "圣光", "en": "Holy Light" },
        { "zh": "暗影", "en": "Shadow Effect" },
        { "zh": "虚空裂隙", "en": "Void Rift" },
        { "zh": "冰晶", "en": "Ice Crystal Effect" },
        { "zh": "风暴", "en": "Storm Effect" },
        { "zh": "迷雾", "en": "Fog Effect" },
        { "zh": "像素化效果", "en": "Pixelation Effect" },
        { "zh": "噪点效果", "en": "Noise Effect" },
        { "zh": "色差", "en": "Chromatic Aberration" },
        { "zh": "胶片颗粒", "en": "Film Grain" },
        { "zh": "CRT显示器效果", "en": "CRT Screen Effect" },
        { "zh": "VHS录像带效果", "en": "VHS Effect" },
        { "zh": "赛博空间效果", "en": "Cyberspace Effect" },
        { "zh": "鬼影", "en": "Ghosting Effect" },
        { "zh": "像素破碎", "en": "Pixel Break Up" },
        { "zh": "数字故障", "en": "Digital Glitch" },
        { "zh": "扫描线", "en": "Scanlines" },
        { "zh": "热浪扭曲", "en": "Heat Haze" },
        { "zh": "涟漪", "en": "Ripple Effect" },
        { "zh": "水花", "en": "Splash Effect" },
        { "zh": "破碎冰块", "en": "Shattering Ice" },
        { "zh": "倒塌碎片", "en": "Collapsing Debris" },
        { "zh": "灰烬", "en": "Ashes Effect" },
        { "zh": "尘暴", "en": "Dust Storm" },
        { "zh": "沙尘暴", "en": "Sandstorm" },
        { "zh": "血雾", "en": "Blood Mist" },
        { "zh": "腐败", "en": "Corruption Effect" },
        { "zh": "生命吸取", "en": "Life Drain" },
        { "zh": "经验值提升", "en": "XP Gain Effect" },
        { "zh": "金钱掉落", "en": "Coin Drop Effect" },
        { "zh": "物品掉落", "en": "Item Drop Effect" },
        { "zh": "提示信息", "en": "Prompt Message Effect" },
        { "zh": "UI反馈", "en": "UI Feedback Effect" },
        { "zh": "点击反馈", "en": "Click Feedback" },
        { "zh": "悬停反馈", "en": "Hover Feedback" },
        { "zh": "加载效果", "en": "Loading Effect" },
        { "zh": "过渡效果", "en": "Transition Effect" },
        { "zh": "切换场景", "en": "Scene Transition" },
        { "zh": "扭曲空间", "en": "Distorted Space" },
        { "zh": "能量波动", "en": "Energy Ripple" },
        { "zh": "电流脉冲", "en": "Electric Pulse" },
        { "zh": "心灵感应", "en": "Telekinesis Effect" },
        { "zh": "精神控制", "en": "Mind Control Effect" },
        { "zh": "灵魂连接", "en": "Soul Link Effect" },
        { "zh": "契约符号", "en": "Contract Symbol" },
        { "zh": "召唤阵", "en": "Summoning Circle" },
        { "zh": "诅咒符文", "en": "Curse Rune" },
        { "zh": "封印解除", "en": "Seal Release Effect" },
        { "zh": "符文激活", "en": "Rune Activation" },
        { "zh": "神器效果", "en": "Artifact Effect" },
        { "zh": "环境交互", "en": "Environment Interaction Effect" }
      ]
    },
    {
      "name": "典型场景 (Typical Scenes)",
      "tags": [
        // 自然场景 (Natural)
        { "zh": "森林", "en": "Forest" },
        { "zh": "茂密丛林", "en": "Dense Jungle" },
        { "zh": "古老森林", "en": "Ancient Forest" },
        { "zh": "神秘森林", "en": "Mysterious Forest" },
        { "zh": "雪山", "en": "Snowy Mountain" },
        { "zh": "火山", "en": "Volcano" },
        { "zh": "沙漠", "en": "Desert" },
        { "zh": "荒漠", "en": "Wasteland" },
        { "zh": "海岸线", "en": "Coastline" },
        { "zh": "海滩", "en": "Beach" },
        { "zh": "海底世界", "en": "Underwater World" },
        { "zh": "深海", "en": "Deep Sea" },
        { "zh": "珊瑚礁", "en": "Coral Reef" },
        { "zh": "溪流", "en": "Stream" },
        { "zh": "瀑布", "en": "Waterfall" },
        { "zh": "湖泊", "en": "Lake" },
        { "zh": "河流", "en": "River" },
        { "zh": "沼泽", "en": "Swamp" },
        { "zh": "湿地", "en": "Wetland" },
        { "zh": "草原", "en": "Grassland" },
        { "zh": "洞穴", "en": "Cave" },
        { "zh": "地下世界", "en": "Underground World" },
        { "zh": "冰川", "en": "Glacier" },
        { "zh": "极光", "en": "Aurora" },
        { "zh": "夜空", "en": "Night Sky" },
        { "zh": "星空", "en": "Starry Sky" },
        { "zh": "小岛", "en": "Island" },
        { "zh": "浮空岛", "en": "Floating Island" },
        { "zh": "深渊", "en": "Abyss" },
        { "zh": "绿洲", "en": "Oasis" },
        { "zh": "花园", "en": "Garden" },
        { "zh": "神秘花园", "en": "Secret Garden" },
        { "zh": "悬崖", "en": "Cliff" },
        { "zh": "峡谷", "en": "Canyon" },
        { "zh": "峡湾", "en": "Fjord" },
        { "zh": "陨石坑", "en": "Crater" },
        { "zh": "间歇泉", "en": "Geyser Field" },
        { "zh": "热带雨林", "en": "Tropical Rainforest" },
        { "zh": "戈壁", "en": "Gobi" },
        { "zh": "高原", "en": "Plateau" },
        { "zh": "苔原", "en": "Tundra" },
        { "zh": "极地冰盖", "en": "Polar Ice Cap" },
        { "zh": "熔岩地狱", "en": "Lava Hell" },
        { "zh": "水晶洞穴", "en": "Crystal Cave" },
        { "zh": "发光蘑菇林", "en": "Bioluminescent Mushroom Forest" },
        { "zh": "巨型植物", "en": "Giant Flora" },
        { "zh": "异形地貌", "en": "Alien Landscape" },
        { "zh": "太空", "en": "Outer Space" },
        { "zh": "星云", "en": "Nebula" },
        { "zh": "行星表面", "en": "Planetary Surface" },
        { "zh": "小行星带", "en": "Asteroid Field" },
        { "zh": "黑洞边缘", "en": "Edge of a Black Hole" },
        { "zh": "未来自然", "en": "Futuristic Nature" },

        // 人造场景 (Man-made)
        { "zh": "城市", "en": "City" },
        { "zh": "未来都市", "en": "Futuristic City" },
        { "zh": "赛博朋克都市", "en": "Cyberpunk City" },
        { "zh": "废弃城市", "en": "Abandoned City" },
        { "zh": "废土城市", "en": "Wasteland City" },
        { "zh": "贫民窟", "en": "Slums" },
        { "zh": "商业区", "en": "Commercial District" },
        { "zh": "住宅区", "en": "Residential Area" },
        { "zh": "工业区", "en": "Industrial Zone" },
        { "zh": "地下城", "en": "Dungeon" },
        { "zh": "城堡", "en": "Castle" },
        { "zh": "要塞", "en": "Fortress" },
        { "zh": "废墟", "en": "Ruins" },
        { "zh": "神庙", "en": "Temple" },
        { "zh": "教堂", "en": "Church" },
        { "zh": "大教堂", "en": "Cathedral" },
        { "zh": "修道院", "en": "Monastery" },
        { "zh": "图书馆", "en": "Library" },
        { "zh": "博物馆", "en": "Museum" },
        { "zh": "监狱", "en": "Prison" },
        { "zh": "基地", "en": "Base" },
        { "zh": "军事基地", "en": "Military Base" },
        { "zh": "地下实验室", "en": "Underground Lab" },
        { "zh": "航天港", "en": "Spaceport" },
        { "zh": "太空站", "en": "Space Station" },
        { "zh": "飞船内部", "en": "Spaceship Interior" },
        { "zh": "工厂", "en": "Factory" },
        { "zh": "发电站", "en": "Power Plant" },
        { "zh": "地铁站", "en": "Subway Station" },
        { "zh": "火车站", "en": "Train Station" },
        { "zh": "机场", "en": "Airport" },
        { "zh": "港口", "en": "Port" },
        { "zh": "桥梁", "en": "Bridge" },
        { "zh": "高速公路", "en": "Highway" },
        { "zh": "隧道", "en": "Tunnel" },
        { "zh": "竞技场", "en": "Arena" },
        { "zh": "斗兽场", "en": "Coliseum" },
        { "zh": "角斗场", "en": "Gladiatorial Arena" },
        { "zh": "集市", "en": "Marketplace" },
        { "zh": "酒馆/酒吧", "en": "Tavern/Bar" },
        { "zh": "旅店", "en": "Inn" },
        { "zh": "商店", "en": "Shop" },
        { "zh": "医院", "en": "Hospital" },
        { "zh": "学校", "en": "School" },
        { "zh": "办公室", "en": "Office" },
        { "zh": "公寓", "en": "Apartment" },
        { "zh": "豪宅", "en": "Mansion" },
        { "zh": "地堡", "en": "Bunker" },
        { "zh": "秘密通道", "en": "Secret Passage" },
        { "zh": "下水道", "en": "Sewers" },
        { "zh": "矿洞", "en": "Mine Shaft" },
        { "zh": "金库", "en": "Vault" },
        { "zh": "实验室", "en": "Laboratory" },
        { "zh": "控制室", "en": "Control Room" },
        { "zh": "核心区域", "en": "Core Area" },
        { "zh": "训练场", "en": "Training Ground" },
        { "zh": "靶场", "en": "Firing Range" },
        { "zh": "模拟室", "en": "Simulation Room" },
        { "zh": "车库", "en": "Garage" },
        { "zh": "维修站", "en": "Repair Bay" },
        { "zh": "高科技研究中心", "en": "High-Tech Research Center" },
        { "zh": "废弃设施", "en": "Abandoned Facility" },
        { "zh": "地下掩体", "en": "Underground Bunker" },
        { "zh": "神圣祭坛", "en": "Sacred Altar" },
        { "zh": "恶魔祭坛", "en": "Demonic Altar" },
        { "zh": "异次元空间", "en": "Alternate Dimension" },
        { "zh": "梦境", "en": "Dreamscape" },
        { "zh": "精神世界", "en": "Mental World" },
        { "zh": "虚拟空间", "en": "Virtual Space" },
        { "zh": "元宇宙", "en": "Metaverse" },
        { "zh": "黑市", "en": "Black Market" },
        { "zh": "下层世界", "en": "Underworld" },
        { "zh": "天堂", "en": "Heaven" },
        { "zh": "地狱", "en": "Hell" },
        { "zh": "灵界", "en": "Spirit Realm" },
        { "zh": "破碎之地", "en": "Shattered Lands" },
        { "zh": "污染区", "en": "Contaminated Zone" },
        { "zh": "隔离区", "en": "Quarantine Zone" },
        { "zh": "疫区", "en": "Plague Zone" },
        { "zh": "灾难现场", "en": "Disaster Site" },
        { "zh": "战场", "en": "Battlefield" },
        { "zh": "战壕", "en": "Trench Warfare" },
        { "zh": "废弃战场", "en": "Abandoned Battlefield" },
        { "zh": "地表", "en": "Surface" },
        { "zh": "高空", "en": "High Altitude" },
        { "zh": "太空殖民地", "en": "Space Colony" },
        { "zh": "月球基地", "en": "Lunar Base" },
        { "zh": "火星基地", "en": "Mars Base" },
        { "zh": "外星遗迹", "en": "Alien Ruins" },
        { "zh": "能源核心", "en": "Energy Core" },
        { "zh": "传送门", "en": "Portal" },
        { "zh": "时间流逝", "en": "Time-Lapsed" },
        { "zh": "四季变换", "en": "Four Seasons" },
        { "zh": "日夜循环", "en": "Day-Night Cycle" },
        { "zh": "动态光照", "en": "Dynamic Lighting" },
        { "zh": "天气系统", "en": "Weather System" },
        { "zh": "可破坏环境", "en": "Destructible Environment" },
        { "zh": "交互式环境", "en": "Interactive Environment" },
        { "zh": "载入区", "en": "Loading Zone" },
        { "zh": "安全区", "en": "Safe Zone" },
        { "zh": "危险区", "en": "Danger Zone" },
        { "zh": "中心区域", "en": "Central Hub" },
        { "zh": "起始区域", "en": "Starting Area" },
        { "zh": "终点区域", "en": "Endgame Area" },
        { "zh": "秘密房间", "en": "Secret Room" },
        { "zh": "隐藏区域", "en": "Hidden Area" },
        { "zh": "挑战关卡", "en": "Challenge Level" },
        { "zh": "新手教程", "en": "Tutorial Area" }
      ]
    },
    {
      "name": "质量设定 (Quality Settings)",
      "tags": [
        // 图像质量 (Graphics Quality)
        { "zh": "高画质", "en": "High Graphics" },
        { "zh": "中画质", "en": "Medium Graphics" },
        { "zh": "低画质", "en": "Low Graphics" },
        { "zh": "超高画质", "en": "Ultra Graphics" },
        { "zh": "极致画质", "en": "Max Graphics" },
        { "zh": "性能模式", "en": "Performance Mode" },
        { "zh": "质量模式", "en": "Quality Mode" },
        { "zh": "光线追踪开", "en": "Ray Tracing On" },
        { "zh": "光线追踪关", "en": "Ray Tracing Off" },
        { "zh": "分辨率：4K", "en": "Resolution: 4K" },
        { "zh": "分辨率：1080p", "en": "Resolution: 1080p" },
        { "zh": "分辨率：720p", "en": "Resolution: 720p" },
        { "zh": "垂直同步开", "en": "V-Sync On" },
        { "zh": "垂直同步关", "en": "V-Sync Off" },
        { "zh": "帧率：60 FPS", "en": "Frame Rate: 60 FPS" },
        { "zh": "帧率：30 FPS", "en": "Frame Rate: 30 FPS" },
        { "zh": "无限帧率", "en": "Unlimited Frame Rate" },
        { "zh": "纹理质量：高", "en": "Texture Quality: High" },
        { "zh": "纹理质量：低", "en": "Texture Quality: Low" },
        { "zh": "模型细节：高", "en": "Model Detail: High" },
        { "zh": "模型细节：低", "en": "Model Detail: Low" },
        { "zh": "阴影质量：高", "en": "Shadow Quality: High" },
        { "zh": "阴影质量：低", "en": "Shadow Quality: Low" },
        { "zh": "抗锯齿：FXAA", "en": "Anti-Aliasing: FXAA" },
        { "zh": "抗锯齿：MSAA", "en": "Anti-Aliasing: MSAA" },
        { "zh": "抗锯齿：TAA", "en": "Anti-Aliasing: TAA" },
        { "zh": "抗锯齿：DLSS", "en": "Anti-Aliasing: DLSS" },
        { "zh": "抗锯齿：FSR", "en": "Anti-Aliasing: FSR" },
        { "zh": "环境光遮蔽：SSAO", "en": "Ambient Occlusion: SSAO" },
        { "zh": "环境光遮蔽：HBAO", "en": "Ambient Occlusion: HBAO" },
        { "zh": "反射质量：高", "en": "Reflection Quality: High" },
        { "zh": "反射质量：低", "en": "Reflection Quality: Low" },
        { "zh": "体积照明：开", "en": "Volumetric Lighting: On" },
        { "zh": "粒子效果：高", "en": "Particle Effects: High" },
        { "zh": "粒子效果：低", "en": "Particle Effects: Low" },
        { "zh": "渲染距离：远", "en": "Render Distance: Far" },
        { "zh": "渲染距离：近", "en": "Render Distance: Near" },
        { "zh": "景深：开", "en": "Depth of Field: On" },
        { "zh": "动态模糊：开", "en": "Motion Blur: On" },
        { "zh": "镜头光晕：开", "en": "Lens Flare: On" },
        { "zh": "色差：开", "en": "Chromatic Aberration: On" },
        { "zh": "胶片颗粒：开", "en": "Film Grain: On" },
        { "zh": "Bloom效果：开", "en": "Bloom Effect: On" },
        { "zh": "环境反射：开", "en": "Environment Reflections: On" },
        { "zh": "屏幕空间反射：开", "en": "Screen Space Reflections: On" },
        { "zh": "水体质量：高", "en": "Water Quality: High" },
        { "zh": "植被细节：高", "en": "Vegetation Detail: High" },
        { "zh": "布料模拟：开", "en": "Cloth Simulation: On" },
        { "zh": "毛发渲染：开", "en": "Hair Rendering: On" },
        { "zh": "可变分辨率渲染 (VRS)", "en": "Variable Rate Shading (VRS)" },
        { "zh": "高级阴影", "en": "Advanced Shadows" },
        { "zh": "程序化云朵", "en": "Procedural Clouds" },
        { "zh": "体积雾", "en": "Volumetric Fog" },
        { "zh": "次表面散射 (SSS)", "en": "Subsurface Scattering (SSS)" },
        { "zh": "法线贴图", "en": "Normal Mapping" },
        { "zh": "视差贴图", "en": "Parallax Mapping" },
        { "zh": "细节贴图", "en": "Detail Mapping" },
        { "zh": "环境贴图", "en": "Environment Mapping" },
        { "zh": "凹凸贴图", "en": "Bump Mapping" },
        { "zh": "高模", "en": "High-Poly Model" },
        { "zh": "低模", "en": "Low-Poly Model" },
        { "zh": "LOD切换", "en": "LOD Switching" },
        { "zh": "像素密度", "en": "Pixel Density" },
        { "zh": "纹理过滤", "en": "Texture Filtering (Anisotropic)" },
        { "zh": "实时渲染", "en": "Real-time Rendering" },
        { "zh": "预渲染", "en": "Pre-rendered" },
        { "zh": "烘焙光照", "en": "Baked Lighting" },
        { "zh": "光照贴图", "en": "Lightmap" },
        { "zh": "实时阴影", "en": "Real-time Shadows" },
        { "zh": "级联阴影贴图", "en": "Cascaded Shadow Maps (CSM)" },
        { "zh": "软阴影", "en": "Soft Shadows" },
        { "zh": "硬阴影", "en": "Hard Shadows" },
        { "zh": "屏幕空间环境光遮蔽 (SSAO)", "en": "Screen Space Ambient Occlusion (SSAO)" },
        { "zh": "屏幕空间反射 (SSR)", "en": "Screen Space Reflections (SSR)" },
        { "zh": "屏幕空间阴影", "en": "Screen Space Shadows" },
        { "zh": "透明度分层", "en": "Transparency Layering" },
        { "zh": "折射", "en": "Refraction" },
        { "zh": "色调映射", "en": "Tone Mapping" },
        { "zh": "色彩校正", "en": "Color Correction" },
        { "zh": "伽马校正", "en": "Gamma Correction" },
        { "zh": "后处理堆栈", "en": "Post-Processing Stack" },
        { "zh": "图像后处理", "en": "Image Post-processing" },
        { "zh": "边缘柔化", "en": "Edge Smoothing" },
        { "zh": "几何细节", "en": "Geometric Detail" },
        { "zh": "顶点着色", "en": "Vertex Shading" },
        { "zh": "像素着色", "en": "Pixel Shading" },
        { "zh": "曲面细分", "en": "Tessellation" },
        { "zh": "法向贴图", "en": "Normal Maps" },
        { "zh": "置换贴图", "en": "Displacement Maps" },
        { "zh": "顶点颜色", "en": "Vertex Colors" },
        { "zh": "雾效", "en": "Fog Effects" },
        { "zh": "光线体积", "en": "Light Volumes" },
        { "zh": "屏幕空间光线", "en": "Screen Space God Rays" },
        { "zh": "着色器复杂性", "en": "Shader Complexity" },
        { "zh": "动态分辨率", "en": "Dynamic Resolution" },
        { "zh": "智能调整", "en": "Intelligent Scaling" },
        { "zh": "性能优化", "en": "Performance Optimization" },
        { "zh": "内存占用", "en": "Memory Usage" },
        { "zh": "显存占用", "en": "VRAM Usage" },
        { "zh": "CPU占用", "en": "CPU Usage" },
        { "zh": "GPU占用", "en": "GPU Usage" },
        { "zh": "网络同步", "en": "Network Latency Compensation" },
        { "zh": "带宽占用", "en": "Bandwidth Usage" },

        // 音频质量 (Audio Quality)
        { "zh": "高音质", "en": "High Audio Quality" },
        { "zh": "低音质", "en": "Low Audio Quality" },
        { "zh": "环绕声", "en": "Surround Sound" },
        { "zh": "立体声", "en": "Stereo Sound" },
        { "zh": "空间音频", "en": "Spatial Audio" },
        { "zh": "环境音效", "en": "Environmental Audio" },
        { "zh": "音乐音量", "en": "Music Volume" },
        { "zh": "音效音量", "en": "Sound Effects Volume" },
        { "zh": "对话音量", "en": "Dialogue Volume" },
        { "zh": "混音设定", "en": "Mixing Settings" },
        { "zh": "音效混响", "en": "Audio Reverb" },
        { "zh": "音效衰减", "en": "Audio Attenuation" },
        { "zh": "音效传播", "en": "Audio Propagation" },
        { "zh": "音频压缩", "en": "Audio Compression" },
        { "zh": "采样率", "en": "Sample Rate" },
        { "zh": "比特率", "en": "Bit Rate" },
        { "zh": "音频通道", "en": "Audio Channels" },

        // 网络质量 (Network Quality)
        { "zh": "低延迟", "en": "Low Latency" },
        { "zh": "高延迟", "en": "High Latency" },
        { "zh": "宽带优化", "en": "Broadband Optimized" },
        { "zh": "蜂窝网络优化", "en": "Cellular Network Optimized" },
        { "zh": "服务器负载", "en": "Server Load" },
        { "zh": "客户端性能", "en": "Client Performance" },
        { "zh": "网络同步", "en": "Network Synchronization" },
        { "zh": "数据包丢失率", "en": "Packet Loss Rate" },
        { "zh": "抖动", "en": "Jitter" },

        // 游戏体验 (Gameplay Experience)
        { "zh": "流畅体验", "en": "Smooth Experience" },
        { "zh": "高沉浸感", "en": "High Immersion" },
        { "zh": "高真实感", "en": "High Realism" },
        { "zh": "高可玩性", "en": "High Replayability" },
        { "zh": "用户体验 (UX) 优化", "en": "User Experience (UX) Optimized" },
        { "zh": "用户界面 (UI) 质量", "en": "User Interface (UI) Quality" },
        { "zh": "可访问性", "en": "Accessibility" },
        { "zh": "辅助功能", "en": "Assistive Features" },
        { "zh": "无障碍模式", "en": "Accessibility Mode" },
        { "zh": "颜色盲模式", "en": "Colorblind Mode" },
        { "zh": "字幕", "en": "Subtitles" },
        { "zh": "手柄震动", "en": "Controller Vibration" },
        { "zh": "手柄自适应扳机", "en": "Adaptive Triggers (Controller)" },
        { "zh": "触觉反馈", "en": "Haptic Feedback" }
      ]
    }
  ]
});