tagData.push({
  "group": "美食 (Food)",
  "categories": [
    {
      "name": "风格 (Style)",
      "tags": [
        { "zh": "美食摄影", "en": "food photography" },
        { "zh": "米其林风格", "en": "Michelin style" },
        { "zh": "精致料理", "en": "gourmet cuisine" },
        { "zh": "家常菜", "en": "homemade cooking" },
        { "zh": "街头小吃", "en": "street food" },
        { "zh": "创意菜", "en": "creative cuisine" },
        { "zh": "融合菜", "en": "fusion cuisine" },
        { "zh": "高级餐饮", "en": "fine dining" },
        { "zh": "休闲餐饮", "en": "casual dining" },
        { "zh": "农家菜", "en": "farmhouse cuisine" },
        { "zh": "本帮菜", "en": "local specialty cuisine" },
        { "zh": "地域美食", "en": "regional cuisine" },
        { "zh": "古法菜", "en": "traditional cooking methods" },
        { "zh": "分子料理", "en": "molecular gastronomy" },
        { "zh": "健康饮食", "en": "healthy eating" },
        { "zh": "素食", "en": "vegetarian" },
        { "zh": "纯素", "en": "vegan" },
        { "zh": "低脂", "en": "low-fat" },
        { "zh": "无麸质", "en": "gluten-free" },
        { "zh": "有机食品", "en": "organic food" },
        { "zh": "生酮饮食", "en": "keto diet" },
        { "zh": "地中海饮食", "en": "Mediterranean diet" },
        { "zh": "热带风情", "en": "tropical style" },
        { "zh": "乡村风味", "en": "rustic flavor" },
        { "zh": "现代简约", "en": "modern minimalist" },
        { "zh": "传统经典", "en": "traditional classic" },
        { "zh": "复古风格", "en": "retro style" },
        { "zh": "节日主题", "en": "festive theme" },
        { "zh": "卡通主题", "en": "cartoon theme" },
        { "zh": "艺术摆盘", "en": "artistic plating" },
        { "zh": "精致摆盘", "en": "delicate plating" },
        { "zh": "简洁摆盘", "en": "simple plating" },
        { "zh": "堆叠摆盘", "en": "stacked plating" },
        { "zh": "涂抹摆盘", "en": "smeared plating" },
        { "zh": "写实主义", "en": "realism" },
        { "zh": "抽象主义", "en": "abstractism" },
        { "zh": "超现实主义", "en": "surrealism" },
        { "zh": "概念性", "en": "conceptual" },
        { "zh": "极简主义", "en": "minimalism" },
        { "zh": "高对比", "en": "high contrast" },
        { "zh": "低饱和度", "en": "low saturation" },
        { "zh": "高饱和度", "en": "high saturation" },
        { "zh": "柔和光线", "en": "soft lighting" },
        { "zh": "硬光", "en": "hard lighting" },
        { "zh": "自然光", "en": "natural light" },
        { "zh": "工作室打光", "en": "studio lighting" },
        { "zh": "暗调", "en": "dark mood" },
        { "zh": "明亮", "en": "bright" },
        { "zh": "食物特写", "en": "food close-up" },
        { "zh": "饭桌俯视", "en": "flat lay food photography" },
        { "zh": "餐具构图", "en": "tableware composition" },
        { "zh": "食材质感", "en": "ingredient texture focus" },
        { "zh": "电影感", "en": "cinematic" },
        { "zh": "胶片感", "en": "film look" },
        { "zh": "怀旧", "en": "nostalgic" },
        { "zh": "充满活力", "en": "vibrant" },
        { "zh": "温馨", "en": "cozy" },
        { "zh": "艺术性", "en": "artistic" },
        { "zh": "工业风", "en": "industrial style" },
        { "zh": "禅意',", "en": "Zen style" },
        { "zh": "波西米亚", "en": "Bohemian" },
        { "zh": "生态", "en": "ecological" },
        { "zh": "农产品", "en": "farm produce" },
        { "zh": "手工制作", "en": "handmade" },
        { "zh": "家庭式", "en": "family style" },
        { "zh": "街边", "en": "street side" },
        { "zh": "餐厅", "en": "restaurant" },
        { "zh": "农场", "en": "farm-to-table" },
        { "zh": "快餐", "en": "fast food" },
        { "zh": "慢食", "en": "slow food" },
        { "zh": "网红", "en": "viral/trendy" },
        { "zh": "经典", "en": "classic" }
      ]
    },
    {
      "name": "景别 (Shot Type/Framing)",
      "tags": [
        { "zh": "特写", "en": "close-up" },
        { "zh": "局部特写", "en": "extreme close-up" },
        { "zh": "中景", "en": "medium shot" },
        { "zh": "全景", "en": "wide shot" },
        { "zh": "俯视", "en": "overhead shot" },
        { "zh": "平视", "en": "eye-level shot" },
        { "zh": "低角度", "en": "low angle shot" },
        { "zh": "高角度", "en": "high angle shot" },
        { "zh": "散景", "en": "bokeh" },
        { "zh": "前景模糊", "en": "foreground blur" },
        { "zh": "背景模糊", "en": "background blur" },
        { "zh": "聚焦", "en": "in focus" },
        { "zh": "景深", "en": "depth of field" },
        { "zh": "浅景深", "en": "shallow depth of field" },
        { "zh": "深景深", "en": "deep depth of field" },
        { "zh": "构图", "en": "composition" },
        { "zh": "三分法构图", "en": "rule of thirds" },
        { "zh": "居中构图", "en": "centered composition" },
        { "zh": "对称构图", "en": "symmetrical composition" },
        { "zh": "引导线", "en": "leading lines" },
        { "zh": "框架构图", "en": "framing composition" },
        { "zh": "逆光拍摄", "en": "backlit shot" },
        { "zh": "侧逆光", "en": "side-back lighting" },
        { "zh": "明暗对比", "en": "light and shadow contrast" },
        { "zh": "烟雾缭绕", "en": "steaming" },
        { "zh": "热气腾腾", "en": "hot and steamy" },
        { "zh": "冒泡", "en": "bubbling" },
        { "zh": "正在制作", "en": "in preparation" },
        { "zh": "正在烹饪", "en": "in cooking process" },
        { "zh": "淋酱动作", "en": "pouring sauce action" },
        { "zh": "切片动作", "en": "slicing action" },
        { "zh": "品尝瞬间", "en": "moment of tasting" },
        { "zh": "咬一口", "en": "bite into it" },
        { "zh": "溅射效果", "en": "splatter effect" },
        { "zh": "滴落", "en": "dripping" },
        { "zh": "堆叠", "en": "stacked" },
        { "zh": "排列整齐", "en": "neatly arranged" },
        { "zh": "散落", "en": "scattered" },
        { "zh": "混乱美", "en": "artistic mess" },
        { "zh": "俯瞰餐桌", "en": "table view from above" },
        { "zh": "手持", "en": "handheld" },
        { "zh": "抓拍", "en": "candid shot" },
        { "zh": "静态拍摄", "en": "still life shot" },
        { "zh": "动态模糊", "en": "motion blur" },
        { "zh": "微距摄影", "en": "macro photography" },
        { "zh": "俯拍", "en": "flat lay" },
        { "zh": "纪实", "en": "documentary style" },
        { "zh": "故事性", "en": "storytelling" },
        { "zh": "环境衬托", "en": "environmental backdrop" },
        { "zh": "焦点清晰", "en": "sharp focus" },
        { "zh": "柔焦", "en": "soft focus" },
        { "zh": "虚化光斑", "en": "bokeh effects" },
        { "zh": "裁剪", "en": "cropped" },
        { "zh": "广角", "en": "wide angle" },
        { "zh": "长焦", "en": "telephoto" },
        { "zh": "移动模糊", "en": "motion blur (camera)" },
        { "zh": "光线追踪", "en": "ray tracing" },
        { "zh": "多重曝光", "en": "multiple exposure" },
        { "zh": "水滴效果", "en": "water droplet effect" },
        { "zh": "冰块效果", "en": "ice cube effect" },
        { "zh": "火焰效果", "en": "flame effect" },
        { "zh": "烟雾效果", "en": "smoke effect" },
        { "zh": "透明度", "en": "transparency" },
        { "zh": "反射", "en": "reflection" },
        { "zh": "倒影", "en": "mirror image" }
      ]
    },
    {
      "name": "中餐 (Chinese Cuisine)",
      "tags": [
        { "zh": "川菜", "en": "Sichuan cuisine" },
        { "zh": "麻婆豆腐", "en": "Mapo tofu" },
        { "zh": "宫保鸡丁", "en": "Kung Pao chicken" },
        { "zh": "水煮鱼", "en": "Sichuan boiled fish" },
        { "zh": "水煮肉片", "en": "Sichuan boiled beef/pork slices" },
        { "zh": "回锅肉", "en": "twice-cooked pork" },
        { "zh": "钵钵鸡", "en": "Bo Bo Chicken" },
        { "zh": "火锅", "en": "hot pot" },
        { "zh": "串串香", "en": "chuan chuan xiang (skewer hot pot)" },
        { "zh": "担担面", "en": "Dandan noodles" },
        { "zh": "夫妻肺片", "en": "Couple's Lung Slices (Spicy Beef Tendon and Tripe)" },
        { "zh": "辣子鸡", "en": "spicy chicken with chilies" },
        { "zh": "鱼香肉丝", "en": "fish-flavored shredded pork" },
        { "zh": "粤菜", "en": "Cantonese cuisine" },
        { "zh": "白切鸡", "en": "steamed chicken" },
        { "zh": "烧鹅", "en": "roasted goose" },
        { "zh": "叉烧", "en": "char siu (BBQ pork)" },
        { "zh": "豉油鸡", "en": "soy sauce chicken" },
        { "zh": "煲仔饭", "en": "claypot rice" },
        { "zh": "干炒牛河", "en": "stir-fried beef ho fun" },
        { "zh": "佛跳墙", "en": "Buddha Jumps Over The Wall" },
        { "zh": "早茶", "en": "dim sum breakfast" },
        { "zh": "潮汕菜", "en": "Chaoshan cuisine" },
        { "zh": "牛肉火锅", "en": "Chaoshan beef hot pot" },
        { "zh": "卤水拼盘", "en": "braised platter" },
        { "zh": "沙茶酱", "en": "satay sauce" },
        { "zh": "鱼丸", "en": "fish balls" },
        { "zh": "湘菜", "en": "Hunan cuisine" },
        { "zh": "剁椒鱼头", "en": "steamed fish head with chopped chili" },
        { "zh": "小炒肉", "en": "stir-fried pork with chili" },
        { "zh": "米粉", "en": "rice noodles" },
        { "zh": "酱油炒饭", "en": "soy sauce fried rice" },
        { "zh": "鲁菜", "en": "Shandong cuisine" },
        { "zh": "葱烧海参", "en": "braised sea cucumber with scallions" },
        { "zh": "糖醋鲤鱼", "en": "sweet and sour carp" },
        { "zh": "九转大肠", "en": "Nine-Turned Large Intestines" },
        { "zh": "德州扒鸡", "en": "Dezhou braised chicken" },
        { "zh": "胶东海鲜", "en": "Jiaodong seafood" },
        { "zh": "淮扬菜", "en": "Huaiyang cuisine" },
        { "zh": "狮子头", "en": "lion's head meatballs" },
        { "zh": "文思豆腐", "en": "Wensi Tofu" },
        { "zh": "大煮干丝", "en": "boiled shredded tofu with ham" },
        { "zh": "扬州炒饭", "en": "Yangzhou fried rice" },
        { "zh": "松鼠鳜鱼", "en": "squirrel-shaped mandarin fish" },
        { "zh": "浙菜", "en": "Zhejiang cuisine" },
        { "zh": "西湖醋鱼", "en": "West Lake vinegar fish" },
        { "zh": "东坡肉", "en": "Dongpo pork" },
        { "zh": "龙井虾仁", "en": "Longjing tea shrimp" },
        { "zh": "叫花鸡", "en": "Beggar's Chicken" },
        { "zh": "徽菜", "en": "Anhui cuisine" },
        { "zh": "臭鳜鱼", "en": "stinky Mandarin fish" },
        { "zh": "毛豆腐", "en": "hairy tofu" },
        { "zh": "闽菜", "en": "Fujian cuisine" },
        { "zh": "佛跳墙", "en": "Buddha Jumps Over The Wall" },
        { "zh": "沙县小吃", "en": "Shaxian snacks" },
        { "zh": "扁肉", "en": "wonton-like dumplings" },
        { "zh": "拌面", "en": "mixed noodles" },
        { "zh": "京菜", "en": "Beijing cuisine" },
        { "zh": "北京烤鸭", "en": "Peking duck" },
        { "zh": "炸酱面", "en": "Zhajiangmian (noodles with fried bean sauce)" },
        { "zh": "涮羊肉", "en": "instant-boiled mutton" },
        { "zh": "老北京铜锅火锅", "en": "old Beijing copper pot hot pot" },
        { "zh": "卤煮火烧", "en": "stewed pork offal with bread" },
        { "zh": "炒肝", "en": "stir-fried liver" },
        { "zh": "护国寺小吃", "en": "Huguo Temple snacks" },
        { "zh": "沪菜", "en": "Shanghai cuisine" },
        { "zh": "红烧肉", "en": "braised pork belly" },
        { "zh": "生煎包", "en": "shengjianbao (pan-fried buns)" },
        { "zh": "小笼包", "en": "xiaolongbao" },
        { "zh": "蟹粉小笼", "en": "crab roe xiaolongbao" },
        { "zh": "八宝饭", "en": "Eight-treasure rice pudding" },
        { "zh": "南翔馒头", "en": "Nanxiang steamed buns" },
        { "zh": "葱油拌面", "en": "scallion oil noodles" },
        { "zh": "两面黄", "en": "crispy noodles" },
        { "zh": "东北菜", "en": "Northeast Chinese cuisine" },
        { "zh": "锅包肉", "en": "Guobaorou (fried pork in sweet and sour sauce)" },
        { "zh": "地三鲜", "en": "stir-fried potato, green pepper, and eggplant" },
        { "zh": "小鸡炖蘑菇", "en": "chicken stew with mushrooms" },
        { "zh": "杀猪菜", "en": "pig slaughter set meal" },
        { "zh": "炖菜", "en": "stewed dishes" },
        { "zh": "扒肉", "en": "braised meat" },
        { "zh": "饺子", "en": "dumplings" },
        { "zh": "新疆菜", "en": "Xinjiang cuisine" },
        { "zh": "大盘鸡", "en": "Dapanji (big plate chicken)" },
        { "zh": "羊肉串", "en": "lamb skewers" },
        { "zh": "馕", "en": "Naan bread" },
        { "zh": "手抓饭", "en": "pilaf" },
        { "zh": "胡辣羊蹄", "en": "spicy lamb trotters" },
        { "zh": "清真菜", "en": "Halal cuisine" },
        { "zh": "西北菜", "en": "Northwestern Chinese cuisine" },
        { "zh": "肉夹馍", "en": "Roujiamo (Chinese hamburger)" },
        { "zh": "羊肉泡馍", "en": "Yangrou Paomo (mutton and pancake soup)" },
        { "zh": "凉皮", "en": "Liangpi (cold noodles)" },
        { "zh": "擀面皮", "en": "Ganmianpi (rolled noodles)" },
        { "zh": "biangbiang面", "en": "Biangbiang noodles" },
        { "zh": "油泼面", "en": "oil-splashed noodles" },
        { "zh": "兰州拉面", "en": "Lanzhou hand-pulled noodles" },
        { "zh": "云南菜", "en": "Yunnan cuisine" },
        { "zh": "过桥米线", "en": "Crossing-the-Bridge Noodles" },
        { "zh": "汽锅鸡", "en": "steam pot chicken" },
        { "zh": "鲜花饼", "en": "flower pastry" },
        { "zh": "虫子宴", "en": "insect feast" },
        { "zh": "贵州菜", "en": "Guizhou cuisine" },
        { "zh": "酸汤鱼", "en": "sour soup fish" },
        { "zh": "丝娃娃", "en": "Siwawa (Guizhou thin pancakes)" },
        { "zh": "肠旺面", "en": "Changwang noodles" },
        { "zh": "米皮", "en": "rice vermicelli" },
        { "zh": "湖北菜", "en": "Hubei cuisine" },
        { "zh": "热干面", "en": "hot dry noodles" },
        { "zh": "鱼香肉丝", "en": "fish-flavored shredded pork" },
        { "zh": "排骨藕汤", "en": "pork rib and lotus root soup" },
        { "zh": "早点", "en": "breakfast foods" },
        { "zh": "烧烤", "en": "Chinese barbecue" },
        { "zh": "砂锅", "en": "claypot dishes" },
        { "zh": "面食", "en": "noodle dishes" },
        { "zh": "炒面", "en": "chow mein" },
        { "zh": "捞面", "en": "lo mein" },
        { "zh": "汤面", "en": "noodle soup" },
        { "zh": "米饭", "en": "rice" },
        { "zh": "炒饭", "en": "fried rice" },
        { "zh": "粥", "en": "congee" },
        { "zh": "凉菜", "en": "cold dishes" },
        { "zh": "热菜", "en": "hot dishes" },
        { "zh": "汤", "en": "soup" },
        { "zh": "羹", "en": "thick soup" },
        { "zh": "炖品", "en": "stew/double-boiled soup" },
        { "zh": "家常小炒", "en": "home-style stir-fries" },
        { "zh": "盖饭", "en": "rice bowl with toppings" },
        { "zh": "馒头", "en": "steamed bun" },
        { "zh": "花卷", "en": "steamed twisted roll" },
        { "zh": "包子", "en": "steamed stuffed bun" },
        { "zh": "馅饼", "en": "pie/flatbread with filling" },
        { "zh": "烧饼", "en": "sesame flatbread" },
        { "zh": "油条", "en": "fried dough sticks" },
        { "zh": "豆浆", "en": "soy milk" },
        { "zh": "麻辣", "en": "spicy and numbing" },
        { "zh": "酸辣", "en": "sour and spicy" },
        { "zh": "咸鲜", "en": "savory and fresh" },
        { "zh": "香辣", "en": "fragrant and spicy" },
        { "zh": "甜口", "en": "sweet flavor" },
        { "zh": "焦香", "en": "charred aroma" },
        { "zh": "酥脆", "en": "crispy" },
        { "zh": "软糯", "en": "soft and sticky" },
        { "zh": "入口即化", "en": "melts in your mouth" },
        { "zh": "锅气", "en": "wok hei (wok aroma)" },
        { "zh": "地道", "en": "authentic" },
        { "zh": "传统", "en": "traditional" },
        { "zh": "创新", "en": "innovative" },
        { "zh": "经典", "en": "classic" },
        { "zh": "特色菜", "en": "specialty dish" },
        { "zh": "老字号", "en": "time-honored brand" }
      ]
    },
    {
      "name": "西餐 (Western Cuisine)",
      "tags": [
        { "zh": "法餐", "en": "French cuisine" },
        { "zh": "鹅肝", "en": "foie gras" },
        { "zh": "法式蜗牛", "en": "escargot" },
        { "zh": "法式洋葱汤", "en": "French onion soup" },
        { "zh": "牛排", "en": "steak" },
        { "zh": "菲力牛排", "en": "filet mignon" },
        { "zh": "肋眼牛排", "en": "ribeye steak" },
        { "zh": "T骨牛排", "en": "T-bone steak" },
        { "zh": "西冷牛排", "en": "sirloin steak" },
        { "zh": "法式长棍面包", "en": "baguette" },
        { "zh": "可颂", "en": "croissant" },
        { "zh": "马卡龙", "en": "macaron" },
        { "zh": "舒芙蕾", "en": "soufflé" },
        { "zh": "勃艮第红酒炖牛肉", "en": "beef bourguignon" },
        { "zh": "意餐", "en": "Italian cuisine" },
        { "zh": "披萨", "en": "pizza" },
        { "zh": "玛格丽特披萨", "en": "Margherita pizza" },
        { "zh": "意大利面", "en": "pasta" },
        { "zh": "意面", "en": "pasta" },
        { "zh": "螺丝面", "en": "fusilli" },
        { "zh": "通心粉", "en": "macaroni" },
        { "zh": "宽面", "en": "fettuccine" },
        { "zh": "意式肉酱面", "en": "spaghetti bolognese" },
        { "zh": "奶油培根意面", "en": "carbonara" },
        { "zh": "番茄意面", "en": "spaghetti al pomodoro" },
        { "zh": "千层面", "en": "lasagna" },
        { "zh": "意式烩饭", "en": "risotto" },
        { "zh": "提拉米苏", "en": "tiramisu" },
        { "zh": "卡布奇诺", "en": "cappuccino" },
        { "zh": "帕尼尼", "en": "panini" },
        { "zh": "意式冰淇淋", "en": "gelato" },
        { "zh": "美式", "en": "American cuisine" },
        { "zh": "汉堡", "en": "burger" },
        { "zh": "薯条", "en": "French fries" },
        { "zh": "炸鸡", "en": "fried chicken" },
        { "zh": "热狗", "en": "hot dog" },
        { "zh": "烤肋排", "en": "BBQ ribs" },
        { "zh": "煎饼", "en": "pancakes" },
        { "zh": "华夫饼", "en": "waffles" },
        { "zh": "甜甜圈", "en": "donut" },
        { "zh": "沙拉", "en": "salad" },
        { "zh": "凯撒沙拉", "en": "Caesar salad" },
        { "zh": "三明治", "en": "sandwich" },
        { "zh": "俱乐部三明治", "en": "club sandwich" },
        { "zh": "可颂三明治", "en": "croissant sandwich" },
        { "zh": "潜艇堡", "en": "sub sandwich" },
        { "zh": "英式", "en": "British cuisine" },
        { "zh": "炸鱼薯条", "en": "fish and chips" },
        { "zh": "英式早餐", "en": "English breakfast" },
        { "zh": "约克郡布丁", "en": "Yorkshire pudding" },
        { "zh": "牧羊人派", "en": "shepherd's pie" },
        { "zh": "德式", "en": "German cuisine" },
        { "zh": "德国香肠", "en": "German sausage" },
        { "zh": "猪肘", "en": "pork knuckle" },
        { "zh": "酸菜", "en": "sauerkraut" },
        { "zh": "俄式", "en": "Russian cuisine" },
        { "zh": "罗宋汤", "en": "borscht" },
        { "zh": "俄式饺子", "en": "pelmeni" },
        { "zh": "地中海菜", "en": "Mediterranean cuisine" },
        { "zh": "希腊沙拉", "en": "Greek salad" },
        { "zh": "西班牙海鲜饭", "en": "paella" },
        { "zh": "塔帕斯", "en": "tapas" },
        { "zh": "墨西哥菜", "en": "Mexican cuisine" },
        { "zh": "塔可", "en": "taco" },
        { "zh": "卷饼", "en": "burrito" },
        { "zh": "玉米片", "en": "nachos" },
        { "zh": "鳄梨酱", "en": "guacamole" },
        { "zh": "咖喱", "en": "curry" },
        { "zh": "印度飞饼", "en": "roti (Indian flatbread)" },
        { "zh": "日料", "en": "Japanese cuisine" },
        { "zh": "寿司", "en": "sushi" },
        { "zh": "刺身", "en": "sashimi" },
        { "zh": "拉面", "en": "ramen" },
        { "zh": "天妇罗", "en": "tempura" },
        { "zh": "照烧", "en": "teriyaki" },
        { "zh": "寿喜烧", "en": "sukiyaki" },
        { "zh": "章鱼小丸子", "en": "takoyaki" },
        { "zh": "韩餐", "en": "Korean cuisine" },
        { "zh": "泡菜", "en": "kimchi" },
        { "zh": "石锅拌饭", "en": "bibimbap" },
        { "zh": "炸鸡啤酒", "en": "fried chicken and beer" },
        { "zh": "部队锅", "en": "budae jjigae (army stew)" },
        { "zh": "东南亚菜", "en": "Southeast Asian cuisine" },
        { "zh": "泰餐", "en": "Thai cuisine" },
        { "zh": "冬阴功汤", "en": "Tom Yum Goong" },
        { "zh": "绿咖喱", "en": "green curry" },
        { "zh": "越南粉", "en": "pho (Vietnamese noodle soup)" },
        { "zh": "新加坡菜", "en": "Singaporean cuisine" },
        { "zh": "海南鸡饭", "en": "Hainanese chicken rice" },
        { "zh": "肉骨茶", "en": "Bak Kut Teh" },
        { "zh": "前菜", "en": "appetizer" },
        { "zh": "主菜", "en": "main course" },
        { "zh": "汤品", "en": "soup" },
        { "zh": "海鲜", "en": "seafood" },
        { "zh": "烤鸡", "en": "roasted chicken" },
        { "zh": "面包", "en": "bread" },
        { "zh": "餐前面包", "en": "bread roll" },
        { "zh": "白面包", "en": "white bread" },
        { "zh": "全麦面包", "en": "whole wheat bread" },
        { "zh": "黑麦面包", "en": "rye bread" },
        { "zh": "蒜蓉面包", "en": "garlic bread" },
        { "zh": "餐后甜点", "en": "dessert" },
        { "zh": "披萨", "en": "pizza" },
        { "zh": "汉堡", "en": "hamburger" },
        { "zh": "芝士汉堡", "en": "cheeseburger" },
        { "zh": "鸡肉汉堡", "en": "chicken burger" },
        { "zh": "鱼肉汉堡", "en": "fish burger" },
        { "zh": "素食汉堡", "en": "vegetarian burger" },
        { "zh": "薯条", "en": "French fries" },
        { "zh": "薯角", "en": "potato wedges" },
        { "zh": "薯泥", "en": "mashed potatoes" },
        { "zh": "玉米浓汤", "en": "corn chowder" },
        { "zh": "蘑菇汤", "en": "mushroom soup" },
        { "zh": "奶油南瓜汤", "en": "creamy pumpkin soup" },
        { "zh": "法式焗蜗牛", "en": "French baked escargot" },
        { "zh": "烤马铃薯", "en": "baked potato" },
        { "zh": "蔬菜沙拉", "en": "vegetable salad" },
        { "zh": "水果沙拉", "en": "fruit salad" },
        { "zh": "吞拿鱼沙拉", "en": "tuna salad" },
        { "zh": "烤三文鱼", "en": "grilled salmon" },
        { "zh": "炸猪排", "en": "pork cutlet" },
        { "zh": "烤羊排", "en": "roasted lamb chops" },
        { "zh": "香肠", "en": "sausage" },
        { "zh": "培根", "en": "bacon" },
        { "zh": "火腿", "en": "ham" },
        { "zh": "烟熏肉", "en": "smoked meat" },
        { "zh": "西式早餐", "en": "Western breakfast" },
        { "zh": "全日餐", "en": "all-day breakfast" },
        { "zh": "Brunch", "en": "brunch" }
      ]
    },
    {
      "name": "点心 (Dim Sum)",
      "tags": [
        { "zh": "广式点心", "en": "Cantonese dim sum" },
        { "zh": "虾饺", "en": "har gow (shrimp dumpling)" },
        { "zh": "烧卖", "en": "siu mai (pork and shrimp dumpling)" },
        { "zh": "叉烧包", "en": "char siu bao (BBQ pork bun)" },
        { "zh": "肠粉", "en": "cheung fun (rice noodle roll)" },
        { "zh": "排骨", "en": "steamed spare ribs" },
        { "zh": "凤爪", "en": "chicken feet" },
        { "zh": "糯米鸡", "en": "lo mai gai (sticky rice in lotus leaf)" },
        { "zh": "流沙包", "en": "liu sha bao (custard bun)" },
        { "zh": "萝卜糕", "en": "lo bak go (radish cake)" },
        { "zh": "马蹄糕", "en": "water chestnut cake" },
        { "zh": "蛋挞", "en": "egg tart" },
        { "zh": "椰挞", "en": "coconut tart" },
        { "zh": "榴莲酥", "en": "durian pastry" },
        { "zh": "叉烧酥", "en": "char siu sou (BBQ pork puff)" },
        { "zh": "油炸鬼", "en": "youtiao (fried dough stick)" },
        { "zh": "咸水角", "en": "ham sui gok (fried glutinous rice dumpling)" },
        { "zh": "春卷", "en": "spring roll" },
        { "zh": "蒸饺", "en": "steamed dumplings" },
        { "zh": "煎饺", "en": "pan-fried dumplings" },
        { "zh": "汤饺", "en": "dumplings in soup" },
        { "zh": "水晶包", "en": "crystal bun" },
        { "zh": "豆沙包", "en": "red bean paste bun" },
        { "zh": "莲蓉包", "en": "lotus seed paste bun" },
        { "zh": "奶黄包", "en": "custard bun" },
        { "zh": "凤眼饺", "en": "phoenix eye dumpling" },
        { "zh": "猪肚", "en": "steamed pig stomach" },
        { "zh": "牛百叶", "en": "steamed beef tripe" },
        { "zh": "金钱肚", "en": "steamed beef omasum" },
        { "zh": "流心西多士", "en": "flowing custard French toast" },
        { "zh": "蒸制", "en": "steamed" },
        { "zh": "煎制", "en": "pan-fried" },
        { "zh": "炸制", "en": "deep-fried" },
        { "zh": "烘烤", "en": "baked" },
        { "zh": "广式茶点", "en": "Cantonese tea snacks" },
        { "zh": "中式糕点", "en": "Chinese pastry" },
        { "zh": "苏式点心", "en": "Suzhou style dim sum" },
        { "zh": "京式点心", "en": "Beijing style dim sum" },
        { "zh": "各地小吃", "en": "local snacks" },
        { "zh": "早点", "en": "breakfast items" },
        { "zh": "午茶", "en": "afternoon tea" },
        { "zh": "夜宵", "en": "late-night snacks" },
        { "zh": "咸味点心", "en": "savory dim sum" },
        { "zh": "甜味点心", "en": "sweet dim sum" },
        { "zh": "松软", "en": "fluffy" },
        { "zh": "Q弹", "en": "chewy/bouncy" },
        { "zh": "饱满馅料", "en": "generous filling" },
        { "zh": "酥皮", "en": "flaky pastry" },
        { "zh": "外焦里嫩", "en": "crispy outside, tender inside" },
        { "zh": "点心师傅", "en": "dim sum master" },
        { "zh": "传统制作", "en": "traditional preparation" },
        { "zh": "手工制作", "en": "handmade" },
        { "zh": "新鲜出炉", "en": "freshly baked/steamed" },
        { "zh": "港式", "en": "Hong Kong style" },
        { "zh": "粤式", "en": "Cantonese style" }
      ]
    },
    {
      "name": "糕点 (Pastry)",
      "tags": [
        { "zh": "中式糕点", "en": "Chinese traditional pastry" },
        { "zh": "月饼", "en": "mooncake" },
        { "zh": "广式月饼", "en": "Cantonese mooncake" },
        { "zh": "苏式月饼", "en": "Suzhou mooncake" },
        { "zh": "京式月饼", "en": "Beijing mooncake" },
        { "zh": "滇式月饼", "en": "Yunnan mooncake" },
        { "zh": "冰皮月饼", "en": "snow skin mooncake" },
        { "zh": "鲜肉月饼", "en": "fresh meat mooncake" },
        { "zh": "五仁月饼", "en": "five nut mooncake" },
        { "zh": "豆沙月饼", "en": "red bean paste mooncake" },
        { "zh": "蛋黄莲蓉月饼", "en": "salted egg yolk lotus seed paste mooncake" },
        { "zh": "青团", "en": "Qingtuan (green glutinous rice balls)" },
        { "zh": "麻花", "en": "mafa (fried dough twist)" },
        { "zh": "绿豆糕", "en": "mung bean cake" },
        { "zh": "桂花糕", "en": "Osmanthus cake" },
        { "zh": "发糕", "en": "steamed sponge cake" },
        { "zh": "重阳糕", "en": "Chongyang cake" },
        { "zh": "年糕", "en": "Nian gao (rice cake)" },
        { "zh": "驴打滚", "en": "Ludagou (rolling donkey)" },
        { "zh": "艾窝窝", "en": "Aiwo Wo (steamed glutinous rice cake)" },
        { "zh": "萨其马", "en": "Sachima (caramelized crisps)" },
        { "zh": "老婆饼", "en": "Wife cake" },
        { "zh": "老公饼", "en": "Husband cake" },
        { "zh": "凤梨酥", "en": "pineapple cake" },
        { "zh": "蛋黄酥", "en": "salted egg yolk pastry" },
        { "zh": "桃酥", "en": "walnut cookies" },
        { "zh": "饼干", "en": "cookies" },
        { "zh": "中式饼干", "en": "Chinese cookies" },
        { "zh": "云片糕", "en": "Yunpiangao (sliced rice cake)" },
        { "zh": "芡实糕", "en": "Makhana cake" },
        { "zh": "荷花酥", "en": "lotus puff pastry" },
        { "zh": "西式糕点", "en": "Western pastry" },
        { "zh": "蛋糕", "en": "cake" },
        { "zh": "生日蛋糕", "en": "birthday cake" },
        { "zh": "婚礼蛋糕", "en": "wedding cake" },
        { "zh": "纸杯蛋糕", "en": "cupcake" },
        { "zh": "芝士蛋糕", "en": "cheesecake" },
        { "zh": "纽约芝士蛋糕", "en": "New York cheesecake" },
        { "zh": "提拉米苏芝士蛋糕", "en": "tiramisu cheesecake" },
        { "zh": "轻乳酪蛋糕", "en": "light cheesecake" },
        { "zh": "慕斯蛋糕", "en": "mousse cake" },
        { "zh": "巧克力蛋糕", "en": "chocolate cake" },
        { "zh": "黑森林蛋糕", "en": "Black Forest cake" },
        { "zh": "红丝绒蛋糕", "en": "red velvet cake" },
        { "zh": "海绵蛋糕", "en": "sponge cake" },
        { "zh": "戚风蛋糕", "en": "chiffon cake" },
        { "zh": "裱花蛋糕", "en": "decorated cake" },
        { "zh": "翻糖蛋糕", "en": "fondant cake" },
        { "zh": "千层蛋糕", "en": "crepe cake" },
        { "zh": "磅蛋糕", "en": "pound cake" },
        { "zh": "面包", "en": "bread" },
        { "zh": "吐司", "en": "toast" },
        { "zh": "法式面包", "en": "baguette" },
        { "zh": "可颂", "en": "croissant" },
        { "zh": "丹麦面包", "en": "Danish pastry" },
        { "zh": "甜甜圈", "en": "donut" },
        { "zh": "司康", "en": "scone" },
        { "zh": "松饼", "en": "muffin" },
        { "zh": "华夫饼", "en": "waffle" },
        { "zh": "煎饼", "en": "pancake" },
        { "zh": "马卡龙", "en": "macaron" },
        { "zh": "泡芙", "en": "cream puff" },
        { "zh": "挞", "en": "tart" },
        { "zh": "派", "en": "pie" },
        { "zh": "苹果派", "en": "apple pie" },
        { "zh": "曲奇", "en": "cookie" },
        { "zh": "布朗尼", "en": "brownie" },
        { "zh": "羊角面包", "en": "croissant" },
        { "zh": "闪电泡芙", "en": "eclair" },
        { "zh": "歌剧院蛋糕", "en": "Opera cake" },
        { "zh": "蒙布朗", "en": "Mont Blanc" },
        { "zh": "可丽饼", "en": "crepe" },
        { "zh": "吉士", "en": "custard" },
        { "zh": "法式吐司", "en": "French toast" },
        { "zh": "烘烤", "en": "baked" },
        { "zh": "蒸制", "en": "steamed" },
        { "zh": "蓬松", "en": "fluffy" },
        { "zh": "湿润", "en": "moist" },
        { "zh": "酥脆", "en": "crispy/flaky" },
        { "zh": "香甜", "en": "sweet and fragrant" },
        { "zh": "绵密", "en": "dense and smooth" },
        { "zh": "入口即化", "en": "melts in your mouth" },
        { "zh": "多层", "en": "layered" },
        { "zh": "节日糕点", "en": "festive pastry" },
        { "zh": "伴手礼", "en": "souvenir pastry" },
        { "zh": "下午茶点心", "en": "afternoon tea pastry" },
        { "zh": "早餐糕点", "en": "breakfast pastry" },
        { "zh": "精致甜点", "en": "delicate dessert" },
        { "zh": "奶油", "en": "cream" },
        { "zh": "水果装饰", "en": "fruit decoration" },
        { "zh": "巧克力装饰", "en": "chocolate decoration" },
        { "zh": "糖霜", "en": "icing" },
        { "zh": "鲜奶油", "en": "whipped cream" },
        { "zh": "烘焙坊", "en": "bakery" },
        { "zh": "糕点师傅", "en": "pastry chef" },
        { "zh": "手工烘焙", "en": "handmade baking" }
      ]
    },
    {
      "name": "甜点 (Dessert)",
      "tags": [
        { "zh": "冰淇淋", "en": "ice cream" },
        { "zh": "圣代", "en": "sundae" },
        { "zh": "甜筒", "en": "ice cream cone" },
        { "zh": "雪糕", "en": "popsicle" },
        { "zh": "冰棒", "en": "ice pop" },
        { "zh": "意式冰淇淋", "en": "gelato" },
        { "zh": "雪芭", "en": "sorbet" },
        { "zh": "酸奶", "en": "yogurt" },
        { "zh": "酸奶酪", "en": "parfait" },
        { "zh": "冻酸奶", "en": "frozen yogurt" },
        { "zh": "布丁", "en": "pudding" },
        { "zh": "焦糖布丁", "en": "creme brulee" },
        { "zh": "巧克力布丁", "en": "chocolate pudding" },
        { "zh": "牛奶布丁", "en": "milk pudding" },
        { "zh": "芒果布丁", "en": "mango pudding" },
        { "zh": "提拉米苏", "en": "tiramisu" },
        { "zh": "慕斯", "en": "mousse" },
        { "zh": "巧克力慕斯", "en": "chocolate mousse" },
        { "zh": "水果慕斯", "en": "fruit mousse" },
        { "zh": "巧克力", "en": "chocolate" },
        { "zh": "巧克力棒", "en": "chocolate bar" },
        { "zh": "松露巧克力", "en": "chocolate truffle" },
        { "zh": "巧克力喷泉", "en": "chocolate fountain" },
        { "zh": "巧克力熔岩蛋糕", "en": "chocolate lava cake" },
        { "zh": "巧克力酱", "en": "chocolate sauce" },
        { "zh": "奶酪", "en": "cheese" },
        { "zh": "芝士拼盘", "en": "cheese platter" },
        { "zh": "舒芙蕾", "en": "soufflé" },
        { "zh": "水果沙拉", "en": "fruit salad" },
        { "zh": "水果捞", "en": "fruit dessert bowl" },
        { "zh": "班戟", "en": "mango pancake" },
        { "zh": "杨枝甘露", "en": "Yangzhi Ganlu (mango pomelo sago)" },
        { "zh": "双皮奶", "en": "double-skin milk pudding" },
        { "zh": "姜撞奶", "en": "ginger milk curd" },
        { "zh": "酒酿圆子", "en": "fermented glutinous rice balls" },
        { "zh": "红豆沙", "en": "red bean paste soup" },
        { "zh": "绿豆沙", "en": "mung bean paste soup" },
        { "zh": "芝麻糊", "en": "black sesame paste" },
        { "zh": "凉粉", "en": "grass jelly" },
        { "zh": "芋圆", "en": "taro balls" },
        { "zh": "仙草", "en": "herbal jelly" },
        { "zh": "龟苓膏", "en": "Guilinggao (tortoise jelly)" },
        { "zh": "冰粉", "en": "ice jelly" },
        { "zh": "刨冰", "en": "shaved ice" },
        { "zh": "雪花冰", "en": "Korean shaved ice" },
        { "zh": "绵绵冰", "en": "fluffy shaved ice" },
        { "zh": "甜品杯", "en": "dessert cup" },
        { "zh": "甜甜圈", "en": "donut" },
        { "zh": "马芬", "en": "muffin" },
        { "zh": "曲奇", "en": "cookie" },
        { "zh": "焦糖", "en": "caramel" },
        { "zh": "焦糖酱", "en": "caramel sauce" },
        { "zh": "奶油", "en": "cream" },
        { "zh": "鲜奶油", "en": "whipped cream" },
        { "zh": "糖浆", "en": "syrup" },
        { "zh": "蜂蜜", "en": "honey" },
        { "zh": "坚果", "en": "nuts" },
        { "zh": "果酱", "en": "jam" },
        { "zh": "巧克力碎", "en": "chocolate chips" },
        { "zh": "薄荷叶", "en": "mint leaves" },
        { "zh": "香草", "en": "vanilla" },
        { "zh": "肉桂", "en": "cinnamon" },
        { "zh": "可可粉", "en": "cocoa powder" },
        { "zh": "糖粉", "en": "powdered sugar" },
        { "zh": "淋面", "en": "glaze/ganache" },
        { "zh": "糖渍水果", "en": "candied fruit" },
        { "zh": "摆盘", "en": "plating" },
        { "zh": "装饰", "en": "garnish" },
        { "zh": "夏日甜点", "en": "summer dessert" },
        { "zh": "冬日甜点", "en": "winter dessert" },
        { "zh": "节日限定", "en": "holiday special" },
        { "zh": "甜而不腻", "en": "sweet but not cloying" },
        { "zh": "凉爽", "en": "cooling" },
        { "zh": "绵密", "en": "smooth and dense" },
        { "zh": "清爽", "en": "refreshing" },
        { "zh": "冻", "en": "chilled/frozen" },
        { "zh": "温暖", "en": "warm" },
        { "zh": "治愈系", "en": "comfort food" },
        { "zh": "分子甜点", "en": "molecular dessert" },
        { "zh": "创意甜点", "en": "creative dessert" },
        { "zh": "手工冰淇淋", "en": "handmade ice cream" },
        { "zh": "冰淇淋球", "en": "scoop of ice cream" },
        { "zh": "水果粒", "en": "fruit bits" },
        { "zh": "饼干碎", "en": "cookie crumbs" },
        { "zh": "燕麦脆", "en": "oat clusters" },
        { "zh": "巧克力屑", "en": "chocolate flakes" }
      ]
    },
    {
      "name": "水果 (Fruit)",
      "tags": [
        { "zh": "苹果", "en": "apple" },
        { "zh": "蛇果", "en": "red delicious apple" },
        { "zh": "富士苹果", "en": "Fuji apple" },
        { "zh": "香蕉", "en": "banana" },
        { "zh": "皇帝蕉", "en": "Dwarf Cavendish banana" },
        { "zh": "橘子", "en": "orange" },
        { "zh": "橙子", "en": "orange" },
        { "zh": "脐橙", "en": "navel orange" },
        { "zh": "血橙", "en": "blood orange" },
        { "zh": "柠檬", "en": "lemon" },
        { "zh": "青柠", "en": "lime" },
        { "zh": "葡萄", "en": "grape" },
        { "zh": "红提", "en": "red grape" },
        { "zh": "青提", "en": "green grape" },
        { "zh": "巨峰葡萄", "en": "Kyoho grape" },
        { "zh": "草莓", "en": "strawberry" },
        { "zh": "蓝莓", "en": "blueberry" },
        { "zh": "树莓", "en": "raspberry" },
        { "zh": "黑莓", "en": "blackberry" },
        { "zh": "樱桃", "en": "cherry" },
        { "zh": "车厘子", "en": "cherry" },
        { "zh": "西瓜", "en": "watermelon" },
        { "zh": "甜王西瓜", "en": "Densuke watermelon" },
        { "zh": "冰糖西瓜", "en": "rock candy watermelon" },
        { "zh": "哈密瓜", "en": "cantaloupe" },
        { "zh": "甜瓜", "en": "melon" },
        { "zh": "蜜瓜", "en": "honeydew melon" },
        { "zh": "芒果", "en": "mango" },
        { "zh": "台芒", "en": "Taiwan mango" },
        { "zh": "金煌芒", "en": "Jin Huang mango" },
        { "zh": "菠萝", "en": "pineapple" },
        { "zh": "凤梨", "en": "pineapple (Taiwanese)" },
        { "zh": "奇异果", "en": "kiwi" },
        { "zh": "猕猴桃", "en": "kiwi fruit" },
        { "zh": "阳光金果", "en": "Sungold kiwi" },
        { "zh": "火龙果", "en": "dragon fruit" },
        { "zh": "红心火龙果", "en": "red dragon fruit" },
        { "zh": "牛油果", "en": "avocado" },
        { "zh": "梨", "en": "pear" },
        { "zh": "鸭梨", "en": "Ya pear" },
        { "zh": "香梨", "en": "fragrant pear" },
        { "zh": "桃子", "en": "peach" },
        { "zh": "水蜜桃", "en": "honey peach" },
        { "zh": "油桃", "en": "nectarine" },
        { "zh": "李子", "en": "plum" },
        { "zh": "杏子", "en": "apricot" },
        { "zh": "柿子", "en": "persimmon" },
        { "zh": "脆柿", "en": "crisp persimmon" },
        { "zh": "石榴", "en": "pomegranate" },
        { "zh": "无花果", "en": "fig" },
        { "zh": "枣", "en": "dates" },
        { "zh": "冬枣", "en": "winter jujube" },
        { "zh": "红枣", "en": "red date" },
        { "zh": "荔枝", "en": "lychee" },
        { "zh": "妃子笑", "en": "Feizixiao lychee" },
        { "zh": "桂味荔枝", "en": "Guiwei lychee" },
        { "zh": "龙眼", "en": "longan" },
        { "zh": "榴莲", "en": "durian" },
        { "zh": "猫山王榴莲", "en": "Musang King durian" },
        { "zh": "金枕榴莲", "en": "Monthong durian" },
        { "zh": "山竹", "en": "mangosteen" },
        { "zh": "百香果", "en": "passion fruit" },
        { "zh": "椰子", "en": "coconut" },
        { "zh": "青椰", "en": "green coconut" },
        { "zh": "黄椰", "en": "yellow coconut" },
        { "zh": "甘蔗", "en": "sugarcane" },
        { "zh": "荸荠", "en": "water chestnut" },
        { "zh": "杨梅", "en": "bayberry" },
        { "zh": "桑葚", "en": "mulberry" },
        { "zh": "枸杞", "en": "goji berry" },
        { "zh": "蔓越莓", "en": "cranberry" },
        { "zh": "黑加仑", "en": "blackcurrant" },
        { "zh": "红醋栗", "en": "redcurrant" },
        { "zh": "杨桃", "en": "star fruit" },
        { "zh": "菠萝蜜", "en": "jackfruit" },
        { "zh": "番石榴", "en": "guava" },
        { "zh": "红毛丹", "en": "rambutan" },
        { "zh": "罗汉果", "en": "monk fruit" },
        { "zh": "丑柑", "en": "dekopon orange" },
        { "zh": "耙耙柑", "en": "Papa Gan (Chinese citrus)" },
        { "zh": "青枣", "en": "green jujube" },
        { "zh": "人心果", "en": "sapodilla" },
        { "zh": "莲雾", "en": "wax apple" },
        { "zh": "嘉宝果", "en": "jabuticaba" },
        { "zh": "火参果", "en": "kiwano" },
        { "zh": "金桔", "en": "kumquat" },
        { "zh": "黄皮", "en": "Wampee" },
        { "zh": "金星果", "en": "star apple" },
        { "zh": "百香果", "en": "passion fruit" },
        { "zh": "人参果", "en": "ginseng fruit" },
        { "zh": "新鲜水果", "en": "fresh fruit" },
        { "zh": "热带水果", "en": "tropical fruit" },
        { "zh": "亚热带水果", "en": "subtropical fruit" },
        { "zh": "温带水果", "en": "temperate fruit" },
        { "zh": "浆果", "en": "berries" },
        { "zh": "柑橘类", "en": "citrus fruits" },
        { "zh": "核果类", "en": "stone fruits" },
        { "zh": "仁果类", "en": "pome fruits" },
        { "zh": "切片水果", "en": "sliced fruit" },
        { "zh": "水果拼盘", "en": "fruit platter" },
        { "zh": "水果杯", "en": "fruit cup" },
        { "zh": "多汁", "en": "juicy" },
        { "zh": "清甜", "en": "sweet and refreshing" },
        { "zh": "酸甜", "en": "sweet and sour" },
        { "zh": "浓郁", "en": "intense flavor" },
        { "zh": "香气浓郁", "en": "fragrant" },
        { "zh": "色彩鲜艳", "en": "vibrant colors" },
        { "zh": "季节水果", "en": "seasonal fruit" },
        { "zh": "有机水果", "en": "organic fruit" },
        { "zh": "现摘", "en": "freshly picked" },
        { "zh": "天然", "en": "natural" },
        { "zh": "维生素", "en": "vitamins" },
        { "zh": "膳食纤维", "en": "dietary fiber" },
        { "zh": "抗氧化", "en": "antioxidant" }
      ]
    },
    {
      "name": "饮品 (Beverage)",
      "tags": [
        { "zh": "咖啡", "en": "coffee" },
        { "zh": "拿铁", "en": "latte" },
        { "zh": "卡布奇诺", "en": "cappuccino" },
        { "zh": "美式咖啡", "en": "Americano" },
        { "zh": "意式浓缩", "en": "espresso" },
        { "zh": "摩卡", "en": "mocha" },
        { "zh": "焦糖玛奇朵", "en": "caramel macchiato" },
        { "zh": "馥芮白", "en": "flat white" },
        { "zh": "冰咖啡", "en": "iced coffee" },
        { "zh": "手冲咖啡", "en": "pour-over coffee" },
        { "zh": "冷萃咖啡", "en": "cold brew coffee" },
        { "zh": "星冰乐", "en": "Frappuccino" },
        { "zh": "咖啡豆", "en": "coffee beans" },
        { "zh": "咖啡粉", "en": "ground coffee" },
        { "zh": "茶", "en": "tea" },
        { "zh": "红茶", "en": "black tea" },
        { "zh": "绿茶", "en": "green tea" },
        { "zh": "乌龙茶", "en": "oolong tea" },
        { "zh": "普洱茶", "en": "Pu'er tea" },
        { "zh": "白茶", "en": "white tea" },
        { "zh": "黄茶", "en": "yellow tea" },
        { "zh": "花草茶", "en": "herbal tea" },
        { "zh": "菊花茶", "en": "chrysanthemum tea" },
        { "zh": "玫瑰花茶", "en": "rose tea" },
        { "zh": "姜茶", "en": "ginger tea" },
        { "zh": "水果茶", "en": "fruit tea" },
        { "zh": "奶茶", "en": "milk tea" },
        { "zh": "珍珠奶茶", "en": "bubble tea" },
        { "zh": "港式奶茶", "en": "Hong Kong style milk tea" },
        { "zh": "台式奶茶", "en": "Taiwanese milk tea" },
        { "zh": "果汁", "en": "juice" },
        { "zh": "橙汁", "en": "orange juice" },
        { "zh": "苹果汁", "en": "apple juice" },
        { "zh": "西瓜汁", "en": "watermelon juice" },
        { "zh": "混合果汁", "en": "mixed fruit juice" },
        { "zh": "鲜榨果汁", "en": "freshly squeezed juice" },
        { "zh": "蔬菜汁", "en": "vegetable juice" },
        { "zh": "芹菜汁", "en": "celery juice" },
        { "zh": "番茄汁", "en": "tomato juice" },
        { "zh": "冰沙", "en": "smoothie" },
        { "zh": "奶昔", "en": "milkshake" },
        { "zh": "可乐", "en": "Coke" },
        { "zh": "雪碧", "en": "Sprite" },
        { "zh": "芬达", "en": "Fanta" },
        { "zh": "苏打水", "en": "soda water" },
        { "zh": "气泡水", "en": "sparkling water" },
        { "zh": "汤力水", "en": "tonic water" },
        { "zh": "碳酸饮料", "en": "carbonated drink" },
        { "zh": "酒类", "en": "alcoholic beverages" },
        { "zh": "啤酒", "en": "beer" },
        { "zh": "精酿啤酒", "en": "craft beer" },
        { "zh": "葡萄酒", "en": "wine" },
        { "zh": "红酒", "en": "red wine" },
        { "zh": "白葡萄酒", "en": "white wine" },
        { "zh": "起泡酒", "en": "sparkling wine" },
        { "zh": "香槟", "en": "champagne" },
        { "zh": "鸡尾酒", "en": "cocktail" },
        { "zh": "莫吉托", "en": "Mojito" },
        { "zh": "玛格丽塔", "en": "Margarita" },
        { "zh": "血腥玛丽", "en": "Bloody Mary" },
        { "zh": "威士忌", "en": "whiskey" },
        { "zh": "伏特加", "en": "vodka" },
        { "zh": "朗姆酒", "en": "rum" },
        { "zh": "金酒", "en": "gin" },
        { "zh": "白酒", "en": "Baijiu" },
        { "zh": "黄酒", "en": "Huangjiu (yellow wine)" },
        { "zh": "清酒", "en": "sake" },
        { "zh": "烧酒", "en": "soju" },
        { "zh": "奶制品", "en": "dairy products" },
        { "zh": "牛奶", "en": "milk" },
        { "zh": "酸奶", "en": "yogurt" },
        { "zh": "豆浆", "en": "soy milk" },
        { "zh": "椰奶", "en": "coconut milk" },
        { "zh": "燕麦奶", "en": "oat milk" },
        { "zh": "杏仁奶", "en": "almond milk" },
        { "zh": "乳清蛋白", "en": "whey protein" },
        { "zh": "纯净水", "en": "pure water" },
        { "zh": "矿泉水", "en": "mineral water" },
        { "zh": "热水", "en": "hot water" },
        { "zh": "冰水", "en": "iced water" },
        { "zh": "健康饮品", "en": "healthy drink" },
        { "zh": "无酒精饮品", "en": "non-alcoholic drink" },
        { "zh": "调制饮品", "en": "mixed drink" },
        { "zh": "冷饮", "en": "cold drink" },
        { "zh": "热饮", "en": "hot drink" },
        { "zh": "清凉", "en": "cooling/refreshing" },
        { "zh": "解渴", "en": "thirst-quenching" },
        { "zh": "气泡丰富", "en": "bubbly" },
        { "zh": "颜色诱人", "en": "appealing color" },
        { "zh": "搭配", "en": "pairing" },
        { "zh": "拉花", "en": "latte art" },
        { "zh": "茶道", "en": "tea ceremony" },
        { "zh": "酒文化", "en": "wine culture" },
        { "zh": "特饮", "en": "specialty drink" },
        { "zh": "季节限定", "en": "seasonal limited" },
        { "zh": "手作饮品", "en": "handmade beverage" }
      ]
    },
    {
      "name": "食材 (Ingredients)",
      "tags": [
        { "zh": "肉类", "en": "meat" },
        { "zh": "牛肉", "en": "beef" },
        { "zh": "猪肉", "en": "pork" },
        { "zh": "鸡肉", "en": "chicken" },
        { "zh": "鸭肉", "en": "duck meat" },
        { "zh": "羊肉", "en": "lamb" },
        { "zh": "鱼肉", "en": "fish meat" },
        { "zh": "海鲜", "en": "seafood" },
        { "zh": "虾", "en": "shrimp" },
        { "zh": "对虾", "en": "prawn" },
        { "zh": "龙虾", "en": "lobster" },
        { "zh": "蟹", "en": "crab" },
        { "zh": "扇贝", "en": "scallop" },
        { "zh": "牡蛎", "en": "oyster" },
        { "zh": "蛤蜊", "en": "clam" },
        { "zh": "青口", "en": "mussel" },
        { "zh": "鱿鱼", "en": "squid" },
        { "zh": "章鱼", "en": "octopus" },
        { "zh": "三文鱼", "en": "salmon" },
        { "zh": "金枪鱼", "en": "tuna" },
        { "zh": "鳕鱼", "en": "cod" },
        { "zh": "蔬菜", "en": "vegetables" },
        { "zh": "西兰花", "en": "broccoli" },
        { "zh": "菜花", "en": "cauliflower" },
        { "zh": "胡萝卜", "en": "carrot" },
        { "zh": "土豆", "en": "potato" },
        { "zh": "番茄", "en": "tomato" },
        { "zh": "洋葱", "en": "onion" },
        { "zh": "大蒜", "en": "garlic" },
        { "zh": "生姜", "en": "ginger" },
        { "zh": "青椒", "en": "green pepper" },
        { "zh": "辣椒", "en": "chili" },
        { "zh": "蘑菇", "en": "mushroom" },
        { "zh": "香菇", "en": "shiitake mushroom" },
        { "zh": "金针菇", "en": "enoki mushroom" },
        { "zh": "木耳", "en": "wood ear mushroom" },
        { "zh": "玉米", "en": "corn" },
        { "zh": "豌豆", "en": "peas" },
        { "zh": "豆角", "en": "green beans" },
        { "zh": "豆腐", "en": "tofu" },
        { "zh": "豆干", "en": "dried tofu" },
        { "zh": "豆芽", "en": "bean sprouts" },
        { "zh": "叶菜", "en": "leafy greens" },
        { "zh": "白菜", "en": "Chinese cabbage" },
        { "zh": "菠菜", "en": "spinach" },
        { "zh": "生菜", "en": "lettuce" },
        { "zh": "卷心菜", "en": "cabbage" },
        { "zh": "鸡蛋", "en": "egg" },
        { "zh": "鸭蛋", "en": "duck egg" },
        { "zh": "鹌鹑蛋", "en": "quail egg" },
        { "zh": "米饭", "en": "rice" },
        { "zh": "糙米", "en": "brown rice" },
        { "zh": "糯米", "en": "glutinous rice" },
        { "zh": "面条", "en": "noodles" },
        { "zh": "面粉", "en": "flour" },
        { "zh": "小麦粉", "en": "wheat flour" },
        { "zh": "玉米粉", "en": "cornmeal" },
        { "zh": "香料", "en": "spices" },
        { "zh": "花椒", "en": "Sichuan peppercorn" },
        { "zh": "八角", "en": "star anise" },
        { "zh": "桂皮", "en": "cinnamon stick" },
        { "zh": "小茴香", "en": "cumin" },
        { "zh": "香叶", "en": "bay leaf" },
        { "zh": "香草", "en": "herbs" },
        { "zh": "罗勒", "en": "basil" },
        { "zh": "迷迭香", "en": "rosemary" },
        { "zh": "牛至", "en": "oregano" },
        { "zh": "百里香", "en": "thyme" },
        { "zh": "香菜", "en": "cilantro/coriander" },
        { "zh": "香葱", "en": "scallion" },
        { "zh": "食盐", "en": "salt" },
        { "zh": "糖", "en": "sugar" },
        { "zh": "酱油", "en": "soy sauce" },
        { "zh": "醋", "en": "vinegar" },
        { "zh": "食用油", "en": "cooking oil" },
        { "zh": "橄榄油", "en": "olive oil" },
        { "zh": "芝麻油", "en": "sesame oil" },
        { "zh": "芝麻", "en": "sesame" },
        { "zh": "花生", "en": "peanut" },
        { "zh": "芝士", "en": "cheese" },
        { "zh": "牛奶", "en": "milk" },
        { "zh": "黄油", "en": "butter" },
        { "zh": "奶油", "en": "cream" },
        { "zh": "坚果", "en": "nuts" },
        { "zh": "核桃", "en": "walnut" },
        { "zh": "杏仁", "en": "almond" },
        { "zh": "腰果", "en": "cashew" },
        { "zh": "开心果", "en": "pistachio" },
        { "zh": "谷物", "en": "grains" },
        { "zh": "藜麦", "en": "quinoa" },
        { "zh": "燕麦", "en": "oats" },
        { "zh": "麦片", "en": "cereal" },
        { "zh": "调味料", "en": "seasoning" },
        { "zh": "骨头", "en": "bones" },
        { "zh": "骨汤", "en": "bone broth" },
        { "zh": "高汤", "en": "stock" },
        { "zh": "新鲜食材", "en": "fresh ingredients" },
        { "zh": "当季食材", "en": "seasonal ingredients" },
        { "zh": "有机食材", "en": "organic ingredients" },
        { "zh": "本地食材", "en": "local ingredients" },
        { "zh": "优质食材", "en": "premium ingredients" },
        { "zh": "蛋白质", "en": "protein" },
        { "zh": "碳水化合物", "en": "carbohydrates" },
        { "zh": "脂肪", "en": "fat" },
        { "zh": "纤维", "en": "fiber" },
        { "zh": "维生素", "en": "vitamins" },
        { "zh": "矿物质", "en": "minerals" },
        { "zh": "健康", "en": "healthy" },
        { "zh": "营养", "en": "nutritious" },
        { "zh": "天然", "en": "natural" },
        { "zh": "无添加", "en": "no additives" },
        { "zh": "原生态", "en": "eco-friendly/primitive" }
      ]
    },
    {
      "name": "烹饪方式 (Cooking Method)",
      "tags": [
        { "zh": "炒", "en": "stir-fry" },
        { "zh": "爆炒", "en": "quick stir-fry" },
        { "zh": "清炒", "en": "light stir-fry" },
        { "zh": "滑炒", "en": "velvet stir-fry" },
        { "zh": "煮", "en": "boil" },
        { "zh": "清煮", "en": "plain boil" },
        { "zh": "炖", "en": "stew" },
        { "zh": "红烧", "en": "braise in soy sauce" },
        { "zh": "清炖", "en": "simmer" },
        { "zh": "蒸", "en": "steam" },
        { "zh": "干蒸", "en": "dry steam" },
        { "zh": "油炸", "en": "deep-fry" },
        { "zh": "脆炸", "en": "crispy fry" },
        { "zh": "酥炸", "en": "fluffy fry" },
        { "zh": "干炸", "en": "dry fry" },
        { "zh": "烤", "en": "roast/bake" },
        { "zh": "炭烤", "en": "charcoal grill" },
        { "zh": "烧烤", "en": "grill/BBQ" },
        { "zh": "炙烤", "en": "broil" },
        { "zh": "煎", "en": "pan-fry" },
        { "zh": "香煎", "en": "fragrant pan-fry" },
        { "zh": "两面煎", "en": "pan-fry both sides" },
        { "zh": "煨", "en": "simmer slowly" },
        { "zh": "焗", "en": "bake/braise in casserole" },
        { "zh": "焖", "en": "braise/smother" },
        { "zh": "焯", "en": "blanch" },
        { "zh": "腌", "en": "marinate" },
        { "zh": "卤", "en": "braise in master stock" },
        { "zh": "熏", "en": "smoke" },
        { "zh": "凉拌", "en": "cold toss" },
        { "zh": "炝", "en": "quick stir-fry with oil and spices" },
        { "zh": "拔丝", "en": "sugar-coated (with pulling effect)" },
        { "zh": "糖醋", "en": "sweet and sour" },
        { "zh": "椒盐", "en": "salt and pepper" },
        { "zh": "蒜蓉", "en": "garlic paste" },
        { "zh": "啫啫", "en": "sizzling claypot" },
        { "zh": "烹", "en": "quick-fry and then braise" },
        { "zh": "扒", "en": "braise and serve with sauce" },
        { "zh": "溜", "en": "quick-fry and then thicken with starch" },
        { "zh": "醉", "en": "marinated in wine" },
        { "zh": "生食", "en": "raw consumption" },
        { "zh": "冷冻", "en": "frozen" },
        { "zh": "发酵", "en": "fermentation" },
        { "zh": "烘焙", "en": "baking" },
        { "zh": "油浸", "en": "confit/oil submerged" },
        { "zh": "低温慢煮", "en": "sous vide" },
        { "zh": "气炸", "en": "air fry" },
        { "zh": "微波", "en": "microwave" },
        { "zh": "明火", "en": "open flame" },
        { "zh": "文火", "en": "gentle heat" },
        { "zh": "武火", "en": "high heat" },
        { "zh": "烹调艺术", "en": "culinary art" },
        { "zh": "厨师技艺", "en": "chef's skill" },
        { "zh": "色香味俱全", "en": "perfect color, aroma, and taste" },
        { "zh": "刀工", "en": "knife skills" },
        { "zh": "火候", "en": "heat control" },
        { "zh": "调味", "en": "seasoning" },
        { "zh": "去腥", "en": "de-fishy" },
        { "zh": "入味", "en": "well-flavored" },
        { "zh": "汁多", "en": "juicy" },
        { "zh": "脆皮", "en": "crispy skin" },
        { "zh": "外酥里嫩", "en": "crispy outside, tender inside" },
        { "zh": "骨肉分离", "en": "meat falling off the bone" },
        { "zh": "回锅", "en": "re-cooked" },
        { "zh": "勾芡", "en": "thickening with starch" },
        { "zh": "上色", "en": "coloring" },
        { "zh": "收汁", "en": "reducing sauce" },
        { "zh": "过油", "en": "sauté briefly then deep-fry" },
        { "zh": "挂糊", "en": "coating with batter" },
        { "zh": "炸糊", "en": "frying with batter" },
        { "zh": "水煮", "en": "boiled" },
        { "zh": "油淋", "en": "oil drizzled" },
        { "zh": "腌制", "en": "cured/marinated" },
        { "zh": "烟熏", "en": "smoked" },
        { "zh": "风干", "en": "air-dried" },
        { "zh": "脱水", "en": "dehydrated" },
        { "zh": "还原", "en": "reconstituted" }
      ]
    },
    {
      "name": "器具 (Utensils/Tableware)",
      "tags": [
        { "zh": "盘子", "en": "plate" },
        { "zh": "餐盘", "en": "dinner plate" },
        { "zh": "沙拉盘", "en": "salad plate" },
        { "zh": "甜点盘", "en": "dessert plate" },
        { "zh": "碟子", "en": "saucer" },
        { "zh": "酱料碟", "en": "sauce dish" },
        { "zh": "碗", "en": "bowl" },
        { "zh": "饭碗", "en": "rice bowl" },
        { "zh": "汤碗", "en": "soup bowl" },
        { "zh": "沙拉碗", "en": "salad bowl" },
        { "zh": "餐具", "en": "cutlery" },
        { "zh": "刀", "en": "knife" },
        { "zh": "牛排刀", "en": "steak knife" },
        { "zh": "黄油刀", "en": "butter knife" },
        { "zh": "叉", "en": "fork" },
        { "zh": "勺子", "en": "spoon" },
        { "zh": "咖啡勺", "en": "coffee spoon" },
        { "zh": "汤勺", "en": "soup spoon" },
        { "zh": "筷子", "en": "chopsticks" },
        { "zh": "竹筷", "en": "bamboo chopsticks" },
        { "zh": "木筷", "en": "wooden chopsticks" },
        { "zh": "不锈钢筷", "en": "stainless steel chopsticks" },
        { "zh": "骨瓷", "en": "bone porcelain" },
        { "zh": "景德镇瓷器", "en": "Jingdezhen porcelain" },
        { "zh": "青瓷", "en": "celadon" },
        { "zh": "陶器", "en": "pottery" },
        { "zh": "玻璃器皿", "en": "glassware" },
        { "zh": "水杯", "en": "water glass" },
        { "zh": "玻璃杯", "en": "glass tumbler" },
        { "zh": "马克杯", "en": "mug" },
        { "zh": "茶杯", "en": "tea cup" },
        { "zh": "高脚杯", "en": "stemmed glass" },
        { "zh": "红酒杯", "en": "red wine glass" },
        { "zh": "白酒杯", "en": "white wine glass" },
        { "zh": "香槟杯", "en": "champagne flute" },
        { "zh": "鸡尾酒杯", "en": "cocktail glass" },
        { "zh": "咖啡杯", "en": "coffee cup" },
        { "zh": "茶壶", "en": "teapot" },
        { "zh": "水壶", "en": "kettle" },
        { "zh": "锅", "en": "pot" },
        { "zh": "炒锅", "en": "wok" },
        { "zh": "平底锅", "en": "frying pan" },
        { "zh": "砂锅", "en": "claypot" },
        { "zh": "高压锅", "en": "pressure cooker" },
        { "zh": "汤锅", "en": "saucepan" },
        { "zh": "蒸锅", "en": "steamer" },
        { "zh": "烤箱", "en": "oven" },
        { "zh": "微波炉", "en": "microwave oven" },
        { "zh": "冰箱", "en": "refrigerator" },
        { "zh": "洗碗机", "en": "dishwasher" },
        { "zh": "砧板", "en": "cutting board" },
        { "zh": "菜刀", "en": "cleaver" },
        { "zh": "厨师刀", "en": "chef's knife" },
        { "zh": "削皮器", "en": "peeler" },
        { "zh": "调料瓶", "en": "spice jar" },
        { "zh": "研磨器", "en": "grinder" },
        { "zh": "盐罐", "en": "salt shaker" },
        { "zh": "胡椒罐", "en": "pepper shaker" },
        { "zh": "餐垫", "en": "placemat" },
        { "zh": "桌布", "en": "tablecloth" },
        { "zh": "餐巾", "en": "napkin" },
        { "zh": "托盘", "en": "tray" },
        { "zh": "茶具", "en": "tea set" },
        { "zh": "咖啡机", "en": "coffee maker" },
        { "zh": "磨豆机", "en": "coffee grinder" },
        { "zh": "搅拌机", "en": "blender" },
        { "zh": "打蛋器", "en": "whisk" },
        { "zh": "计量勺", "en": "measuring spoon" },
        { "zh": "计量杯", "en": "measuring cup" },
        { "zh": "计时器", "en": "timer" },
        { "zh": "陶瓷", "en": "ceramic" },
        { "zh": "瓷器", "en": "porcelain" },
        { "zh": "木质", "en": "wooden" },
        { "zh": "金属", "en": "metal" },
        { "zh": "竹编", "en": "bamboo woven" },
        { "zh": "石器", "en": "stoneware" },
        { "zh": "不锈钢", "en": "stainless steel" },
        { "zh": "铸铁锅", "en": "cast iron pot" },
        { "zh": "精美餐具", "en": "gorgeous tableware" },
        { "zh": "复古餐具", "en": "vintage tableware" },
        { "zh": "现代餐具", "en": "modern tableware" },
        { "zh": "艺术餐具", "en": "artistic tableware" },
        { "zh": "传统餐具", "en": "traditional tableware" },
        { "zh": "厨房用具", "en": "kitchenware" },
        { "zh": "烹饪工具", "en": "cooking tools" },
        { "zh": "烘焙工具", "en": "baking tools" },
        { "zh": "厨具", "en": "kitchen utensils" },
        { "zh": "硅胶厨具", "en": "silicone kitchenware" },
        { "zh": "炉灶", "en": "stove" },
        { "zh": "油烟机", "en": "range hood" }
      ]
    },
    {
      "name": "餐饮场景 (Dining Scene/Environment)",
      "tags": [
        { "zh": "餐厅", "en": "restaurant" },
        { "zh": "高级餐厅", "en": "fine dining restaurant" },
        { "zh": "中餐厅", "en": "Chinese restaurant" },
        { "zh": "西餐厅", "en": "Western restaurant" },
        { "zh": "特色餐厅", "en": "specialty restaurant" },
        { "zh": "咖啡馆", "en": "cafe" },
        { "zh": "面包店", "en": "bakery" },
        { "zh": "甜点店", "en": "dessert shop" },
        { "zh": "酒吧", "en": "bar" },
        { "zh": "小酒馆", "en": "bistro" },
        { "zh": "美食广场", "en": "food court" },
        { "zh": "街边摊", "en": "street stall" },
        { "zh": "夜市", "en": "night market" },
        { "zh": "厨房", "en": "kitchen" },
        { "zh": "家庭厨房", "en": "home kitchen" },
        { "zh": "专业厨房", "en": "professional kitchen" },
        { "zh": "开放式厨房", "en": "open kitchen" },
        { "zh": "餐桌", "en": "dining table" },
        { "zh": "餐吧", "en": "dining bar" },
        { "zh": "厨房岛台", "en": "kitchen island" },
        { "zh": "户外用餐", "en": "outdoor dining" },
        { "zh": "露天餐厅", "en": "al fresco dining" },
        { "zh": "阳台用餐", "en": "balcony dining" },
        { "zh": "庭院用餐", "en": "patio dining" },
        { "zh": "野餐", "en": "picnic" },
        { "zh": "烧烤派对", "en": "BBQ party" },
        { "zh": "露营野炊", "en": "camping cooking" },
        { "zh": "海边晚餐", "en": "beach dinner" },
        { "zh": "湖畔野餐", "en": "lake picnic" },
        { "zh": "农场", "en": "farm" },
        { "zh": "菜市场", "en": "vegetable market" },
        { "zh": "超市", "en": "supermarket" },
        { "zh": "烹饪课堂", "en": "cooking class" },
        { "zh": "美食节", "en": "food festival" },
        { "zh": "美食之旅", "en": "food tour" },
        { "zh": "聚餐", "en": "gathering meal" },
        { "zh": "生日宴", "en": "birthday banquet" },
        { "zh": "节日大餐", "en": "holiday feast" },
        { "zh": "家庭聚会", "en": "family gathering" },
        { "zh": "朋友聚会", "en": "friends gathering" },
        { "zh": "约会晚餐", "en": "date night dinner" },
        { "zh": "商务午餐", "en": "business lunch" },
        { "zh": "下午茶", "en": "afternoon tea" },
        { "zh": "早餐", "en": "breakfast" },
        { "zh": "午餐", "en": "lunch" },
        { "zh": "晚餐", "en": "dinner" },
        { "zh": "夜宵", "en": "late night snack" },
        { "zh": "自助餐", "en": "buffet" },
        { "zh": "包间", "en": "private room" },
        { "zh": "酒吧氛围", "en": "bar atmosphere" },
        { "zh": "温馨", "en": "cozy" },
        { "zh": "浪漫", "en": "romantic" },
        { "zh": "热闹", "en": "lively" },
        { "zh": "繁忙", "en": "busy" },
        { "zh": "宁静", "en": "peaceful" },
        { "zh": "精致", "en": "exquisite" },
        { "zh": "奢华", "en": "luxurious" },
        { "zh": "简约", "en": "simple" },
        { "zh": "自然光", "en": "natural light" },
        { "zh": "柔和光线", "en": "soft lighting" },
        { "zh": "烛光", "en": "candlelight" },
        { "zh": "暖色调", "en": "warm tones" },
        { "zh": "木质桌面", "en": "wooden table" },
        { "zh": "大理石台面", "en": "marble countertop" },
        { "zh": "玻璃窗", "en": "glass window" },
        { "zh": "绿植点缀", "en": "green plant decor" },
        { "zh": "背景虚化", "en": "blurred background" },
        { "zh": "环境光", "en": "ambient lighting" },
        { "zh": "落地窗", "en": "floor-to-ceiling window" },
        { "zh": "城市景观", "en": "city view" },
        { "zh": "海景", "en": "sea view" },
        { "zh": "山景", "en": "mountain view" },
        { "zh": "花园景观", "en": "garden view" },
        { "zh": "工业风", "en": "industrial style" },
        { "zh": "复古", "en": "vintage" },
        { "zh": "现代", "en": "modern" },
        { "zh": "传统", "en": "traditional" },
        { "zh": "艺术画廊", "en": "art gallery setting" },
        { "zh": "集市", "en": "market" },
        { "zh": "外卖", "en": "takeaway/delivery" },
        { "zh": "打包", "en": "packed meal" },
        { "zh": "用餐体验", "en": "dining experience" },
        { "zh": "服务", "en": "service" },
        { "zh": "氛围", "en": "ambiance" },
        { "zh": "食客", "en": "diner/eater" },
        { "zh": "顾客", "en": "customer" }
      ]
    },
    {
      "name": "口感/风味 (Taste/Flavor Profile)",
      "tags": [
        { "zh": "甜", "en": "sweet" },
        { "zh": "咸", "en": "salty" },
        { "zh": "酸", "en": "sour" },
        { "zh": "辣", "en": "spicy" },
        { "zh": "苦", "en": "bitter" },
        { "zh": "鲜", "en": "umami/fresh" },
        { "zh": "麻", "en": "numbing (Sichuan peppercorn)" },
        { "zh": "香", "en": "fragrant/aromatic" },
        { "zh": "酥", "en": "crispy/flaky" },
        { "zh": "脆", "en": "crispy/crunchy" },
        { "zh": "嫩", "en": "tender" },
        { "zh": "滑", "en": "smooth" },
        { "zh": "爽", "en": "refreshing" },
        { "zh": "糯", "en": "glutinous/sticky" },
        { "zh": "软", "en": "soft" },
        { "zh": "Q弹", "en": "chewy/bouncy" },
        { "zh": "浓郁", "en": "rich/intense" },
        { "zh": "清淡", "en": "light/mild" },
        { "zh": "劲道", "en": "chewy (noodles/meat)" },
        { "zh": "多汁", "en": "juicy" },
        { "zh": "粘稠", "en": "viscous/thick" },
        { "zh": "清爽口感", "en": "crisp and refreshing taste" },
        { "zh": "油腻", "en": "greasy" },
        { "zh": "焦香", "en": "caramelized/toasted aroma" },
        { "zh": "奶香", "en": "milky aroma" },
        { "zh": "果香", "en": "fruity aroma" },
        { "zh": "酒香", "en": "alcoholic aroma" },
        { "zh": "烟熏", "en": "smoky" },
        { "zh": "微甜", "en": "slightly sweet" },
        { "zh": "微辣", "en": "slightly spicy" },
        { "zh": "酸甜口", "en": "sweet and sour (taste)" },
        { "zh": "咸鲜口", "en": "savory and fresh (taste)" },
        { "zh": "麻辣口", "en": "spicy and numbing (taste)" },
        { "zh": "回甘", "en": "sweet aftertaste" },
        { "zh": "层次丰富", "en": "rich in layers/complex flavors" },
        { "zh": "余韵悠长", "en": "long-lasting aftertaste" },
        { "zh": "平衡", "en": "balanced flavor" },
        { "zh": "刺激", "en": "stimulating/spicy" },
        { "zh": "独特", "en": "unique" },
        { "zh": "经典风味", "en": "classic flavor" },
        { "zh": "创新风味", "en": "innovative flavor" },
        { "zh": "诱人", "en": "tempting" },
        { "zh": "美味", "en": "delicious" },
        { "zh": "可口", "en": "tasty" },
        { "zh": "入口即化", "en": "melts in your mouth" },
        { "zh": "细腻", "en": "delicate/fine texture" },
        { "zh": "粗犷", "en": "robust/hearty" },
        { "zh": "饱满", "en": "full-bodied" },
        { "zh": "清脆", "en": "crisp (vegetables)" },
        { "zh": "软烂", "en": "soft and tender (braised meat)" },
        { "zh": "胶质", "en": "gelatinous" },
        { "zh": "弹牙", "en": "springy (seafood/noodles)" },
        { "zh": "醇厚", "en": "mellow/rich" },
        { "zh": "馥郁", "en": "rich and fragrant" },
        { "zh": "清香", "en": "lightly fragrant" },
        { "zh": "本味", "en": "original flavor" },
        { "zh": "纯正", "en": "pure" },
        { "zh": "复合", "en": "complex/compound" },
        { "zh": "焦糖化", "en": "caramelized" },
        { "zh": "发酵味", "en": "fermented taste" },
        { "zh": "烟熏味", "en": "smoky taste" },
        { "zh": "炭烧味", "en": "charred taste" },
        { "zh": "辛辣", "en": "pungent/hot spicy" },
        { "zh": "芳香", "en": "aromatic" },
        { "zh": "甘甜", "en": "sweet and refreshing" }
      ]
    },
    {
      "name": "其他 (Miscellaneous)",
      "tags": [
        { "zh": "美食博主", "en": "food blogger" },
        { "zh": "美食家", "en": "gourmet" },
        { "zh": "厨师", "en": "chef" },
        { "zh": "食谱", "en": "recipe" },
        { "zh": "烹饪过程", "en": "cooking process" },
        { "zh": "食材准备", "en": "ingredient preparation" },
        { "zh": "摆盘艺术", "en": "plating art" },
        { "zh": "食物特写", "en": "food close-up" },
        { "zh": "餐桌摆设", "en": "table setting" },
        { "zh": "美食道具", "en": "food props" },
        { "zh": "手部出镜", "en": "hands in frame" },
        { "zh": "冒热气", "en": "steaming hot" },
        { "zh": "新鲜出炉", "en": "freshly baked" },
        { "zh": "金黄酥脆", "en": "golden and crispy" },
        { "zh": "色彩鲜艳", "en": "vibrant colors" },
        { "zh": "食材丰富", "en": "rich ingredients" },
        { "zh": "视觉冲击", "en": "visual impact" },
        { "zh": "垂涎欲滴", "en": "mouth-watering" },
        { "zh": "食欲大增", "en": "appetite-boosting" },
        { "zh": "健康均衡", "en": "healthy and balanced" },
        { "zh": "生活方式", "en": "lifestyle" },
        { "zh": "美食体验", "en": "food experience" },
        { "zh": "文化", "en": "culture" },
        { "zh": "传统", "en": "tradition" },
        { "zh": "创新", "en": "innovation" },
        { "zh": "分享", "en": "sharing" },
        { "zh": "欢聚", "en": "gathering" },
        { "zh": "家庭感", "en": "homely feel" },
        { "zh": "精致感", "en": "exquisite feel" },
        { "zh": "高级感", "en": "high-end feel" },
        { "zh": "自然美", "en": "natural beauty" },
        { "zh": "烟火气", "en": "down-to-earth atmosphere" },
        { "zh": "人间烟火", "en": "human touch/lively atmosphere" },
        { "zh": "美食疗愈", "en": "food therapy" },
        { "zh": "独一无二", "en": "one-of-a-kind" },
        { "zh": "限时供应", "en": "limited time offer" },
        { "zh": "特色菜", "en": "specialty dish" },
        { "zh": "招牌菜", "en": "signature dish" },
        { "zh": "私房菜", "en": "private kitchen dish" },
        { "zh": "定制", "en": "customized" },
        { "zh": "手工制作", "en": "handmade" },
        { "zh": "匠心", "en": "craftsmanship" },
        { "zh": "历史悠久", "en": "long history" },
        { "zh": "老字号", "en": "time-honored brand" },
        { "zh": "现代", "en": "modern" },
        { "zh": "复古", "en": "vintage" },
        { "zh": "艺术", "en": "art" },
        { "zh": "团购", "en": "group buy" },
        { "zh": "优惠", "en": "discount" },
        { "zh": "会员专享", "en": "member exclusive" },
        { "zh": "外卖", "en": "takeaway" },
        { "zh": "外送", "en": "delivery" },
        { "zh": "预定", "en": "reservation" },
        { "zh": "排队", "en": "queue" },
        { "zh": "评价", "en": "review" },
        { "zh": "推荐", "en": "recommendation" },
        { "zh": "必吃榜", "en": "must-eat list" },
        { "zh": "探店", "en": "food exploring" },
        { "zh": "探访", "en": "visiting" },
        { "zh": "打卡", "en": "check-in" },
        { "zh": "沉浸式", "en": "immersive" },
        { "zh": "互动性", "en": "interactive" },
        { "zh": "科普", "en": "popular science" },
        { "zh": "小众", "en": "niche" },
        { "zh": "大众", "en": "popular" },
        { "zh": "国宴", "en": "state banquet" },
        { "zh": "珍馐", "en": "delicacy" },
        { "zh": "饕餮", "en": "gourmand feast" },
        { "zh": "食疗", "en": "dietary therapy" },
        { "zh": "应季", "en": "seasonal" },
        { "zh": "产地直供", "en": "direct from origin" },
        { "zh": "原生态", "en": "eco-authentic" },
        { "zh": "健康理念", "en": "health concept" },
        { "zh": "环保", "en": "eco-friendly" },
        { "zh": "可持续发展", "en": "sustainable development" },
        { "zh": "公平贸易", "en": "fair trade" },
        { "zh": "慢节奏", "en": "slow-paced" },
        { "zh": "快节奏", "en": "fast-paced" },
        { "zh": "城市生活", "en": "urban life" },
        { "zh": "乡村生活", "en": "country life" },
        { "zh": "厨房美学", "en": "kitchen aesthetics" },
        { "zh": "烘焙乐趣", "en": "baking fun" },
        { "zh": "烹饪技巧", "en": "cooking skills" },
        { "zh": "营养学", "en": "nutrition" },
        { "zh": "食品安全", "en": "food safety" },
        { "zh": "食品科学", "en": "food science" },
        { "zh": "创新菜品", "en": "innovative dishes" },
        { "zh": "传统工艺", "en": "traditional craftsmanship" },
        { "zh": "美食之旅", "en": "culinary journey" },
        { "zh": "味蕾体验", "en": "taste bud experience" },
        { "zh": "社群", "en": "community" },
        { "zh": "分享经济", "en": "sharing economy" },
        { "zh": "美食文创", "en": "food cultural and creative products" }
      ]
    }
  ]
});