tagData.push({
  "group": "植物 (Plants)",
  "categories": [
    {
      "name": "画风 (Art Style)",
      "tags": [
        { "zh": "写实主义", "en": "realistic" },
        { "zh": "超写实", "en": "hyperrealistic" },
        { "zh": "概念艺术", "en": "concept art" },
        { "zh": "幻想艺术", "en": "fantasy art" },
        { "zh": "数字绘画", "en": "digital painting" },
        { "zh": "油画风格", "en": "oil painting style" },
        { "zh": "水彩画风格", "en": "watercolor style" },
        { "zh": "素描", "en": "sketch style" },
        { "zh": "线条艺术", "en": "line art" },
        { "zh": "墨水画", "en": "ink drawing" },
        { "zh": "铅笔画", "en": "pencil drawing" },
        { "zh": "厚涂", "en": "impasto" },
        { "zh": "印象派", "en": "impressionistic" },
        { "zh": "表现主义", "en": "expressionistic" },
        { "zh": "抽象艺术", "en": "abstract art" },
        { "zh": "极简主义", "en": "minimalist style" },
        { "zh": "波普艺术", "en": "pop art" },
        { "zh": "新艺术运动", "en": "Art Nouveau" },
        { "zh": "装饰艺术", "en": "Art Deco" },
        { "zh": "剪影", "en": "silhouette" },
        { "zh": "卡通", "en": "cartoon" },
        { "zh": "动画风格", "en": "anime style" },
        { "zh": "美式卡通", "en": "American cartoon style" },
        { "zh": "迪士尼风格", "en": "Disney style" },
        { "zh": "皮克斯风格", "en": "Pixar style" },
        { "zh": "吉卜力风格", "en": "Ghibli style" },
        { "zh": "童书插画", "en": "children's book illustration" },
        { "zh": "植物学插画", "en": "botanical illustration" },
        { "zh": "科学插画", "en": "scientific illustration" },
        { "zh": "矢量图", "en": "vector art" },
        { "zh": "像素艺术", "en": "pixel art" },
        { "zh": "低多边形", "en": "low poly" },
        { "zh": "雕塑", "en": "sculpture" },
        { "zh": "玻璃艺术", "en": "stained glass art" }, // 琉璃
        { "zh": "剪纸艺术", "en": "papercut art" },
        { "zh": "折纸艺术", "en": "origami" },
        { "zh": "毛毡艺术", "en": "felt art" },
        { "zh": "刺绣艺术", "en": "embroidery art" },
        { "zh": "涂鸦风格", "en": "doodle style" },
        { "zh": "漫画风格", "en": "comic book style" },
        { "zh": "纹身艺术", "en": "tattoo art" },
        { "zh": "电影剧照", "en": "cinematic still" },
        { "zh": "动画截帧", "en": "animation frame" },
        { "zh": "游戏画面", "en": "game screenshot" },
        { "zh": "摄影", "en": "photography" },
        { "zh": "微距摄影", "en": "macro photography" },
        { "zh": "自然摄影", "en": "nature photography" },
        { "zh": "艺术摄影", "en": "artistic photography" },
        { "zh": "纪实摄影", "en": "documentary photography" },
        { "zh": "3D渲染", "en": "3D render" },
        { "zh": "CGI", "en": "CGI" },
        { "zh": "VFX", "en": "VFX" },
        { "zh": "赛博朋克", "en": "cyberpunk style" },
        { "zh": "蒸汽朋克", "en": "steampunk style" },
        { "zh": "未来主义", "en": "futuristic style" },
        { "zh": "复古未来主义", "en": "retro-futuristic" },
        { "zh": "哥特式", "en": "gothic style" },
        { "zh": "巴洛克", "en": "Baroque style" },
        { "zh": "洛可可", "en": "Rococo style" },
        { "zh": "新古典主义", "en": "Neoclassical style" },
        { "zh": "浪漫主义", "en": "Romanticism" },
        { "zh": "超现实主义", "en": "surrealism" },
        { "zh": "立体主义", "en": "cubism" },
        { "zh": "点彩画", "en": "pointillism" },
        { "zh": "现实主义画派", "en": "Realism (painting)" },
        { "zh": "中国画", "en": "Chinese painting style" },
        { "zh": "日本浮世绘", "en": "Japanese Ukiyo-e" },
        { "zh": "西方油画", "en": "Western oil painting" },
        { "zh": "洞穴壁画风格", "en": "cave painting style" },
        { "zh": "插画", "en": "illustration" },
        { "zh": "概念草图", "en": "concept sketch" },
        { "zh": "蓝图风格", "en": "blueprint style" },
        { "zh": "手绘", "en": "hand-drawn" },
        { "zh": "颗粒感", "en": "grainy texture" },
        { "zh": "噪点", "en": "noise (visual effect)" },
        { "zh": "数字艺术", "en": "digital art" },
        { "zh": "水墨画", "en": "ink wash painting" },
        { "zh": "工笔画", "en": "gongbi painting" },
        { "zh": "写意画", "en": "xieyi painting" },
        { "zh": "木刻版画", "en": "woodblock print" },
        { "zh": "铜版画", "en": "engraving" },
        { "zh": "丝网印刷", "en": "screen printing" }
      ]
    },
    {
      "name": "植物种类 (Plant Types)",
      "tags": [
        // 树木 (Trees)
        { "zh": "树木", "en": "tree" },
        { "zh": "橡树", "en": "oak tree" },
        { "zh": "枫树", "en": "maple tree" },
        { "zh": "松树", "en": "pine tree" },
        { "zh": "桦树", "en": "birch tree" },
        { "zh": "柳树", "en": "willow tree" },
        { "zh": "棕榈树", "en": "palm tree" },
        { "zh": "猴面包树", "en": "baobab tree" },
        { "zh": "红杉", "en": "redwood tree" },
        { "zh": "樱花树", "en": "cherry blossom tree" },
        { "zh": "苹果树", "en": "apple tree" },
        { "zh": "柑橘树", "en": "citrus tree" },
        { "zh": "冷杉", "en": "fir tree" },
        { "zh": "云杉", "en": "spruce tree" },
        { "zh": "白杨", "en": "aspen tree" },
        { "zh": "桉树", "en": "eucalyptus tree" },
        { "zh": "柏树", "en": "cypress tree" },
        { "zh": "榕树", "en": "banyan tree" },
        { "zh": "枣椰树", "en": "date palm" },
        { "zh": "椰子树", "en": "coconut tree" },
        { "zh": "银杏树", "en": "ginkgo tree" },
        { "zh": "梧桐树", "en": "sycamore tree" },
        { "zh": "无花果树", "en": "fig tree" },
        { "zh": "橄榄树", "en": "olive tree" },
        { "zh": "木棉树", "en": "kapok tree" },
        { "zh": "菩提树", "en": "bodhi tree" },
        { "zh": "龙血树", "en": "dragon's blood tree" },
        { "zh": "面包树", "en": "breadfruit tree" },
        { "zh": "金合欢", "en": "acacia tree" },
        { "zh": "热带树", "en": "tropical tree" },
        { "zh": "针叶树", "en": "coniferous tree" },
        { "zh": "落叶树", "en": "deciduous tree" },
        { "zh": "常绿树", "en": "evergreen tree" },
        { "zh": "乔木", "en": "arbor" },
        { "zh": "灌木", "en": "shrub" },
        { "zh": "盆景", "en": "bonsai" },

        // 花卉 (Flowers)
        { "zh": "花卉", "en": "flower" },
        { "zh": "玫瑰", "en": "rose" },
        { "zh": "郁金香", "en": "tulip" },
        { "zh": "向日葵", "en": "sunflower" },
        { "zh": "百合", "en": "lily" },
        { "zh": "兰花", "en": "orchid" },
        { "zh": "雏菊", "en": "daisy" },
        { "zh": "罂粟", "en": "poppy" },
        { "zh": "荷花", "en": "lotus" },
        { "zh": "睡莲", "en": "water lily" },
        { "zh": "薰衣草", "en": "lavender" },
        { "zh": "茉莉", "en": "jasmine" },
        { "zh": "樱花", "en": "cherry blossom" },
        { "zh": "水仙", "en": "daffodil" },
        { "zh": "康乃馨", "en": "carnation" },
        { "zh": "菊花", "en": "chrysanthemum" },
        { "zh": "牡丹", "en": "peony" },
        { "zh": "芙蓉", "en": "hibiscus" },
        { "zh": "丁香", "en": "lilac" },
        { "zh": "毛地黄", "en": "foxglove" },
        { "zh": "风信子", "en": "hyacinth" },
        { "zh": "美人蕉", "en": "cannalily" },
        { "zh": "风铃草", "en": "bellflower" },
        { "zh": "金盏花", "en": "marigold" },
        { "zh": "鸢尾花", "en": "iris" },
        { "zh": "三色堇", "en": "pansy" },
        { "zh": "牵牛花", "en": "morning glory" },
        { "zh": "大丽花", "en": "dahlia" },
        { "zh": "非洲菊", "en": "gerbera daisy" },
        { "zh": "仙客来", "en": "cyclamen" },
        { "zh": "紫罗兰", "en": "violet" },
        { "zh": "向日葵", "en": "sunflower" },
        { "zh": "扶桑", "en": "hibiscus" },
        { "zh": "杜鹃花", "en": "azalea" },
        { "zh": "绣球花", "en": "hydrangea" },
        { "zh": "彼岸花", "en": "red spider lily" },
        { "zh": "曼陀罗", "en": "datura" },
        { "zh": "虞美人", "en": "corn poppy" },
        { "zh": "油菜花", "en": "rapeseed flower" },
        { "zh": "桂花", "en": "sweet osmanthus" },
        { "zh": "梅花", "en": "plum blossom" },
        { "zh": "桃花", "en": "peach blossom" },
        { "zh": "杏花", "en": "apricot blossom" },
        { "zh": "山茶花", "en": "camellia" },
        { "zh": "报春花", "en": "primrose" },
        { "zh": "非洲紫罗兰", "en": "African violet" },
        { "zh": "仙人掌花", "en": "cactus flower" },
        { "zh": "多肉植物花", "en": "succulent flower" },
        { "zh": "食虫植物花", "en": "carnivorous plant flower" },
        { "zh": "野生花卉", "en": "wildflower" },
        { "zh": "切花", "en": "cut flower" },
        { "zh": "花束", "en": "flower bouquet" },
        { "zh": "花瓣", "en": "petal" },
        { "zh": "花蕊", "en": "stamen" },
        { "zh": "花粉", "en": "pollen" },
        { "zh": "花蕾", "en": "flower bud" },
        { "zh": "开花植物", "en": "flowering plant" },

        // 草本植物 (Herbs & Grasses)
        { "zh": "草", "en": "grass" },
        { "zh": "蕨类植物", "en": "fern" },
        { "zh": "苔藓", "en": "moss" },
        { "zh": "三叶草", "en": "clover" },
        { "zh": "蒲公英", "en": "dandelion" },
        { "zh": "薄荷", "en": "mint" },
        { "zh": "罗勒", "en": "basil" },
        { "zh": "迷迭香", "en": "rosemary" },
        { "zh": "百里香", "en": "thyme" },
        { "zh": "芦荟", "en": "aloe vera" },
        { "zh": "小麦", "en": "wheat" },
        { "zh": "玉米", "en": "corn" },
        { "zh": "水稻", "en": "rice (plant)" },
        { "zh": "竹子", "en": "bamboo" },
        { "zh": "莎草", "en": "sedge" },
        { "zh": "香蕉树", "en": "banana plant" },
        { "zh": "姜", "en": "ginger (plant)" },
        { "zh": "葱", "en": "scallion (plant)" },
        { "zh": "葱", "en": "onion (plant)" },
        { "zh": "大蒜", "en": "garlic (plant)" },
        { "zh": "马铃薯", "en": "potato plant" },
        { "zh": "番茄", "en": "tomato plant" },
        { "zh": "辣椒", "en": "pepper plant" },
        { "zh": "紫苏", "en": "shiso" },
        { "zh": "野草", "en": "weed" },
        { "zh": "杂草", "en": "wild grass" },
        { "zh": "多年生植物", "en": "perennial plant" },
        { "zh": "一年生植物", "en": "annual plant" },
        { "zh": "两年生植物", "en": "biennial plant" },
        { "zh": "观赏草", "en": "ornamental grass" },
        { "zh": "草本植物", "en": "herbaceous plant" },

        // 藤本植物 (Vines & Creepers)
        { "zh": "藤蔓", "en": "vine" },
        { "zh": "常春藤", "en": "ivy" },
        { "zh": "爬山虎", "en": "Virginia creeper" },
        { "zh": "葡萄藤", "en": "grapevine" },
        { "zh": "葫芦藤", "en": "gourd vine" },
        { "zh": "苦瓜藤", "en": "bitter melon vine" },
        { "zh": "金银花", "en": "honeysuckle" },
        { "zh": "牵牛花藤", "en": "morning glory vine" },
        { "zh": "丝瓜藤", "en": "luffa vine" },
        { "zh": "攀援植物", "en": "climbing plant" },
        { "zh": "蔓生植物", "en": "creeping plant" },

        // 藻类、地衣、菌类 (Algae, Lichens, Fungi)
        { "zh": "海藻", "en": "algae" },
        { "zh": "水藻", "en": "pond scum" },
        { "zh": "珊瑚藻", "en": "coralline algae" },
        { "zh": "地衣", "en": "lichen" },
        { "zh": "蘑菇", "en": "mushroom" },
        { "zh": "毒蘑菇", "en": "poisonous mushroom" },
        { "zh": "灵芝", "en": "reishi mushroom" },
        { "zh": "松露", "en": "truffle" },
        { "zh": "苔藓植物", "en": "bryophyte" },
        { "zh": "真菌", "en": "fungus" },
        { "zh": "酵母", "en": "yeast" },
        { "zh": "霉菌", "en": "mold" },

        // 特殊植物 (Specialized Plants)
        { "zh": "仙人掌", "en": "cactus" },
        { "zh": "多肉植物", "en": "succulent" },
        { "zh": "景天科植物", "en": "sedum" },
        { "zh": "生石花", "en": "lithops" },
        { "zh": "龙舌兰", "en": "agave" },
        { "zh": "肉质植物", "en": "fleshy plant" },
        { "zh": "食虫植物", "en": "carnivorous plant" },
        { "zh": "猪笼草", "en": "pitcher plant" },
        { "zh": "捕蝇草", "en": "Venus flytrap" },
        { "zh": "茅膏菜", "en": "sundew" },
        { "zh": "瓶子草", "en": "sarracenia" },
        { "zh": "水生植物", "en": "aquatic plant" },
        { "zh": "浮水植物", "en": "floating plant" },
        { "zh": "沉水植物", "en": "submerged plant" },
        { "zh": "挺水植物", "en": "emergent plant" },
        { "zh": "红树林植物", "en": "mangrove plant" },
        { "zh": "寄生植物", "en": "parasitic plant" },
        { "zh": "腐生植物", "en": "saprophytic plant" },
        { "zh": "附生植物", "en": "epiphyte" },
        { "zh": "兰科植物", "en": "orchidaceae" },
        { "zh": "凤梨科植物", "en": "bromeliad" },
        { "zh": "空凤", "en": "air plant" },
        { "zh": "苔藓植物", "en": "bryophyte" },
        { "zh": "蕨类植物", "en": "pteridophyte" },
        { "zh": "裸子植物", "en": "gymnosperm" },
        { "zh": "被子植物", "en": "angiosperm" },
        { "zh": "种子植物", "en": "seed plant" },
        { "zh": "苔藓", "en": "moss" },
        { "zh": "地衣", "en": "lichen" },
        { "zh": "蕨", "en": "fern" },
        { "zh": "苔藓地衣", "en": "moss and lichen" },

        // 其他 (Others)
        { "zh": "幼苗", "en": "seedling" },
        { "zh": "幼树", "en": "sapling" },
        { "zh": "种子", "en": "seed" },
        { "zh": "果实", "en": "fruit" },
        { "zh": "蔬菜", "en": "vegetable" },
        { "zh": "谷物", "en": "grain" },
        { "zh": "药草", "en": "medicinal herb" },
        { "zh": "香料植物", "en": "spice plant" },
        { "zh": "农作物", "en": "crop" },
        { "zh": "观赏植物", "en": "ornamental plant" },
        { "zh": "盆栽", "en": "potted plant" },
        { "zh": "室内植物", "en": "houseplant" },
        { "zh": "室外植物", "en": "outdoor plant" },
        { "zh": "本土植物", "en": "native plant" },
        { "zh": "入侵物种", "en": "invasive species" },
        { "zh": "濒危植物", "en": "endangered plant" },
        { "zh": "活植物", "en": "live plant" },
        { "zh": "死亡植物", "en": "dead plant" },
        { "zh": "化石植物", "en": "fossilized plant" }
      ]
    },
    {
      "name": "生长形态/结构 (Growth Form/Structure)",
      "tags": [
        { "zh": "树冠", "en": "tree canopy" },
        { "zh": "树干", "en": "tree trunk" },
        { "zh": "树枝", "en": "tree branch" },
        { "zh": "树根", "en": "tree roots" },
        { "zh": "叶子", "en": "leaf" },
        { "zh": "绿叶", "en": "green leaves" },
        { "zh": "阔叶", "en": "broadleaf" },
        { "zh": "针叶", "en": "needle leaf" },
        { "zh": "花朵", "en": "flower" },
        { "zh": "花瓣", "en": "petal" },
        { "zh": "花蕊", "en": "stamen" },
        { "zh": "花萼", "en": "sepal" },
        { "zh": "果实", "en": "fruit" },
        { "zh": "种子", "en": "seed" },
        { "zh": "茎", "en": "stem" },
        { "zh": "藤蔓", "en": "vine" },
        { "zh": "草地", "en": "grassland" },
        { "zh": "花圃", "en": "flower bed" },
        { "zh": "植物群", "en": "vegetation" },
        { "zh": "林下植被", "en": "undergrowth" },
        { "zh": "地被植物", "en": "groundcover" },
        { "zh": "灌木丛", "en": "bush" },
        { "zh": "树篱", "en": "hedge" },
        { "zh": "气生根", "en": "aerial roots" },
        { "zh": "气囊", "en": "air bladder" },
        { "zh": "树皮", "en": "bark" },
        { "zh": "年轮", "en": "tree rings" },
        { "zh": "树瘤", "en": "burl" },
        { "zh": "树洞", "en": "tree hole" },
        { "zh": "花序", "en": "inflorescence" },
        { "zh": "单朵花", "en": "single flower" },
        { "zh": "花簇", "en": "cluster of flowers" },
        { "zh": "卷须", "en": "tendril" },
        { "zh": "刺", "en": "thorn" },
        { "zh": "叶脉", "en": "leaf veins" },
        { "zh": "叶鞘", "en": "leaf sheath" },
        { "zh": "根茎", "en": "rhizome" },
        { "zh": "块茎", "en": "tuber" },
        { "zh": "鳞茎", "en": "bulb" },
        { "zh": "孢子", "en": "spore" },
        { "zh": "菌盖", "en": "mushroom cap" },
        { "zh": "菌柄", "en": "mushroom stem" },
        { "zh": "菌褶", "en": "mushroom gills" },
        { "zh": "叶形（掌状、羽状等）", "en": "leaf shape (palmate, pinnate, etc.)" },
        { "zh": "树冠形状（圆锥形、卵形等）", "en": "tree crown shape (conical, oval, etc.)" },
        { "zh": "植物细胞", "en": "plant cell" },
        { "zh": "叶绿体", "en": "chloroplast" },
        { "zh": "维管束", "en": "vascular bundle" },
        { "zh": "木质部", "en": "xylem" },
        { "zh": "韧皮部", "en": "phloem" },
        { "zh": "组织", "en": "plant tissue" },
        { "zh": "解剖结构", "en": "anatomical structure" }
      ]
    },
    {
      "name": "栖息地/环境 (Habitat/Environment)",
      "tags": [
        { "zh": "森林", "en": "forest" },
        { "zh": "茂密森林", "en": "dense forest" },
        { "zh": "热带雨林", "en": "tropical rainforest" },
        { "zh": "温带森林", "en": "temperate forest" },
        { "zh": "北方森林", "en": "boreal forest / taiga" },
        { "zh": "红树林", "en": "mangrove forest" },
        { "zh": "竹林", "en": "bamboo forest" },
        { "zh": "丛林", "en": "jungle" },
        { "zh": "灌木丛", "en": "shrubland" },
        { "zh": "草原", "en": "grassland" },
        { "zh": "稀树草原", "en": "savanna" },
        { "zh": "平原", "en": "plains" },
        { "zh": "沙漠", "en": "desert" },
        { "zh": "沙丘", "en": "sand dunes" },
        { "zh": "荒漠", "en": "xeric habitat" },
        { "zh": "极地", "en": "polar region" },
        { "zh": "苔原", "en": "tundra" },
        { "zh": "山脉", "en": "mountains" },
        { "zh": "山坡", "en": "mountain slope" },
        { "zh": "山谷", "en": "valley" },
        { "zh": "高原", "en": "plateau" },
        { "zh": "河流", "en": "river" },
        { "zh": "湖泊", "en": "lake" },
        { "zh": "池塘", "en": "pond" },
        { "zh": "溪流", "en": "stream" },
        { "zh": "瀑布", "en": "waterfall" },
        { "zh": "海洋", "en": "ocean" },
        { "zh": "海岸线", "en": "coastline" },
        { "zh": "海滩", "en": "beach" },
        { "zh": "珊瑚礁", "en": "coral reef" },
        { "zh": "湿地", "en": "wetland" },
        { "zh": "沼泽", "en": "swamp" },
        { "zh": "泥炭地", "en": "peatland" },
        { "zh": "岸边", "en": "riverbank" },
        { "zh": "水下", "en": "underwater" },
        { "zh": "土壤", "en": "soil" },
        { "zh": "岩石缝隙", "en": "rock crevice" },
        { "zh": "悬崖峭壁", "en": "cliff face" },
        { "zh": "农场", "en": "farm" },
        { "zh": "农田", "en": "farmland" },
        { "zh": "花园", "en": "garden" },
        { "zh": "植物园", "en": "botanical garden" },
        { "zh": "温室", "en": "greenhouse" },
        { "zh": "室内", "en": "indoor environment" },
        { "zh": "城市景观", "en": "urban landscape" },
        { "zh": "公园", "en": "park" },
        { "zh": "荒野", "en": "wilderness" },
        { "zh": "自然保护区", "en": "nature reserve" },
        { "zh": "热带", "en": "tropical" },
        { "zh": "温带", "en": "temperate" },
        { "zh": "寒带", "en": "arctic" },
        { "zh": "干旱", "en": "arid" },
        { "zh": "潮湿", "en": "humid" },
        { "zh": "贫瘠之地", "en": "barren land" },
        { "zh": "肥沃土壤", "en": "fertile soil" },
        { "zh": "腐烂的木头", "en": "rotting wood" }
      ]
    },
    {
      "name": "季节/时间 (Season/Time)",
      "tags": [
        { "zh": "春季", "en": "spring" },
        { "zh": "春光明媚", "en": "spring bloom" },
        { "zh": "发芽", "en": "budding" },
        { "zh": "花开", "en": "blossoming" },
        { "zh": "夏季", "en": "summer" },
        { "zh": "盛夏", "en": "mid-summer" },
        { "zh": "繁茂", "en": "lush" },
        { "zh": "秋季", "en": "autumn / fall" },
        { "zh": "落叶", "en": "falling leaves" },
        { "zh": "枫叶", "en": "autumn foliage" },
        { "zh": "丰收", "en": "harvest season" },
        { "zh": "冬季", "en": "winter" },
        { "zh": "冰雪覆盖", "en": "snow-covered" },
        { "zh": "休眠", "en": "dormant" },
        { "zh": "清晨", "en": "early morning" },
        { "zh": "黎明", "en": "dawn" },
        { "zh": "上午", "en": "morning" },
        { "zh": "中午", "en": "midday" },
        { "zh": "下午", "en": "afternoon" },
        { "zh": "黄昏", "en": "dusk" },
        { "zh": "日落", "en": "sunset" },
        { "zh": "夜晚", "en": "night" },
        { "zh": "月光", "en": "moonlight" },
        { "zh": "黎明破晓", "en": "sunrise" },
        { "zh": "全天", "en": "all day" },
        { "zh": "一年四季", "en": "four seasons" }
      ]
    },
    {
      "name": "颜色 (Color)",
      "tags": [
        { "zh": "绿色", "en": "green" },
        { "zh": "翠绿", "en": "emerald green" },
        { "zh": "橄榄绿", "en": "olive green" },
        { "zh": "森林绿", "en": "forest green" },
        { "zh": "苔绿色", "en": "moss green" },
        { "zh": "黄绿色", "en": "lime green" },
        { "zh": "深绿色", "en": "dark green" },
        { "zh": "浅绿色", "en": "light green" },
        { "zh": "粉色", "en": "pink" },
        { "zh": "淡粉", "en": "pastel pink" },
        { "zh": "玫瑰色", "en": "rose" },
        { "zh": "红色", "en": "red" },
        { "zh": "深红", "en": "crimson" },
        { "zh": "火红色", "en": "fiery red" },
        { "zh": "橙色", "en": "orange" },
        { "zh": "金橙色", "en": "golden orange" },
        { "zh": "黄色", "en": "yellow" },
        { "zh": "亮黄", "en": "bright yellow" },
        { "zh": "金色", "en": "golden" },
        { "zh": "蓝色", "en": "blue" },
        { "zh": "天蓝色", "en": "sky blue" },
        { "zh": "深蓝", "en": "deep blue" },
        { "zh": "紫色", "en": "purple" },
        { "zh": "薰衣草紫", "en": "lavender" },
        { "zh": "深紫", "en": "deep purple" },
        { "zh": "白色", "en": "white" },
        { "zh": "纯白", "en": "pure white" },
        { "zh": "象牙色", "en": "ivory" },
        { "zh": "棕色", "en": "brown" },
        { "zh": "土棕色", "en": "earthy brown" },
        { "zh": "灰色", "en": "grey" },
        { "zh": "黑色", "en": "black" },
        { "zh": "彩色", "en": "colorful" },
        { "zh": "单色", "en": "monochrome" },
        { "zh": "渐变色", "en": "gradient colors" },
        { "zh": "鲜艳色", "en": "vivid colors" },
        { "zh": "柔和色", "en": "muted colors" },
        { "zh": "明亮色", "en": "bright colors" },
        { "zh": "暗淡色", "en": "dull colors" },
        { "zh": "透明", "en": "transparent" },
        { "zh": "半透明", "en": "translucent" },
        { "zh": "色彩斑斓", "en": "multicolored" },
        { "zh": "自然色调", "en": "natural color palette" }
      ]
    },
    {
      "name": "行为/生命阶段 (Actions/Life Stages)",
      "tags": [
        { "zh": "生长", "en": "growing" },
        { "zh": "发芽", "en": "sprouting" },
        { "zh": "开花", "en": "blooming" },
        { "zh": "结果", "en": "fruiting" },
        { "zh": "凋谢", "en": "wilting" },
        { "zh": "枯萎", "en": "withering" },
        { "zh": "落叶", "en": "shedding leaves" },
        { "zh": "休眠", "en": "dormancy" },
        { "zh": "光合作用", "en": "photosynthesis" },
        { "zh": "呼吸作用", "en": "respiration" },
        { "zh": "蒸腾作用", "en": "transpiration" },
        { "zh": "授粉", "en": "pollination" },
        { "zh": "传播种子", "en": "seed dispersal" },
        { "zh": "攀爬", "en": "climbing (vines)" },
        { "zh": "蔓延", "en": "spreading (creepers)" },
        { "zh": "适应", "en": "adapting" },
        { "zh": "生存", "en": "surviving" },
        { "zh": "死亡", "en": "dying" },
        { "zh": "腐烂", "en": "decaying" },
        { "zh": "生命周期", "en": "life cycle" },
        { "zh": "自然选择", "en": "natural selection" },
        { "zh": "新生", "en": "new growth" },
        { "zh": "成熟", "en": "maturity" },
        { "zh": "衰老", "en": "senescence" },
        { "zh": "捕食（食虫植物）", "en": "predation (carnivorous plants)" }
      ]
    },
    {
      "name": "角度/构图 (Angle/Composition)",
      "tags": [
        { "zh": "特写", "en": "close-up" },
        { "zh": "局部特写", "en": "extreme close-up" },
        { "zh": "花瓣特写", "en": "petal close-up" },
        { "zh": "叶脉特写", "en": "leaf vein close-up" },
        { "zh": "半身", "en": "medium shot" },
        { "zh": "全身", "en": "full shot (for single plant)" },
        { "zh": "远景", "en": "long shot" },
        { "zh": "大远景", "en": "extreme long shot" },
        { "zh": "环境远景", "en": "establishing shot" },
        { "zh": "广角镜头", "en": "wide angle shot" },
        { "zh": "超广角", "en": "ultrawide angle" },
        { "zh": "微距镜头", "en": "macro shot" },
        { "zh": "远摄镜头", "en": "telephoto shot" },
        { "zh": "鱼眼镜头", "en": "fisheye lens" },
        { "zh": "鸟瞰图", "en": "bird's eye view" },
        { "zh": "俯视图", "en": "overhead view" },
        { "zh": "虫眼视图", "en": "worm's eye view" },
        { "zh": "低角度", "en": "low angle" },
        { "zh": "高角度", "en": "high angle" },
        { "zh": "水平视角", "en": "eye-level shot" },
        { "zh": "倾斜角度", "en": "Dutch angle" },
        { "zh": "动态角度", "en": "dynamic angle" },
        { "zh": "静态拍摄", "en": "static shot" },
        { "zh": "穿行", "en": "dolly shot (through foliage)" },
        { "zh": "景深", "en": "depth of field (DOF)" },
        { "zh": "散景", "en": "bokeh" },
        { "zh": "浅景深", "en": "shallow depth of field" },
        { "zh": "深景深", "en": "deep depth of field" },
        { "zh": "聚焦", "en": "in focus" },
        { "zh": "失焦", "en": "out of focus" },
        { "zh": "中心构图", "en": "centered composition" },
        { "zh": "三分法构图", "en": "rule of thirds" },
        { "zh": "对称构图", "en": "symmetrical composition" },
        { "zh": "对角线构图", "en": "diagonal composition" },
        { "zh": "引导线", "en": "leading lines" },
        { "zh": "框架构图", "en": "framing composition" },
        { "zh": "开放构图", "en": "open composition" },
        { "zh": "封闭构图", "en": "closed composition" },
        { "zh": "前景", "en": "foreground" },
        { "zh": "背景", "en": "background" },
        { "zh": "清晰前景", "en": "sharp foreground" },
        { "zh": "虚化背景", "en": "blurred background" },
        { "zh": "轮廓", "en": "silhouette" },
        { "zh": "全景", "en": "panoramic" },
        { "zh": "横向构图", "en": "horizontal composition" },
        { "zh": "纵向构图", "en": "vertical composition" },
        { "zh": "空旷构图", "en": "negative space" },
        { "zh": "填充画面", "en": "fill the frame" },
        { "zh": "重复图案", "en": "repeating pattern" },
        { "zh": "纹理特写", "en": "texture close-up" },
        { "zh": "几何构图", "en": "geometric composition" },
        { "zh": "有机构图", "en": "organic composition" }
      ]
    },
    {
      "name": "光线/氛围 (Lighting/Mood)",
      "tags": [
        { "zh": "阳光", "en": "sunny" },
        { "zh": "直射光", "en": "direct sunlight" },
        { "zh": "柔和光线", "en": "soft lighting" },
        { "zh": "硬光", "en": "harsh lighting" },
        { "zh": "自然光", "en": "natural light" },
        { "zh": "人造光", "en": "artificial light" },
        { "zh": "低对比度光", "en": "low-contrast light" },
        { "zh": "高对比度光线", "en": "high-contrast lighting" },
        { "zh": "戏剧性光照", "en": "dramatic lighting" },
        { "zh": "轮廓光", "en": "rim light" },
        { "zh": "逆光", "en": "backlit" },
        { "zh": "侧光", "en": "side lighting" },
        { "zh": "顶光", "en": "top lighting" },
        { "zh": "穿透光", "en": "light filtering through" },
        { "zh": "丁达尔效应", "en": "crepuscular rays" },
        { "zh": "光斑", "en": "lens flare" },
        { "zh": "辉光", "en": "bloom lighting" },
        { "zh": "阴影", "en": "shadows" },
        { "zh": "清晰阴影", "en": "sharp shadows" },
        { "zh": "柔和阴影", "en": "soft shadows" },
        { "zh": "剪影照明", "en": "silhouette lighting" },
        { "zh": "黄金时段", "en": "golden hour" },
        { "zh": "蓝调时刻", "en": "blue hour" },
        { "zh": "环境照明", "en": "ambient light" },
        { "zh": "重点照明", "en": "spotlight" },
        { "zh": "弥漫光", "en": "diffused light" },
        { "zh": "宁静", "en": "serene" },
        { "zh": "平静", "en": "calm" },
        { "zh": "神秘", "en": "mysterious" },
        { "zh": "黑暗", "en": "dark" },
        { "zh": "光明", "en": "bright" },
        { "zh": "生机勃勃", "en": "vibrant" },
        { "zh": "忧郁", "en": "melancholy" },
        { "zh": "梦幻", "en": "dreamlike" },
        { "zh": "奇幻", "en": "fantastical" },
        { "zh": "安详", "en": "tranquil" },
        { "zh": "富有生命力", "en": "lively" },
        { "zh": "柔和", "en": "subdued" },
        { "zh": "湿润的", "en": "damp" },
        { "zh": "干燥的", "en": "dry" },
        { "zh": "酷热的", "en": "scorching" },
        { "zh": "冰冷的", "en": "frosty" },
        { "zh": "冷光", "en": "cool light" },
        { "zh": "暖光", "en": "warm light" },
        { "zh": "微光", "en": "glowing" },
        { "zh": "闪烁", "en": "twinkling" }
      ]
    },
    {
      "name": "情绪/主题 (Mood/Theme)",
      "tags": [
        { "zh": "自然之美", "en": "beauty of nature" },
        { "zh": "生命力", "en": "vitality" },
        { "zh": "生长与衰败", "en": "growth and decay" },
        { "zh": "和谐", "en": "harmony" },
        { "zh": "宁静", "en": "tranquility" },
        { "zh": "繁茂", "en": "abundance" },
        { "zh": "孤独", "en": "solitude" },
        { "zh": "坚韧", "en": "resilience" },
        { "zh": "脆弱", "en": "fragility" },
        { "zh": "希望", "en": "hope" },
        { "zh": "重生", "en": "rebirth" },
        { "zh": "神秘", "en": "mystery" },
        { "zh": "魔法", "en": "magic" },
        { "zh": "超自然", "en": "supernatural" },
        { "zh": "异世界", "en": "otherworldly" },
        { "zh": "治愈", "en": "healing" },
        { "zh": "冥想", "en": "meditation" },
        { "zh": "逃避现实", "en": "escapism" },
        { "zh": "生态保护", "en": "ecological conservation" },
        { "zh": "生物多样性", "en": "biodiversity" },
        { "zh": "环境意识", "en": "environmental awareness" },
        { "zh": "仙境", "en": "fairytale forest" },
        { "zh": "失落的乐园", "en": "lost paradise" },
        { "zh": "植物智慧", "en": "plant intelligence" },
        { "zh": "隐藏的奥秘", "en": "hidden secrets" },
        { "zh": "诗意", "en": "poetic" },
        { "zh": "田园", "en": "pastoral" },
        { "zh": "浪漫", "en": "romantic" },
        { "zh": "忧郁", "en": "melancholy" },
        { "zh": "怀旧", "en": "nostalgic" },
        { "zh": "静物", "en": "still life" },
        { "zh": "抽象概念", "en": "abstract concept" },
        { "zh": "象征意义", "en": "symbolism" },
        { "zh": "历史感", "en": "historical (plants)" },
        { "zh": "古老", "en": "ancient" },
        { "zh": "未来派", "en": "futuristic botany" },
        { "zh": "科幻植物", "en": "sci-fi plants" }
      ]
    },
    {
      "name": "画面元素 (Visual Elements)",
      "tags": [
        { "zh": "水滴", "en": "water drops" },
        { "zh": "露珠", "en": "dew drops" },
        { "zh": "雨", "en": "rain" },
        { "zh": "雪", "en": "snow" },
        { "zh": "冰", "en": "ice" },
        { "zh": "霜", "en": "frost" },
        { "zh": "薄雾", "en": "mist" },
        { "zh": "烟雾", "en": "fog / smoke" },
        { "zh": "灰尘", "en": "dust" },
        { "zh": "泥土", "en": "soil" },
        { "zh": "岩石", "en": "rocks" },
        { "zh": "地面", "en": "ground" },
        { "zh": "树皮纹理", "en": "bark texture" },
        { "zh": "叶面纹理", "en": "leaf texture" },
        { "zh": "花瓣纹理", "en": "petal texture" },
        { "zh": "藤蔓缠绕", "en": "entwined vines" },
        { "zh": "树根纠结", "en": "tangled roots" },
        { "zh": "树桩", "en": "tree stump" },
        { "zh": "倒下的树", "en": "fallen tree" },
        { "zh": "枯枝", "en": "dead branches" },
        { "zh": "落叶堆", "en": "pile of leaves" },
        { "zh": "水面", "en": "water surface" },
        { "zh": "水波纹", "en": "water ripples" },
        { "zh": "水池", "en": "pond" },
        { "zh": "喷泉", "en": "fountain" },
        { "zh": "云朵", "en": "clouds" },
        { "zh": "阳光透过", "en": "sunlight filtering through" },
        { "zh": "倒影", "en": "reflection" },
        { "zh": "影子", "en": "shadow" },
        { "zh": "光斑", "en": "light spots" },
        { "zh": "虚化", "en": "blur" },
        { "zh": "清晰", "en": "sharpness" },
        { "zh": "纹理", "en": "texture" },
        { "zh": "图案", "en": "pattern" },
        { "zh": "前景植物", "en": "foreground plants" },
        { "zh": "背景植物", "en": "background plants" },
        { "zh": "模糊背景", "en": "blurred background" },
        { "zh": "清晰背景", "en": "sharp background" },
        { "zh": "鸟类（在植物上）", "en": "birds (on plants)" },
        { "zh": "昆虫（在植物上）", "en": "insects (on plants)" },
        { "zh": "小动物（在植物中）", "en": "small animals (among plants)" },
        { "zh": "温室玻璃", "en": "greenhouse glass" },
        { "zh": "花盆", "en": "flower pot" },
        { "zh": "园艺工具", "en": "gardening tools" },
        { "zh": "浇水壶", "en": "watering can" },
        { "zh": "花架", "en": "trellis" },
        { "zh": "蜂巢", "en": "beehive" },
        { "zh": "鸟巢", "en": "bird nest" },
        { "zh": "露水", "en": "dew" },
        { "zh": "水珠", "en": "beads of water" },
        { "zh": "琥珀", "en": "amber (with trapped plant)" },
        { "zh": "枯木", "en": "driftwood" },
        { "zh": "真菌菌丝", "en": "fungal mycelium" },
        { "zh": "土壤裂纹", "en": "cracked earth" },
        { "zh": "藤蔓覆盖的墙壁", "en": "vine-covered wall" }
      ]
    }
  ]
});