tagData.push({
  "group": "汽车 (Automobile)",
  "categories": [
  {
  "name": "画风 (Art Style)",
  "tags": [
  { "zh": "写实主义", "en": "realistic" },
  { "zh": "超写实", "en": "hyperrealistic" },
  { "zh": "概念艺术", "en": "concept art" },
  { "zh": "卡通", "en": "cartoon" },
  { "zh": "动画", "en": "anime style" },
  { "zh": "赛博朋克", "en": "cyberpunk style" },
  { "zh": "未来主义", "en": "futuristic style" },
  { "zh": "复古未来主义", "en": "retro-futuristic" },
  { "zh": "蒸汽波", "en": "vaporwave style" },
  { "zh": "低多边形", "en": "low poly" },
  { "zh": "像素化", "en": "pixel art" },
  { "zh": "卡通渲染", "en": "cel-shaded" },
  { "zh": "油画风格", "en": "oil painting style" },
  { "zh": "水彩画风格", "en": "watercolor style" },
  { "zh": "素描", "en": "sketch style" },
  { "zh": "抽象艺术", "en": "abstract art" },
  { "zh": "工业设计", "en": "industrial design" },
  { "zh": "极简主义", "en": "minimalist style" },
  { "zh": "宏伟", "en": "cinematic" },
  { "zh": "艺术摄影", "en": "art photography" }
  ]
  },
  {
  "name": "品牌 (Brand)",
  "tags": [
  { "zh": "法拉利", "en": "Ferrari" },
  { "zh": "兰博基尼", "en": "Lamborghini" },
  { "zh": "保时捷", "en": "Porsche" },
  { "zh": "布加迪", "en": "Bugatti" },
  { "zh": "迈凯伦", "en": "McLaren" },
  { "zh": "梅赛德斯-奔驰", "en": "Mercedes-Benz" },
  { "zh": "宝马", "en": "BMW" },
  { "zh": "奥迪", "en": "Audi" },
  { "zh": "特斯拉", "en": "Tesla" },
  { "zh": "丰田", "en": "Toyota" },
  { "zh": "本田", "en": "Honda" },
  { "zh": "日产 GTR", "en": "Nissan GTR" },
  { "zh": "劳斯莱斯", "en": "Rolls-Royce" },
  { "zh": "宾利", "en": "Bentley" },
  { "zh": "阿斯顿·马丁", "en": "Aston Martin" },
  { "zh": "科尼赛克", "en": "Koenigsegg" },
  { "zh": "帕加尼", "en": "Pagani" },
  { "zh": "莲花", "en": "Lotus" },
  { "zh": "路虎", "en": "Land Rover" },
  { "zh": "捷豹", "en": "Jaguar" },
  { "zh": "沃尔沃", "en": "Volvo" },
  { "zh": "大众", "en": "Volkswagen" },
  { "zh": "福特", "en": "Ford" },
  { "zh": "雪佛兰", "en": "Chevrolet" },
  { "zh": "GMC", "en": "GMC" },
  { "zh": "克莱斯勒", "en": "Chrysler" },
  { "zh": "吉普", "en": "Jeep" },
  { "zh": "马自达", "en": "Mazda" },
  { "zh": "斯巴鲁", "en": "Subaru" },
  { "zh": "铃木", "en": "Suzuki" },
  { "zh": "三菱", "en": "Mitsubishi" },
  { "zh": "现代", "en": "Hyundai" },
  { "zh": "起亚", "en": "Kia" },
  { "zh": "标致", "en": "Peugeot" },
  { "zh": "雷诺", "en": "Renault" },
  { "zh": "雪铁龙", "en": "Citroën" },
  { "zh": "菲亚特", "en": "Fiat" },
  { "zh": "阿尔法·罗密欧", "en": "Alfa Romeo" },
  { "zh": "比亚迪", "en": "BYD" },
  { "zh": "蔚来", "en": "NIO" },
  { "zh": "小鹏", "en": "XPeng" },
  { "zh": "理想", "en": "Li Auto" },
  { "zh": "吉利", "en": "Geely" },
  { "zh": "奇瑞", "en": "Chery" },
  { "zh": "长城", "en": "Great Wall Motors" },
  { "zh": "红旗", "en": "Hongqi" },
  { "zh": "通用汽车", "en": "General Motors" },
  { "zh": "福田汽车", "en": "Foton Motor" },
  { "zh": "日野", "en": "Hino" },
  { "zh": "斯堪尼亚", "en": "Scania" },
  { "zh": "曼恩", "en": "MAN (trucks)" },
  { "zh": "达夫", "en": "DAF" },
  { "zh": "依维柯", "en": "Iveco" },
  { "zh": "雷克萨斯", "en": "Lexus" },
  { "zh": "讴歌", "en": "Acura" },
  { "zh": "英菲尼迪", "en": "Infiniti" },
  { "zh": "凯迪拉克", "en": "Cadillac" },
  { "zh": "林肯", "en": "Lincoln" },
  { "zh": "萨博", "en": "Saab" },
  { "zh": "雪铁龙", "en": "Citroen" },
  { "zh": "DS", "en": "DS Automobiles" },
  { "zh": "Smart", "en": "Smart" },
  { "zh": "MINI", "en": "MINI" },
  { "zh": "劳伦士", "en": "Lorinser" },
  { "zh": "AMC", "en": "AMC" },
  { "zh": "DeLorean", "en": "DeLorean" },
  { "zh": "Morgan", "en": "Morgan" },
  { "zh": "Caterham", "en": "Caterham" },
  { "zh": "Ariel", "en": "Ariel" },
  { "zh": "Ruf", "en": "Ruf" },
  { "zh": "Zenvo", "en": "Zenvo" }
  ]
  },
  {
  "name": "车种 (Vehicle Type)",
  "tags": [
  { "zh": "轿车", "en": "sedan" },
  { "zh": "Coupe", "en": "coupe" },
  { "zh": "敞篷车", "en": "convertible" },
  { "zh": "双座敞篷车", "en": "roadster" },
  { "zh": "旅行车", "en": "wagon" },
  { "zh": "掀背车", "en": "hatchback" },
  { "zh": "SUV", "en": "SUV" },
  { "zh": "CUV (跨界SUV)", "en": "crossover SUV" },
  { "zh": "皮卡", "en": "pickup truck" },
  { "zh": "小型货车", "en": "minivan" },
  { "zh": "厢式货车", "en": "van" },
  { "zh": "卡车", "en": "truck" },
  { "zh": "公共汽车", "en": "bus" },
  { "zh": "超级跑车", "en": "supercar" },
  { "zh": "顶级跑车", "en": "hypercar" },
  { "zh": "跑车", "en": "sports car" },
  { "zh": "豪华轿车", "en": "luxury car" },
  { "zh": "电动汽车", "en": "electric car (EV)" },
  { "zh": "混合动力车", "en": "hybrid car" },
  { "zh": "概念车", "en": "concept car" },
  { "zh": "古董车", "en": "vintage car" },
  { "zh": "老爷车", "en": "classic car" },
  { "zh": "肌肉车", "en": "muscle car" },
  { "zh": "热棒车", "en": "hot rod" },
  { "zh": "方程式赛车", "en": "formula 1 car" },
  { "zh": "耐力赛车", "en": "endurance race car" },
  { "zh": "拉力赛车", "en": "rally car" },
  { "zh": "漂移车", "en": "drift car" },
  { "zh": "越野车", "en": "off-road vehicle" },
  { "zh": "房车", "en": "RV (recreational vehicle)" },
  { "zh": "露营车", "en": "campervan" },
  { "zh": "出租车", "en": "taxi" },
  { "zh": "警车", "en": "police car" },
  { "zh": "救护车", "en": "ambulance" },
  { "zh": "消防车", "en": "fire truck" },
  { "zh": "未来派汽车", "en": "futuristic car" },
  { "zh": "自动驾驶汽车", "en": "autonomous vehicle" },
  { "zh": "厢式客货两用车", "en": "vanagon" },
  { "zh": "皮卡敞篷车", "en": "ute (utility vehicle)" },
  { "zh": "水陆两栖车", "en": "amphibious vehicle" },
  { "zh": "摩托车", "en": "motorcycle" },
  { "zh": "踏板车", "en": "scooter" },
  { "zh": "三轮车", "en": "rickshaw" },
  { "zh": "卡丁车", "en": "go-kart" },
  { "zh": "沙滩车", "en": "ATV (all-terrain vehicle)" }
  ]
  },
  {
  "name": "角度 (Angle)",
  "tags": [
  { "zh": "正面视图", "en": "front view" },
  { "zh": "侧面视图", "en": "side view" },
  { "zh": "后视图", "en": "rear view" },
  { "zh": "四分之三前视图", "en": "three-quarter front view" },
  { "zh": "四分之三后视图", "en": "three-quarter rear view" },
  { "zh": "顶视图", "en": "top view" },
  { "zh": "鸟瞰图", "en": "bird's eye view" },
  { "zh": "虫眼视图", "en": "worm's eye view" },
  { "zh": "低角度", "en": "low angle" },
  { "zh": "高角度", "en": "high angle" },
  { "zh": "平视视角", "en": "eye-level shot" },
  { "zh": "倾斜角度", "en": "dutch angle" },
  { "zh": "动态角度", "en": "dynamic angle" },
  { "zh": "抽象角度", "en": "abstract angle" },
  { "zh": "运动模糊", "en": "motion blur" },
  { "zh": "追踪镜头", "en": "tracking shot" },
  { "zh": "主观视角", "en": "first-person view" },
  { "zh": "车内视角", "en": "in-car view" },
  { "zh": "广角镜头", "en": "wide angle shot" },
  { "zh": "特写镜头", "en": "close-up shot" },
  { "zh": "远摄镜头", "en": "telephoto shot" },
  { "zh": "鱼眼镜头", "en": "fisheye lens" },
  { "zh": "反射", "en": "reflection" },
  { "zh": "倒影", "en": "mirror image" },
  { "zh": "俯冲镜头", "en": "dive shot" },
  { "zh": "跟随镜头", "en": "follow shot" },
  { "zh": "环绕镜头", "en": "orbit shot" },
  { "zh": "特写细节", "en": "detail shot" }
  ]
  },
  {
  "name": "景别 (Shot Type/Framing)",
  "tags": [
  { "zh": "特写", "en": "close-up" },
  { "zh": "局部特写", "en": "extreme close-up" },
  { "zh": "半身", "en": "medium shot" },
  { "zh": "全身", "en": "full shot" },
  { "zh": "远景", "en": "long shot" },
  { "zh": "大远景", "en": "establishing shot" },
  { "zh": "广阔景别", "en": "wide shot" },
  { "zh": "前景模糊", "en": "foreground blur" },
  { "zh": "背景模糊景深", "en": "bokeh" },
  { "zh": "聚焦车轮", "en": "wheel focus" },
  { "zh": "聚焦大灯", "en": "headlight focus" },
  { "zh": "聚焦车身线条", "en": "body line focus" },
  { "zh": "低景深", "en": "shallow depth of field" },
  { "zh": "高景深", "en": "deep depth of field" },
  { "zh": "全景", "en": "panoramic" },
  { "zh": "裁剪构图", "en": "cropped composition" },
  { "zh": "中央构图", "en": "centered composition" },
  { "zh": "三分法构图", "en": "rule of thirds" },
  { "zh": "对称构图", "en": "symmetrical composition" },
  { "zh": "引导线", "en": "leading lines" },
  { "zh": "框架构图", "en": "framing (composition)" },
  { "zh": "无人机视角", "en": "drone shot" },
  { "zh": "航拍", "en": "aerial view" },
  { "zh": "长曝光", "en": "long exposure" },
  { "zh": "曝光过度", "en": "overexposed" },
  { "zh": "曝光不足", "en": "underexposed" }
  ]
  },
  {
  "name": "车型 (Specific Body Styles / Attributes)",
  "tags": [
  { "zh": "双门轿跑", "en": "two-door coupe" },
  { "zh": "四门轿车", "en": "four-door sedan" },
  { "zh": "紧凑型", "en": "compact (car)" },
  { "zh": "中型", "en": "mid-size (car)" },
  { "zh": "全尺寸", "en": "full-size (car)" },
  { "zh": "GT跑车", "en": "grand tourer" },
  { "zh": "高性能版", "en": "performance variant" },
  { "zh": "电动超跑", "en": "electric hypercar" },
  { "zh": "空气动力学设计", "en": "aerodynamic design" },
  { "zh": "模块化底盘", "en": "modular chassis" },
  { "zh": "碳纤维车身", "en": "carbon fiber body" },
  { "zh": "轻量化设计", "en": "lightweight design" },
  { "zh": "流线型", "en": "streamlined" },
  { "zh": "低矮车身", "en": "low-slung" },
  { "zh": "宽体套件", "en": "widebody kit" },
  { "zh": "赛道专用", "en": "track-focused" },
  { "zh": "定制车", "en": "custom car" },
  { "zh": "改装车", "en": "tuned car" },
  { "zh": "概念车外观", "en": "concept car look" },
  { "zh": "限量版", "en": "limited edition" },
  { "zh": "复古造型", "en": "retro-styled" },
  { "zh": "未来科技外观", "en": "futuristic aesthetics" },
  { "zh": "鸥翼门", "en": "gull-wing doors" },
  { "zh": "剪刀门", "en": "scissor doors" },
  { "zh": "蝴蝶门", "en": "butterfly doors" },
  { "zh": "滑动门", "en": "sliding doors" },
  { "zh": "无框车门", "en": "frameless doors" },
  { "zh": "全景天窗", "en": "panoramic sunroof" },
  { "zh": "可拆卸车顶", "en": "removable roof" },
  { "zh": "空气悬架", "en": "air suspension" },
  { "zh": "主动空气动力学", "en": "active aero" },
  { "zh": "固定尾翼", "en": "fixed wing" },
  { "zh": "可升降尾翼", "en": "active spoiler" },
  { "zh": "扩散器", "en": "diffuser" },
  { "zh": "大型进气口", "en": "large air intake" },
  { "zh": "双边排气", "en": "dual exhaust" },
  { "zh": "中置排气", "en": "center exhaust" },
  { "zh": "合金轮毂", "en": "alloy wheels" },
  { "zh": "锻造轮毂", "en": "forged wheels" },
  { "zh": "碳陶刹车", "en": "carbon ceramic brakes" }
  ]
  },
  {
  "name": "内饰 (Interior)",
  "tags": [
  { "zh": "驾驶舱", "en": "cockpit" },
  { "zh": "仪表盘", "en": "dashboard" },
  { "zh": "方向盘", "en": "steering wheel" },
  { "zh": "运动方向盘", "en": "sport steering wheel" },
  { "zh": "数字仪表盘", "en": "digital dashboard" },
  { "zh": "中控台", "en": "center console" },
  { "zh": "信息娱乐系统", "en": "infotainment system" },
  { "zh": "触摸屏", "en": "touchscreen" },
  { "zh": "真皮座椅", "en": "leather seats" },
  { "zh": "桶形座椅", "en": "bucket seats" },
  { "zh": "运动座椅", "en": "sport seats" },
  { "zh": "Alcantara内饰", "en": "Alcantara interior" },
  { "zh": "碳纤维内饰", "en": "carbon fiber interior trim" },
  { "zh": "木纹内饰", "en": "wood trim" },
  { "zh": "换挡杆", "en": "gear shifter" },
  { "zh": "拨片换挡", "en": "paddle shifters" },
  { "zh": "踏板", "en": "pedals" },
  { "zh": "抬头显示", "en": "head-up display (HUD)" },
  { "zh": "环境氛围灯", "en": "ambient lighting" },
  { "zh": "门板", "en": "door panels" },
  { "zh": "车顶内衬", "en": "headliner" },
  { "zh": "后视镜", "en": "rear view mirror" },
  { "zh": "侧后视镜", "en": "side mirrors" },
  { "zh": "空调出风口", "en": "air vents" },
  { "zh": "杯架", "en": "cup holders" },
  { "zh": "储物空间", "en": "storage compartments" },
  { "zh": "高级音响系统", "en": "premium sound system" },
  { "zh": "乘坐舒适性", "en": "riding comfort" },
  { "zh": "内部宽敞", "en": "spacious interior" },
  { "zh": "豪华内饰", "en": "luxurious interior" },
  { "zh": "简约内饰", "en": "minimalist interior" },
  { "zh": "未来科技内饰", "en": "futuristic interior" },
  { "zh": "赛车化内饰", "en": "race-inspired interior" },
  { "zh": "镀铬内饰件", "en": "chrome interior accents" },
  { "zh": "缝线", "en": "stitching (interior)" },
  { "zh": "安全气囊", "en": "airbag" },
  { "zh": "安全带", "en": "seatbelt" },
  { "zh": "迎宾踏板", "en": "door sills" },
  { "zh": "地板垫", "en": "floor mats" }
  ]
  },
  {
  "name": "上市年份 (Launch Year / Era)",
  "tags": [
  { "zh": "现代汽车", "en": "modern car" },
  { "zh": "经典车", "en": "classic car" },
  { "zh": "古董车", "en": "vintage car" },
  { "zh": "老式车", "en": "antique car" },
  { "zh": "未来概念车", "en": "futuristic concept" },
  { "zh": "20世纪50年代", "en": "1950s car" },
  { "zh": "20世纪60年代", "en": "1960s car" },
  { "zh": "20世纪70年代", "en": "1970s car" },
  { "zh": "20世纪80年代", "en": "1980s car" },
  { "zh": "20世纪90年代", "en": "1990s car" },
  { "zh": "21世纪初", "en": "2000s car" },
  { "zh": "2010年代", "en": "2010s car" },
  { "zh": "2020年代", "en": "2020s car" },
  { "zh": "复古风格", "en": "retro style" },
  { "zh": "新车", "en": "new car" },
  { "zh": "旧车", "en": "old car" },
  { "zh": "破旧车", "en": "beat-up car" },
  { "zh": "定制年份", "en": "year-specific custom" },
  { "zh": "未来派年份", "en": "futuristic (year)" },
  { "zh": "过去年代", "en": "past era" },
  { "zh": "未来年代", "en": "future era" }
  ]
  },
  {
  "name": "车身颜色 (Body Color)",
  "tags": [
  { "zh": "红色车身", "en": "red body" },
  { "zh": "蓝色车身", "en": "blue body" },
  { "zh": "黑色车身", "en": "black body" },
  { "zh": "白色车身", "en": "white body" },
  { "zh": "银色车身", "en": "silver body" },
  { "zh": "灰色车身", "en": "grey body" },
  { "zh": "黄色车身", "en": "yellow body" },
  { "zh": "绿色车身", "en": "green body" },
  { "zh": "橙色车身", "en": "orange body" },
  { "zh": "紫色车身", "en": "purple body" },
  { "zh": "粉色车身", "en": "pink body" },
  { "zh": "金色车身", "en": "gold body" },
  { "zh": "青铜色车身", "en": "bronze body" },
  { "zh": "栗色车身", "en": "maroon body" },
  { "zh": "哑光漆", "en": "matte paint" },
  { "zh": "金属漆", "en": "metallic paint" },
  { "zh": "珠光漆", "en": "pearl paint" },
  { "zh": "镀铬", "en": "chrome finish" },
  { "zh": "定制喷漆", "en": "custom paint job" },
  { "zh": "双色喷漆", "en": "two-tone paint" },
  { "zh": "渐变色喷漆", "en": "gradient paint" },
  { "zh": "拉力赛涂装", "en": "rally livery" },
  { "zh": "赛车涂装", "en": "racing livery" },
  { "zh": "条纹", "en": "stripes" },
  { "zh": "贴花", "en": "decals" },
  { "zh": "生锈", "en": "rusty" },
  { "zh": "脏污", "en": "dirty (car)" },
  { "zh": "干净", "en": "clean (car)" },
  { "zh": "闪亮", "en": "glossy" },
  { "zh": "抛光", "en": "polished" },
  { "zh": "霓虹色车身", "en": "neon color" },
  { "zh": "透明车身", "en": "transparent body" }
  ]
  },
  {
  "name": "背景 (Background/Environment)",
  "tags": [
  { "zh": "在城市中", "en": "in a city" },
  { "zh": "在赛道上", "en": "on a race track" },
  { "zh": "在山路上", "en": "on a mountain road" },
  { "zh": "在雨中", "en": "in the rain" },
  { "zh": "夜晚", "en": "at night" },
  { "zh": "日落", "en": "sunset" },
  { "zh": "霓虹灯", "en": "neon lights" },
  { "zh": "戏剧性光照", "en": "dramatic lighting" },
  { "zh": "工作室灯光", "en": "studio lighting" },
  { "zh": "车库", "en": "in a garage" },
  { "zh": "展厅", "en": "in a showroom" },
  { "zh": "城市街景", "en": "urban street" },
  { "zh": "郊区街道", "en": "suburban street" },
  { "zh": "乡村道路", "en": "country road" },
  { "zh": "高速公路", "en": "highway" },
  { "zh": "沙漠", "en": "desert" },
  { "zh": "海岸线", "en": "coastline" },
  { "zh": "森林", "en": "forest" },
  { "zh": "雪景", "en": "snowy landscape" },
  { "zh": "未来都市", "en": "futuristic city" },
  { "zh": "废墟", "en": "dystopian ruins" },
  { "zh": "太空", "en": "in space" },
  { "zh": "开放场地", "en": "open field" },
  { "zh": "工业区", "en": "industrial area" },
  { "zh": "隧道", "en": "tunnel" },
  { "zh": "桥上", "en": "on a bridge" },
  { "zh": "停车场", "en": "parking lot" },
  { "zh": "洗车场", "en": "car wash" },
  { "zh": "修理厂", "en": "mechanic shop" },
  { "zh": "车展", "en": "car show" },
  { "zh": "白天", "en": "daytime" },
  { "zh": "黎明", "en": "dawn" },
  { "zh": "黄昏", "en": "dusk" },
  { "zh": "晴空万里", "en": "clear sky" },
  { "zh": "阴天", "en": "cloudy sky" },
  { "zh": "暴风雨", "en": "stormy weather" },
  { "zh": "雾蒙蒙", "en": "foggy" },
  { "zh": "多阳光", "en": "sunny" },
  { "zh": "柔和光线", "en": "soft lighting" },
  { "zh": "硬光", "en": "harsh lighting" },
  { "zh": "自然光", "en": "natural light" },
  { "zh": "人造光", "en": "artificial light" },
  { "zh": "车道", "en": "driveway" },
  { "zh": "路边", "en": "roadside" },
  { "zh": "背景虚化", "en": "blurred background" },
  { "zh": "清晰背景", "en": "sharp background" },
  { "zh": "路灯", "en": "street lights" },
  { "zh": "城市灯光", "en": "city lights" },
  { "zh": "光轨", "en": "light trails" },
  { "zh": "雨滴", "en": "rain drops" },
  { "zh": "闪电", "en": "lightning" },
  { "zh": "尘土飞扬", "en": "dusty (background)" },
  { "zh": "烟雾弥漫", "en": "smoggy (background)" },
  { "zh": "镜面地表", "en": "wet pavement reflection" },
  { "zh": "倒影", "en": "reflection (background)" },
  { "zh": "前景物体", "en": "foreground objects" }
  ]
  }
  ]
  });