tagData.push({
  "group": "工业美术 (Industrial Arts)",
  "categories": [
    {
      "name": "陶瓷艺术 (Ceramic Art)",
      "tags": [
        // 白瓷类
        { "zh": "白瓷", "en": "white porcelain" },
        { "zh": "德化白瓷 (Blanc de Chine)", "en": "Dehua white porcelain (Blanc de Chine)" },
        { "zh": "邢窑白瓷", "en": "Xing ware white porcelain" },
        { "zh": "定窑白瓷", "en": "Ding ware white porcelain" },
        { "zh": "高白釉", "en": "high white glaze" },
        { "zh": "卵白釉 (枢府瓷)", "en": "luanbai glaze (Shufu porcelain)" },
        { "zh": "甜白釉", "en": "tianbai (sweet white) glaze" },
        { "zh": "乳白釉", "en": "creamy white glaze" },
        { "zh": "象牙白", "en": "ivory white" },
        { "zh": "雪白", "en": "snow white" },
        { "zh": "纯白", "en": "pure white" },
        // 青瓷类
        { "zh": "青瓷", "en": "celadon porcelain" },
        { "zh": "龙泉青瓷", "en": "Longquan celadon porcelain" },
        { "zh": "越窑青瓷", "en": "Yue ware celadon porcelain" },
        { "zh": "汝窑天青", "en": "Ru ware sky-blue celadon" },
        { "zh": "官窑青瓷", "en": "Guan ware celadon" },
        { "zh": "哥窑开片", "en": "Ge ware celadon with crackle glaze" },
        { "zh": "粉青釉", "en": "fenqing (pale bluish-green) glaze" },
        { "zh": "梅子青釉", "en": "meiziqing (plum-green) glaze" },
        { "zh": "豆青釉", "en": "douqing (pea green) glaze" },
        { "zh": "影青釉 (青白瓷)", "en": "yingqing (bluish-white) glaze" },
        { "zh": "天龙青", "en": "tianlong green" },
        { "zh": "翠青釉", "en": "emerald green glaze" },
        { "zh": "湖水绿", "en": "lake green" },
        { "zh": "橄榄绿", "en": "olive green" },
        { "zh": "石灰青", "en": "ash green" },
        // 青花瓷类
        { "zh": "青花瓷", "en": "blue and white porcelain" },
        { "zh": "元青花", "en": "Yuan dynasty blue and white porcelain" },
        { "zh": "永宣青花", "en": "Yongle and Xuande blue and white porcelain" },
        { "zh": "成化青花", "en": "Chenghua blue and white porcelain" },
        { "zh": "苏麻离青料", "en": "Sumali blue pigment" },
        { "zh": "平等青料", "en": "pingdeng blue pigment" },
        { "zh": "钴蓝", "en": "cobalt blue" },
        { "zh": "发色沉稳", "en": "stable coloring (blue and white)" },
        { "zh": "晕散效果", "en": "smudged/blurry effect (blue and white)" },
        { "zh": "铁锈斑", "en": "iron rust spots (blue and white)" },
        { "zh": "淡描青花", "en": "faint blue and white drawing" },
        { "zh": "青花留白", "en": "blue and white with reserved white" },
        { "zh": "青花加彩", "en": "blue and white with overglaze enamels" },
        // 色釉瓷类 (Monochrome Glazed Porcelain)
        { "zh": "色釉", "en": "monochrome glaze" },
        { "zh": "红釉", "en": "red glaze" },
        { "zh": "郎窑红", "en": "Langyao red glaze" },
        { "zh": "祭红釉 (鲜红釉)", "en": "sacrificial red glaze (fresh red glaze)" },
        { "zh": "豇豆红釉", "en": "bean-red glaze" },
        { "zh": "霁蓝釉", "en": "sacrificial blue glaze" },
        { "zh": "天蓝釉", "en": "sky blue glaze" },
        { "zh": "孔雀蓝釉", "en": "peacock blue glaze" },
        { "zh": "茄皮紫釉", "en": "aubergine purple glaze" },
        { "zh": "黄釉", "en": "yellow glaze" },
        { "zh": "娇黄釉", "en": "jiao huang (bright yellow) glaze" },
        { "zh": "绿釉", "en": "green glaze" },
        { "zh": "瓜皮绿釉", "en": "melon peel green glaze" },
        { "zh": "洒蓝釉 (雪花蓝)", "en": "sprinkled blue glaze (snowflake blue)" },
        { "zh": "炉钧釉", "en": "lujun glaze" },
        { "zh": "茶叶末釉", "en": "tea dust glaze" },
        { "zh": "窑变釉", "en": "flambé glaze" },
        { "zh": "仿钧釉", "en": "imitation Jun glaze" },
        { "zh": "仿官釉", "en": "imitation Guan glaze" },
        { "zh": "仿哥釉", "en": "imitation Ge glaze" },
        { "zh": "仿石釉", "en": "imitation stone glaze" },
        { "zh": "珍珠釉", "en": "pearl glaze" },
        { "zh": "珊瑚红", "en": "coral red" },
        { "zh": "苹果绿", "en": "apple green" },
        { "zh": "胭脂红", "en": "rouge red" },
        // 彩瓷工艺 (Decorated Porcelain Techniques)
        { "zh": "斗彩", "en": "doucai (contrasting colors) porcelain" },
        { "zh": "成化斗彩", "en": "Chenghua doucai" },
        { "zh": "粉彩", "en": "famille rose porcelain" },
        { "zh": "墨彩", "en": "ink wash enamels" },
        { "zh": "浅绛彩", "en": "qianjiangcai (light sepia enamels)" },
        { "zh": "新粉彩", "en": "new style famille rose" },
        { "zh": "洋彩 (轧道)", "en": "yangcai (Western-style enamels, often with ground)'" },
        { "zh": "广彩", "en": "Guangcai (Canton enamels) porcelain" }, // 常被认为是“洋瓷”的一种表现
        { "zh": "珐琅彩", "en": "falangcai (painted enamel porcelain)" },
        { "zh": "康熙五彩", "en": "Kangxi wucai (five-color) porcelain" },
        { "zh": "雍正粉彩", "en": "Yongzheng famille rose" },
        { "zh": "乾隆期彩", "en": "Qianlong period polychrome enamels" },
        { "zh": "素三彩", "en": "sancai (three-color) porcelain with unglazed biscuit" },
        { "zh": "琉璃彩", "en": "liuli (glazed pottery with enamel)" },
        { "zh": "描金彩", "en": "gilded enamels" },
        { "zh": "金地粉彩", "en": "famille rose with gold ground" },
        { "zh": "锦地粉彩", "en": "famille rose with brocade ground" },
        { "zh": "轧道工艺", "en": "zhadiao (incised/stippled ground) technique" },
        { "zh": "开光装饰", "en": "reserve decoration (on porcelain)" },
        { "zh": "洋瓷", "en": "Westernized porcelain/imported porcelain style" }, // 广义概念，可指向多种受西方影响或为西方市场生产的瓷器
        { "zh": "手绘瓷器", "en": "hand-painted porcelain" },
        { "zh": "贴花瓷器", "en": "decal porcelain" },
        { "zh": "镂空瓷器", "en": "pierced porcelain" },
        { "zh": "薄胎瓷器", "en": "egg-shell porcelain" },
        { "zh": "玲珑瓷器", "en": "linglong ('rice-grain') porcelain" },
        { "zh": "瓷雕", "en": "porcelain sculpture" },
        { "zh": "瓷板画", "en": "porcelain panel painting" },
        { "zh": "中国陶瓷", "en": "Chinese ceramics" },
        { "zh": "欧洲陶瓷", "en": "European ceramics" },
        { "zh": "日本陶瓷", "en": "Japanese ceramics" },
        { "zh": "现代陶瓷", "en": "modern ceramics" },
        { "zh": "国际陶瓷", "en": "international ceramics" }
      ]
    },
    {
      "name": "金石玉器 (Jade & Stone Art)",
      "tags": [
        // 宝石类
        { "zh": "宝石", "en": "gemstone" },
        { "zh": "钻石", "en": "diamond" },
        { "zh": "红宝石", "en": "ruby" },
        { "zh": "蓝宝石", "en": "sapphire" },
        { "zh": "祖母绿", "en": "emerald" },
        { "zh": "碧玺", "en": "tourmaline" },
        { "zh": "欧泊", "en": "opal" },
        { "zh": "坦桑石", "en": "tanzanite" },
        { "zh": "尖晶石", "en": "spinel" },
        { "zh": "石榴石", "en": "garnet" },
        { "zh": "紫水晶", "en": "amethyst" },
        { "zh": "海蓝宝", "en": "aquamarine" },
        { "zh": "托帕石", "en": "topaz" },
        { "zh": "月光石", "en": "moonstone" },
        { "zh": "金绿宝石", "en": "chrysoberyl" },
        { "zh": "珍珠", "en": "pearl" },
        { "zh": "猫眼", "en": "cat's eye" },
        { "zh": "星光宝石", "en": "star gemstone" },
        { "zh": "裸石", "en": "loose stone" },
        { "zh": "刻面宝石", "en": "faceted gemstone" },
        { "zh": "弧面宝石", "en": "cabochon gemstone" },
        { "zh": "宝石原石", "en": "gemstone rough" },
        { "zh": "彩色宝石", "en": "colored gemstones" },
        { "zh": "半宝石", "en": "semi-precious stone" },
        // 玉器类
        { "zh": "玉器", "en": "jade ware" },
        { "zh": "和田玉", "en": "Hetian jade" },
        { "zh": "新疆和田玉", "en": "Xinjiang Hetian jade" },
        { "zh": "翡翠", "en": "jadeite" },
        { "zh": "缅甸翡翠", "en": "Burmese jadeite" },
        { "zh": "岫岩玉", "en": "Xiuyan jade" },
        { "zh": "独山玉", "en": "Dushan jade" },
        { "zh": "青玉", "en": "celadon jade" },
        { "zh": "白玉", "en": "white jade" },
        { "zh": "碧玉", "en": "spinach green jade" },
        { "zh": "墨玉", "en": "black jade" },
        { "zh": "黄玉", "en": "yellow jade" },
        { "zh": "羊脂玉", "en": "mutton fat jade" },
        { "zh": "高古玉", "en": "ancient jade" },
        { "zh": "明清玉", "en": "Ming and Qing dynasty jade" },
        { "zh": "玉雕", "en": "jade carving" },
        { "zh": "琢玉工艺", "en": "jade working craftsmanship" },
        { "zh": "软玉", "en": "nephrite" },
        { "zh": "硬玉", "en": "jadeite" },
        { "zh": "玛瑙", "en": "agate" },
        { "zh": "水晶", "en": "crystal" },
        { "zh": "青金石", "en": "lapis lazuli" },
        { "zh": "绿松石", "en": "turquoise" },
        { "zh": "琥珀", "en": "amber" },
        { "zh": "珊瑚", "en": "coral" },
        { "zh": "寿山石", "en": "Shoushan stone" },
        { "zh": "鸡血石", "en": "chicken blood stone" },
        { "zh": "青田石", "en": "Qingtian stone" },
        { "zh": "巴林石", "en": "Balin stone" },
        { "zh": "芙蓉石", "en": "rose quartz" },
        { "zh": "大理石雕", "en": "marble carving" },
        { "zh": "花岗岩雕", "en": "granite carving" },
        { "zh": "青石雕", "en": "bluestone carving" },
        { "zh": "砚台", "en": "inkstone" },
        { "zh": "印章雕刻", "en": "seal carving" },
        // 珠宝设计与镶嵌
        { "zh": "高定珠宝", "en": "haute joaillerie" },
        { "zh": "艺术珠宝", "en": "art jewelry" },
        { "zh": "珠宝设计", "en": "jewelry design" },
        { "zh": "珠宝镶嵌", "en": "gemstone setting" },
        { "zh": "爪镶", "en": "prong setting" },
        { "zh": "包镶", "en": "bezel setting" },
        { "zh": "微镶", "en": "micro-pavé setting" },
        { "zh": "密镶", "en": "pavé setting" },
        { "zh": "槽镶 (轨道镶)", "en": "channel setting" },
        { "zh": "群镶", "en": "cluster setting" },
        { "zh": "隐秘式镶嵌", "en": "invisible setting" },
        { "zh": "定制珠宝", "en": "bespoke jewelry" },
        { "zh": "古典珠宝", "en": "classical jewelry" },
        { "zh": "现代珠宝", "en": "modern jewelry" },
        { "zh": "首饰", "en": "ornaments/jewelry" },
        { "zh": "项链", "en": "necklace" },
        { "zh": "手镯", "en": "bracelet" },
        { "zh": "戒指", "en": "ring" },
        { "zh": "耳环", "en": "earrings" },
        { "zh": "胸针", "en": "brooch" },
        { "zh": "头饰", "en": "headpiece" },
        { "zh": "钻戒", "en": "diamond ring" },
        { "zh": "订婚戒指", "en": "engagement ring" },
        { "zh": "结婚戒指", "en": "wedding band" }
      ]
    },
    {
      "name": "金属工艺 (Metalwork)",
      "tags": [
        // 铜器类
        { "zh": "铜器", "en": "bronze ware" },
        { "zh": "青铜器", "en": "ancient bronze ware" },
        { "zh": "商周青铜器", "en": "Shang and Zhou dynasty bronze ware" },
        { "zh": "秦汉铜器", "en": "Qin and Han dynasty bronze ware" },
        { "zh": "鎏金铜器", "en": "gilt-bronze ware" },
        { "zh": "镀金铜器", "en": "gold-plated bronze ware" },
        { "zh": "错金银铜器", "en": "bronze ware with gold and silver inlay" },
        { "zh": "嵌金嵌银", "en": "gold and silver inlay" },
        { "zh": "铸铜", "en": "bronze casting" },
        { "zh": "锻铜", "en": "wrought bronze" },
        { "zh": "铜雕", "en": "bronze sculpture" },
        { "zh": "铜炉", "en": "bronze censer" },
        { "zh": "铜镜", "en": "bronze mirror" },
        { "zh": "铜胎", "en": "bronze body" },
        { "zh": "紫铜", "en": "red copper" },
        { "zh": "黄铜", "en": "brass" },
        { "zh": "白铜", "en": "cupronickel" },
        { "zh": "青铜", "en": "bronze (alloy)" },
        // 珐琅彩类 (Enamelware)
        { "zh": "珐琅彩", "en": "enamel color/enamel painting" }, // 作为工艺或颜色
        { "zh": "珐琅器", "en": "enamelware" },
        { "zh": "景泰蓝", "en": "cloisonné enamel (Jingtailan)" },
        { "zh": "掐丝珐琅", "en": "cloisonné enamel" },
        { "zh": "金胎珐琅", "en": "gold-body enamel (gilt-bronze cloisonné)" },
        { "zh": "铜胎掐丝珐琅", "en": "copper-body cloisonné enamel" },
        { "zh": "画珐琅", "en": "painted enamel" },
        { "zh": "錾胎珐琅", "en": "repoussé enamel" },
        { "zh": "内填珐琅 (嵌胎珐琅)", "en": "champlevé enamel" },
        { "zh": "透明珐琅", "en": "plique-à-jour enamel" },
        { "zh": "大明景泰蓝", "en": "Daming Jingtailan (Ming dynasty cloisonné)" },
        { "zh": "御用珐琅", "en": "imperial enamelware" },
        { "zh": "广州珐琅", "en": "Guangzhou painted enamel" },
        { "zh": "北京珐琅", "en": "Beijing cloisonné" },
        { "zh": "珐琅釉料", "en": "enamel glazes" },
        { "zh": "金属胎珐琅", "en": "metal-body enamelware" },
        { "zh": "瓷胎珐琅", "en": "porcelain-body enamelware" },
        // 金银器与细金工艺
        { "zh": "金器", "en": "goldware" },
        { "zh": "银器", "en": "silverware" },
        { "zh": "金银细工", "en": "fine gold and silver work" },
        { "zh": "花丝镶嵌", "en": "filigree and inlay (metalware)" },
        { "zh": "錾刻", "en": "chasing and repoussé" },
        { "zh": "累丝", "en": "stacking filigree" },
        { "zh": "点翠", "en": "kingfisher feather inlay (often on silver/gold)" },
        { "zh": "烧蓝", "en": "fired blue enamel (on silver)" },
        { "zh": "镀金", "en": "gold plating" },
        { "zh": "镀银", "en": "silver plating" },
        { "zh": "鎏金", "en": "fire gilding" },
        { "zh": "包金", "en": "gold filled/wrapped" },
        { "zh": "锤鍱工艺", "en": "hammered metal technique" },
        { "zh": "冲压", "en": "stamping (metal)" },
        { "zh": "铸造", "en": "casting (metal)" },
        { "zh": "焊接", "en": "welding" },
        { "zh": "铆接", "en": "riveting" },
        { "zh": "浮雕金属", "en": "relief metalwork" },
        { "zh": "失蜡法", "en": "lost-wax casting" },
        { "zh": "银饰", "en": "silver ornaments" },
        { "zh": "金饰", "en": "gold ornaments" },
        { "zh": "锡器", "en": "pewterware" },
        { "zh": "铁艺", "en": "wrought iron art" },
        { "zh": "不锈钢制品", "en": "stainless steel products" },
        { "zh": "航空铝材", "en": "aerospace aluminum" }
      ]
    },
    {
      "name": "漆器艺术 (Lacquer Art)",
      "tags": [
        { "zh": "漆器", "en": "lacquerware" },
        { "zh": "大漆 (天然漆)", "en": "urushi (natural lacquer)" },
        { "zh": "雕漆", "en": "carved lacquer" },
        { "zh": "剔红", "en": "carved red lacquer" },
        { "zh": "剔黑", "en": "carved black lacquer" },
        { "zh": "剔彩", "en": "carved polychrome lacquer" },
        { "zh": "螺钿漆器", "en": "mother-of-pearl inlaid lacquerware" },
        { "zh": "描金漆器", "en": "gilded lacquerware" },
        { "zh": "彩绘漆器", "en": "painted lacquerware" },
        { "zh": "金银平脱", "en": "heida (lacquer with metal inlay)" },
        { "zh": "戗金", "en": "qiangjin (incised and filled with gold powder)" },
        { "zh": "莳绘 (日本漆器)", "en": "maki-e (Japanese gilded lacquer)" },
        { "zh": "变涂", "en": "variable lacquer finish" },
        { "zh": "犀皮漆", "en": "rhino-skin lacquer" },
        { "zh": "填漆", "en": "filled lacquer" },
        { "zh": "镶嵌漆器", "en": "inlaid lacquerware" },
        { "zh": "扬州漆器", "en": "Yangzhou lacquerware" },
        { "zh": "福州脱胎漆器", "en": "Fuzhou bodiless lacquerware" },
        { "zh": "平遥推光漆器", "en": "Pingyao polished lacquerware" },
        { "zh": "漆画", "en": "lacquer painting" },
        { "zh": "漆艺", "en": "lacquer art" },
        { "zh": "漆雕", "en": "lacquer carving" },
        { "zh": "髹漆工艺", "en": "lacquering technique" },
        { "zh": "漆胎", "en": "lacquer body" },
        { "zh": "麻布胎", "en": "hemp cloth body (lacquerware)" },
        { "zh": "木胎", "en": "wood body (lacquerware)" },
        { "zh": "纸胎", "en": "paper body (lacquerware)" },
        { "zh": "夹纻胎", "en": "cloth-reinforced lacquerware" }
      ]
    },
    {
      "name": "其他材质与工艺 (Other Materials & Crafts)",
      "tags": [
        // 木器、竹器、牙角雕
        { "zh": "木雕", "en": "wood carving" },
        { "zh": "竹雕", "en": "bamboo carving" },
        { "zh": "根雕", "en": "root carving" },
        { "zh": "红木家具", "en": "rosewood furniture" },
        { "zh": "紫檀家具", "en": "zitan (red sandalwood) furniture" },
        { "zh": "花梨木家具", "en": "huanghuali (rosewood) furniture" },
        { "zh": "楠木家具", "en": "nanmu furniture" },
        { "zh": "竹编", "en": "bamboo weaving" },
        { "zh": "牙雕", "en": "ivory carving (historic/replica)" },
        { "zh": "骨雕", "en": "bone carving" },
        { "zh": "角雕", "en": "horn carving" },
        // 纺织、玻璃、泥塑、石雕等
        { "zh": "刺绣", "en": "embroidery" },
        { "zh": "苏绣", "en": "Suzhou embroidery" },
        { "zh": "湘绣", "en": "Hunan embroidery" },
        { "zh": "缂丝", "en": "kesi (tapestry weaving)" },
        { "zh": "织锦", "en": "brocade" },
        { "zh": "南京云锦", "en": "Nanjing Yunjin brocade" },
        { "zh": "蜡染", "en": "batik" },
        { "zh": "扎染", "en": "tie-dye" },
        { "zh": "玻璃器皿", "en": "glassware" },
        { "zh": "琉璃工艺", "en": "liuli (ancient Chinese glass/glazed pottery art)" },
        { "zh": "吹制玻璃", "en": "blown glass" },
        { "zh": "水晶器", "en": "crystal ware" },
        { "zh": "泥塑", "en": "clay sculpture" },
        { "zh": "石雕", "en": "stone carving" },
        { "zh": "砖雕", "en": "brick carving" },
        { "zh": "唐卡", "en": "Thangka (Tibetan scroll painting)" },
        { "zh": "皮影", "en": "shadow puppetry" },
        { "zh": "剪纸", "en": "paper cutting" },
        { "zh": "中国结", "en": "Chinese knotting" }
      ]
    },
    {
      "name": "历史时期与地域流派 (Historical Periods & Regional Schools)",
      "tags": [
        // 三星堆特别分类
        { "zh": "三星堆", "en": "Sanxingdui (artifacts/culture)" },
        { "zh": "三星堆青铜器", "en": "Sanxingdui bronze ware" },
        { "zh": "三星堆金器", "en": "Sanxingdui goldware" },
        { "zh": "三星堆玉器", "en": "Sanxingdui jade ware" },
        { "zh": "古蜀文明", "en": "Ancient Shu Civilization" },
        { "zh": "三星堆人像", "en": "Sanxingdui human figures" },
        { "zh": "三星堆神树", "en": "Sanxingdui sacred tree" },
        { "zh": "三星堆面具", "en": "Sanxingdui masks" },
        { "zh": "古老图腾", "en": "ancient totem" },
        { "zh": "神秘文明", "en": "mysterious civilization" },
        // 中国古代时期
        { "zh": "新石器时代", "en": "Neolithic Era" },
        { "zh": "商周时期", "en": "Shang and Zhou Dynasties" },
        { "zh": "春秋战国", "en": "Spring and Autumn / Warring States periods" },
        { "zh": "秦汉时期", "en": "Qin and Han Dynasties" },
        { "zh": "魏晋南北朝", "en": "Wei, Jin, Southern and Northern Dynasties" },
        { "zh": "隋唐时期", "en": "Sui and Tang Dynasties" },
        { "zh": "五代辽宋金元", "en": "Five Dynasties, Liao, Song, Jin, Yuan" },
        { "zh": "明清时期", "en": "Ming and Qing Dynasties" },
        { "zh": "清三代 (康雍乾)", "en": "Three Reigns of Qing (Kangxi, Yongzheng, Qianlong)" },
        { "zh": "民国时期", "en": "Republican Era" },
        { "zh": "当代中国工艺", "en": "Contemporary Chinese Crafts" },
        // 流派与地域
        { "zh": "景德镇", "en": "Jingdezhen" },
        { "zh": "扬州", "en": "Yangzhou" },
        { "zh": "苏州", "en": "Suzhou" },
        { "zh": "北京", "en": "Beijing" },
        { "zh": "广作", "en": "Guangdong School (e.g. furniture)" },
        { "zh": "苏作", "en": "Suzhou School (e.g. furniture, jade)" },
        { "zh": "京作", "en": "Beijing School (e.g. furniture, enamels)" },
        { "zh": "海派", "en": "Shanghai School (cultural influence)" },
        { "zh": "宫廷风格", "en": "Imperial Court Style" },
        { "zh": "文人风格", "en": "Scholar's Style" },
        { "zh": "民间艺术", "en": "Folk Art" },
        { "zh": "少数民族工艺", "en": "Ethnic Minority Crafts" },
        { "zh": "中国传统", "en": "Chinese traditional" },
        { "zh": "现代工业", "en": "Modern industrial" },
        { "zh": "西方设计", "en": "Western design" },
        { "zh": "日本工艺", "en": "Japanese craftsmanship" },
        { "zh": "欧洲艺术", "en": "European art" }
      ]
    },
    {
      "name": "器型与功能 (Forms & Functions)",
      "tags": [
        // 实用器皿
        { "zh": "瓶", "en": "vase (bottle)" },
        { "zh": "尊", "en": "zun (sacrificial vessel)" },
        { "zh": "罐", "en": "jar" },
        { "zh": "壶", "en": "pot/ewer" },
        { "zh": "碗", "en": "bowl" },
        { "zh": "盘", "en": "plate/dish" },
        { "zh": "杯", "en": "cup" },
        { "zh": "碟", "en": "saucer" },
        { "zh": "鼎", "en": "ding (ancient tripod cauldron)" },
        { "zh": "爵", "en": "jue (ancient wine vessel)" },
        { "zh": "簋", "en": "gui (ancient food vessel)" },
        { "zh": "豆", "en": "dou (ancient food vessel)" },
        { "zh": "炉", "en": "censer/brazier" },
        { "zh": "文房用具", "en": "scholar's desk articles" },
        { "zh": "笔筒", "en": "brush pot" },
        { "zh": "笔洗", "en": "brush washer" },
        { "zh": "水盂", "en": "water pot" },
        { "zh": "镇纸", "en": "paperweight" },
        { "zh": "印盒", "en": "seal paste box" },
        { "zh": "鼻烟壶", "en": "snuff bottle" },
        { "zh": "茶具", "en": "tea set" },
        { "zh": "酒具", "en": "wine set" },
        { "zh": "餐具", "en": "dinnerware" },
        { "zh": "家具", "en": "furniture" },
        { "zh": "箱柜", "en": "chests and cabinets" },
        { "zh": "屏风", "en": "folding screen" },
        { "zh": "灯具", "en": "lighting fixtures" },
        { "zh": "乐器", "en": "musical instruments" },
        // 观赏与佩饰
        { "zh": "雕塑", "en": "sculpture" },
        { "zh": "摆件", "en": "ornament/display item" },
        { "zh": "人物造像", "en": "figure sculpture" },
        { "zh": "动物造型", "en": "animal figures" },
        { "zh": "花鸟纹饰", "en": "flower and bird motifs" },
        { "zh": "神兽", "en": "mythical beasts" },
        { "zh": "如意", "en": "ruyi scepter" },
        { "zh": "手镯", "en": "bracelet/bangle" },
        { "zh": "项链", "en": "necklace" },
        { "zh": "戒指", "en": "ring" },
        { "zh": "耳环", "en": "earrings" },
        { "zh": "发簪", "en": "hairpin" },
        { "zh": "挂饰", "en": "pendant/hanging ornament" },
        { "zh": "胸针", "en": "brooch" },
        { "zh": "玉牌", "en": "jade plaque" },
        { "zh": "佩玉", "en": "jade pendant" },
        { "zh": "印章", "en": "seal/chop" },
        { "zh": "扇子", "en": "fan (artistic)" },
        { "zh": "鼻烟壶", "en": "snuff bottle" },
        { "zh": "观赏石", "en": "scholar's rock" }
      ]
    },
    {
      "name": "主题与纹饰 (Themes & Motifs)",
      "tags": [
        { "zh": "龙纹", "en": "dragon motif" },
        { "zh": "凤纹", "en": "phoenix motif" },
        { "zh": "瑞兽纹", "en": "auspicious beasts motif" },
        { "zh": "人物故事", "en": "figure story motif" },
        { "zh": "仙人题材", "en": "immortal theme" },
        { "zh": "山水风景", "en": "landscape motif" },
        { "zh": "花鸟鱼虫", "en": "flowers, birds, fish, insects motif" },
        { "zh": "祥云纹", "en": "auspicious cloud motif" },
        { "zh": "卷草纹", "en": "scrolling foliage motif" },
        { "zh": "缠枝纹", "en": "continuous scrolling motif" },
        { "zh": "回纹", "en": "key fret pattern" },
        { "zh": "锦地纹", "en": "brocade pattern ground" },
        { "zh": "八宝纹", "en": "Eight Buddhist Emblems motif" },
        { "zh": "暗八仙", "en": "Eight Immortals' Attributes motif" },
        { "zh": "福禄寿", "en": "Fu Lu Shou (fortune, prosperity, longevity) symbols" },
        { "zh": "博古纹", "en": "bogutu (antiques collection motif)" },
        { "zh": "百子图", "en": "hundred children motif" },
        { "zh": "吉祥图案", "en": "auspicious patterns" },
        { "zh": "几何图案", "en": "geometric patterns" },
        { "zh": "西方神话", "en": "Western mythology" },
        { "zh": "宗教符号", "en": "religious symbols" },
        { "zh": "自然元素", "en": "natural elements" },
        { "zh": "节庆主题", "en": "festive themes" },
        { "zh": "狩猎图", "en": "hunting scene" },
        { "zh": "耕织图", "en": "farming and weaving scene" },
        { "zh": "渔樵耕读", "en": "fisherman, woodcutter, farmer, scholar" },
        { "zh": "诗书画印", "en": "poetry, calligraphy, painting, seal (elements)" }
      ]
    },
    {
      "name": "设计与美学 (Design & Aesthetics)",
      "tags": [
        { "zh": "古典美学", "en": "classical aesthetics" },
        { "zh": "现代设计", "en": "modern design" },
        { "zh": "极简风格", "en": "minimalist style" },
        { "zh": "奢华风格", "en": "luxury style" },
        { "zh": "工匠精神", "en": "artisan spirit" },
        { "zh": "东方美学", "en": "oriental aesthetics" },
        { "zh": "西方美学", "en": "western aesthetics" },
        { "zh": "人体工学", "en": "ergonomics" },
        { "zh": "功能主义", "en": "functionalism" },
        { "zh": "材质对比", "en": "material contrast" },
        { "zh": "色彩搭配", "en": "color combination" },
        { "zh": "光影效果", "en": "light and shadow effects" },
        { "zh": "精雕细琢", "en": "meticulously carved" },
        { "zh": "匠心独运", "en": "ingenious craftsmanship" },
        { "zh": "创新设计", "en": "innovative design" },
        { "zh": "限量版", "en": "limited edition" },
        { "zh": "定制化", "en": "customization" },
        { "zh": "手工制作", "en": "handmade" },
        { "zh": "工业制造", "en": "industrial manufacturing" },
        { "zh": "传承与创新", "en": "heritage and innovation" },
        { "zh": "抽象艺术", "en": "abstract art" },
        { "zh": "具象表现", "en": "figurative representation" },
        { "zh": "艺术收藏", "en": "art collection" },
        { "zh": "博物馆藏品", "en": "museum collection" },
        { "zh": "高清晰度", "en": "high definition" },
        { "zh": "超现实", "en": "surrealism" },
        { "zh": "写实", "en": "realism" },
        { "zh": "唯美", "en": "aesthetic (beautiful)" },
        { "zh": "精致优雅", "en": "exquisite and elegant" },
        { "zh": "和谐统一", "en": "harmony and unity" },
        { "zh": "平衡对称", "en": "balanced and symmetrical" }
      ]
    }
  ]
});