tagData.push({
  "group": "通用词汇 (General Vocabulary)",
  "categories": [
    {
      "name": "风格 (Art Style / Genre)",
      "tags": [
        { "zh": "写实主义", "en": "realistic" },
        { "zh": "超写实", "en": "hyperrealistic" },
        { "zh": "概念艺术", "en": "concept art" },
        { "zh": "卡通", "en": "cartoon" },
        { "zh": "动画", "en": "anime style" },
        { "zh": "赛博朋克", "en": "cyberpunk style" },
        { "zh": "未来主义", "en": "futuristic style" },
        { "zh": "复古未来主义", "en": "retro-futuristic" },
        { "zh": "蒸汽波", "en": "vaporwave style" },
        { "zh": "低多边形", "en": "low poly" },
        { "zh": "像素化", "en": "pixel art" },
        { "zh": "卡通渲染", "en": "cel-shaded" },
        { "zh": "油画风格", "en": "oil painting style" },
        { "zh": "水彩画风格", "en": "watercolor style" },
        { "zh": "素描", "en": "sketch style" },
        { "zh": "线稿", "en": "line art" },
        { "zh": "抽象艺术", "en": "abstract art" },
        { "zh": "工业设计", "en": "industrial design" },
        { "zh": "极简主义", "en": "minimalist style" },
        { "zh": "电影感", "en": "cinematic" },
        { "zh": "艺术摄影", "en": "art photography" },
        { "zh": "印象派", "en": "impressionistic" },
        { "zh": "表现主义", "en": "expressionistic" },
        { "zh": "立体主义", "en": "cubist" },
        { "zh": "超现实主义", "en": "surrealistic" },
        { "zh": "波普艺术", "en": "pop art" },
        { "zh": "涂鸦艺术", "en": "graffiti art" },
        { "zh": "街头艺术", "en": "street art" },
        { "zh": "哥特式", "en": "gothic style" },
        { "zh": "巴洛克", "en": "baroque style" },
        { "zh": "洛可可", "en": "rococo style" },
        { "zh": "新艺术", "en": "art nouveau" },
        { "zh": "装饰艺术", "en": "art deco" },
        { "zh": "蒸汽朋克", "en": "steampunk" },
        { "zh": "柴油朋克", "en": "dieselpunk" },
        { "zh": "废土朋克", "en": "atompunk" },
        { "zh": "合成波", "en": "synthwave" },
        { "zh": "低保真", "en": "lo-fi" },
        { "zh": "复古艺术", "en": "vintage art" },
        { "zh": "中世纪", "en": "medieval style" },
        { "zh": "幻想艺术", "en": "fantasy art" },
        { "zh": "科幻艺术", "en": "sci-fi art" },
        { "zh": "蒸汽朋克", "en": "steampunk" },
        { "zh": "唯美主义", "en": "aesthetic" },
        { "zh": "梦幻", "en": "dreamlike" },
        { "zh": "恐怖", "en": "horror" },
        { "zh": "幽默", "en": "humorous" },
        { "zh": "悲伤", "en": "sad" },
        { "zh": "安静", "en": "serene" },
        { "zh": "充满活力", "en": "vibrant" },
        { "zh": "黑暗", "en": "dark" },
        { "zh": "明亮", "en": "bright" },
        { "zh": "柔和", "en": "soft" },
        { "zh": "锐利", "en": "sharp" },
        { "zh": "扭曲", "en": "distorted" },
        { "zh": "模糊", "en": "blurry" },
        { "zh": "颗粒感", "en": "grainy" },
        { "zh": "噪点", "en": "noisy" },
        { "zh": "清晰", "en": "crisp" },
        { "zh": "粗糙", "en": "rough" },
        { "zh": "光滑", "en": "smooth" },
        { "zh": "纹理", "en": "textured" },
        { "zh": "细节丰富", "en": "highly detailed" },
        { "zh": "细节缺失", "en": "low detail" },
        { "zh": "概念化", "en": "conceptual" },
        { "zh": "示意图", "en": "schematic" },
        { "zh": "蓝图", "en": "blueprint" },
        { "zh": "等距视图", "en": "isometric view" },
        { "zh": "顶视图", "en": "top-down view" },
        { "zh": "侧视图", "en": "side view" },
        { "zh": "X光视图", "en": "X-ray view" },
        { "zh": "雕塑", "en": "sculptural" },
        { "zh": "剪影", "en": "silhouette" },
        { "zh": "抽象表现主义", "en": "abstract expressionism" },
        { "zh": "未来主义派对", "en": "futuristic party" },
        { "zh": "朋克", "en": "punk" },
        { "zh": "哥特式恐怖", "en": "gothic horror" },
        { "zh": "赛博朋克城市", "en": "cyberpunk city" },
        { "zh": "乌托邦", "en": "utopian" },
        { "zh": "反乌托邦", "en": "dystopian" },
        { "zh": "新神话", "en": "neo-mythological" },
        { "zh": "史诗", "en": "epic" },
        { "zh": "浪漫主义", "en": "romanticism" },
        { "zh": "古典主义", "en": "classicism" },
        { "zh": "洛可可", "en": "rococo" },
        { "zh": "超现实主义", "en": "surrealism" },
        { "zh": "波普艺术", "en": "pop art" },
        { "zh": "新艺术运动", "en": "art nouveau" },
        { "zh": "几何形状", "en": "geometric shapes" },
        { "zh": "有机形状", "en": "organic shapes" },
        { "zh": "对称", "en": "symmetric" },
        { "zh": "不对称", "en": "asymmetric" },
        { "zh": "极简主义", "en": "minimalistic" },
        { "zh": "复杂", "en": "complex" },
        { "zh": "简洁", "en": "simple" },
        { "zh": "混乱", "en": "chaotic" },
        { "zh": "有序", "en": "orderly" },
        { "zh": "宏大", "en": "grand" },
        { "zh": "私密", "en": "intimate" },
        { "zh": "活泼", "en": "lively" },
        { "zh": "忧郁", "en": "melancholic" },
        { "zh": "神秘", "en": "mysterious" },
        { "zh": "空灵", "en": "ethereal" },
        { "zh": "粗犷", "en": "gritty" },
        { "zh": "精致", "en": "exquisite" },
        { "zh": "优雅", "en": "elegant" },
        { "zh": "狂野", "en": "wild" },
        { "zh": "卡通化", "en": "cartoony" },
        { "zh": "漫画", "en": "comic book style" },
        { "zh": "绘本", "en": "storybook illustration" },
        { "zh": "儿童插画", "en": "children's illustration" },
        { "zh": "水墨画", "en": "ink wash painting" },
        { "zh": "国画", "en": "traditional Chinese painting" },
        { "zh": "浮世绘", "en": "ukiyo-e" },
        { "zh": "日式风格", "en": "Japanese style" },
        { "zh": "韩式风格", "en": "Korean style" },
        { "zh": "南美风格", "en": "South American style" },
        { "zh": "非洲风格", "en": "African style" },
        { "zh": "北欧风格", "en": "Nordic style" },
        { "zh": "波西米亚", "en": "bohemian" },
        { "zh": "农舍风", "en": "farmhouse style" },
        { "zh": "工业风", "en": "industrial style" },
        { "zh": "洛丽塔", "en": "lolita fashion" },
        { "zh": "朋克摇滚", "en": "punk rock" },
        { "zh": "哥特摇滚", "en": "gothic rock" },
        { "zh": "蒸汽摇滚", "en": "steam rock" },
        { "zh": "新浪潮", "en": "new wave" },
        { "zh": "未来波普", "en": "future pop" },
        { "zh": "未来合成", "en": "future synth" },
        { "zh": "太空歌剧", "en": "space opera" },
        { "zh": "剑与魔法", "en": "sword and sorcery" },
        { "zh": "都市幻想", "en": "urban fantasy" },
        { "zh": "替代历史", "en": "alternate history" },
        { "zh": "后末日", "en": "post-apocalyptic" },
        { "zh": "克苏鲁神话", "en": "lovecraftian horror" },
        { "zh": "柴油朋克", "en": "dieselpunk" },
        { "zh": "科幻西部", "en": "sci-fi western" },
        { "zh": "生物朋克", "en": "biopunk" },
        { "zh": "太阳朋克", "en": "solarpunk" },
        { "zh": "迷幻", "en": "psychedelic" },
        { "zh": "蒸汽波", "en": "vaporwave" },
        { "zh": "故障艺术", "en": "glitch art" },
        { "zh": "超现实主义", "en": "surrealism" },
        { "zh": "超立方体", "en": "hypercube" },
        { "zh": "分形", "en": "fractal" },
        { "zh": "万花筒", "en": "kaleidoscope" }
      ]
    },
    {
      "name": "媒介 (Medium)",
      "tags": [
        { "zh": "数字艺术", "en": "digital art" },
        { "zh": "摄影", "en": "photography" },
        { "zh": "油画", "en": "oil painting" },
        { "zh": "水彩画", "en": "watercolor" },
        { "zh": "素描", "en": "pencil sketch" },
        { "zh": "炭笔画", "en": "charcoal drawing" },
        { "zh": "马克笔画", "en": "marker art" },
        { "zh": "插画", "en": "illustration" },
        { "zh": "概念图", "en": "concept render" },
        { "zh": "雕塑", "en": "sculpture" },
        { "zh": "3D渲染", "en": "3D render" },
        { "zh": "CGI", "en": "CGI" },
        { "zh": "超现实主义绘画", "en": "hyperrealism painting" },
        { "zh": "喷漆画", "en": "spray paint art" },
        { "zh": "版画", "en": "printmaking" },
        { "zh": "黏土模型", "en": "clay model" },
        { "zh": "装置艺术", "en": "installation art" },
        { "zh": "行为艺术", "en": "performance art" },
        { "zh": "混合媒体", "en": "mixed media" },
        { "zh": "电影", "en": "film still" },
        { "zh": "视频游戏截图", "en": "video game screenshot" },
        { "zh": "电影剧照", "en": "film grab" },
        { "zh": "动画帧", "en": "animation frame" },
        { "zh": "虚拟现实", "en": "virtual reality (VR)" },
        { "zh": "增强现实", "en": "augmented reality (AR)" },
        { "zh": "全息图", "en": "hologram" },
        { "zh": "投影", "en": "projection" },
        { "zh": "浮雕", "en": "bas-relief" },
        { "zh": "镶嵌画", "en": "mosaic" },
        { "zh": "壁画", "en": "mural" },
        { "zh": "涂鸦", "en": "doodle" },
        { "zh": "速写", "en": "speed painting" },
        { "zh": "数字绘画", "en": "digital painting" },
        { "zh": "像素艺术", "en": "pixel art" },
        { "zh": "矢量图", "en": "vector art" },
        { "zh": "线图", "en": "line drawing" },
        { "zh": "丝网印刷", "en": "screen print" },
        { "zh": "动画", "en": "animation" },
        { "zh": "漫画", "en": "comic" },
        { "zh": "木刻", "en": "woodcut" },
        { "zh": "蚀刻", "en": "etching" },
        { "zh": "石版画", "en": "lithograph" },
        { "zh": "纸张", "en": "paper" },
        { "zh": "画布", "en": "canvas" },
        { "zh": "金属", "en": "metal" },
        { "zh": "玻璃", "en": "glass" },
        { "zh": "木材", "en": "wood" },
        { "zh": "塑料", "en": "plastic" },
        { "zh": "泥土", "en": "earth" },
        { "zh": "冰", "en": "ice" },
        { "zh": "流体", "en": "fluid simulation" },
        { "zh": "粒子系统", "en": "particle system" },
        { "zh": "体素", "en": "voxel art" },
        { "zh": "手工制作", "en": "handmade" },
        { "zh": "传统艺术", "en": "traditional art" },
        { "zh": "新媒体艺术", "en": "new media art" }
      ]
    },
    {
      "name": "光照 (Lighting)",
      "tags": [
        { "zh": "自然光", "en": "natural light" },
        { "zh": "人造光", "en": "artificial light" },
        { "zh": "阳光", "en": "sunlight" },
        { "zh": "直射光", "en": "direct light" },
        { "zh": "柔和光", "en": "soft light" },
        { "zh": "硬光", "en": "hard light" },
        { "zh": "逆光", "en": "backlight" },
        { "zh": "侧光", "en": "side light" },
        { "zh": "顶光", "en": "top light" },
        { "zh": "底光", "en": "bottom light" },
        { "zh": "环境光", "en": "ambient light" },
        { "zh": "聚光灯", "en": "spotlight" },
        { "zh": "泛光灯", "en": "floodlight" },
        { "zh": "霞光", "en": "rim light" },
        {"zh": "电影照明", "en": "cinematic lighting"},
        { "zh": "三点照明", "en": "three-point lighting" },
        { "zh": "高光", "en": "highlights" },
        { "zh": "阴影", "en": "shadows" },
        { "zh": "长阴影", "en": "long shadows" },
        { "zh": "对比鲜明", "en": "high contrast" },
        { "zh": "低对比度", "en": "low contrast" },
        { "zh": "戏剧性光照", "en": "dramatic lighting" },
        { "zh": "柔和光线", "en": "soft illumination" },
        { "zh": "工作室灯光", "en": "studio lighting" },
        { "zh": "霓虹灯", "en": "neon lighting" },
        { "zh": "辉光", "en": "glow" },
        { "zh": "光晕", "en": "lens flare" },
        { "zh": "体积光", "en": "volumetric lighting" },
        { "zh": "神圣光线", "en": "god rays" },
        { "zh": "穿透光", "en": "crepuscular rays" },
        { "zh": "月光", "en": "moonlight" },
        { "zh": "闪电", "en": "lightning" },
        { "zh": "烛光", "en": "candlelight" },
        { "zh": "火光", "en": "firelight" },
        { "zh": "灯笼光", "en": "lantern light" },
        { "zh": "手电筒光", "en": "flashlight beam" },
        { "zh": "水下光线", "en": "underwater lighting" },
        { "zh": "雾光", "en": "foggy light" },
        { "zh": "窗户光", "en": "window light" },
        { "zh": "反射光", "en": "reflected light" },
        { "zh": "高调", "en": "high key lighting" },
        { "zh": "低调", "en": "low key lighting" },
        { "zh": "动态光照", "en": "dynamic lighting" },
        { "zh": "全局照明", "en": "global illumination (GI)" },
        { "zh": "路径追踪", "en": "path tracing" },
        { "zh": "光线追踪", "en": "ray tracing" },
        { "zh": "光谱", "en": "spectral lighting" },
        { "zh": "彩虹", "en": "rainbow lighting" },
        { "zh": "发光", "en": "luminous" },
        { "zh": "内发光", "en": "iridescent" },
        { "zh": "背景光", "en": "fill light" },
        { "zh": "造型光", "en": "kick light" },
        { "zh": "环境光遮蔽", "en": "ambient occlusion (AO)" },
        { "zh": "明暗对比", "en": "chiaroscuro" },
        { "zh": "伦勃朗照明", "en": "Rembrandt lighting" },
        { "zh": "蝴蝶照明", "en": "butterfly lighting" },
        { "zh": "分裂照明", "en": "split lighting" },
        { "zh": "环形照明", "en": "loop lighting" }
      ]
    },
    {
      "name": "景别 (Shot Type / Framing)",
      "tags": [
        { "zh": "特写", "en": "close-up" },
        { "zh": "局部特写", "en": "extreme close-up" },
        { "zh": "中景", "en": "medium shot" },
        { "zh": "半身", "en": "bust shot" },
        { "zh": "全身", "en": "full shot" },
        { "zh": "远景", "en": "long shot" },
        { "zh": "大远景", "en": "establishing shot" },
        { "zh": "广阔景别", "en": "wide shot" },
        { "zh": "前景模糊", "en": "foreground blur" },
        { "zh": "背景模糊", "en": "background blur" },
        { "zh": "景深", "en": "depth of field" },
        { "zh": "焦散", "en": "bokeh" },
        { "zh": "浅景深", "en": "shallow depth of field" },
        { "zh": "深景深", "en": "deep depth of field" },
        { "zh": "全景", "en": "panoramic" },
        { "zh": "裁剪构图", "en": "cropped composition" },
        { "zh": "中央构图", "en": "centered composition" },
        { "zh": "三分法构图", "en": "rule of thirds" },
        { "zh": "黄金比例", "en": "golden ratio" },
        { "zh": "对称构图", "en": "symmetrical composition" },
        { "zh": "引导线", "en": "leading lines" },
        { "zh": "框架构图", "en": "framing (composition)" },
        { "zh": "开放构图", "en": "open composition" },
        { "zh": "封闭构图", "en": "closed composition" },
        { "zh": "对角线构图", "en": "diagonal composition" },
        { "zh": "螺旋构图", "en": "spiral composition" },
        { "zh": "三角形构图", "en": "triangular composition" },
        { "zh": "L型构图", "en": "L-shaped composition" },
        { "zh": "S型构图", "en": "S-shaped composition" },
        { "zh": "重复构图", "en": "repetitive composition" },
        { "zh": "负空间", "en": "negative space" },
        { "zh": "正空间", "en": "positive space" },
        { "zh": "纹理构图", "en": "texture composition" },
        { "zh": "图案构图", "en": "pattern composition" },
        { "zh": "并置", "en": "juxtaposition" },
        { "zh": "对比", "en": "contrast (composition)" },
        { "zh": "平衡", "en": "balance (composition)" },
        { "zh": "不对称平衡", "en": "asymmetrical balance" },
        { "zh": "径向平衡", "en": "radial balance" },
        { "zh": "前景", "en": "foreground" },
        { "zh": "中景", "en": "midground" },
        { "zh": "背景", "en": "background" },
        { "zh": "景框内构图", "en": "in-frame composition" },
        { "zh": "水平构图", "en": "horizontal composition" },
        { "zh": "垂直构图", "en": "vertical composition" },
        { "zh": "方形构图", "en": "square composition" },
        { "zh": "圆构图", "en": "circular composition" },
        { "zh": "失衡构图", "en": "unbalanced composition" },
        { "zh": "节奏感", "en": "rhythm (composition)" },
        { "zh": "动势", "en": "dynamism (composition)" },
        { "zh": "焦点", "en": "focal point" },
        { "zh": "中心点", "en": "center point" },
        { "zh": "视觉重量", "en": "visual weight" },
        { "zh": "主导元素", "en": "dominant element" },
        { "zh": "次要元素", "en": "subordinate elements" },
        { "zh": "边缘", "en": "edge (composition)" },
        { "zh": "角落", "en": "corner (composition)" }
      ]
    },
    {
      "name": "视角 (Perspective / Angle)",
      "tags": [
        { "zh": "正面视图", "en": "front view" },
        { "zh": "侧面视图", "en": "side view" },
        { "zh": "后视图", "en": "rear view" },
        { "zh": "三视图", "en": "three-quarter view" },
        { "zh": "顶视图", "en": "top view" },
        { "zh": "鸟瞰图", "en": "bird's eye view" },
        { "zh": "虫眼视图", "en": "worm's eye view" },
        { "zh": "低角度", "en": "low angle" },
        { "zh": "高角度", "en": "high angle" },
        { "zh": "平视视角", "en": "eye-level shot" },
        { "zh": "倾斜角度", "en": "dutch angle" },
        { "zh": "动态角度", "en": "dynamic angle" },
        { "zh": "主观视角", "en": "first-person view (POV)" },
        { "zh": "广角镜头", "en": "wide angle shot" },
        { "zh": "长焦镜头", "en": "telephoto shot" },
        { "zh": "鱼眼镜头", "en": "fisheye lens" },
        { "zh": "微距镜头", "en": "macro lens" },
        { "zh": "移轴镜头", "en": "tilt-shift lens" },
        { "zh": "远摄镜头", "en": "long lens" },
        { "zh": "追踪镜头", "en": "tracking shot" },
        { "zh": "无人机视角", "en": "drone shot" },
        { "zh": "航拍", "en": "aerial view" },
        { "zh": "潜水视角", "en": "underwater view" },
        { "zh": "空间透视", "en": "aerial perspective" },
        { "zh": "线性透视", "en": "linear perspective" },
        { "zh": "一点透视", "en": "one-point perspective" },
        { "zh": "两点透视", "en": "two-point perspective" },
        { "zh": "三点透视", "en": "three-point perspective" },
        { "zh": "多点透视", "en": "multi-point perspective" },
        { "zh": "强制透视", "en": "forced perspective" },
        { "zh": "平行透视", "en": "parallel perspective" },
        { "zh": "圆形构图", "en": "circular composition" },
        { "zh": "垂直构图", "en": "vertical composition" },
        { "zh": "水平构图", "en": "horizontal composition" },
        { "zh": "过肩镜头", "en": "over-the-shoulder shot" },
        { "zh": "特写视角", "en": "detail shot" },
        { "zh": "模糊背景", "en": "blurred background" },
        { "zh": "焦点", "en": "in focus" },
        { "zh": "失焦", "en": "out of focus" },
        { "zh": "手持相机", "en": "handheld camera" },
        { "zh": "稳定相机", "en": "stabilized camera" },
        { "zh": "摇摄", "en": "panoramic view" },
        { "zh": "倾斜", "en": "tilted" },
        { "zh": "旋转", "en": "rotated" },
        { "zh": "畸变", "en": "distortion" }
      ]
    },
    {
      "name": "构图 (Composition)",
      "tags": [
        { "zh": "三分法", "en": "rule of thirds" },
        { "zh": "黄金比例", "en": "golden ratio" },
        { "zh": "对称", "en": "symmetry" },
        { "zh": "不对称", "en": "asymmetry" },
        { "zh": "引导线", "en": "leading lines" },
        { "zh": "框架", "en": "framing" },
        { "zh": "负空间", "en": "negative space" },
        { "zh": "重复", "en": "repetition" },
        { "zh": "韵律", "en": "rhythm" },
        { "zh": "平衡", "en": "balance" },
        { "zh": "对比", "en": "contrast" },
        { "zh": "焦点", "en": "focal point" },
        { "zh": "景深", "en": "depth of field" },
        { "zh": "透视", "en": "perspective" },
        { "zh": "纹理", "en": "texture" },
        { "zh": "图案", "en": "pattern" },
        { "zh": "形状", "en": "shape" },
        { "zh": "线条", "en": "line (composition)" },
        { "zh": "构图简洁", "en": "clean composition" },
        { "zh": "复杂构图", "en": "complex composition" },
        { "zh": "留白", "en": "white space" },
        { "zh": "密集", "en": "dense" },
        { "zh": "分散", "en": "sparse" },
        { "zh": "中心构图", "en": "centered composition" },
        { "zh": "对角线构图", "en": "diagonal composition" },
        { "zh": "螺旋构图", "en": "spiral composition" },
        { "zh": "三角构图", "en": "triangular composition" },
        { "zh": "L形构图", "en": "L-shape composition" },
        { "zh": "S形构图", "en": "S-shape composition" },
        { "zh": "开放构图", "en": "open composition" },
        { "zh": "封闭构图", "en": "closed composition" },
        { "zh": "视觉流程", "en": "visual flow" },
        { "zh": "视觉重量", "en": "visual weight" },
        { "zh": "主导元素", "en": "dominant element" },
        { "zh": "次要元素", "en": "subordinate elements" },
        { "zh": "并置", "en": "juxtaposition" },
        { "zh": "剪影", "en": "silhouette" },
        { "zh": "剪裁", "en": "cropping" },
        { "zh": "水平线", "en": "horizon line" },
        { "zh": "消失点", "en": "vanishing point" },
        { "zh": "视平线", "en": "eye-level horizon" }
      ]
    },
    {
      "name": "配色 (Color Scheme)",
      "tags": [
        { "zh": "冷色调", "en": "cool colors" },
        { "zh": "暖色调", "en": "warm colors" },
        { "zh": "单色", "en": "monochromatic" },
        { "zh": "互补色", "en": "complementary colors" },
        { "zh": "三原色", "en": "triadic colors" },
        { "zh": "邻近色", "en": "analogous colors" },
        { "zh": "高饱和度", "en": "high saturation" },
        { "zh": "低饱和度", "en": "low saturation" },
        { "zh": "鲜艳色彩", "en": "vibrant colors" },
        { "zh": "柔和色彩", "en": "muted colors" },
        { "zh": "明亮色彩", "en": "bright colors" },
        { "zh": "暗沉色彩", "en": "dull colors" },
        { "zh": "潘通色", "en": "pantone colors" },
        { "zh": "CMYK", "en": "CMYK colors" },
        { "zh": "RGB", "en": "RGB colors" },
        { "zh": "霓虹色", "en": "neon colors" },
        { "zh": "金属色", "en": "metallic colors" },
        { "zh": "珠光色", "en": "pearlescent colors" },
        { "zh": "磨砂色", "en": "matte colors" },
        { "zh": "透明色", "en": "transparent colors" },
        { "zh": "黑白色", "en": "black and white" },
        { "zh": "棕褐色", "en": "sepia" },
        { "zh": "渐变色", "en": "gradient colors" },
        { "zh": "双色调", "en": "duotone" },
        { "zh": "三色调", "en": "tritone" },
        { "zh": "柔和色调", "en": "pastel colors" },
        { "zh": "大地色系", "en": "earth tones" },
        { "zh": "水彩色调", "en": "watercolor palette" },
        { "zh": "未来主义配色", "en": "futuristic palette" },
        { "zh": "赛博配色", "en": "cybernetic palette" },
        { "zh": "复古配色", "en": "vintage palette" },
        { "zh": "工业配色", "en": "industrial palette" },
        { "zh": "日落色", "en": "sunset colors" },
        { "zh": "黎明色", "en": "dawn colors" },
        { "zh": "夜晚色", "en": "night colors" },
        { "zh": "森林色", "en": "forest colors" },
        { "zh": "海洋色", "en": "oceanic colors" },
        { "zh": "糖果色", "en": "candy colors" },
        { "zh": "脏色", "en": "grungy colors" },
        { "zh": "斑驳色", "en": "mottled colors" },
        { "zh": "随机配色", "en": "random colors" },
        { "zh": "特定颜色主题", "en": "specific color theme" },
        { "zh": "色彩冲突", "en": "color clash" },
        { "zh": "色彩和谐", "en": "color harmony" },
        { "zh": "色彩隔离", "en": "color isolation" },
        { "zh": "色彩象征", "en": "symbolic colors" },
        { "zh": "色彩心理学", "en": "color psychology" },
        { "zh": "色彩混合", "en": "color blending" },
        { "zh": "色彩过渡", "en": "color transition" },
        { "zh": "色调分离", "en": "split toning" },
        { "zh": "颜色校正", "en": "color correction" },
        { "zh": "颜色分级", "en": "color grading" },
        { "zh": "高对比色", "en": "high contrast colors" },
        { "zh": "低对比色", "en": "low contrast colors" },
        { "zh": "发光色", "en": "luminous colors" },
        { "zh": "暗色系", "en": "dark color scheme" },
        { "zh": "亮色系", "en": "light color scheme" },
        { "zh": "褪色", "en": "faded colors" },
        { "zh": "自然色", "en": "natural colors" },
        { "zh": "非自然色", "en": "unnatural colors" }
      ]
    },
    {
      "name": "调色 (Color Grading / Film Look)",
      "tags": [
        { "zh": "鲜艳", "en": "vivid" },
        { "zh": "柔和", "en": "soft (colors)" },
        { "zh": "高对比度", "en": "high contrast" },
        { "zh": "低对比度", "en": "low contrast" },
        { "zh": "黑白", "en": "black and white" },
        { "zh": "棕褐色调", "en": "sepia tone" },
        { "zh": "灰度", "en": "grayscale" },
        { "zh": "去饱和", "en": "desaturated" },
        { "zh": "色彩增强", "en": "color vividness" },
        { "zh": "胶片颗粒", "en": "film grain" },
        { "zh": "噪点", "en": "noise (image)" },
        { "zh": "复古滤镜", "en": "vintage filter" },
        { "zh": "电影滤镜", "en": "cinematic filter" },
        { "zh": "冷色调滤镜", "en": "cool tone filter" },
        { "zh": "暖色调滤镜", "en": "warm tone filter" },
        { "zh": "赛博朋克滤镜", "en": "cyberpunk filter" },
        { "zh": "梦幻滤镜", "en": "dreamy filter" },
        { "zh": "暗黑滤镜", "en": "dark filter" },
        { "zh": "光效", "en": "light effects" },
        { "zh": "薄雾", "en": "haze" },
        { "zh": "发光", "en": "glow" },
        { "zh": "光晕", "en": "bloom" },
        { "zh": "光斑", "en": "lens flare" },
        { "zh": "色差", "en": "chromatic aberration" },
        { "zh": "小插图", "en": "vignette" },
        { "zh": "锐化", "en": "sharpened" },
        { "zh": "模糊", "en": "blurred" },
        { "zh": "丁达尔效应", "en": "Tyndall effect" },
        { "zh": "光线效果", "en": "light streaks" },
        { "zh": "高动态范围 (HDR)", "en": "HDR (High Dynamic Range)" },
        { "zh": "低动态范围 (LDR)", "en": "LDR (Low Dynamic Range)" },
        { "zh": "曝光过度", "en": "overexposed" },
        { "zh": "曝光不足", "en": "underexposed" },
        { "zh": "亮度", "en": "brightness" },
        { "zh": "饱和度", "en": "saturation" },
        { "zh": "色相", "en": "hue" },
        { "zh": "伽马校正", "en": "gamma correction" },
        { "zh": "色调分离", "en": "split toning" },
        { "zh": "色彩平衡", "en": "color balance" },
        { "zh": "曲线调整", "en": "curve adjustment" },
        { "zh": "色彩映射", "en": "color mapping" },
        { "zh": "后期处理", "en": "post-processing" },
        { "zh": "色彩冲击", "en": "color pop" },
        { "zh": "霓虹灯效果", "en": "neon effect" },
        { "zh": "模拟电影", "en": "film emulation" },
        { "zh": "DCP调色", "en": "DCP grading" },
        { "zh": "LUT文件", "en": "LUT (Look Up Table)" },
        { "zh": "电影蓝调", "en": "cinematic blues" },
        { "zh": "橙色和青色", "en": "orange and teal" }
      ]
    },
    {
      "name": "质量 (Quality / Resolution)",
      "tags": [
        { "zh": "高分辨率", "en": "high resolution" },
        { "zh": "8K", "en": "8K" },
        { "zh": "4K", "en": "4K" },
        { "zh": "超细节", "en": "ultra detailed" },
        { "zh": "杰作", "en": "masterpiece" },
        { "zh": "最佳质量", "en": "best quality" },
        { "zh": "高清", "en": "HD" },
        { "zh": "电影级", "en": "cinematic" },
        { "zh": "写真级", "en": "photorealistic" },
        { "zh": "CG艺术", "en": "CGI art" },
        { "zh": "VFX", "en": "VFX" },
        { "zh": "艺术站", "en": "Artstation" },
        { "zh": "DeviantArt", "en": "DeviantArt" },
        { "zh": "Pixiv", "en": "Pixiv" },
        { "zh": "流行趋势", "en": "trending on Artstation" },
        { "zh": "高质量", "en": "high quality" },
        { "zh": "低质量", "en": "low quality" },
        { "zh": "丑陋", "en": "ugly" },
        { "zh": "糟糕的艺术", "en": "bad art" },
        { "zh": "模糊", "en": "blurry" },
        { "zh": "失真", "en": "distorted" },
        { "zh": "过曝", "en": "overexposed" },
        { "zh": "欠曝", "en": "underexposed" },
        { "zh": "噪声", "en": "noisy (image)" },
        { "zh": "颗粒感", "en": "grainy" },
        { "zh": "锐利", "en": "sharp focus" },
        { "zh": "柔焦", "en": "soft focus" },
        { "zh": "干净", "en": "clean" },
        { "zh": "粗糙", "en": "gritty" },
        { "zh": "像素化", "en": "pixelated" },
        { "zh": "渲染不足", "en": "under-rendered" },
        { "zh": "锯齿", "en": "aliasing" },
        { "zh": "抗锯齿", "en": "anti-aliasing" },
        { "zh": "平滑", "en": "smooth (image)" },
        { "zh": "纹理细节", "en": "texture details" },
        { "zh": "光泽度", "en": "glossiness" },
        { "zh": "反射", "en": "reflections" },
        { "zh": "透明度", "en": "transparency" },
        { "zh": "半透明", "en": "translucency" },
        { "zh": "散射", "en": "subsurface scattering" },
        { "zh": "清晰度", "en": "crispness" },
        { "zh": "图像深度", "en": "image depth" },
        { "zh": "颜色精度", "en": "color accuracy" },
        { "zh": "艺术指导", "en": "art directed" },
        { "zh": "专业", "en": "professional (quality)" },
        { "zh": "业余", "en": "amateur (quality)" },
        { "zh": "粗略", "en": "rough" },
        { "zh": "精细", "en": "refined" }
      ]
    },
    {
      "name": "环境 (Environment / Setting)",
      "tags": [
        { "zh": "户外", "en": "outdoor" },
        { "zh": "室内", "en": "indoor" },
        { "zh": "自然景观", "en": "natural landscape" },
        { "zh": "城市景观", "en": "cityscape" },
        { "zh": "乡村", "en": "countryside" },
        { "zh": "科幻世界", "en": "sci-fi world" },
        { "zh": "幻想世界", "en": "fantasy world" },
        { "zh": "水下", "en": "underwater" },
        { "zh": "太空", "en": "outer space" },
        { "zh": "沙漠", "en": "desert" },
        { "zh": "森林", "en": "forest" },
        { "zh": "山脉", "en": "mountains" },
        { "zh": "海洋", "en": "ocean" },
        { "zh": "湖泊", "en": "lake" },
        { "zh": "河流", "en": "river" },
        { "zh": "平原", "en": "plains" },
        { "zh": "雪地", "en": "snowy landscape" },
        { "zh": "冰川", "en": "glacier" },
        { "zh": "火山", "en": "volcano" },
        { "zh": "海滩", "en": "beach" },
        { "zh": "洞穴", "en": "cave" },
        { "zh": "废墟", "en": "ruins" },
        { "zh": "遗迹", "en": "ancient ruins" },
        { "zh": "未来城市", "en": "futuristic city" },
        { "zh": "贫民窟", "en": "slums" },
        { "zh": "大都市", "en": "megalopolis" },
        { "zh": "农场", "en": "farm" },
        { "zh": "花园", "en": "garden" },
        { "zh": "公园", "en": "park" },
        { "zh": "街道", "en": "street" },
        { "zh": "街道小巷", "en": "alleyway" },
        { "zh": "广场", "en": "plaza" },
        { "zh": "市场", "en": "market" },
        { "zh": "码头", "en": "dock" },
        { "zh": "港口", "en": "harbor" },
        { "zh": "机场", "en": "airport" },
        { "zh": "火车站", "en": "train station" },
        { "zh": "工厂", "en": "factory" },
        { "zh": "实验室", "en": "laboratory" },
        { "zh": "医院", "en": "hospital" },
        { "zh": "办公室", "en": "office" },
        { "zh": "住宅区", "en": "residential area" },
        { "zh": "商业区", "en": "commercial area" },
        { "zh": "工业区", "en": "industrial area" },
        { "zh": "学校", "en": "school" },
        { "zh": "图书馆", "en": "library" },
        { "zh": "博物馆", "en": "museum" },
        { "zh": "剧院", "en": "theater" },
        { "zh": "音乐厅", "en": "concert hall" },
        { "zh": "体育场", "en": "stadium" },
        { "zh": "健身房", "en": "gym" },
        { "zh": "餐厅", "en": "restaurant" },
        { "zh": "咖啡馆", "en": "cafe" },
        { "zh": "酒吧", "en": "bar" },
        { "zh": "夜总会", "en": "nightclub" },
        { "zh": "教堂", "en": "church" },
        { "zh": "寺庙", "en": "temple" },
        { "zh": "城堡", "en": "castle" },
        { "zh": "宫殿", "en": "palace" },
        { "zh": "地牢", "en": "dungeon" },
        { "zh": "监狱", "en": "prison" },
        { "zh": "废弃地", "en": "abandoned place" },
        { "zh": "地下世界", "en": "underground world" },
        { "zh": "外星景观", "en": "alien landscape" },
        { "zh": "深渊", "en": "abyss" },
        { "zh": "天堂", "en": "heaven" },
        { "zh": "地狱", "en": "hell" },
        { "zh": "梦境", "en": "dreamscape" },
        { "zh": "后末日景观", "en": "post-apocalyptic landscape" },
        { "zh": "瘟疫之地", "en": "blight" },
        { "zh": "魔法森林", "en": "enchanted forest" },
        { "zh": "迷宫", "en": "maze" },
        { "zh": "桥梁", "en": "bridge" },
        { "zh": "隧道", "en": "tunnel" },
        { "zh": "瀑布", "en": "waterfall" },
        { "zh": "河流", "en": "river" },
        { "zh": "湖泊", "en": "lake" },
        { "zh": "池塘", "en": "pond" },
        { "zh": "水池", "en": "swimming pool" },
        { "zh": "喷泉", "en": "fountain" },
        { "zh": "雕塑公园", "en": "sculpture park" },
        { "zh": "动物园", "en": "zoo" },
        { "zh": "植物园", "en": "botanical garden" },
        { "zh": "墓地", "en": "graveyard" },
        { "zh": "公墓", "en": "cemetery" },
        { "zh": "遗址", "en": "archaeological site" },
        { "zh": "金字塔", "en": "pyramid" },
        { "zh": "神庙", "en": "temple ruins" },
        { "zh": "圆形剧场", "en": "amphitheater" }
      ]
    },
    {
      "name": "天气/气氛 (Weather / Atmosphere)",
      "tags": [
        { "zh": "晴天", "en": "sunny" },
        { "zh": "阴天", "en": "cloudy" },
        { "zh": "多云", "en": "overcast" },
        { "zh": "雨天", "en": "rainy" },
        { "zh": "下雪", "en": "snowing" },
        { "zh": "雾蒙蒙", "en": "foggy" },
        { "zh": "大雾", "en": "misty" },
        { "zh": "风暴", "en": "stormy" },
        { "zh": "闪电", "en": "lightning" },
        { "zh": "雷暴", "en": "thunderstorm" },
        { "zh": "沙尘暴", "en": "sandstorm" },
        { "zh": "晴朗", "en": "clear (weather)" },
        { "zh": "寒冷", "en": "cold" },
        { "zh": "温暖", "en": "warm" },
        { "zh": "炎热", "en": "hot" },
        { "zh": "白天", "en": "daytime" },
        { "zh": "夜晚", "en": "nighttime" },
        { "zh": "黎明", "en": "dawn" },
        { "zh": "黄昏", "en": "dusk" },
        { "zh": "日出", "en": "sunrise" },
        { "zh": "日落", "en": "sunset" },
        { "zh": "阴沉", "en": "gloomy" },
        { "zh": "和平", "en": "peaceful" },
        { "zh": "恐怖", "en": "eerie" },
        { "zh": "活力", "en": "energetic" },
        { "zh": "宁静", "en": "serene" },
        { "zh": "压抑", "en": "oppressive" },
        { "zh": "欢乐", "en": "joyful" },
        { "zh": "悲伤", "en": "melancholic" },
        { "zh": "神秘", "en": "mysterious" },
        { "zh": "史诗", "en": "epic" },
        { "zh": "浪漫", "en": "romantic" },
        { "zh": "诡异", "en": "creepy" },
        { "zh": "超现实", "en": "surreal" },
        { "zh": "梦幻", "en": "dreamlike" },
        { "zh": "疏离", "en": "isolated" },
        { "zh": "拥挤", "en": "crowded" },
        { "zh": "繁忙", "en": "bustling" },
        { "zh": "安静", "en": "quiet" },
        { "zh": "热闹", "en": "lively" },
        { "zh": "温馨", "en": "cozy" },
        { "zh": "冷漠", "en": "bleak" },
        { "zh": "危险", "en": "dangerous" },
        { "zh": "安全", "en": "safe" },
        { "zh": "污染", "en": "polluted" },
        { "zh": "纯净", "en": "pristine" },
        { "zh": "自然", "en": "natural" },
        { "zh": "人为", "en": "man-made" },
        { "zh": "破坏性", "en": "cataclysmic" },
        { "zh": "平静", "en": "calm" },
        { "zh": "动荡", "en": "turbulent" },
        { "zh": "超自然", "en": "supernatural" },
        { "zh": "祥和", "en": "tranquil" },
        { "zh": "萧瑟", "en": "desolate" },
        { "zh": "炽热", "en": "scorching" },
        { "zh": "刺骨", "en": "biting (cold)" },
        { "zh": "和煦", "en": "balmy" },
        { "zh": "朦胧", "en": "hazy" },
        { "zh": "闪烁", "en": "shimmering" },
        { "zh": "风吹", "en": "windy" },
        { "zh": "雪暴", "en": "blizzard" },
        { "zh": "冰雹", "en": "hail" },
        { "zh": "龙卷风", "en": "tornado" },
        { "zh": "洪水", "en": "flood" },
        { "zh": "地震", "en": "earthquake" },
        { "zh": "火山爆发", "en": "volcanic eruption" }
      ]
    },
    {
      "name": "情绪 (Emotion / Mood)",
      "tags": [
        { "zh": "快乐", "en": "joyful" },
        { "zh": "悲伤", "en": "sad" },
        { "zh": "愤怒", "en": "angry" },
        { "zh": "恐惧", "en": "fearful" },
        { "zh": "兴奋", "en": "excited" },
        { "zh": "平静", "en": "calm" },
        { "zh": "宁静", "en": "serene" },
        { "zh": "希望", "en": "hopeful" },
        { "zh": "绝望", "en": "desperate" },
        { "zh": "爱", "en": "loving" },
        { "zh": "孤独", "en": "lonely" },
        { "zh": "焦虑", "en": "anxious" },
        { "zh": "满足", "en": "content" },
        { "zh": "厌恶", "en": "disgusted" },
        { "zh": "惊讶", "en": "surprised" },
        { "zh": "困惑", "en": "confused" },
        { "zh": "好奇", "en": "curious" },
        { "zh": "疲惫", "en": "tired" },
        { "zh": "活力", "en": "energetic" },
        { "zh": "决心", "en": "determined" },
        { "zh": "沮丧", "en": "frustrated" },
        { "zh": "自豪", "en": "proud" },
        { "zh": "羞愧", "en": "ashamed" },
        { "zh": "犯罪感", "en": "guilty" },
        { "zh": "无聊", "en": "bored" },
        { "zh": "愉快", "en": "pleasant" },
        { "zh": "不愉快", "en": "unpleasant" },
        { "zh": "和平", "en": "peaceful" },
        { "zh": "混乱", "en": "chaotic" },
        { "zh": "紧张", "en": "tense" },
        { "zh": "放松", "en": "relaxed" },
        { "zh": "沉思", "en": "contemplative" },
        { "zh": "怀旧", "en": "nostalgic" },
        { "zh": "超然", "en": "detached" },
        { "zh": "同情", "en": "empathetic" },
        { "zh": "冷漠", "en": "indifferent" },
        { "zh": "警惕", "en": "alert" },
        { "zh": "脆弱", "en": "vulnerable" },
        { "zh": "自信", "en": "confident" },
        { "zh": "谦逊", "en": "humble" },
        { "zh": "怨恨", "en": "resentful" },
        { "zh": "嫉妒", "en": "jealous" },
        { "zh": "爱慕", "en": "admiring" },
        { "zh": "崇拜", "en": "adoring" },
        { "zh": "敬畏", "en": "awe-inspiring" },
        { "zh": "惊讶", "en": "astonished" },
        { "zh": "震撼", "en": "shocked" }
      ]
    },
    {
      "name": "画面元素 (Visual Elements)",
      "tags": [
        { "zh": "人物", "en": "people" },
        { "zh": "动物", "en": "animals" },
        { "zh": "植物", "en": "plants" },
        { "zh": "建筑", "en": "buildings" },
        { "zh": "车辆", "en": "vehicles" },
        { "zh": "机械", "en": "machinery" },
        { "zh": "食物", "en": "food" },
        { "zh": "饮料", "en": "drinks" },
        { "zh": "武器", "en": "weapons" },
        { "zh": "工具", "en": "tools" },
        { "zh": "服装", "en": "clothing" },
        { "zh": "配饰", "en": "accessories" },
        { "zh": "珠宝", "en": "jewelry" },
        { "zh": "艺术品", "en": "artwork" },
        { "zh": "雕塑", "en": "sculptures" },
        { "zh": "书籍", "en": "books" },
        { "zh": "电子产品", "en": "electronics" },
        { "zh": "家具", "en": "furniture" },
        { "zh": "玩具", "en": "toys" },
        { "zh": "灯光", "en": "lights" },
        { "zh": "阴影", "en": "shadows" },
        { "zh": "反射", "en": "reflections" },
        { "zh": "透明物体", "en": "transparent objects" },
        { "zh": "烟雾", "en": "smoke" },
        { "zh": "雾气", "en": "fog" },
        { "zh": "水滴", "en": "water drops" },
        { "zh": "雨", "en": "rain" },
        { "zh": "雪", "en": "snow" },
        { "zh": "火", "en": "fire" },
        { "zh": "冰", "en": "ice" },
        { "zh": "岩石", "en": "rocks" },
        { "zh": "碎片", "en": "debris" },
        { "zh": "废墟", "en": "rubble" },
        { "zh": "鲜花", "en": "flowers" },
        { "zh": "树木", "en": "trees" },
        { "zh": "草地", "en": "grass" },
        { "zh": "水面", "en": "water surface" },
        { "zh": "云朵", "en": "clouds" },
        { "zh": "星星", "en": "stars" },
        { "zh": "月亮", "en": "moon" },
        { "zh": "太阳", "en": "sun" },
        { "zh": "行星", "en": "planets" },
        { "zh": "星系", "en": "galaxy" },
        { "zh": "抽象形状", "en": "abstract shapes" },
        { "zh": "几何形状", "en": "geometric shapes" },
        { "zh": "纹理", "en": "textures" },
        { "zh": "图案", "en": "patterns" },
        { "zh": "线条", "en": "lines" },
        { "zh": "形状", "en": "forms" },
        { "zh": "颜色", "en": "colors" },
        { "zh": "空间", "en": "space" },
        { "zh": "运动", "en": "motion" },
        { "zh": "静止", "en": "stillness" },
        { "zh": "混乱", "en": "chaos" },
        { "zh": "秩序", "en": "order" },
        { "zh": "能量效果", "en": "energy effects" },
        { "zh": "魔法效果", "en": "magic effects" },
        { "zh": "科技界面", "en": "tech UI" },
        { "zh": "全息图", "en": "holograms" },
        { "zh": "光子", "en": "photons" },
        { "zh": "粒子", "en": "particles" },
        { "zh": "烟花", "en": "fireworks" },
        { "zh": "爆炸", "en": "explosion" }
      ]
    },
    {
      "name": "时间 (Time)",
      "tags": [
        { "zh": "白天", "en": "day" },
        { "zh": "夜晚", "en": "night" },
        { "zh": "黎明", "en": "dawn" },
        { "zh": "黄昏", "en": "dusk" },
        { "zh": "日出", "en": "sunrise" },
        { "zh": "日落", "en": "sunset" },
        { "zh": "清晨", "en": "early morning" },
        { "zh": "傍晚", "en": "late afternoon" },
        { "zh": "正午", "en": "midday" },
        { "zh": "午夜", "en": "midnight" },
        { "zh": "过去", "en": "past" },
        { "zh": "现在", "en": "present" },
        { "zh": "未来", "en": "future" },
        { "zh": "古时", "en": "ancient times" },
        { "zh": "中世纪", "en": "medieval period" },
        { "zh": "文艺复兴", "en": "renaissance" },
        { "zh": "工业革命", "en": "industrial revolution" },
        { "zh": "战时", "en": "war time" },
        { "zh": "和平年代", "en": "peace time" },
        { "zh": "末日后", "en": "post-apocalyptic" },
        { "zh": "未来派", "en": "futuristic (time)" },
        { "zh": "时间旅行", "en": "time travel" },
        { "zh": "慢动作", "en": "slow motion" },
        { "zh": "快动作", "en": "fast motion" },
        { "zh": "时间流逝", "en": "timelapse" },
        { "zh": "永恒", "en": "timeless" },
        { "zh": "瞬间", "en": "moment" },
        { "zh": "时代", "en": "era" },
        { "zh": "季节", "en": "season" },
        { "zh": "春天", "en": "spring" },
        { "zh": "夏天", "en": "summer" },
        { "zh": "秋天", "en": "autumn" },
        { "zh": "冬天", "en": "winter" }
      ]
    },
    {
      "name": "人物/生物 (Characters / Creatures)",
      "tags": [
        { "zh": "人类", "en": "human" },
        { "zh": "男性", "en": "male" },
        { "zh": "女性", "en": "female" },
        { "zh": "儿童", "en": "child" },
        { "zh": "老人", "en": "elderly" },
        { "zh": "婴儿", "en": "baby" },
        { "zh": "群体", "en": "crowd" },
        { "zh": "单人", "en": "solo" },
        { "zh": "机器人", "en": "robot" },
        { "zh": "赛博格", "en": "cyborg" },
        { "zh": "异形", "en": "alien" },
        { "zh": "怪物", "en": "monster" },
        { "zh": "神话生物", "en": "mythical creature" },
        { "zh": "龙", "en": "dragon" },
        { "zh": "精灵", "en": "elf" },
        { "zh": "矮人", "en": "dwarf" },
        { "zh": "兽人", "en": "orc" },
        { "zh": "吸血鬼", "en": "vampire" },
        { "zh": "狼人", "en": "werewolf" },
        { "zh": "僵尸", "en": "zombie" },
        { "zh": "幽灵", "en": "ghost" },
        { "zh": "天使", "en": "angel" },
        { "zh": "恶魔", "en": "demon" },
        { "zh": "超级英雄", "en": "superhero" },
        { "zh": "反派", "en": "villain" },
        { "zh": "士兵", "en": "soldier" },
        { "zh": "骑士", "en": "knight" },
        { "zh": "法师", "en": "wizard" },
        { "zh": "弓箭手", "en": "archer" },
        { "zh": "刺客", "en": "assassin" },
        { "zh": "医生", "en": "doctor" },
        { "zh": "科学家", "en": "scientist" },
        { "zh": "艺术家", "en": "artist" },
        { "zh": "音乐家", "en": "musician" },
        { "zh": "运动员", "en": "athlete" },
        { "zh": "舞者", "en": "dancer" },
        { "zh": "模特", "en": "model" },
        { "zh": "名人", "en": "celebrity" },
        { "zh": "政治家", "en": "politician" },
        { "zh": "商人", "en": "businessman" },
        { "zh": "农民", "en": "farmer" },
        { "zh": "渔夫", "en": "fisherman" },
        { "zh": "猎人", "en": "hunter" },
        { "zh": "探险家", "en": "explorer" },
        { "zh": "宇航员", "en": "astronaut" },
        { "zh": "外星生命", "en": "extraterrestrial life" },
        { "zh": "幻想种族", "en": "fantasy race" },
        { "zh": "神", "en": "deity" },
        { "zh": "半神", "en": "demigod" },
        { "zh": "英雄", "en": "hero" },
        { "zh": "平民", "en": "civilian" },
        { "zh": "学生", "en": "student" },
        { "zh": "教师", "en": "teacher" },
        { "zh": "工人", "en": "worker" },
        { "zh": "警察", "en": "police officer" },
        { "zh": "消防员", "en": "firefighter" },
        { "zh": "厨师", "en": "chef" },
        { "zh": "服务员", "en": "waiter" },
        { "zh": "流浪者", "en": "drifter" }
      ]
    }
  ]
});