tagData.push({
  "group": "动物 (Animals)",
  "categories": [
    {
      "name": "画风 (Art Style)",
      "tags": [
        { "zh": "写实主义", "en": "realistic" },
        { "zh": "超写实", "en": "hyperrealistic" },
        { "zh": "概念艺术", "en": "concept art" },
        { "zh": "幻想艺术", "en": "fantasy art" },
        { "zh": "数字绘画", "en": "digital painting" },
        { "zh": "油画风格", "en": "oil painting style" },
        { "zh": "水彩画风格", "en": "watercolor style" },
        { "zh": "素描", "en": "sketch style" },
        { "zh": "线条艺术", "en": "line art" },
        { "zh": "墨水画", "en": "ink drawing" },
        { "zh": "铅笔画", "en": "pencil drawing" },
        { "zh": "厚涂", "en": "impasto" },
        { "zh": "印象派", "en": "impressionistic" },
        { "zh": "表现主义", "en": "expressionistic" },
        { "zh": "抽象艺术", "en": "abstract art" },
        { "zh": "极简主义", "en": "minimalist style" },
        { "zh": "波普艺术", "en": "pop art" },
        { "zh": "新艺术运动", "en": "Art Nouveau" },
        { "zh": "装饰艺术", "en": "Art Deco" },
        { "zh": "剪影", "en": "silhouette" },
        { "zh": "卡通", "en": "cartoon" },
        { "zh": "动画风格", "en": "anime style" },
        { "zh": "美式卡通", "en": "American cartoon style" },
        { "zh": "迪士尼风格", "en": "Disney style" },
        { "zh": "皮克斯风格", "en": "Pixar style" },
        { "zh": "吉卜力风格", "en": "Ghibli style" },
        { "zh": "粘土动画", "en": "claymation" },
        { "zh": "定格动画", "en": "stop-motion" },
        { "zh": "童书插画", "en": "children's book illustration" },
        { "zh": "科学插画", "en": "scientific illustration" },
        { "zh": "矢量图", "en": "vector art" },
        { "zh": "像素艺术", "en": "pixel art" },
        { "zh": "低多边形", "en": "low poly" },
        { "zh": "雕塑", "en": "sculpture" },
        { "zh": "玻璃艺术", "en": "stained glass art" },
        { "zh": "剪纸艺术", "en": "papercut art" },
        { "zh": "折纸艺术", "en": "origami" },
        { "zh": "毛毡艺术", "en": "felt art" },
        { "zh": "刺绣艺术", "en": "embroidery art" },
        { "zh": "涂鸦风格", "en": "doodle style" },
        { "zh": "漫画风格", "en": "comic book style" },
        { "zh": "纹身艺术", "en": "tattoo art" },
        { "zh": "电影剧照", "en": "cinematic still" },
        { "zh": "动画截帧", "en": "animation frame" },
        { "zh": "游戏画面", "en": "game screenshot" },
        { "zh": "摄影", "en": "photography" },
        { "zh": "野生动物摄影", "en": "wildlife photography" },
        { "zh": "微距摄影", "en": "macro photography" },
        { "zh": "水下摄影", "en": "underwater photography" },
        { "zh": "艺术摄影", "en": "artistic photography" },
        { "zh": "纪实摄影", "en": "documentary photography" },
        { "zh": "3D渲染", "en": "3D render" },
        { "zh": "CGI", "en": "CGI" },
        { "zh": "VFX", "en": "VFX" },
        { "zh": "赛博朋克", "en": "cyberpunk style" },
        { "zh": "蒸汽朋克", "en": "steampunk style" },
        { "zh": "未来主义", "en": "futuristic style" },
        { "zh": "复古未来主义", "en": "retro-futuristic" },
        { "zh": "哥特式", "en": "gothic style" },
        { "zh": "巴洛克", "en": "Baroque style" },
        { "zh": "洛可可", "en": "Rococo style" },
        { "zh": "新古典主义", "en": "Neoclassical style" },
        { "zh": "浪漫主义", "en": "Romanticism" },
        { "zh": "超现实主义", "en": "surrealism" },
        { "zh": "立体主义", "en": "cubism" },
        { "zh": "点彩画", "en": "pointillism" },
        { "zh": "现实主义画派", "en": "Realism (painting)" },
        { "zh": "中国画", "en": "Chinese painting style" },
        { "zh": "日本浮世绘", "en": "Japanese Ukiyo-e" },
        { "zh": "西方油画", "en": "Western oil painting" },
        { "zh": "岩画", "en": "cave painting style" },
        { "zh": "插画", "en": "illustration" },
        { "zh": "概念草图", "en": "concept sketch" },
        { "zh": "蓝图风格", "en": "blueprint style" },
        { "zh": "手绘", "en": "hand-drawn" },
        { "zh": "颗粒感", "en": "grainy texture" },
        { "zh": "噪点", "en": "noise (visual effect)" },
        { "zh": "数字艺术", "en": "digital art" }
      ]
    },
    {
      "name": "哺乳动物 (Mammals)",
      "tags": [
        { "zh": "狮子", "en": "lion" },
        { "zh": "老虎", "en": "tiger" },
        { "zh": "花豹", "en": "leopard" },
        { "zh": "美洲豹", "en": "jaguar" },
        { "zh": "猎豹", "en": "cheetah" },
        { "zh": "雪豹", "en": "snow leopard" },
        { "zh": "美洲狮/跳羚", "en": "cougar/puma" },
        { "zh": "猞猁", "en": "lynx" },
        { "zh": "薮猫", "en": "serval" },
        { "zh": "非洲野狗", "en": "African wild dog" },
        { "zh": "野狼", "en": "gray wolf" },
        { "zh": "北极狼", "en": "arctic wolf" },
        { "zh": "灰狼", "en": "timber wolf" },
        { "zh": "狐狸", "en": "fox" },
        { "zh": "赤狐", "en": "red fox" },
        { "zh": "北极狐", "en": "arctic fox" },
        { "zh": "耳廓狐", "en": "fennec fox" },
        { "zh": "土狼", "en": "hyena" },
        { "zh": "大象", "en": "elephant" },
        { "zh": "非洲象", "en": "African elephant" },
        { "zh": "亚洲象", "en": "Asian elephant" },
        { "zh": "熊", "en": "bear" },
        { "zh": "棕熊", "en": "grizzly bear" },
        { "zh": "黑熊", "en": "black bear" },
        { "zh": "北极熊", "en": "polar bear" },
        { "zh": "熊猫", "en": "panda" },
        { "zh": "小熊猫", "en": "red panda" },
        { "zh": "鹿", "en": "deer" },
        { "zh": "麋鹿", "en": "moose" },
        { "zh": "驯鹿", "en": "reindeer" },
        { "zh": "斑马", "en": "zebra" },
        { "zh": "长颈鹿", "en": "giraffe" },
        { "zh": "犀牛", "en": "rhinoceros" },
        { "zh": "河马", "en": "hippopotamus" },
        { "zh": "袋鼠", "en": "kangaroo" },
        { "zh": "考拉", "en": "koala" },
        { "zh": "骆驼", "en": "camel" },
        { "zh": "单峰骆驼", "en": "dromedary camel" },
        { "zh": "双峰骆驼", "en": "Bactrian camel" },
        { "zh": "猴子", "en": "monkey" },
        { "zh": "黑猩猩", "en": "chimpanzee" },
        { "zh": "大猩猩", "en": "gorilla" },
        { "zh": "红毛猩猩", "en": "orangutan" },
        { "zh": "狒狒", "en": "baboon" },
        { "zh": "狐猴", "en": "lemur" },
        { "zh": "懒猴", "en": "loris" },
        { "zh": "眼镜猴", "en": "tarsier" },
        { "zh": "树懒", "en": "sloth" },
        { "zh": "食蚁兽", "en": "anteater" },
        { "zh": "穿山甲", "en": "pangolin" },
        { "zh": "鸭嘴兽", "en": "platypus" },
        { "zh": "水豚", "en": "capybara" },
        { "zh": "海狸鼠", "en": "nutria" },
        { "zh": "土拨鼠", "en": "marmot" },
        { "zh": "地鼠", "en": "groundhog" },
        { "zh": "松鼠", "en": "squirrel" },
        { "zh": "花栗鼠", "en": "chipmunk" },
        { "zh": "兔子", "en": "rabbit" },
        { "zh": "野兔", "en": "hare" },
        { "zh": "刺猬", "en": "hedgehog" },
        { "zh": "豪猪", "en": "porcupine" },
        { "zh": "犰狳", "en": "armadillo" },
        { "zh": "浣熊", "en": "raccoon" },
        { "zh": "小浣熊", "en": "r raccoon dog" },
        { "zh": "臭鼬", "en": "skunk" },
        { "zh": "獾", "en": "badger" },
        { "zh": "水獭", "en": "otter" },
        { "zh": "貂", "en": "marten" },
        { "zh": "雪貂", "en": "ferret" },
        { "zh": "猫鼬", "en": "meerkat" },
        { "zh": "麝猫", "en": "civet" },
        { "zh": "蝙蝠", "en": "bat" },
        { "zh": "大耳蝠", "en": "long-eared bat" },
        { "zh": "鲸鱼", "en": "whale" },
        { "zh": "海豚", "en": "dolphin" },
        { "zh": "海豹", "en": "seal" },
        { "zh": "海狮", "en": "sea lion" },
        { "zh": "海象", "en": "walrus" },
        { "zh": "儒艮", "en": "dugong" },
        { "zh": "海牛", "en": "manatee" },
        { "zh": "家猫", "en": "domestic cat" },
        { "zh": "家犬", "en": "domestic dog" },
        { "zh": "马", "en": "horse" },
        { "zh": "斑马", "en": "zebra" },
        { "zh": "驴", "en": "donkey" },
        { "zh": "骡", "en": "mule" },
        { "zh": "牛", "en": "cow" },
        { "zh": "水牛", "en": "buffalo" },
        { "zh": "野牛", "en": "bison" },
        { "zh": "羊", "en": "sheep" },
        { "zh": "山羊", "en": "goat" },
        { "zh": "猪", "en": "pig" },
        { "zh": "野猪", "en": "wild boar" },
        { "zh": "疣猪", "en": "warthog" },
        { "zh": "穿山甲", "en": "pangolin" },
        { "zh": "鸭嘴兽", "en": "platypus" },
        { "zh": "针鼹", "en": "echidna" },
        { "zh": "食肉动物", "en": "carnivore" },
        { "zh": "食草动物", "en": "herbivore" },
        { "zh": "杂食动物", "en": "omnivore" },
        { "zh": "有袋动物", "en": "marsupial" },
        { "zh": "啮齿动物", "en": "rodent" },
        { "zh": "灵长类动物", "en": "primate" },
        { "zh": "偶蹄目动物", "en": "artiodactyl" },
        { "zh": "食虫动物", "en": "insectivore" },
        { "zh": "鳍足动物", "en": "pinniped" },
        { "zh": "鲸目动物", "en": "cetacean" },
        { "zh": "反刍动物", "en": "ruminant" },
        { "zh": "猛兽", "en": "big cat" },
        { "zh": "犬科动物", "en": "canid" },
        { "zh": "猫科动物", "en": "felid" },
        { "zh": "熊科动物", "en": "ursid" }
      ]
    },
    {
      "name": "海洋动物 (Marine Animals)",
      "tags": [
        { "zh": "鲨鱼", "en": "shark" },
        { "zh": "大白鲨", "en": "great white shark" },
        { "zh": "虎鲨", "en": "tiger shark" },
        { "zh": "锤头鲨", "en": "hammerhead shark" },
        { "zh": "鲸鲨", "en": "whale shark" },
        { "zh": "逆戟鲸/虎鲸", "en": "orca (killer whale)" },
        { "zh": "蓝鲸", "en": "blue whale" },
        { "zh": "座头鲸", "en": "humpback whale" },
        { "zh": "抹香鲸", "en": "sperm whale" },
        { "zh": "海豚", "en": "dolphin" },
        { "zh": "江豚", "en": "porpoise" },
        { "zh": "海豹", "en": "seal" },
        { "zh": "海狮", "en": "sea lion" },
        { "zh": "海象", "en": "walrus" },
        { "zh": "儒艮", "en": "dugong" },
        { "zh": "海牛", "en": "manatee" },
        { "zh": "海龟", "en": "sea turtle" },
        { "zh": "绿海龟", "en": "green sea turtle" },
        { "zh": "棱皮龟", "en": "leatherback turtle" },
        { "zh": "海蛇", "en": "sea snake" },
        { "zh": "章鱼", "en": "octopus" },
        { "zh": "太平洋巨型章鱼", "en": "giant Pacific octopus" },
        { "zh": "蓝环章鱼", "en": "blue-ringed octopus" },
        { "zh": "鱿鱼", "en": "squid" },
        { "zh": "巨型鱿鱼", "en": "giant squid" },
        { "zh": "墨鱼", "en": "cuttlefish" },
        { "zh": "水母", "en": "jellyfish" },
        { "zh": "僧帽水母", "en": "Portuguese man o' war" },
        { "zh": "海葵", "en": "sea anemone" },
        { "zh": "螃蟹", "en": "crab" },
        { "zh": "寄居蟹", "en": "hermit crab" },
        { "zh": "瓷蟹", "en": "porcelain crab" },
        { "zh": "椰子蟹", "en": "coconut crab" },
        { "zh": "龙虾", "en": "lobster" },
        { "zh": "虾", "en": "shrimp" },
        { "zh": "海星", "en": "starfish" },
        { "zh": "海胆", "en": "sea urchin" },
        { "zh": "海参", "en": "sea cucumber" },
        { "zh": "海马", "en": "seahorse" },
        { "zh": "叶海龙", "en": "leafy seadragon" },
        { "zh": "小丑鱼", "en": "clownfish" },
        { "zh": "珊瑚鱼", "en": "reef fish" },
        { "zh": "蝠鲼/魔鬼鱼", "en": "manta ray" },
        { "zh": "电鳐", "en": "electric ray" },
        { "zh": "河豚", "en": "pufferfish" },
        { "zh": "狮子鱼", "en": "lionfish" },
        { "zh": "海鳗", "en": "moray eel" },
        { "zh": "鳗鱼", "en": "eel" },
        { "zh": "海胆", "en": "sea urchin" },
        { "zh": "蛤蜊", "en": "clam" },
        { "zh": "牡蛎", "en": "oyster" },
        { "zh": "扇贝", "en": "scallop" },
        { "zh": "蜗牛", "en": "sea snail" },
        { "zh": "藤壶", "en": "barnacle" },
        { "zh": "贻贝", "en": "mussel" },
        { "zh": "海星", "en": "sea star" },
        { "zh": "沙钱", "en": "sand dollar" },
        { "zh": "蠕虫", "en": "marine worm" },
        { "zh": "海绵", "en": "sea sponge" },
        { "zh": "各类鱼类", "en": "various fish species" },
        { "zh": "金鱼", "en": "goldfish" },
        { "zh": "锦鲤", "en": "koi" },
        { "zh": "比目鱼", "en": "flounder" },
        { "zh": "鳕鱼", "en": "cod" },
        { "zh": "鲑鱼", "en": "salmon" },
        { "zh": "金枪鱼", "en": "tuna" },
        { "zh": "箭鱼", "en": "swordfish" },
        { "zh": "马鲛鱼", "en": "mackerel" },
        { "zh": "鲱鱼", "en": "herring" },
        { "zh": "热带鱼", "en": "tropical fish" },
        { "zh": "深海鱼", "en": "deep-sea fish" },
        { "zh": "水生动物", "en": "aquatic animal" },
        { "zh": "深海生物", "en": "deep-sea creature" },
        { "zh": "浮游生物", "en": "plankton" },
        { "zh": "海藻", "en": "seaweed" },
        { "zh": "海草", "en": "seagrass" },
        { "zh": "珊瑚", "en": "coral" },
        { "zh": "珊瑚礁生态系统", "en": "coral reef ecosystem" }
      ]
    },
    {
      "name": "鸟类 (Birds)",
      "tags": [
        { "zh": "鹰", "en": "eagle" },
        { "zh": "白头海雕", "en": "bald eagle" },
        { "zh": "金雕", "en": "golden eagle" },
        { "zh": "隼", "en": "falcon" },
        { "zh": "游隼", "en": "peregrine falcon" },
        { "zh": "秃鹫", "en": "vulture" },
        { "zh": "非洲秃鹫", "en": "African vulture" },
        { "zh": "猫头鹰", "en": "owl" },
        { "zh": "雪鸮", "en": "snowy owl" },
        { "zh": "大角鸮", "en": "great horned owl" },
        { "zh": "乌鸦", "en": "crow" },
        { "zh": "渡鸦", "en": "raven" },
        { "zh": "喜鹊", "en": "magpie" },
        { "zh": "知更鸟", "en": "robin" },
        { "zh": "麻雀", "en": "sparrow" },
        { "zh": "燕子", "en": "swallow" },
        { "zh": "蜂鸟", "en": "hummingbird" },
        { "zh": "啄木鸟", "en": "woodpecker" },
        { "zh": "翠鸟", "en": "kingfisher" },
        { "zh": "鹦鹉", "en": "parrot" },
        { "zh": "金刚鹦鹉", "en": "macaw" },
        { "zh": "凤头鹦鹉", "en": "cockatoo" },
        { "zh": "爱情鸟", "en": "lovebird" },
        { "zh": "鹦哥", "en": "budgerigar" },
        { "zh": "雀", "en": "finch" },
        { "zh": "金丝雀", "en": "canary" },
        { "zh": "鸽子", "en": "pigeon" },
        { "zh": "斑鸠", "en": "dove" },
        { "zh": "天鹅", "en": "swan" },
        { "zh": "鸭子", "en": "duck" },
        { "zh": "鹅", "en": "goose" },
        { "zh": "鹈鹕", "en": "pelican" },
        { "zh": "海鸥", "en": "seagull" },
        { "zh": "信天翁", "en": "albatross" },
        { "zh": "企鹅", "en": "penguin" },
        { "zh": "帝企鹅", "en": "emperor penguin" },
        { "zh": "火烈鸟", "en": "flamingo" },
        { "zh": "苍鹭", "en": "heron" },
        { "zh": "鹳", "en": "stork" },
        { "zh": "鹤", "en": "crane" },
        { "zh": "朱鹮", "en": "ibis" },
        { "zh": "鹭", "en": "egret" },
        { "zh": "鹮", "en": "spoonbill" },
        { "zh": "孔雀", "en": "peacock" },
        { "zh": "鸵鸟", "en": "ostrich" },
        { "zh": "鸸鹋", "en": "emu" },
        { "zh": "食火鸡", "en": "cassowary" },
        { "zh": "奇异鸟", "en": "kiwi" },
        { "zh": "走鹃", "en": "roadrunner" },
        { "zh": "巨嘴鸟", "en": "toucan" },
        { "zh": "极乐鸟", "en": "bird of paradise" },
        { "zh": "冠冕鸽", "en": "crowned pigeon" },
        { "zh": "园丁鸟", "en": "bowerbird" },
        { "zh": "椋鸟", "en": "starling" },
        { "zh": "知更鸟", "en": "robin" },
        { "zh": "夜莺", "en": "nightingale" },
        { "zh": "云雀", "en": "lark" },
        { "zh": "山雀", "en": "tit (bird)" },
        { "zh": "猛禽", "en": "raptor" },
        { "zh": "鸣禽", "en": "songbird" },
        { "zh": "水禽", "en": "waterfowl" },
        { "zh": "涉禽", "en": "wading bird" },
        { "zh": "海鸟", "en": "seabird" },
        { "zh": "陆鸟", "en": "land bird" },
        { "zh": "不会飞的鸟", "en": "flightless bird" },
        { "zh": "候鸟", "en": "migratory bird" },
        { "zh": "留鸟", "en": "resident bird" },
        { "zh": "幼鸟", "en": "hatchling / fledgling" },
        { "zh": "禽类", "en": "poultry" },
        { "zh": "鸡", "en": "chicken" },
        { "zh": "火鸡", "en": "turkey" },
        { "zh": "鹌鹑", "en": "quail" },
        { "zh": "雉鸡", "en": "pheasant" },
        { "zh": "家禽", "en": "domestic fowl" }
      ]
    },
    {
      "name": "爬行动物 (Reptiles)",
      "tags": [
        { "zh": "蛇", "en": "snake" },
        { "zh": "眼镜蛇", "en": "cobra" },
        { "zh": "眼镜王蛇", "en": "king cobra" },
        { "zh": "莽蛇", "en": "boa constrictor" },
        { "zh": "蟒蛇", "en": "python" },
        { "zh": "响尾蛇", "en": "rattlesnake" },
        { "zh": "蝰蛇", "en": "viper" },
        { "zh": "绿曼巴蛇", "en": "green mamba" },
        { "zh": "加蓬蝰蛇", "en": "Gaboon viper" },
        { "zh": "蜥蜴", "en": "lizard" },
        { "zh": "变色龙", "en": "chameleon" },
        { "zh": "壁虎", "en": "gecko" },
        { "zh": "豹纹守宫", "en": "leopard gecko" },
        { "zh": "鬣蜥", "en": "iguana" },
        { "zh": "鬃狮蜥", "en": "bearded dragon" },
        { "zh": "科莫多巨蜥", "en": "Komodo dragon" },
        { "zh": "巨蜥", "en": "monitor lizard" },
        { "zh": "飞蜥", "en": "flying lizard" },
        { "zh": "鳄鱼", "en": "crocodile" },
        { "zh": "咸水鳄", "en": "saltwater crocodile" },
        { "zh": "巨湾鳄", "en": "Nile crocodile" },
        { "zh": "短吻鳄", "en": "alligator" },
        { "zh": "密西西比短吻鳄", "en": "American alligator" },
        { "zh": "凯门鳄", "en": "caiman" },
        { "zh": "龟", "en": "turtle" },
        { "zh": "陆龟", "en": "tortoise" },
        { "zh": "箱龟", "en": "box turtle" },
        { "zh": "淡水龟", "en": "freshwater turtle" },
        { "zh": "海龟", "en": "sea turtle" },
        { "zh": "喙头蜥", "en": "tuatara" },
        { "zh": "石龙子", "en": "skink" },
        { "zh": "蚓蜥", "en": "worm lizard" },
        { "zh": "爬行类", "en": "reptilian" },
        { "zh": "冷血动物", "en": "cold-blooded animal" }
      ]
    },
    {
      "name": "两栖动物 (Amphibians)",
      "tags": [
        { "zh": "青蛙", "en": "frog" },
        { "zh": "树蛙", "en": "tree frog" },
        { "zh": "箭毒蛙", "en": "poison dart frog" },
        { "zh": "雨蛙", "en": "rain frog" },
        { "zh": "牛蛙", "en": "bullfrog" },
        { "zh": "蟾蜍", "en": "toad" },
        { "zh": "巨型蟾蜍", "en": "cane toad" },
        { "zh": "蝾螈", "en": "salamander" },
        { "zh": "火蝾螈", "en": "fire salamander" },
        { "zh": "墨西哥钝口螈", "en": "axolotl" },
        { "zh": "纽特/水蜥", "en": "newt" },
        { "zh": "无腿两栖动物", "en": "caecilian" },
        { "zh": "两栖类", "en": "amphibian" }
      ]
    },
    {
      "name": "昆虫 & 节肢动物 (Insects & Arthropods)",
      "tags": [
        { "zh": "蝴蝶", "en": "butterfly" },
        { "zh": "帝王蝶", "en": "monarch butterfly" },
        { "zh": "凤蝶", "en": "swallowtail butterfly" },
        { "zh": "蛾子", "en": "moth" },
        { "zh": "天蛾", "en": "sphinx moth" },
        { "zh": "蚕蛾", "en": "silkworm moth" },
        { "zh": "蜜蜂", "en": "bee" },
        { "zh": "大黄蜂", "en": "bumblebee" },
        { "zh": "黄蜂", "en": "wasp" },
        { "zh": "大胡蜂", "en": "hornet" },
        { "zh": "蚂蚁", "en": "ant" },
        { "zh": "行军蚁", "en": "army ant" },
        { "zh": "蜘蛛", "en": "spider" },
        { "zh": "狼蛛", "en": "tarantula" },
        { "zh": "黑寡妇蜘蛛", "en": "black widow spider" },
        { "zh": "跳蛛", "en": "jumping spider" },
        { "zh": "蟹蛛", "en": "crab spider" },
        { "zh": "蝎子", "en": "scorpion" },
        { "zh": "甲虫", "en": "beetle" },
        { "zh": "瓢虫", "en": "ladybug" },
        { "zh": "独角仙", "en": "rhinoceros beetle" },
        { "zh": "锹甲", "en": "stag beetle" },
        { "zh": "萤火虫", "en": "firefly" },
        { "zh": "螳螂", "en": "mantis" },
        { "zh": "竹节虫", "en": "stick insect" },
        { "zh": "叶虫", "en": "leaf insect" },
        { "zh": "蜻蜓", "en": "dragonfly" },
        { "zh": "豆娘", "en": "damselfly" },
        { "zh": "蚱蜢", "en": "grasshopper" },
        { "zh": "蟋蟀", "en": "cricket" },
        { "zh": "蝗虫", "en": "locust" },
        { "zh": "蝉", "en": "cicada" },
        { "zh": "蚊子", "en": "mosquito" },
        { "zh": "苍蝇", "en": "fly" },
        { "zh": "蟑螂", "en": "cockroach" },
        { "zh": "跳蚤", "en": "flea" },
        { "zh": "虱子", "en": "louse" },
        { "zh": "臭虫", "en": "bed bug" },
        { "zh": "蜈蚣", "en": "centipede" },
        { "zh": "千足虫", "en": "millipede" },
        { "zh": "蜗牛", "en": "snail" },
        { "zh": "蛞蝓", "en": "slug" },
        { "zh": "蠕虫", "en": "earthworm" },
        { "zh": "毛毛虫", "en": "caterpillar" },
        { "zh": "蝴蝶幼虫", "en": "larva" },
        { "zh": "蛹", "en": "pupa" },
        { "zh": "虱目鱼", "en": "silverfish" },
        { "zh": "耳夹虫", "en": "earwig" },
        { "zh": "潮虫", "en": "woodlouse" },
        { "zh": "蜘蛛纲动物", "en": "arachnid" },
        { "zh": "甲壳类动物", "en": "crustacean" },
        { "zh": "节肢动物", "en": "arthropod" },
        { "zh": "昆虫", "en": "insect" }
      ]
    },
    {
      "name": "其他生物 (Other Creatures)",
      "tags": [
        { "zh": "恐龙", "en": "dinosaur" },
        { "zh": "霸王龙", "en": "Tyrannosaurus Rex (T-Rex)" },
        { "zh": "三角龙", "en": "Triceratops" },
        { "zh": "迅猛龙", "en": "velociraptor" },
        { "zh": "梁龙", "en": "Brontosaurus" },
        { "zh": "剑龙", "en": "Stegosaurus" },
        { "zh": "长颈龙", "en": "Brachiosaurus" },
        { "zh": "翼龙", "en": "pterodactyl" },
        { "zh": "沧龙", "en": "Mosasaurus" },
        { "zh": "鱼龙", "en": "Ichthyosaurus" },
        { "zh": "猛犸象", "en": "mammoth" },
        { "zh": "剑齿虎", "en": "saber-toothed tiger" },
        { "zh": "渡渡鸟", "en": "dodo bird" },
        { "zh": "泰坦巨蟒", "en": "Titanoboa" },
        { "zh": "巨齿鲨", "en": "Megalodon" },
        { "zh": "史前生物", "en": "prehistoric creature" },
        { "zh": "灭绝动物", "en": "extinct animal" },
        { "zh": "神话生物", "en": "mythical creature" },
        { "zh": "幻想生物", "en": "fantasy creature" },
        { "zh": "独角兽", "en": "unicorn" },
        { "zh": "龙", "en": "dragon" },
        { "zh": "西方龙", "en": "Western dragon" },
        { "zh": "东方龙", "en": "Eastern dragon" },
        { "zh": "凤凰", "en": "phoenix" },
        { "zh": "美人鱼", "en": "mermaid" },
        { "zh": "人头狮身", "en": "sphinx" },
        { "zh": "狮鹫", "en": "griffin" },
        { "zh": "刻耳柏洛斯/地狱犬", "en": "Cerberus" },
        { "zh": "美杜莎", "en": "Medusa (gorgon)" },
        { "zh": "米诺陶", "en": "Minotaur" },
        { "zh": "九头蛇", "en": "Hydra" },
        { "zh": "独眼巨人", "en": "cyclops" },
        { "zh": "丘比特", "en": "cupid" },
        { "zh": "半人马", "en": "centaur" },
        { "zh": "尼斯湖水怪", "en": "Loch Ness Monster" },
        { "zh": "雪人", "en": "Yeti" },
        { "zh": "大脚怪", "en": "Bigfoot" },
        { "zh": "精灵生物", "en": "fae creature" },
        { "zh": "哥斯拉", "en": "Godzilla" },
        { "zh": "金刚", "en": "King Kong" },
        { "zh": "口袋妖怪", "en": "Pokemon" },
        { "zh": "数码宝贝", "en": "Digimon" },
        { "zh": "外星生物", "en": "alien creature" },
        { "zh": "机器人动物", "en": "robot animal" },
        { "zh": "半机械生物", "en": "cyborg creature" },
        { "zh": "生化动物", "en": "bio-engineered animal" },
        { "zh": "变种生物", "en": "mutant creature" },
        { "zh": "拟人化动物", "en": "anthro animal" },
        { "zh": "卡通吉祥物", "en": "cartoon mascot" },
        { "zh": "妖怪", "en": "yokai" },
        { "zh": "鬼怪", "en": "ghostly creature" },
        { "zh": "植物怪物", "en": "plant monster" },
        { "zh": "海洋怪物", "en": "sea monster" },
        { "zh": "克苏鲁生物", "en": "Cthulhu creature" }
      ]
    },
    {
      "name": "物种属性/特征 (Species Attributes/Characteristics)",
      "tags": [
        { "zh": "幼崽", "en": "baby animal" },
        { "zh": "幼狮", "en": "cub (lion)" },
        { "zh": "小豹", "en": "cub (leopard)" },
        { "zh": "小狼", "en": "pup (wolf)" },
        { "zh": "小熊", "en": "cub (bear)" },
        { "zh": "小象", "en": "calf (elephant)" },
        { "zh": "小鹿", "en": "fawn (deer)" },
        { "zh": "马驹", "en": "foal (horse)" },
        { "zh": "小猫", "en": "kitten (cat)" },
        { "zh": "幼犬", "en": "puppy (dog)" },
        { "zh": "雏鸟", "en": "chick (bird)" },
        { "zh": "飞禽幼鸟", "en": "fledgling" },
        { "zh": "蝌蚪", "en": "tadpole" },
        { "zh": "卵", "en": "egg" },
        { "zh": "群体", "en": "group of animals" },
        { "zh": "兽群", "en": "herd" },
        { "zh": "鸟群", "en": "flock" },
        { "zh": "狼群", "en": "pack" },
        { "zh": "鱼群", "en": "school (fish)" },
        { "zh": "昆虫群", "en": "swarm (insects)" },
        { "zh": "雄性", "en": "male (animal)" },
        { "zh": "雌性", "en": "female (animal)" },
        { "zh": "毛皮", "en": "fur" },
        { "zh": "绒毛", "en": "fluffy" },
        { "zh": "羽毛", "en": "feathers" },
        { "zh": "鳞片", "en": "scales" },
        { "zh": "皮肤纹理", "en": "skin texture" },
        { "zh": "甲壳", "en": "shell / carapace" },
        { "zh": "翅膀", "en": "wings" },
        { "zh": "触角", "en": "antennae" },
        { "zh": "角", "en": "horns" },
        { "zh": "鹿角", "en": "antlers" },
        { "zh": "爪子", "en": "claws / paws" },
        { "zh": "利爪", "en": "talons" },
        { "zh": "尖牙", "en": "fangs" },
        { "zh": "獠牙", "en": "tusks" },
        { "zh": "尾巴", "en": "tail" },
        { "zh": "鳍", "en": "fins" },
        { "zh": "鳃", "en": "gills" },
        { "zh": "斑纹", "en": "spots" },
        { "zh": "条纹", "en": "stripes" },
        { "zh": "斑点", "en": "dappled" },
        { "zh": "图案", "en": "patterns" },
        { "zh": "伪装", "en": "camouflage" },
        { "zh": "发光", "en": "bioluminescent" },
        { "zh": "体型庞大", "en": "large size" },
        { "zh": "体型微小", "en": "small size" },
        { "zh": "巨型", "en": "gigantic" },
        { "zh": "微型", "en": "miniature" },
        { "zh": "稀有", "en": "rare species" },
        { "zh": "濒危", "en": "endangered species" },
        { "zh": "地方特有", "en": "endemic species" },
        { "zh": "异形", "en": "mutated / deformed" },
        { "zh": "半机械", "en": "cybernetic" },
        { "zh": "受伤", "en": "injured" },
        { "zh": "残疾", "en": "disabled" },
        { "zh": "衰老", "en": "aged / elderly" },
        { "zh": "年轻", "en": "young" },
        { "zh": "成熟", "en": "mature" },
        { "zh": "雄伟的", "en": "majestic" },
        { "zh": "高贵的", "en": "regal" },
        { "zh": "可爱的", "en": "cute" },
        { "zh": "萌", "en": "adorable" },
        { "zh": "凶猛的", "en": "fierce" },
        { "zh": "野蛮的", "en": "savage" },
        { "zh": "温顺的", "en": "docile" },
        { "zh": "优雅的", "en": "elegant" },
        { "zh": "敏捷的", "en": "agile" },
        { "zh": "强大的", "en": "powerful" },
        { "zh": "笨拙的", "en": "clumsy" },
        { "zh": "色彩斑斓的", "en": "colorful" },
        { "zh": "发光眼睛", "en": "glowing eyes" },
        { "zh": "毛发蓬松的", "en": "shaggy" },
        { "zh": "光滑的", "en": "smooth" },
        { "zh": "多刺的", "en": "spiky" },
        { "zh": "分叉舌头", "en": "forked tongue" },
        { "zh": "毒液", "en": "venomous" },
        { "zh": "有毒的", "en": "poisonous" },
        { "zh": "有斑点的", "en": "spotted" },
        { "zh": "有条纹的", "en": "striped" },
        { "zh": "带刺的", "en": "thorny" }
      ]
    },
    {
      "name": "行为/动作 (Actions/Behaviors)",
      "tags": [
        { "zh": "奔跑", "en": "running" },
        { "zh": "跳跃", "en": "jumping" },
        { "zh": "飞翔", "en": "flying" },
        { "zh": "滑翔", "en": "gliding" },
        { "zh": "游泳", "en": "swimming" },
        { "zh": "潜水", "en": "diving" },
        { "zh": "滑行", "en": "slithering" },
        { "zh": "爬行", "en": "crawling" },
        { "zh": "行走", "en": "walking" },
        { "zh": "站立", "en": "standing" },
        { "zh": "坐着", "en": "sitting" },
        { "zh": "躺卧", "en": "lying down" },
        { "zh": "休息", "en": "resting" },
        { "zh": "睡觉", "en": "sleeping" },
        { "zh": "打盹", "en": "napping" },
        { "zh": "进食", "en": "eating" },
        { "zh": "捕食", "en": "hunting" },
        { "zh": "觅食", "en": "foraging" },
        { "zh": "喝水", "en": "drinking" },
        { "zh": "玩耍", "en": "playing" },
        { "zh": "嬉戏", "en": "frolicking" },
        { "zh": "吼叫", "en": "roaring" },
        { "zh": "咆哮", "en": "growling" },
        { "zh": "低吼", "en": "snarling" },
        { "zh": "尖叫", "en": "screeching" },
        { "zh": "鸣叫", "en": "chirping" },
        { "zh": "唱歌", "en": "singing (bird)" },
        { "zh": "叫喊", "en": "calling (animal)" },
        { "zh": "筑巢", "en": "nesting" },
        { "zh": "挖洞", "en": "burrowing" },
        { "zh": "交配", "en": "mating" },
        { "zh": "求爱", "en": "courting" },
        { "zh": "打斗", "en": "fighting" },
        { "zh": "争吵", "en": "squabbling" },
        { "zh": "攻击", "en": "attacking" },
        { "zh": "防御", "en": "defending" },
        { "zh": "威吓", "en": "menacing" },
        { "zh": "逃跑", "en": "fleeing" },
        { "zh": "追逐", "en": "chasing" },
        { "zh": "隐藏", "en": "hiding" },
        { "zh": "伪装", "en": "blending in" },
        { "zh": "互动", "en": "interacting" },
        { "zh": "彼此依偎", "en": "cuddling" },
        { "zh": "舔毛", "en": "grooming" },
        { "zh": "哺乳", "en": "nursing" },
        { "zh": "喂养", "en": "feeding cubs/chicks" },
        { "zh": "凝视", "en": "gazing" },
        { "zh": "观察", "en": "observing" },
        { "zh": "探索", "en": "exploring" },
        { "zh": "警惕", "en": "alert" },
        { "zh": "好奇", "en": "curious" },
        { "zh": "沉思", "en": "contemplative" },
        { "zh": "害怕", "en": "frightened" },
        { "zh": "愤怒", "en": "angry" },
        { "zh": "平静", "en": "calm" },
        { "zh": "痛苦", "en": "distressed" },
        { "zh": "快乐", "en": "joyful" },
        { "zh": "沮丧", "en": "melancholy" },
        { "zh": "咆哮", "en": "bellowing" },
        { "zh": "嘶鸣", "en": "whinnying (horse)" },
        { "zh": "吠叫", "en": "barking (dog)" },
        { "zh": "喵叫", "en": "meowing (cat)" },
        { "zh": "咕噜", "en": "purring (cat)" },
        { "zh": "吱吱叫", "en": "squeaking (mouse)" },
        { "zh": "迁徙", "en": "migrating" },
        { "zh": "冬眠", "en": "hibernating" },
        { "zh": "夏眠", "en": "estivating" },
        { "zh": "脱皮", "en": "shedding skin" },
        { "zh": "蜕壳", "en": "molting" },
        { "zh": "求生", "en": "surviving" },
        { "zh": "适应", "en": "adapting" },
        { "zh": "奔向镜头", "en": "running towards camera" },
        { "zh": "飞向镜头", "en": "flying towards camera" },
        { "zh": "跳向镜头", "en": "jumping towards camera" },
        { "zh": "瞪大眼睛", "en": "wide-eyed" },
        { "zh": "睁开眼睛", "en": "eyes open" },
        { "zh": "闭上眼睛", "en": "eyes closed" },
        { "zh": "低头", "en": "head down" },
        { "zh": "抬头", "en": "head up" },
        { "zh": "咬", "en": "biting" },
        { "zh": "抓", "en": "scratching" }
      ]
    },
    {
      "name": "栖息地/环境 (Habitat/Environment)",
      "tags": [
        { "zh": "森林", "en": "forest" },
        { "zh": "茂密森林", "en": "dense forest" },
        { "zh": "热带雨林", "en": "tropical rainforest" },
        { "zh": "温带森林", "en": "temperate forest" },
        { "zh": "北方森林/针叶林", "en": "boreal forest / taiga" },
        { "zh": "红树林", "en": "mangrove forest" },
        { "zh": "竹林", "en": "bamboo forest" },
        { "zh": "丛林", "en": "jungle" },
        { "zh": "灌木丛", "en": "bushland" },
        { "zh": "草原", "en": "grassland" },
        { "zh": "稀树草原", "en": "savanna" },
        { "zh": "平原", "en": "plains" },
        { "zh": "沙漠", "en": "desert" },
        { "zh": "沙丘", "en": "sand dunes" },
        { "zh": "荒漠", "en": "wasteland" },
        { "zh": "极地", "en": "polar region" },
        { "zh": "北极", "en": "Arctic" },
        { "zh": "南极", "en": "Antarctic" },
        { "zh": "冰川", "en": "glacier" },
        { "zh": "冰山", "en": "iceberg" },
        { "zh": "苔原", "en": "tundra" },
        { "zh": "山脉", "en": "mountains" },
        { "zh": "山顶", "en": "mountain peak" },
        { "zh": "雪山", "en": "snowy mountains" },
        { "zh": "火山", "en": "volcano" },
        { "zh": "洞穴", "en": "cave" },
        { "zh": "地下", "en": "underground" },
        { "zh": "河流", "en": "river" },
        { "zh": "湖泊", "en": "lake" },
        { "zh": "池塘", "en": "pond" },
        { "zh": "溪流", "en": "stream" },
        { "zh": "瀑布", "en": "waterfall" },
        { "zh": "海洋", "en": "ocean" },
        { "zh": "深海", "en": "deep sea" },
        { "zh": "海岸线", "en": "coastline" },
        { "zh": "海滩", "en": "beach" },
        { "zh": "沙滩", "en": "sandy beach" },
        { "zh": "岩石海岸", "en": "rocky coast" },
        { "zh": "悬崖", "en": "cliff" },
        { "zh": "珊瑚礁", "en": "coral reef" },
        { "zh": "潮汐池", "en": "tide pool" },
        { "zh": "潮间带", "en": "intertidal zone" },
        { "zh": "湿地", "en": "wetland" },
        { "zh": "沼泽", "en": "swamp" },
        { "zh": "红树林", "en": "mangrove" },
        { "zh": "陆地", "en": "land" },
        { "zh": "天空", "en": "sky" },
        { "zh": "水下", "en": "underwater" },
        { "zh": "航空", "en": "aerial" },
        { "zh": "高原", "en": "plateau" },
        { "zh": "峡谷", "en": "canyon" },
        { "zh": "岛屿", "en": "island" },
        { "zh": "热带", "en": "tropical" },
        { "zh": "温带", "en": "temperate" },
        { "zh": "寒带", "en": "arctic" },
        { "zh": "亚洲", "en": "Asia" },
        { "zh": "非洲", "en": "Africa" },
        { "zh": "北美洲", "en": "North America" },
        { "zh": "南美洲", "en": "South America" },
        { "zh": "欧洲", "en": "Europe" },
        { "zh": "澳大利亚", "en": "Australia" },
        { "zh": "农场", "en": "farm" },
        { "zh": "牧场", "en": "pasture" },
        { "zh": "谷仓", "en": "barn" },
        { "zh": "乡村", "en": "countryside" },
        { "zh": "城市", "en": "urban area" },
        { "zh": "公园", "en": "park" },
        { "zh": "花园", "en": "garden" },
        { "zh": "动物园", "en": "zoo" },
        { "zh": "水族馆", "en": "aquarium" },
        { "zh": "保护区", "en": "wildlife sanctuary" },
        { "zh": "自然保护区", "en": "nature reserve" },
        { "zh": "巢穴", "en": "den / nest / burrow" },
        { "zh": "树上", "en": "in a tree" },
        { "zh": "枝头", "en": "on a branch" },
        { "zh": "洞穴入口", "en": "cave entrance" },
        { "zh": "泥地", "en": "muddy terrain" },
        { "zh": "岩石地", "en": "rocky terrain" },
        { "zh": "雪地", "en": "snowy ground" },
        { "zh": "冰面", "en": "ice surface" },
        { "zh": "沼泽地", "en": "marshland" },
        { "zh": "废墟", "en": "ruins" },
        { "zh": "实验室", "en": "laboratory" },
        { "zh": "围墙内", "en": "within an enclosure" },
        { "zh": "开放空间", "en": "open space" },
        { "zh": "狭窄空间", "en": "confined space" },
        { "zh": "天空", "en": "sky" },
        { "zh": "云层中", "en": "amidst clouds" },
        { "zh": "星空下", "en": "under a starry sky" }
      ]
    },
    {
      "name": "角度/构图 (Angle/Composition)",
      "tags": [
        { "zh": "特写", "en": "close-up" },
        { "zh": "局部特写", "en": "extreme close-up" },
        { "zh": "面部特写", "en": "facial close-up" },
        { "zh": "眼睛特写", "en": "eye close-up" },
        { "zh": "半身", "en": "medium shot" },
        { "zh": "全身", "en": "full shot" },
        { "zh": "远景", "en": "long shot" },
        { "zh": "大远景", "en": "extreme long shot" },
        { "zh": "环境远景", "en": "establishing shot" },
        { "zh": "广角镜头", "en": "wide angle shot" },
        { "zh": "超广角", "en": "ultrawide angle" },
        { "zh": "微距镜头", "en": "macro shot" },
        { "zh": "远摄镜头", "en": "telephoto shot" },
        { "zh": "鱼眼镜头", "en": "fisheye lens" },
        { "zh": "鸟瞰图", "en": "bird's eye view" },
        { "zh": "俯视图", "en": "overhead view" },
        { "zh": "虫眼视图", "en": "worm's eye view" },
        { "zh": "低角度", "en": "low angle" },
        { "zh": "高角度", "en": "high angle" },
        { "zh": "水平视角", "en": "eye-level shot" },
        { "zh": "主体视角", "en": "point of view (POV)" },
        { "zh": "第一人称视角", "en": "first-person view" },
        { "zh": "第三人称视角", "en": "third-person view" },
        { "zh": "倾斜角度", "en": "Dutch angle" },
        { "zh": "动态角度", "en": "dynamic angle" },
        { "zh": "静态拍摄", "en": "static shot" },
        { "zh": "平移镜头", "en": "panning shot" },
        { "zh": "追踪镜头", "en": "tracking shot" },
        { "zh": "运动模糊", "en": "motion blur" },
        { "zh": "景深", "en": "depth of field (DOF)" },
        { "zh": "散景", "en": "bokeh" },
        { "zh": "浅景深", "en": "shallow depth of field" },
        { "zh": "深景深", "en": "deep depth of field" },
        { "zh": "聚焦", "en": "in focus" },
        { "zh": "失焦", "en": "out of focus" },
        { "zh": "中心构图", "en": "centered composition" },
        { "zh": "三分法构图", "en": "rule of thirds" },
        { "zh": "对称构图", "en": "symmetrical composition" },
        { "zh": "对角线构图", "en": "diagonal composition" },
        { "zh": "引导线", "en": "leading lines" },
        { "zh": "框架构图", "en": "framing composition" },
        { "zh": "开放构图", "en": "open composition" },
        { "zh": "封闭构图", "en": "closed composition" },
        { "zh": "黄金比例", "en": "golden ratio" },
        { "zh": "黄金螺旋", "en": "Fibonacci spiral" },
        { "zh": "前景", "en": "foreground" },
        { "zh": "背景", "en": "background" },
        { "zh": "明亮主题，黑暗背景", "en": "bright subject, dark background" },
        { "zh": "清晰前景", "en": "sharp foreground" },
        { "zh": "虚化背景", "en": "blurred background" },
        { "zh": "轮廓", "en": "silhouette" },
        { "zh": "全景", "en": "panoramic" },
        { "zh": "横向构图", "en": "horizontal composition" },
        { "zh": "纵向构图", "en": "vertical composition" },
        { "zh": "正视图", "en": "front view" },
        { "zh": "侧视图", "en": "side view" },
        { "zh": "后视图", "en": "rear view" },
        { "zh": "四分之三视图", "en": "three-quarter view" },
        { "zh": "空旷构图", "en": "negative space" },
        { "zh": "填充画面", "en": "fill the frame" },
        { "zh": "多重曝光", "en": "multiple exposure" },
        { "zh": "特写肖像", "en": "portrait close-up" },
        { "zh": "宽画幅", "en": "cinemascope" },
        { "zh": "变形镜头", "en": "anamorphic lens" },
        { "zh": "手持拍摄", "en": "handheld camera" },
        { "zh": "稳定器拍摄", "en": "stabilized shot" },
        { "zh": "无人机视角", "en": "drone shot" },
        { "zh": "航拍", "en": "aerial shot" }
      ]
    },
    {
      "name": "光线/氛围 (Lighting/Mood)",
      "tags": [
        { "zh": "阳光", "en": "sunny" },
        { "zh": "直射光", "en": "direct sunlight" },
        { "zh": "柔和光线", "en": "soft lighting" },
        { "zh": "硬光", "en": "harsh lighting" },
        { "zh": "自然光", "en": "natural light" },
        { "zh": "人造光", "en": "artificial light" },
        { "zh": "低对比度光", "en": "low-contrast light" },
        { "zh": "高对比度光线", "en": "high-contrast lighting" },
        { "zh": "戏剧性光照", "en": "dramatic lighting" },
        { "zh": "轮廓光", "en": "rim light" },
        { "zh": "背光", "en": "backlit" },
        { "zh": "侧光", "en": "side lighting" },
        { "zh": "顶光", "en": "top lighting" },
        { "zh": "底光", "en": "underlighting" },
        { "zh": "反射", "en": "reflection" },
        { "zh": "水面倒影", "en": "water reflection" },
        { "zh": "光线穿透", "en": "light rays" },
        { "zh": "丁达尔效应", "en": "crepuscular rays" },
        { "zh": "光斑", "en": "lens flare" },
        { "zh": "辉光", "en": "bloom lighting" },
        { "zh": "阴影", "en": "shadows" },
        { "zh": "清晰阴影", "en": "sharp shadows" },
        { "zh": "柔和阴影", "en": "soft shadows" },
        { "zh": "剪影照明", "en": "silhouette lighting" },
        { "zh": "白天", "en": "daytime" },
        { "zh": "日出", "en": "sunrise" },
        { "zh": "黎明", "en": "dawn" },
        { "zh": "黄金时段", "en": "golden hour" },
        { "zh": "正午", "en": "midday" },
        { "zh": "日落", "en": "sunset" },
        { "zh": "黄昏/傍晚", "en": "dusk / twilight" },
        { "zh": "蓝调时刻", "en": "blue hour" },
        { "zh": "夜晚", "en": "night" },
        { "zh": "月光", "en": "moonlight" },
        { "zh": "星光", "en": "starlight" },
        { "zh": "极光", "en": "aurora" },
        { "zh": "环境照明", "en": "ambient light" },
        { "zh": "重点照明", "en": "spotlight" },
        { "zh": "弥漫光", "en": "diffused light" },
        { "zh": "晴朗天空", "en": "clear sky" },
        { "zh": "阴天", "en": "cloudy" },
        { "zh": "暴风雨", "en": "stormy weather" },
        { "zh": "雾蒙蒙", "en": "foggy" },
        { "zh": "雨天", "en": "rainy" },
        { "zh": "雪天", "en": "snowy" },
        { "zh": "宁静", "en": "serene" },
        { "zh": "平静", "en": "calm" },
        { "zh": "神秘", "en": "mysterious" },
        { "zh": "黑暗", "en": "dark" },
        { "zh": "光明", "en": "bright" },
        { "zh": "生机勃勃", "en": "vibrant" },
        { "zh": "忧郁", "en": "melancholy" },
        { "zh": "恐怖", "en": "eerie" },
        { "zh": "梦幻", "en": "dreamlike" },
        { "zh": "奇幻", "en": "fantastical" },
        { "zh": "史诗般", "en": "epic" },
        { "zh": "安详", "en": "tranquil" },
        { "zh": "荒凉", "en": "desolate" },
        { "zh": "充满活力", "en": "lively" },
        { "zh": "柔和", "en": "subdued" },
        { "zh": "压抑", "en": "oppressive" },
        { "zh": "希望", "en": "hopeful" },
        { "zh": "兴奋", "en": "exciting" },
        { "zh": "孤独", "en": "lonely" },
        { "zh": "治愈", "en": "healing" },
        { "zh": "紧张", "en": "tense" },
        { "zh": "庄严", "en": "solemn" },
        { "zh": "温馨", "en": "cozy" }
      ]
    },
    {
      "name": "颜色 (Color)",
      "tags": [
        { "zh": "红色", "en": "red" },
        { "zh": "深红", "en": "crimson" },
        { "zh": "朱红", "en": "vermilion" },
        { "zh": "蓝色", "en": "blue" },
        { "zh": "天蓝", "en": "sky blue" },
        { "zh": "钴蓝", "en": "cobalt blue" },
        { "zh": "藏青", "en": "navy blue" },
        { "zh": "绿色", "en": "green" },
        { "zh": "翠绿", "en": "emerald green" },
        { "zh": "橄榄绿", "en": "olive green" },
        { "zh": "森林绿", "en": "forest green" },
        { "zh": "黄色", "en": "yellow" },
        { "zh": "柠檬黄", "en": "lemon yellow" },
        { "zh": "金黄", "en": "golden yellow" },
        { "zh": "黑色", "en": "black" },
        { "zh": "墨黑", "en": "jet black" },
        { "zh": "炭黑", "en": "charcoal black" },
        { "zh": "白色", "en": "white" },
        { "zh": "雪白", "en": "snow white" },
        { "zh": "象牙白", "en": "ivory" },
        { "zh": "棕色", "en": "brown" },
        { "zh": "巧克力色", "en": "chocolate brown" },
        { "zh": "土棕色", "en": "sepia" },
        { "zh": "米色", "en": "beige" },
        { "zh": "橙色", "en": "orange" },
        { "zh": "琥珀色", "en": "amber" },
        { "zh": "紫色", "en": "purple" },
        { "zh": "薰衣草色", "en": "lavender" },
        { "zh": "洋红", "en": "magenta" },
        { "zh": "粉色", "en": "pink" },
        { "zh": "玫瑰粉", "en": "rose pink" },
        { "zh": "灰色", "en": "grey" },
        { "zh": "银色", "en": "silver" },
        { "zh": "金色", "en": "gold" },
        { "zh": "青铜色", "en": "bronze" },
        { "zh": "彩色", "en": "colorful" },
        { "zh": "单色", "en": "monochrome" },
        { "zh": "黑白", "en": "black and white" },
        { "zh": "灰度", "en": "grayscale" },
        { "zh": "淡色", "en": "pastel colors" },
        { "zh": "鲜艳色", "en": "vivid colors" },
        { "zh": "饱和色", "en": "saturated colors" },
        { "zh": "去饱和色", "en": "desaturated colors" },
        { "zh": "原色", "en": "primary colors" },
        { "zh": "补色", "en": "complementary colors" },
        { "zh": "冷色调", "en": "cool tones" },
        { "zh": "暖色调", "en": "warm tones" },
        { "zh": "霓虹色", "en": "neon colors" },
        { "zh": "金属色", "en": "metallic colors" },
        { "zh": "荧光色", "en": "fluorescent colors" },
        { "zh": "透明", "en": "transparent" },
        { "zh": "半透明", "en": "translucent" },
        { "zh": "渐变色", "en": "gradient colors" },
        { "zh": "亮色", "en": "bright colors" },
        { "zh": "暗色", "en": "dark colors" },
        { "zh": "地球色调", "en": "earthy tones" },
        { "zh": "水生色调", "en": "aquatic tones" },
        { "zh": "沙漠色调", "en": "desert tones" },
        { "zh": "森林色调", "en": "forest tones" },
        { "zh": "自定义颜色", "en": "custom color palette" }
      ]
    },
    {
      "name": "情绪/主题 (Mood/Theme)",
      "tags": [
        { "zh": "野生", "en": "wild" },
        { "zh": "驯服", "en": "domesticated" },
        { "zh": "捕食者与猎物", "en": "predator and prey" },
        { "zh": "动物肖像", "en": "animal portrait" },
        { "zh": "母爱", "en": "maternal love" },
        { "zh": "父爱", "en": "paternal love" },
        { "zh": "幼年", "en": "childhood" },
        { "zh": "童真", "en": "innocence" },
        { "zh": "野性之美", "en": "beauty of wilderness" },
        { "zh": "生态平衡", "en": "ecological balance" },
        { "zh": "生物多样性", "en": "biodiversity" },
        { "zh": "环境保护", "en": "environmental conservation" },
        { "zh": "自然", "en": "nature" },
        { "zh": "宏伟", "en": "majestic" },
        { "zh": "宁静", "en": "peaceful" },
        { "zh": "神秘", "en": "mystical" },
        { "zh": "凶猛", "en": "ferocious" },
        { "zh": "可爱", "en": "adorable" },
        { "zh": "强大", "en": "powerful" },
        { "zh": "脆弱", "en": "vulnerable" },
        { "zh": "孤独", "en": "lonely" },
        { "zh": "群体生活", "en": "communal living" },
        { "zh": "和谐", "en": "harmony" },
        { "zh": "生存", "en": "survival" },
        { "zh": "斗争", "en": "struggle" },
        { "zh": "适应", "en": "adaptation" },
        { "zh": "进化", "en": "evolution" },
        { "zh": "智慧", "en": "wisdom" },
        { "zh": "本能", "en": "instinct" },
        { "zh": "拟人", "en": "anthropomorphic" },
        { "zh": "寓言", "en": "fable" },
        { "zh": "童话", "en": "fairy tale" },
        { "zh": "神话", "en": "mythology" },
        { "zh": "传说", "en": "legend" },
        { "zh": "民间故事", "en": "folklore" },
        { "zh": "科幻", "en": "science fiction" },
        { "zh": "幻想", "en": "fantasy" },
        { "zh": "蒸汽朋克", "en": "steampunk" },
        { "zh": "赛博朋克", "en": "cyberpunk" },
        { "zh": "后启示录", "en": "post-apocalyptic" },
        { "zh": "黑色幽默", "en": "dark humor" },
        { "zh": "幽默", "en": "humorous" },
        { "zh": "悲剧", "en": "tragic" },
        { "zh": "恐怖", "en": "horror" },
        { "zh": "悬疑", "en": "suspense" },
        { "zh": "励志", "en": "inspirational" },
        { "zh": "教育", "en": "educational" },
        { "zh": "象征主义", "en": "symbolism" },
        { "zh": "超现实主义", "en": "surrealism" },
        { "zh": "梦境", "en": "dreamscape" },
        { "zh": "乌托邦", "en": "utopian" },
        { "zh": "反乌托邦", "en": "dystopian" },
        { "zh": "哲学", "en": "philosophical" },
        { "zh": "社会评论", "en": "social commentary" },
        { "zh": "怀旧", "en": "nostalgic" },
        { "zh": "复古", "en": "vintage" },
        { "zh": "现代", "en": "modern" },
        { "zh": "未来", "en": "futuristic" },
        { "zh": "抽象概念", "en": "abstract concept" },
        { "zh": "情感表达", "en": "emotional expression" },
        { "zh": "生命周期", "en": "life cycle" },
        { "zh": "伪装与适应", "en": "camouflage & adaptation" },
        { "zh": "夜间活动", "en": "nocturnal activity" },
        { "zh": "栖息地丧失", "en": "habitat loss" },
        { "zh": "异种友谊", "en": "inter-species friendship" },
        { "zh": "捕食链", "en": "food chain" },
        { "zh": "大迁徙", "en": "great migration" },
        { "zh": "生与死", "en": "life and death" }
      ]
    },
    {
      "name": "画面元素 (Visual Elements)",
      "tags": [
        { "zh": "水滴", "en": "water drops" },
        { "zh": "雨", "en": "rain" },
        { "zh": "下雪", "en": "snowfall" },
        { "zh": "冰", "en": "ice" },
        { "zh": "霜", "en": "frost" },
        { "zh": "蒸汽", "en": "steam" },
        { "zh": "雾", "en": "mist" },
        { "zh": "烟", "en": "smoke" },
        { "zh": "灰尘", "en": "dust" },
        { "zh": "泥土", "en": "mud" },
        { "zh": "岩石", "en": "rocks" },
        { "zh": "巨石", "en": "boulders" },
        { "zh": "山脉", "en": "mountains" },
        { "zh": "丘陵", "en": "hills" },
        { "zh": "沙子", "en": "sand" },
        { "zh": "雪", "en": "snow" },
        { "zh": "地面", "en": "ground" },
        { "zh": "树木", "en": "trees" },
        { "zh": "森林", "en": "forest vegetation" },
        { "zh": "植物", "en": "plants" },
        { "zh": "鲜花", "en": "flowers" },
        { "zh": "树叶", "en": "leaves" },
        { "zh": "草地", "en": "grass" },
        { "zh": "藤蔓", "en": "vines" },
        { "zh": "苔藓", "en": "moss" },
        { "zh": "蘑菇", "en": "mushrooms" },
        { "zh": "水体", "en": "body of water" },
        { "zh": "水面", "en": "water surface" },
        { "zh": "水波", "en": "ripples" },
        { "zh": "浪花", "en": "splashes" },
        { "zh": "水花", "en": "spray" },
        { "zh": "瀑布", "en": "waterfall" },
        { "zh": "溪流", "en": "stream" },
        { "zh": "河流", "en": "river" },
        { "zh": "湖泊", "en": "lake" },
        { "zh": "池塘", "en": "pond" },
        { "zh": "海洋", "en": "ocean" },
        { "zh": "蓝天", "en": "blue sky" },
        { "zh": "云彩", "en": "clouds" },
        { "zh": "风暴云", "en": "stormy clouds" },
        { "zh": "彩虹", "en": "rainbow" },
        { "zh": "星空", "en": "starry sky" },
        { "zh": "银河", "en": "Milky Way" },
        { "zh": "月亮", "en": "moon" },
        { "zh": "太阳", "en": "sun" },
        { "zh": "阳光", "en": "sunbeams" },
        { "zh": "闪电", "en": "lightning" },
        { "zh": "火山喷发", "en": "volcanic eruption" },
        { "zh": "倒影", "en": "reflection" },
        { "zh": "水下倒影", "en": "underwater reflection" },
        { "zh": "镜面效果", "en": "mirror effect" },
        { "zh": "影子", "en": "shadow" },
        { "zh": "清晰的影子", "en": "sharp shadows" },
        { "zh": "柔和的影子", "en": "soft shadows" },
        { "zh": "光斑", "en": "lens flare" },
        { "zh": "光线效果", "en": "light effects" },
        { "zh": "粒子效果", "en": "particle effects" },
        { "zh": "尘埃粒子", "en": "dust particles" },
        { "zh": "雨滴效果", "en": "raindrop effects" },
        { "zh": "雾气弥漫", "en": "haze" },
        { "zh": "薄雾", "en": "misty atmosphere" },
        { "zh": "环境光", "en": "ambient light" },
        { "zh": "轮廓光", "en": "rim light" },
        { "zh": "体积照明", "en": "volumetric lighting" },
        { "zh": "霞光", "en": "afterglow" },
        { "zh": "前景物体", "en": "foreground objects" },
        { "zh": "背景虚化", "en": "blurred background" },
        { "zh": "清晰背景", "en": "sharp background" },
        { "zh": "前景虚化", "en": "foreground blur" },
        { "zh": "模糊效果", "en": "blur effect" },
        { "zh": "纹理", "en": "texture" },
        { "zh": "图案", "en": "pattern" },
        { "zh": "渐变", "en": "gradient" },
        { "zh": "抽象背景", "en": "abstract background" },
        { "zh": "虚化光斑", "en": "bokeh effects" },
        { "zh": "烟雾缭绕", "en": "smoky atmosphere" },
        { "zh": "火焰", "en": "flames" },
        { "zh": "余烬", "en": "embers" },
        { "zh": "废墟", "en": "ruins" },
        { "zh": "古迹", "en": "ancient structures" },
        { "zh": "人类痕迹", "en": "human traces" },
        { "zh": "道路", "en": "road" },
        { "zh": "桥", "en": "bridge" },
        { "zh": "破败建筑", "en": "dilapidated building" }
      ]
    }
  ]
});