tagData.push({
  "group": "人物 (Character)",
  "categories": [
  {
  "name": "人物类型 (Character Types)",
  "tags": [
  { "zh": "1个女孩", "en": "1girl" },
  { "zh": "2个女孩", "en": "2girls" },
  { "zh": "多个女孩", "en": "multiple girls" },
  { "zh": "1个男孩", "en": "1boy" },
  { "zh": "2个男孩", "en": "2boys" },
  { "zh": "多个男孩", "en": "multiple boys" },
  { "zh": "多人", "en": "multiple people" },
  { "zh": "男性", "en": "male" },
  { "zh": "女性", "en": "female" },
  { "zh": "儿童", "en": "children" },
  { "zh": "婴儿", "en": "baby" },
  { "zh": "少年", "en": "teenager" },
  { "zh": "青年", "en": "young adult" },
  { "zh": "成年人", "en": "adult" },
  { "zh": "中年人", "en": "middle-aged" },
  { "zh": "老年人", "en": "elder" },
  { "zh": "美少女", "en": "bishoujo" },
  { "zh": "美少年", "en": "bishounen" },
  { "zh": "辣妹", "en": "gyaru" },
  { "zh": "正太", "en": "shota" },
  { "zh": "萝莉", "en": "loli" },
  { "zh": "御姐", "en": "ojousama" },
  { "zh": "肌肉男", "en": "muscular male" },
  { "zh": "性感女性", "en": "sexy female" },
  { "zh": "Q版人物", "en": "chibi" },
  { "zh": "兽人", "en": "anthro" },
  { "zh": "半兽人", "en": "kemonomimi" },
  { "zh": "机器人", "en": "robot" },
  { "zh": "赛博格", "en": "cyborg" },
  { "zh": "非人类", "en": "non-human" },
  { "zh": "怪物女孩", "en": "monster girl" },
  { "zh": "外星人", "en": "alien" },
  { "zh": "人类", "en": "human" },
  { "zh": "矮小", "en": "petite" },
  { "zh": "高大", "en": "tall (person)" },
  { "zh": "瘦弱", "en": "skinny" },
  { "zh": "苗条", "en": "slender" },
  { "zh": "丰满", "en": "curvy" },
  { "zh": "肥胖", "en": "obese" },
  { "zh": "运动员型", "en": "athletic" },
  { "zh": "双胞胎", "en": "twins" },
  { "zh": "三胞胎", "en": "triplets" },
  { "zh": "独奏", "en": "solo" }
  ]
  },
  {
  "name": "职业 (Professions)",
  "tags": [
  { "zh": "偶像", "en": "idol" },
  { "zh": "学生", "en": "student" },
  { "zh": "老师", "en": "teacher" },
  { "zh": "护士", "en": "nurse" },
  { "zh": "医生", "en": "doctor" },
  { "zh": "女仆", "en": "maid" },
  { "zh": "服务员", "en": "waitress" },
  { "zh": "警察", "en": "police" },
  { "zh": "侦探", "en": "detective" },
  { "zh": "宇航员", "en": "astronaut" },
  { "zh": "骑士", "en": "knight" },
  { "zh": "魔法师", "en": "wizard" },
  { "zh": "女巫", "en": "witch" },
  { "zh": "忍者", "en": "ninja" },
  { "zh": "办公室白领", "en": "office worker" },
  { "zh": "厨师", "en": "chef" },
  { "zh": "士兵", "en": "soldier" },
  { "zh": "科学家", "en": "scientist" },
  { "zh": "工程师", "en": "engineer" },
  { "zh": "农民", "en": "farmer" },
  { "zh": "渔民", "en": "fisherman" },
  { "zh": "艺术家", "en": "artist" },
  { "zh": "音乐家", "en": "musician" },
  { "zh": "作家", "en": "writer" },
  { "zh": "运动员", "en": "athlete" },
  { "zh": "消防员", "en": "firefighter" },
  { "zh": "快递员", "en": "delivery driver" },
  { "zh": "清洁工", "en": "janitor" },
  { "zh": "法官", "en": "judge" },
  { "zh": "律师", "en": "lawyer" },
  { "zh": "海盗", "en": "pirate" },
  { "zh": "牛仔", "en": "cowboy" },
  { "zh": "部落战士", "en": "tribal warrior" },
  { "zh": "刺客", "en": "assassin" },
  { "zh": "船长", "en": "captain" },
  { "zh": "飞行员", "en": "pilot" },
  { "zh": "芭蕾舞者", "en": "ballerina" },
  { "zh": "模特", "en": "model" },
  { "zh": "摄影师", "en": "photographer" },
  { "zh": "记者", "en": "journalist" },
  { "zh": "调酒师", "en": "bartender" },
  { "zh": "服务生", "en": "bellhop" },
  { "zh": "警官", "en": "officer" },
  { "zh": "军人", "en": "military" },
  { "zh": "武士", "en": "samurai" },
  { "zh": "角斗士", "en": "gladiator" },
  { "zh": "吟游诗人", "en": "bard" },
  { "zh": "炼金术士", "en": "alchemist" },
  { "zh": "修女", "en": "nun" },
  { "zh": "神父", "en": "priest" },
  { "zh": "国王", "en": "king" },
  { "zh": "女王", "en": "queen" },
  { "zh": "王子", "en": "prince" },
  { "zh": "公主", "en": "princess" },
  { "zh": "贵族", "en": "noble" },
  { "zh": "奴隶", "en": "slave" },
  { "zh": "商人", "en": "merchant" },
  { "zh": "学者", "en": "scholar" },
  { "zh": "僧侣", "en": "monk" },
  { "zh": "黑客", "en": "hacker" },
  { "zh": "赛车手", "en": "racer" },
  { "zh": "建筑师", "en": "architect" },
  { "zh": "兽医", "en": "veterinarian" },
  { "zh": "地质学家", "en": "geologist" },
  { "zh": "考古学家", "en": "archaeologist" },
  { "zh": "工程师", "en": "engineer" },
  { "zh": "宇航员", "en": "astronaut" }
  ]
  },
  {
  "name": "角色 (Roles/Archetypes)",
  "tags": [
  { "zh": "英雄", "en": "hero" },
  { "zh": "反派", "en": "villain" },
  { "zh": "天使", "en": "angel" },
  { "zh": "恶魔", "en": "devil" },
  { "zh": "吸血鬼", "en": "vampire" },
  { "zh": "精灵", "en": "elf" },
  { "zh": "矮人", "en": "dwarf" },
  { "zh": "哥布林", "en": "goblin" },
  { "zh": "僵尸", "en": "zombie" },
  { "zh": "狼人", "en": "werewolf" },
  { "zh": "幽灵", "en": "ghost" },
  { "zh": "神明", "en": "deity" },
  { "zh": "超级英雄", "en": "superhero" },
  { "zh": "新娘", "en": "bride" },
  { "zh": "新郎", "en": "groom" },
  { "zh": "女武神", "en": "valkyrie" },
  { "zh": "妖精", "en": "fairy" },
  { "zh": "人鱼", "en": "mermaid" },
  { "zh": "兽人", "en": "orc" },
  { "zh": "魅魔", "en": "succubus" },
  { "zh": "白发萝莉", "en": "white hair loli" },
  { "zh": "傲娇", "en": "tsundere" },
  { "zh": "病娇", "en": "yandere" },
  { "zh": "三无少女", "en": "kuudere" },
  { "zh": "怕生少女", "en": "dandere" },
  { "zh": "元气少女", "en": "genki girl" },
  { "zh": "不良", "en": "delinquent" },
  { "zh": "猫娘", "en": "cat girl" },
  { "zh": "狐仙娘", "en": "kitsune girl" },
  { "zh": "剑士", "en": "swordsman" },
  { "zh": "弓箭手", "en": "archer" },
  { "zh": "战士", "en": "warrior" },
  { "zh": "法师", "en": "mage" },
  { "zh": "盗贼", "en": "rogue" },
  { "zh": "牧师", "en": "cleric" },
  { "zh": "圣骑士", "en": "paladin" },
  { "zh": "德鲁伊", "en": "druid" },
  { "zh": "游侠", "en": "ranger" },
  { "zh": "召唤师", "en": "summoner" },
  { "zh": "女战士", "en": "amazon" },
  { "zh": "老者", "en": "sage" },
  { "zh": "智者", "en": "wise man" },
  { "zh": "少女", "en": "maiden" },
  { "zh": "美魔女", "en": "femme fatale" },
  { "zh": "机器人女孩", "en": "robot girl" },
  { "zh": "AI", "en": "AI" },
  { "zh": "改造人", "en": "augmented human" },
  { "zh": "克隆人", "en": "clone" },
  { "zh": "幻影", "en": "phantom" },
  { "zh": "妖精", "en": "sprite" },
  { "zh": "半神", "en": "demigod" },
  { "zh": "先知", "en": "prophet" },
  { "zh": "领袖", "en": "leader" },
  { "zh": "追随者", "en": "follower" },
  { "zh": "受害者", "en": "victim" },
  { "zh": "幸存者", "en": "survivor" },
  { "zh": "反叛者", "en": "rebel" },
  { "zh": "无辜者", "en": "innocent" },
  { "zh": "罪犯", "en": "criminal" },
  { "zh": "骗子", "en": "trickster" },
  { "zh": "导师", "en": "mentor" },
  { "zh": "学徒", "en": "apprentice" },
  { "zh": "陌生人", "en": "stranger" },
  { "zh": "偶像", "en": "idol" },
  {"zh": "不良少年", "en": "yankee (character)"},
  {"zh": "大小姐", "en": "ojou-sama"},
  {"zh": "眼镜娘", "en": "meganekko"},
  {"zh": "眼镜男", "en": "megane otoko"}
  ]
  },
  {
  "name": "五官 (Facial Features)",
  "tags": [
  { "zh": "美丽的脸", "en": "beautiful face" },
  { "zh": "英俊的脸", "en": "handsome face" },
  { "zh": "可爱的脸", "en": "cute face" },
  { "zh": "精致的五官", "en": "delicate features" },
  { "zh": "大大的眼睛", "en": "large eyes" },
  { "zh": "细长的眼睛", "en": "narrow eyes" },
  { "zh": "圆眼睛", "en": "round eyes" },
  { "zh": "蓝眼睛", "en": "blue eyes" },
  { "zh": "红眼睛", "en": "red eyes" },
  { "zh": "金眼睛", "en": "gold eyes" },
  { "zh": "绿眼睛", "en": "green eyes" },
  { "zh": "紫眼睛", "en": "purple eyes" },
  { "zh": "灰眼睛", "en": "grey eyes" },
  { "zh": "棕眼睛", "en": "brown eyes" },
  {"zh": "闪亮的眼睛", "en": "sparkling eyes"},
  {"zh": "疲惫的眼睛", "en": "tired eyes"},
  {"zh": "空洞的眼神", "en": "empty eyes"},
  {"zh": "死鱼眼", "en": "dead eyes"},
  { "zh": "异色瞳", "en": "heterochromia" },
  { "zh": "闭眼", "en": "closed eyes" },
  { "zh": "半闭眼", "en": "half-closed eyes" },
  { "zh": "眼罩", "en": "eyepatch" },
  { "zh": "眼镜", "en": "glasses" },
  { "zh": "墨镜", "en": "sunglasses" },
  { "zh": "长睫毛", "en": "long eyelashes" },
  { "zh": "浓密眉毛", "en": "thick eyebrows" },
  { "zh": "细眉毛", "en": "thin eyebrows" },
  { "zh": "雀斑", "en": "freckles" },
  { "zh": "酒窝", "en": "dimples" },
  { "zh": "尖耳朵", "en": "pointy ears" },
  { "zh": "毛绒耳朵", "en": "furry ears" },
  {"zh": "动物耳朵", "en": "animal ears"},
  { "zh": "獠牙", "en": "fangs" },
  { "zh": "微笑的嘴", "en": "smiling mouth" },
  { "zh": "小嘴", "en": "small mouth" },
  { "zh": "厚唇", "en": "full lips" },
  { "zh": "薄唇", "en": "thin lips" },
  { "zh": "涂口红", "en": "lipstick" },
  { "zh": "痣", "en": "mole" },
  { "zh": "泪痣", "en": "teardrop mole" },
  { "zh": "伤疤", "en": "scar" },
  { "zh": "皱纹", "en": "wrinkles" },
  { "zh": "胡须", "en": "beard" },
  { "zh": "小胡子", "en": "moustache" },
  { "zh": "八字胡", "en": "walrus moustache" },
  { "zh": "山羊胡", "en": "goatee" },
  { "zh": "络腮胡", "en": "full beard" },
  { "zh": "胡茬", "en": "stubble" },
  { "zh": "尖下巴", "en": "pointed chin" },
  { "zh": "双下巴", "en": "double chin" },
  { "zh": "高鼻梁", "en": "high nose bridge" },
  { "zh": "小鼻子", "en": "small nose" },
  { "zh": "红脸颊", "en": "rosy cheeks" },
  { "zh": "婴儿肥", "en": "chubby cheeks" },
  { "zh": "雀斑", "en": "pockmarks" },
  { "zh": "假睫毛", "en": "false eyelashes" },
  { "zh": "眼线", "en": "eyeliner" },
  { "zh": "眼影", "en": "eyeshadow" },
  { "zh": "腮红", "en": "blush (makeup)" }
  ]
  },
  {
  "name": "表情 (Expressions)",
  "tags": [
  { "zh": "微笑", "en": "smile" },
  { "zh": "大笑", "en": "laughing" },
  { "zh": "偷偷笑", "en": "chuckle" },
  { "zh": "开心的", "en": "happy" },
  { "zh": "悲伤的", "en": "sad" },
  { "zh": "哭泣", "en": "crying" },
  { "zh": "眼泪", "en": "tears" },
  { "zh": "生气的", "en": "angry" },
  { "zh": "恼怒", "en": "annoyed" },
  { "zh": "害羞", "en": "shy" },
  { "zh": "脸红", "en": "blush" },
  { "zh": "严肃的", "en": "serious" },
  { "zh": "冷漠的", "en": "indifferent" },
  { "zh": "惊讶", "en": "surprised" },
  { "zh": "恐惧", "en": "scared" },
  { "zh": "自信的", "en": "confident" },
  { "zh": "醉的", "en": "drunk" },
  { "zh": "困倦的", "en": "sleepy" },
  { "zh": "困惑的", "en": "confused" },
  { "zh": "思考", "en": "thinking" },
  { "zh": "得意", "en": "smirk" },
  { "zh": "撅嘴", "en": "pouting" },
  { "zh": "张着嘴", "en": "open mouth" },
  { "zh": "吐舌头", "en": "tongue out" },
  { "zh": "苦涩的笑容", "en": "wry smile" },
  { "zh": "无聊", "en": "bored" },
  { "zh": "期待", "en": "anticipation" },
  { "zh": "绝望", "en": "despair" },
  { "zh": "震惊", "en": "shocked" },
  { "zh": "咆哮", "en": "roaring" },
  { "zh": "咧嘴笑", "en": "grin" },
  { "zh": "愁眉苦脸", "en": "frowning" },
  { "zh": "扬眉", "en": "raised eyebrow" },
  { "zh": "低头", "en": "looking down" },
  { "zh": "抬头", "en": "looking up" },
  { "zh": "专注", "en": "focused" },
  { "zh": "调皮", "en": "mischievous" },
  { "zh": "空虚", "en": "empty expression" },
  { "zh": "冥想", "en": "meditating expression" },
  { "zh": "饥饿", "en": "hungry" },
  { "zh": "口渴", "en": "thirsty" },
  { "zh": "冷", "en": "cold (expression)" },
  { "zh": "热", "en": "hot (expression)" },
  { "zh": "疲惫", "en": "exhausted" },
  { "zh": "平静", "en": "calm" },
  { "zh": "满足", "en": "content" },
  { "zh": "渴望", "en": "longing" },
  { "zh": "着迷", "en": "fascinated" },
  { "zh": "羞辱", "en": "embarrassed" }
  ]
  },
  {
  "name": "头发 (Hair)",
  "tags": [
  { "zh": "长发", "en": "long hair" },
  { "zh": "短发", "en": "short hair" },
  { "zh": "及肩长发", "en": "medium hair" },
  { "zh": "超长发", "en": "very long hair" },
  { "zh": "齐腰发", "en": "waist-length hair" },
  { "zh": "及膝发", "en": "knee-length hair" },
  { "zh": "双马尾", "en": "twintails" },
  { "zh": "单马尾", "en": "ponytail" },
  { "zh": "高马尾", "en": "high ponytail" },
  { "zh": "低马尾", "en": "low ponytail" },
  { "zh": "麻花辫", "en": "braid" },
  { "zh": "双辫", "en": "two braids" },
  { "zh": "法式辫", "en": "french braid" },
  { "zh": "鱼骨辫", "en": "fishtail braid" },
  { "zh": "发髻", "en": "hair bun" },
  { "zh": "包子头", "en": "double buns" },
  { "zh": "半束发", "en": "half updo" },
  { "zh": "波浪卷", "en": "wavy hair" },
  { "zh": "卷发", "en": "curly hair" },
  { "zh": "螺旋卷", "en": "ringlets" },
  { "zh": "直发", "en": "straight hair" },
  { "zh": "白发", "en": "white hair" },
  { "zh": "黑发", "en": "black hair" },
  { "zh": "金发", "en": "blonde hair" },
  { "zh": "棕发", "en": "brown hair" },
  { "zh": "红发", "en": "red hair" },
  { "zh": "蓝发", "en": "blue hair" },
  { "zh": "绿发", "en": "green hair" },
  { "zh": "紫发", "en": "purple hair" },
  { "zh": "粉发", "en": "pink hair" },
  { "zh": "银发", "en": "silver hair" },
  { "zh": "灰发", "en": "grey hair" },
  { "zh": "橙发", "en": "orange hair" },
  { "zh": "彩色头发", "en": "multicolored hair" },
  { "zh": "渐变色头发", "en": "gradient hair" },
  { "zh": "挑染", "en": "streaked hair" },
  { "zh": "刘海", "en": "bangs" },
  { "zh": "齐刘海", "en": "blunt bangs" },
  { "zh": "侧分刘海", "en": "side swept bangs" },
  { "zh": "空气刘海", "en": "see-through bangs" },
  { "zh": "中分", "en": "center part" },
  { "zh": "呆毛", "en": "ahoge" },
  { "zh": "发尾", "en": "hair tips" },
  { "zh": "蓬松头发", "en": "voluminous hair" },
  { "zh": "扁平头发", "en": "flat hair" },
  { "zh": "湿发", "en": "wet hair" },
  { "zh": "凌乱的头发", "en": "messy hair" },
  { "zh": "光滑的发型", "en": "slicked back hair" },
  { "zh": "光头", "en": "bald" },
  { "zh": "脏辫", "en": "dreadlocks" },
  { "zh": "爆炸头", "en": "afro" },
  { "zh": "染发", "en": "dyed hair" },
  { "zh": "挑染", "en": "highlights" },
  { "zh": "低调染", "en": "lowlights" },
  { "zh": "发梢分叉", "en": "split ends" },
  { "zh": "发丝飘扬", "en": "hair blowing in wind" },
  { "zh": "波波头", "en": "bob cut" },
  { "zh": "公主切", "en": "hime cut" },
  { "zh": "狼剪", "en": "shag cut" },
  { "zh": "莫霍克", "en": "mohawk" },
  { "zh": "丸子头", "en": "topknot" },
  { "zh": "齐耳短发", "en": "ear-length hair" }
  ]
  },
  {
  "name": "装饰 (Accessories)",
  "tags": [
  { "zh": "项链", "en": "necklace" },
  { "zh": "耳环", "en": "earrings" },
  { "zh": "戒指", "en": "ring" },
  { "zh": "手镯", "en": "bracelet" },
  { "zh": "脚链", "en": "anklet" },
  { "zh": "锁骨链", "en": "choker" },
  { "zh": "发夹", "en": "hair clip" },
  { "zh": "发带", "en": "hair tie" },
  { "zh": "发饰", "en": "hair ornament" },
  { "zh": "丝带", "en": "ribbon" },
  { "zh": "头带", "en": "headband" },
  { "zh": "手套", "en": "gloves" },
  { "zh": "指套", "en": "fingerless gloves" },
  { "zh": "围巾", "en": "scarf" },
  { "zh": "披肩", "en": "shawl" },
  { "zh": "腰带", "en": "belt" },
  { "zh": "领带", "en": "tie" },
  { "zh": "领结", "en": "bow tie" },
  { "zh": "胸针", "en": "brooch" },
  { "zh": "手表", "en": "watch" },
  { "zh": "智能手表", "en": "smartwatch" },
  { "zh": "背包", "en": "backpack" },
  { "zh": "手提包", "en": "handbag" },
  { "zh": "单肩包", "en": "shoulder bag" },
  { "zh": "挎包", "en": "messenger bag" },
  { "zh": "耳罩", "en": "earmuffs" },
  { "zh": "腕带", "en": "wristband" },
  { "zh": "道具", "en": "prop" },
  { "zh": "武器", "en": "weapon" },
  { "zh": "剑", "en": "sword" },
  { "zh": "弓", "en": "bow" },
  { "zh": "盾牌", "en": "shield" },
  { "zh": "枪", "en": "firearm" },
  { "zh": "法杖", "en": "staff" },
  { "zh": "魔杖", "en": "wand" },
  { "zh": "翅膀", "en": "wings" },
  { "zh": "尾巴", "en": "tail" },
  { "zh": "猫耳", "en": "cat ears" },
  { "zh": "狗耳", "en": "dog ears" },
  { "zh": "狐狸耳", "en": "fox ears" },
  { "zh": "光环", "en": "halo" },
  { "zh": "角", "en": "horns" },
  { "zh": "口罩", "en": "mask" },
  { "zh": "面罩", "en": "face mask" },
  { "zh": "纹身", "en": "tattoo" },
  { "zh": "穿孔", "en": "piercing" },
  { "zh": "耳钉", "en": "ear stud" },
  { "zh": "鼻环", "en": "nose ring" },
  { "zh": "纹身袖", "en": "tattoo sleeve" },
  { "zh": "丝巾", "en": "silk scarf" },
  { "zh": "眼镜链", "en": "glasses chain" },
  { "zh": "怀表", "en": "pocket watch" },
  { "zh": "手帕", "en": "handkerchief" },
  { "zh": "扇子", "en": "fan" },
  { "zh": "遮阳伞", "en": "parasol" },
  { "zh": "雨伞", "en": "umbrella" },
  { "zh": "小册子", "en": "booklet" },
  { "zh": "乐器", "en": "musical instrument" },
  { "zh": "便携设备", "en": "portable device" },
  { "zh": "耳机", "en": "headphones" },
  { "zh": "VR头显", "en": "VR headset" },
  { "zh": "香烟", "en": "cigarette" },
  { "zh": "烟斗", "en": "pipe" },
  { "zh": "烟雾", "en": "smoke" },
  { "zh": "手杖", "en": "cane" },
  { "zh": "拐杖", "en": "crutch" },
  { "zh": "手铐", "en": "handcuffs" },
  { "zh": "链条", "en": "chains" },
  { "zh": "项圈", "en": "collar" },
  { "zh": "丝带", "en": "ribbons" },
  { "zh": "蝴蝶结", "en": "bow" },
  { "zh": "胸花", "en": "corsage" },
  { "zh": "胸袋方巾", "en": "pocket square" },
  { "zh": "肩章", "en": "epaulettes" }
  ]
  },
  {
  "name": "服装 (Clothing)",
  "tags": [
  { "zh": "制服", "en": "uniform" },
  { "zh": "校服", "en": "school uniform" },
  { "zh": "水手服", "en": "sailor uniform" },
  { "zh": "西装", "en": "suit" },
  { "zh": "燕尾服", "en": "tuxedo" },
  { "zh": "连衣裙", "en": "dress" },
  { "zh": "礼服", "en": "gown" },
  { "zh": "晚礼服", "en": "evening gown" },
  { "zh": "舞会礼服", "en": "ball gown" },
  { "zh": "迷你裙连衣裙", "en": "mini dress" },
  { "zh": "裹身裙", "en": "wrap dress" },
  { "zh": "吊带连衣裙", "en": "strapless dress" },
  { "zh": "哥特萝莉", "en": "gothic lolita" },
  { "zh": "和服", "en": "kimono" },
  { "zh": "浴衣", "en": "yukata" },
  { "zh": "旗袍", "en": "cheongsam" },
  { "zh": "婚纱", "en": "wedding dress" },
  { "zh": "比基尼", "en": "bikini" },
  { "zh": "泳装", "en": "swimsuit" },
  { "zh": "连体泳衣", "en": "one-piece swimsuit" },
  { "zh": "连帽衫", "en": "hoodie" },
  { "zh": "夹克", "en": "jacket" },
  { "zh": "外套", "en": "coat" },
  { "zh": "风衣", "en": "trench coat" },
  { "zh": "羽绒服", "en": "puffer jacket" },
  { "zh": "皮夹克", "en": "leather jacket" },
  { "zh": "牛仔夹克", "en": "denim jacket" },
  { "zh": "铠甲", "en": "armor" },
  { "zh": "T恤", "en": "t-shirt" },
  { "zh": "Polo衫", "en": "polo shirt" },
  { "zh": "衬衫", "en": "shirt" },
  { "zh": "套衫", "en": "blouse" },
  { "zh": "背心", "en": "vest" },
  { "zh": "毛衣", "en": "sweater" },
  { "zh": "开衫", "en": "cardigan" },
  { "zh": "短裙", "en": "skirt" },
  { "zh": "超短裙", "en": "mini skirt" },
  { "zh": "长裙", "en": "maxi skirt" },
  { "zh": "铅笔裙", "en": "pencil skirt" },
  { "zh": "百褶裙", "en": "pleated skirt" },
  { "zh": "长裤", "en": "pants" },
  { "zh": "牛仔裤", "en": "jeans" },
  { "zh": "短裤", "en": "shorts" },
  { "zh": "热裤", "en": "hotpants" },
  { "zh": "工装裤", "en": "cargo pants" },
  { "zh": "打底裤", "en": "leggings" },
  { "zh": "背带裤", "en": "overalls" },
  { "zh": "内衣", "en": "underwear" },
  { "zh": "胸罩", "en": "bra" },
  { "zh": "内裤", "en": "panties" },
  { "zh": "丁字裤", "en": "thong" },
  { "zh": "平角内裤", "en": "boxers" },
  { "zh": "紧身衣", "en": "bodysuit" },
  { "zh": "睡衣", "en": "pajamas" },
  { "zh": "围裙", "en": "apron" },
  { "zh": "长袍", "en": "robe" },
  { "zh": "斗篷", "en": "cape" },
  { "zh": "休闲装", "en": "casual wear" },
  { "zh": "正装", "en": "formal wear" },
  { "zh": "运动服", "en": "sportswear" },
  { "zh": "运动衫", "en": "sweatshirt" },
  { "zh": "运动裤", "en": "sweatpants" },
  { "zh": "透明衣物", "en": "transparent clothing" },
  { "zh": "蕾丝", "en": "lace" },
  { "zh": "破烂的衣服", "en": "ripped clothing" },
  { "zh": "束身衣", "en": "corset" },
  { "zh": "吊袜带", "en": "garter belt" },
  { "zh": "吊带裙", "en": "slip dress" },
  { "zh": "睡袍", "en": "nightgown" },
  { "zh": "睡裙", "en": "lingerie dress" },
  { "zh": "网格衣物", "en": "mesh clothing" },
  { "zh": "皮革衣物", "en": "leather clothing" },
  { "zh": "丝绸衣物", "en": "silk clothing" },
  { "zh": "棉质衣物", "en": "cotton clothing" },
  { "zh": "羊毛衣物", "en": "wool clothing" },
  { "zh": "针织衣物", "en": "knitwear" },
  { "zh": "露背装", "en": "backless" },
  { "zh": "露肩装", "en": "off-shoulder" },
  { "zh": "单肩装", "en": "one-shoulder" },
  { "zh": "深V领", "en": "cleavage" },
  { "zh": "低胸", "en": "low cut" },
  { "zh": "露脐装", "en": "midriff" },
  { "zh": "无袖", "en": "sleeveless" },
  { "zh": "短袖", "en": "short sleeves" },
  { "zh": "长袖", "en": "long sleeves" },
  { "zh": "蓬蓬袖", "en": "puffy sleeves" },
  { "zh": "喇叭袖", "en": "bell sleeves" },
  { "zh": "超短上衣", "en": "crop top" },
  { "zh": "鱼尾裙", "en": "mermaid dress" },
  { "zh": "洛丽塔", "en": "lolita fashion" },
  { "zh": "哥特", "en": "gothic (fashion)" },
  { "zh": "朋克", "en": "punk (fashion)" },
  { "zh": "蒸汽朋克", "en": "steampunk" },
  { "zh": "日本传统服饰", "en": "japanese traditional clothing" },
  { "zh": "中国传统服饰", "en": "chinese traditional clothing" },
  { "zh": "民族服饰", "en": "folk costume" },
  { "zh": "女管家服", "en": "housewife apron" },
  { "zh": "兔女郎装", "en": "bunny suit" },
  { "zh": "猫女郎装", "en": "cat suit" },
  { "zh": "圣诞服", "en": "santa outfit" },
  { "zh": "万圣节服装", "en": "halloween costume" },
  { "zh": "角色扮演", "en": "cosplay" },
  { "zh": "斗篷", "en": "cloak" },
  { "zh": "腰包", "en": "fanny pack" }
  ]
  },
  {
  "name": "鞋帽 (Footwear/Headwear)",
  "tags": [
  { "zh": "帽子", "en": "hat" },
  { "zh": "棒球帽", "en": "baseball cap" },
  { "zh": "贝雷帽", "en": "beret" },
  { "zh": "毛线帽", "en": "beanie" },
  { "zh": "宽边帽", "en": "sun hat" },
  { "zh": "草帽", "en": "straw hat" },
  { "zh": "礼帽", "en": "fedora" },
  { "zh": "高顶礼帽", "en": "top hat" },
  { "zh": "牛仔帽", "en": "cowboy hat" },
  { "zh": "头盔", "en": "helmet" },
  { "zh": "皇冠", "en": "crown" },
  { "zh": "头饰", "en": "tiara" },
  { "zh": "头巾", "en": "headscarf" },
  { "zh": "面纱", "en": "veil" },
  { "zh": "发带", "en": "bandana" },
  { "zh": "鞋子", "en": "shoes" },
  { "zh": "运动鞋", "en": "sneakers" },
  { "zh": "靴子", "en": "boots" },
  { "zh": "高跟鞋", "en": "high heels" },
  { "zh": "细高跟", "en": "stiletto heels" },
  { "zh": "坡跟鞋", "en": "wedge heels" },
  { "zh": "厚底鞋", "en": "platform shoes" },
  { "zh": "凉鞋", "en": "sandals" },
  { "zh": "平底鞋", "en": "flats" },
  { "zh": "芭蕾舞鞋", "en": "ballet flats" },
  { "zh": "乐福鞋", "en": "loafers" },
  { "zh": "牛津鞋", "en": "oxford shoes" },
  { "zh": "拖鞋", "en": "slippers" },
  { "zh": "木屐", "en": "clogs" },
  { "zh": "袜子", "en": "socks" },
  { "zh": "短袜", "en": "ankle socks" },
  { "zh": "中筒袜", "en": "crew socks" },
  { "zh": "过膝袜", "en": "thighhighs" },
  { "zh": "长筒袜", "en": "stockings" },
  { "zh": "连裤袜", "en": "pantyhose" },
  { "zh": "渔网袜", "en": "fishnets" },
  { "zh": "赤脚", "en": "bare feet" },
  { "zh": "脚趾分开", "en": "separated toes" },
  { "zh": "脚链", "en": "anklet" },
  { "zh": "足部特写", "en": "feet focus" },
  { "zh": "包头鞋", "en": "closed-toe shoes" },
  { "zh": "露趾鞋", "en": "open-toe shoes" },
  { "zh": "罗马凉鞋", "en": "gladiator sandals" },
  { "zh": "雪地靴", "en": "snow boots" },
  { "zh": "皮靴", "en": "leather boots" },
  { "zh": "雨靴", "en": "rain boots" },
  { "zh": "运动靴", "en": "athletic boots" },
  { "zh": "登山靴", "en": "hiking boots" },
  { "zh": "舞鞋", "en": "dance shoes" },
  { "zh": "旱冰鞋", "en": "rollerblades" },
  { "zh": "溜冰鞋", "en": "ice skates" },
  { "zh": "袜子", "en": "hosiery" },
  { "zh": "脚蹼", "en": "flippers" }
  ]
  },
  {
  "name": "姿势 (Poses)",
  "tags": [
  { "zh": "站立", "en": "standing" },
  { "zh": "坐着", "en": "sitting" },
  { "zh": "躺着", "en": "lying" },
  { "zh": "蹲着", "en": "crouching" },
  { "zh": "跪着", "en": "kneeling" },
  { "zh": "靠着", "en": "leaning" },
  { "zh": "弓着腰", "en": "bending over" },
  { "zh": "双腿交叉", "en": "legs crossed" },
  { "zh": "盘腿", "en": "cross-legged" },
  { "zh": "看向观众", "en": "looking at viewer" },
  { "zh": "回头看", "en": "looking back" },
  { "zh": "仰视", "en": "looking up at viewer" },
  { "zh": "俯视", "en": "looking down at viewer" },
  { "zh": "举手", "en": "raising hands" },
  { "zh": "手插在口袋里", "en": "hands in pockets" },
  { "zh": "抱胸", "en": "arms crossed" },
  { "zh": "叉腰", "en": "hands on hips" },
  { "zh": "双手背后", "en": "hands behind back" },
  { "zh": "敬礼", "en": "saluting" },
  { "zh": "鞠躬", "en": "bowing" },
  { "zh": "单膝跪地", "en": "one knee" },
  { "zh": "摆姿势", "en": "posing" },
  { "zh": "V字手势", "en": "v-sign" },
  { "zh": "侧面", "en": "side profile" },
  { "zh": "背面", "en": "from behind" },
  { "zh": "正面", "en": "front view" },
  { "zh": "特写", "en": "close-up" },
  { "zh": "半身", "en": "half body" },
  { "zh": "全身", "en": "full body" },
  { "zh": "上半身", "en": "upper body" },
  { "zh": "下半身", "en": "lower body" },
  { "zh": "脸部特写", "en": "face focus" },
  { "zh": "远景", "en": "wide shot" },
  { "zh": "中景", "en": "medium shot" },
  { "zh": "高角度", "en": "high angle" },
  { "zh": "低角度", "en": "low angle" },
  { "zh": "动态姿势", "en": "dynamic pose" },
  { "zh": "漂浮", "en": "floating" },
  { "zh": "悬空", "en": "levitating" },
  { "zh": "倒立", "en": "handstand" },
  { "zh": "劈叉", "en": "splits" },
  { "zh": "伸开双臂", "en": "arms outstretched" },
  { "zh": "双手合十", "en": "hands clasped" },
  { "zh": "手托下巴", "en": "hand to chin" },
  { "zh": "手扶脸颊", "en": "hand on cheek" },
  { "zh": "手搭肩", "en": "hand on shoulder" },
  { "zh": "手在胸前", "en": "hands on chest" },
  { "zh": "手在身后", "en": "hands behind back" },
  { "zh": "摸头", "en": "touching head" },
  { "zh": "摸脸", "en": "touching face" },
  { "zh": "抓头发", "en": "grabbing hair" },
  { "zh": "搔头", "en": "scratching head" },
  { "zh": "伸舌头", "en": "sticking out tongue" },
  { "zh": "张开双腿", "en": "spread legs" },
  { "zh": "双膝并拢", "en": "knees together" },
  { "zh": "一字马", "en": "straight leg split" },
  { "zh": "脚踝交叉", "en": "ankles crossed" },
  { "zh": "蜷缩", "en": "curled up" },
  { "zh": "仰卧", "en": "supine" },
  { "zh": "俯卧", "en": "prone" },
  { "zh": "半坐", "en": "half-sitting" },
  { "zh": "盘坐", "en": "lotus position" },
  { "zh": "跪坐", "en": "seiza" },
  { "zh": "歪头", "en": "head tilt" },
  { "zh": "侧卧", "en": "lying on side" },
  { "zh": "背对", "en": "back to viewer" },
  { "zh": "面对", "en": "facing viewer" }
  ]
  },
  {
  "name": "动作 (Actions)",
  "tags": [
  { "zh": "跑步", "en": "running" },
  { "zh": "跳跃", "en": "jumping" },
  { "zh": "超强跳跃", "en": "super jump" },
  { "zh": "跳舞", "en": "dancing" },
  { "zh": "走路", "en": "walking" },
  { "zh": "伸展", "en": "stretching" },
  { "zh": "战斗姿态", "en": "fighting stance" },
  { "zh": "拥抱", "en": "hugging" },
  { "zh": "亲吻", "en": "kissing" },
  { "zh": "手牵手", "en": "holding hands" },
  { "zh": "喝水", "en": "drinking" },
  { "zh": "吃东西", "en": "eating" },
  { "zh": "睡觉", "en": "sleeping" },
  { "zh": "打盹", "en": "napping" },
  { "zh": "游戏", "en": "playing" },
  { "zh": "阅读", "en": "reading" },
  { "zh": "写作", "en": "writing" },
  { "zh": "绘画", "en": "drawing" },
  { "zh": "唱歌", "en": "singing" },
  { "zh": "弹奏乐器", "en": "playing instrument" },
  { "zh": "挥手", "en": "waving" },
  { "zh": "指点", "en": "pointing" },
  { "zh": "伸手", "en": "reaching" },
  { "zh": "爬行", "en": "crawling" },
  { "zh": "游泳", "en": "swimming" },
  { "zh": "飞行", "en": "flying" },
  { "zh": "打架", "en": "fighting" },
  { "zh": "攻击", "en": "attacking" },
  { "zh": "防御", "en": "defending" },
  { "zh": "施法", "en": "casting spell" },
  { "zh": "烹饪", "en": "cooking" },
  { "zh": "烘焙", "en": "baking" },
  { "zh": "清洁", "en": "cleaning" },
  { "zh": "工作", "en": "working" },
  { "zh": "学习", "en": "studying" },
  { "zh": "冥想", "en": "meditating" },
  { "zh": "携带", "en": "carrying" },
  { "zh": "举起", "en": "lifting" },
  { "zh": "推", "en": "pushing" },
  { "zh": "拉", "en": "pulling" },
  { "zh": "投掷", "en": "throwing" },
  { "zh": "接住", "en": "catching" },
  { "zh": "踢", "en": "kicking" },
  { "zh": "出拳", "en": "punching" },
  { "zh": "攀爬", "en": "climbing" },
  { "zh": "下降", "en": "falling" },
  { "zh": "滑行", "en": "sliding" },
  { "zh": "倾听", "en": "listening" },
  { "zh": "交谈", "en": "talking" },
  { "zh": "聊天", "en": "chatting" },
  { "zh": "耳语", "en": "whispering" },
  { "zh": "喊叫", "en": "shouting" },
  { "zh": "微笑", "en": "smiling" },
  { "zh": "哭泣", "en": "weeping" },
  { "zh": "颤抖", "en": "trembling" },
  { "zh": "抓紧", "en": "clutching" },
  { "zh": "跺脚", "en": "stomping" },
  { "zh": "假装", "en": "posing (action)" },
  { "zh": "挥舞", "en": "wielding" },
  { "zh": "鞠躬", "en": "curtseying" },
  { "zh": "滑板", "en": "skateboarding" },
  { "zh": "驾驶", "en": "driving" },
  { "zh": "骑行", "en": "riding" },
  { "zh": "冲浪", "en": "surfing" },
  { "zh": "潜水", "en": "diving" },
  { "zh": "钓鱼", "en": "fishing" },
  { "zh": "烘烤", "en": "toasting" },
  { "zh": "园艺", "en": "gardening" },
  { "zh": "缝纫", "en": "sewing" },
  { "zh": "编织", "en": "knitting" },
  { "zh": "冥想", "en": "contemplating" },
  { "zh": "打字", "en": "typing" },
  { "zh": "刷牙", "en": "brushing teeth" },
  { "zh": "洗澡", "en": "bathing" },
  { "zh": "淋浴", "en": "showering" },
  { "zh": "购物", "en": "shopping" },
  { "zh": "散步", "en": "strolling" },
  { "zh": "庆祝", "en": "celebrating" },
  { "zh": "跳绳", "en": "skipping rope" }
  ]
  },
  {
  "name": "环境 (Environment)",
  "tags": [
  { "zh": "室内", "en": "indoors" },
  { "zh": "室外", "en": "outdoors" },
  { "zh": "房间", "en": "room" },
  { "zh": "卧室", "en": "bedroom" },
  { "zh": "客厅", "en": "living room" },
  { "zh": "厨房", "en": "kitchen" },
  { "zh": "浴室", "en": "bathroom" },
  { "zh": "办公室", "en": "office" },
  { "zh": "学校", "en": "school" },
  { "zh": "教室", "en": "classroom" },
  { "zh": "图书馆", "en": "library" },
  { "zh": "医院", "en": "hospital" },
  { "zh": "商店", "en": "shop" },
  { "zh": "咖啡馆", "en": "cafe" },
  { "zh": "餐厅", "en": "restaurant" },
  { "zh": "酒吧", "en": "bar" },
  { "zh": "舞台", "en": "stage" },
  { "zh": "剧院", "en": "theater" },
  { "zh": "音乐厅", "en": "concert hall" },
  { "zh": "体育馆", "en": "gym" },
  { "zh": "博物馆", "en": "museum" },
  { "zh": "教堂", "en": "church" },
  { "zh": "寺庙", "en": "temple" },
  { "zh": "城堡", "en": "castle" },
  { "zh": "宫殿", "en": "palace" },
  { "zh": "实验室", "en": "laboratory" },
  { "zh": "工厂", "en": "factory" },
  { "zh": "仓库", "en": "warehouse" },
  { "zh": "废墟", "en": "ruins" },
  { "zh": "森林", "en": "forest" },
  { "zh": "树林", "en": "woods" },
  { "zh": "公园", "en": "park" },
  { "zh": "花园", "en": "garden" },
  { "zh": "海滩", "en": "beach" },
  { "zh": "山脉", "en": "mountain" },
  { "zh": "河流", "en": "river" },
  { "zh": "湖泊", "en": "lake" },
  { "zh": "海洋", "en": "ocean" },
  { "zh": "海底", "en": "underwater" },
  { "zh": "沙漠", "en": "desert" },
  { "zh": "雪景", "en": "snowy landscape" },
  { "zh": "冰川", "en": "glacier" },
  { "zh": "瀑布", "en": "waterfall" },
  { "zh": "火山", "en": "volcano" },
  { "zh": "洞穴", "en": "cave" },
  { "zh": "岛屿", "en": "island" },
  { "zh": "农田", "en": "farmland" },
  { "zh": "牧场", "en": "pasture" },
  { "zh": "城市", "en": "city" },
  { "zh": "街道", "en": "street" },
  { "zh": "小巷", "en": "alley" },
  { "zh": "建筑物", "en": "building" },
  { "zh": "摩天大楼", "en": "skyscraper" },
  { "zh": "桥梁", "en": "bridge" },
  { "zh": "屋顶", "en": "rooftop" },
  { "zh": "天台", "en": "balcony" },
  { "zh": "太空", "en": "space" },
  { "zh": "宇宙", "en": "universe" },
  { "zh": "星空", "en": "starry sky" },
  { "zh": "科幻背景", "en": "sci-fi setting" },
  { "zh": "奇幻背景", "en": "fantasy setting" },
  { "zh": "末日废墟", "en": "post-apocalyptic" },
  { "zh": "白天", "en": "day" },
  { "zh": "夜晚", "en": "night" },
  { "zh": "傍晚", "en": "dusk" },
  { "zh": "黎明", "en": "dawn" },
  { "zh": "日出", "en": "sunrise" },
  { "zh": "日落", "en": "sunset" },
  { "zh": "晴天", "en": "sunny" },
  { "zh": "雨天", "en": "rainy" },
  { "zh": "雪天", "en": "snowy" },
  { "zh": "多云", "en": "cloudy" },
  { "zh": "雾蒙蒙", "en": "foggy" },
  { "zh": "彩虹", "en": "rainbow" },
  { "zh": "自然光", "en": "natural light" },
  { "zh": "人造光", "en": "artificial light" },
  { "zh": "灯光", "en": "lighting" },
  { "zh": "阴影", "en": "shadows" },
  { "zh": "聚光灯", "en": "spotlight" },
  { "zh": "霓虹灯", "en": "neon lights" },
  { "zh": "烛光", "en": "candlelight" },
  { "zh": "炉火", "en": "fireplace" },
  { "zh": "全景", "en": "panorama" },
  { "zh": "地平线", "en": "horizon" },
  { "zh": "窗外风景", "en": "view from window" },
  { "zh": "太空站", "en": "space station" },
  { "zh": "月球", "en": "moon" },
  { "zh": "火星", "en": "mars" },
  { "zh": "仙境", "en": "fairyland" },
  { "zh": "梦境", "en": "dreamscape" },
  { "zh": "虚拟现实", "en": "virtual reality" },
  { "zh": "天堂", "en": "heaven" },
  { "zh": "地狱", "en": "hell" },
  { "zh": "荒地", "en": "wasteland" },
  { "zh": "丛林", "en": "jungle" },
  { "zh": "沼泽", "en": "swamp" },
  { "zh": "苔原", "en": "tundra" },
  { "zh": "峡谷", "en": "canyon" },
  { "zh": "悬崖", "en": "cliff" },
  { "zh": "草原", "en": "grassland" },
  { "zh": "农场", "en": "farm" },
  { "zh": "葡萄园", "en": "vineyard" },
  { "zh": "果园", "en": "orchard" },
  { "zh": "乡村", "en": "countryside" },
  { "zh": "郊区", "en": "suburban" },
  { "zh": "码头", "en": "dock" },
  { "zh": "港口", "en": "port" },
  { "zh": "码头", "en": "pier" },
  { "zh": "船上", "en": "on a boat" },
  { "zh": "飞机内", "en": "inside airplane" },
  { "zh": "车内", "en": "inside car" },
  { "zh": "列车内", "en": "inside train" },
  { "zh": "废弃地", "en": "abandoned place" },
  { "zh": "黑暗", "en": "darkness" },
  { "zh": "光明", "en": "light (environment)" },
  { "zh": "蒸汽缭绕", "en": "steamy" },
  { "zh": "烟雾弥漫", "en": "smoggy" },
  { "zh": "尘土飞扬", "en": "dusty" },
  { "zh": "暴风雨", "en": "stormy" },
  { "zh": "闪电", "en": "lightning" },
  { "zh": "薄雾", "en": "mist" },
  { "zh": "朦胧", "en": "hazy" },
  { "zh": "极光", "en": "aurora" },
  { "zh": "晴朗的天空", "en": "clear sky" },
  { "zh": "阴天", "en": "overcast" },
  { "zh": "月光", "en": "moonlight" },
  { "zh": "阳光", "en": "sunlight" },
  { "zh": "斑驳的光影", "en": "dappled light" },
  { "zh": "暖光", "en": "warm light" },
  { "zh": "冷光", "en": "cool light" },
  { "zh": "爆炸", "en": "explosion" },
  { "zh": "火灾", "en": "fire" },
  { "zh": "洪水", "en": "flood" },
  { "zh": "地震", "en": "earthquake" },
  { "zh": "宁静", "en": "serene" },
  { "zh": "喧闹", "en": "bustling" },
  { "zh": "和平", "en": "peaceful" },
  { "zh": "战争", "en": "war torn" },
  { "zh": "危险", "en": "dangerous" },
  { "zh": "荒凉", "en": "desolate" }
  ]
  }
  ]
  });