tagData.push({
  "group": "服装 (Apparel)",
  "categories": [
    {
      "name": "服装类型 (Apparel Type)",
      "tags": [
        { "zh": "休闲服", "en": "casual wear" },
        { "zh": "正装", "en": "formal wear" },
        { "zh": "商务装", "en": "business wear" },
        { "zh": "运动服", "en": "sportswear" },
        { "zh": "居家服", "en": "loungewear" },
        { "zh": "睡衣", "en": "sleepwear" },
        { "zh": "内衣", "en": "underwear" },
        { "zh": "泳装", "en": "swimwear" },
        { "zh": "职业装", "en": "uniforms" },
        { "zh": "工装", "en": "workwear" },
        { "zh": "校服", "en": "school uniform" },
        { "zh": "防护服", "en": "protective clothing" },
        { "zh": "功能服", "en": "functional wear" },
        { "zh": "高级定制", "en": "haute couture" },
        { "zh": "成衣", "en": "ready-to-wear" },
        { "zh": "日常服装", "en": "everyday clothing" },
        { "zh": "户外服装", "en": "outdoor clothing" },
        { "zh": "节日服装", "en": "festive wear" },
        { "zh": "复古服装", "en": "vintage clothing" },
        { "zh": "主题服装", "en": "themed apparel" },
        { "zh": "舞台服装", "en": "stage costume" },
        { "zh": "礼服", "en": "gala attire" },
        { "zh": "民族服装", "en": "ethnic attire" },
        { "zh": "传统服装", "en": "traditional clothing" },
        { "zh": "定制服装", "en": "bespoke clothing" },
        { "zh": "环保服装", "en": "sustainable fashion" },
        { "zh": "智能服装", "en": "smart clothing" },
        { "zh": "孕妇装", "en": "maternity wear" },
        { "zh": "童装", "en": "children's wear" },
        { "zh": "宠物服装", "en": "pet apparel" },
        { "zh": "制服诱惑", "en": "uniform fetish" },
        { "zh": "节日主题", "en": "holiday themed" },
        { "zh": "派对服装", "en": "party wear" },
        { "zh": "晚装", "en": "evening wear" },
        { "zh": "日装", "en": "daywear" },
        { "zh": "表演服", "en": "performance costume" },
        { "zh": "cosplay 服装", "en": "cosplay costume" },
        { "zh": "婚纱", "en": "wedding dress" },
        { "zh": "伴娘礼服", "en": "bridesmaid dress" },
        { "zh": "新郎礼服", "en": "groom's attire" },
        { "zh": "滑雪服", "en": "ski suit" },
        { "zh": "潜水服", "en": "wetsuit" }
      ]
    },
    {
      "name": "上装 (Tops)",
      "tags": [
        { "zh": "T恤", "en": "T-shirt" },
        { "zh": "圆领T恤", "en": "crew neck T-shirt" },
        { "zh": "V领T恤", "en": "V-neck T-shirt" },
        { "zh": "亨利领T恤", "en": "Henley T-shirt" },
        { "zh": "Polo衫", "en": "Polo shirt" },
        { "zh": "衬衫", "en": "shirt" },
        { "zh": "牛津衬衫", "en": "Oxford shirt" },
        { "zh": "法兰绒衬衫", "en": "flannel shirt" },
        { "zh": "牛仔衬衫", "en": "denim shirt" },
        { "zh": "格子衬衫", "en": "plaid shirt" },
        { "zh": "条纹衬衫", "en": "striped shirt" },
        { "zh": "印花衬衫", "en": "printed shirt" },
        { "zh": "丝绸衬衫", "en": "silk shirt" },
        { "zh": "棉质衬衫", "en": "cotton shirt" },
        { "zh": "女式衬衫", "en": "blouse" },
        { "zh": "雪纺衫", "en": "chiffon blouse" },
        { "zh": "蕾丝衫", "en": "lace blouse" },
        { "zh": "泡泡袖上衣", "en": "puff sleeve top" },
        { "zh": "针织衫", "en": "knitted top" },
        { "zh": "毛衣", "en": "sweater" },
        { "zh": "圆领毛衣", "en": "crew-neck sweater" },
        { "zh": "V领毛衣", "en": "V-neck sweater" },
        { "zh": "高领毛衣", "en": "turtleneck sweater" },
        { "zh": "开衫", "en": "cardigan" },
        { "zh": "套头衫", "en": "pullover" },
        { "zh": "卫衣", "en": "hoodie" },
        { "zh": "连帽卫衣", "en": "hooded sweatshirt" },
        { "zh": "运动衫", "en": "sweatshirt" },
        { "zh": "背心", "en": "vest (top)" },
        { "zh": "吊带背心", "en": "cami top" },
        { "zh": "无袖上衣", "en": "sleeveless top" },
        { "zh": "作物上衣", "en": "crop top" },
        { "zh": "抹胸", "en": "bandeau top" },
        { "zh": "运动背心", "en": "tank top" },
        { "zh": "套头毛衣", "en": "jumper" },
        { "zh": "马甲", "en": "waistcoat" },
        { "zh": "紧身衣", "en": "bodysuit" },
        { "zh": "短袖", "en": "short sleeve" },
        { "zh": "长袖", "en": "long sleeve" },
        { "zh": "七分袖", "en": "three-quarter sleeve" },
        { "zh": "泡泡袖", "en": "puff sleeve" },
        { "zh": "喇叭袖", "en": "bell sleeve" },
        { "zh": "蝙蝠袖", "en": "batwing sleeve" },
        { "zh": "插肩袖", "en": "raglan sleeve" },
        { "zh": "落肩袖", "en": "dropped shoulder" },
        { "zh": "无袖", "en": "sleeveless" },
        { "zh": "露肩", "en": "off-shoulder" },
        { "zh": "单肩", "en": "one-shoulder" },
        { "zh": "露脐", "en": "belly-baring" },
        { "zh": "裹身", "en": "wrap style" },
        { "zh": "系带", "en": "tie-front" },
        { "zh": "镂空", "en": "cut-out details" },
        { "zh": "透视装", "en": "sheer top" },
        { "zh": "褶皱细节", "en": "ruffled details" },
        { "zh": "刺绣上衣", "en": "embroidered top" },
        { "zh": "拼接设计", "en": "patchwork top" },
        { "zh": "流苏装饰", "en": "fringe top" },
        { "zh": "亮片上衣", "en": "sequin top" },
        { "zh": "露背上衣", "en": "backless top" },
        { "zh": "翻领上衣", "en": "collared top" },
        { "zh": "不对称领口", "en": "asymmetrical neckline" },
        { "zh": "短款上衣", "en": "cropped top" },
        { "zh": "长款上衣", "en": "tunic top" },
        { "zh": "超大号上衣", "en": "oversized top" },
        { "zh": "紧身上衣", "en": "bodycon top" }
      ]
    },
    {
      "name": "下装 (Bottoms)",
      "tags": [
        { "zh": "裤子", "en": "pants" },
        { "zh": "牛仔裤", "en": "jeans" },
        { "zh": "直筒牛仔裤", "en": "straight-leg jeans" },
        { "zh": "修身牛仔裤", "en": "skinny jeans" },
        { "zh": "阔腿牛仔裤", "en": "wide-leg jeans" },
        { "zh": "靴型牛仔裤", "en": "bootcut jeans" },
        { "zh": "高腰牛仔裤", "en": "high-waisted jeans" },
        { "zh": "低腰牛仔裤", "en": "low-rise jeans" },
        { "zh": "破洞牛仔裤", "en": "distressed jeans" },
        { "zh": "锥形裤", "en": "tapered pants" },
        { "zh": "阔腿裤", "en": "wide-leg pants" },
        { "zh": "烟管裤", "en": "cigarette pants" },
        { "zh": "休闲裤", "en": "casual pants" },
        { "zh": "西裤", "en": "dress pants" },
        { "zh": "卡其裤", "en": "khakis" },
        { "zh": "运动裤", "en": "track pants" },
        { "zh": "瑜伽裤", "en": "yoga pants" },
        { "zh": "打底裤", "en": "leggings" },
        { "zh": "运动打底裤", "en": "athletic leggings" },
        { "zh": "短裤", "en": "shorts" },
        { "zh": "牛仔短裤", "en": "denim shorts" },
        { "zh": "运动短裤", "en": "athletic shorts" },
        { "zh": "百慕大短裤", "en": "Bermuda shorts" },
        { "zh": "裙子", "en": "skirt" },
        { "zh": "迷你裙", "en": "mini skirt" },
        { "zh": "铅笔裙", "en": "pencil skirt" },
        { "zh": "A字裙", "en": "A-line skirt" },
        { "zh": "百褶裙", "en": "pleated skirt" },
        { "zh": "伞裙", "en": "circle skirt" },
        { "zh": "中长裙", "en": "midi skirt" },
        { "zh": "长裙", "en": "maxi skirt" },
        { "zh": "牛仔裙", "en": "denim skirt" },
        { "zh": "裹身裙", "en": "wrap skirt" },
        { "zh": "开衩裙", "en": "slit skirt" },
        { "zh": "鱼尾裙", "en": "mermaid skirt" },
        { "zh": "背带裤", "en": "overalls" },
        { "zh": "连体裤", "en": "jumpsuit" },
        { "zh": "连体短裤", "en": "romper" },
        { "zh": "工装裤", "en": "cargo pants" },
        { "zh": "哈伦裤", "en": "harem pants" },
        { "zh": "束脚裤", "en": "joggers" },
        { "zh": "冲锋裤", "en": "shell pants" },
        { "zh": "雪裤", "en": "snow pants" },
        { "zh": "滑雪裤", "en": "ski pants" },
        { "zh": "沙滩裤", "en": "board shorts" },
        { "zh": "裙裤", "en": "culottes" },
        { "zh": "灯笼裤", "en": "bloomers" },
        { "zh": "骑马裤", "en": "breeches" },
        { "zh": "紧身裙", "en": "bodycon skirt" },
        { "zh": "层叠裙", "en": "tiered skirt" },
        { "zh": "不对称裙摆", "en": "asymmetrical hem skirt" },
        { "zh": "流苏裙", "en": "fringe skirt" },
        { "zh": "拼接裤", "en": "patchwork pants" },
        { "zh": "纸袋裤", "en": "paperbag waist pants" },
        { "zh": "九分裤", "en": "cropped pants" },
        { "zh": "七分裤", "en": "capri pants" },
        { "zh": "微喇裤", "en": "flare pants" },
        { "zh": "运动裙", "en": "skort (skirt with shorts underneath)" },
        { "zh": "皮革裙", "en": "leather skirt" },
        { "zh": "丝绸半裙", "en": "silk midi skirt" }
      ]
    },
    {
      "name": "外衣 (Outerwear)",
      "tags": [
        { "zh": "夹克", "en": "jacket" },
        { "zh": "皮夹克", "en": "leather jacket" },
        { "zh": "牛仔夹克", "en": "denim jacket" },
        { "zh": "轰炸机夹克", "en": "bomber jacket" },
        { "zh": "派克大衣", "en": "parka" },
        { "zh": "羽绒服", "en": "down jacket" },
        { "zh": "风衣", "en": "trench coat" },
        { "zh": "大衣", "en": "coat" },
        { "zh": "羊毛大衣", "en": "wool coat" },
        { "zh": "薄大衣", "en": "light coat" },
        { "zh": "西装外套", "en": "blazer" },
        { "zh": "雨衣", "en": "raincoat" },
        { "zh": "防风夹克", "en": "windbreaker" },
        { "zh": "滑雪夹克", "en": "ski jacket" },
        { "zh": "冲锋衣", "en": "hardshell jacket" },
        { "zh": "运动夹克", "en": "sports jacket" },
        { "zh": "马甲", "en": "vest (outerwear)" },
        { "zh": "羽绒马甲", "en": "puffer vest" },
        { "zh": "斗篷", "en": "cape" },
        { "zh": "披肩", "en": "shawl" },
        { "zh": "雨披", "en": "poncho" },
        { "zh": "开衫 (厚)", "en": "thick cardigan" },
        { "zh": "羊羔绒外套", "en": "sherpa jacket" },
        { "zh": "飞行夹克", "en": "flight jacket" },
        { "zh": "机车夹克", "en": "biker jacket" },
        { "zh": "教练夹克", "en": "coach jacket" },
        { "zh": "户外背心", "en": "outdoor vest" },
        { "zh": "钓鱼背心", "en": "fishing vest" },
        { "zh": "狩猎背心", "en": "hunting vest" },
        { "zh": "衬衫夹克", "en": "shacket" },
        { "zh": "束腰大衣", "en": "belted coat" },
        { "zh": "双排扣大衣", "en": "double-breasted coat" },
        { "zh": "单排扣大衣", "en": "single-breasted coat" },
        { "zh": "长款大衣", "en": "long coat" },
        { "zh": "短款夹克", "en": "short jacket" },
        { "zh": "超大号外套", "en": "oversized outerwear" },
        { "zh": "派对外套", "en": "party jacket (e.g., sequined)" },
        { "zh": "定制外套", "en": "tailored jacket" },
        { "zh": "军装外套", "en": "military coat" },
        { "zh": "运动队夹克", "en": "varsity jacket" },
        { "zh": "滑雪服套装", "en": "ski suit" },
        { "zh": "冲浪服", "en": "wetsuit" },
        { "zh": "防晒衣", "en": "sun protective jacket" },
        { "zh": "防水夹克", "en": "waterproof jacket" },
        { "zh": "防风夹克", "en": "windproof jacket" },
        { "zh": "透气外套", "en": "breathable outerwear" },
        { "zh": "绝缘外套", "en": "insulated jacket" },
        { "zh": "马球大衣", "en": "polo coat" },
        { "zh": "切斯特菲尔德大衣", "en": "Chesterfield coat" },
        { "zh": "卡班大衣", "en": "pea coat" },
        { "zh": "牛角扣大衣", "en": "duffel coat" }
      ]
    },
    {
      "name": "连衣裙类 (Dresses & Gowns)",
      "tags": [
        { "zh": "连衣裙", "en": "dress" },
        { "zh": "迷你连衣裙", "en": "mini dress" },
        { "zh": "中长连衣裙", "en": "midi dress" },
        { "zh": "长连衣裙", "en": "maxi dress" },
        { "zh": "A字连衣裙", "en": "A-line dress" },
        { "zh": "铅笔连衣裙", "en": "pencil dress" },
        { "zh": "紧身连衣裙", "en": "bodycon dress" },
        { "zh": "裹身连衣裙", "en": "wrap dress" },
        { "zh": "吊带连衣裙", "en": "slip dress" },
        { "zh": "衬衫连衣裙", "en": "shirt dress" },
        { "zh": "毛衣连衣裙", "en": "sweater dress" },
        { "zh": "T恤连衣裙", "en": "T-shirt dress" },
        { "zh": "运动连衣裙", "en": "athletic dress" },
        { "zh": "休闲连衣裙", "en": "casual dress" },
        { "zh": "晚礼服", "en": "evening gown" },
        { "zh": "舞会礼服", "en": "ball gown" },
        { "zh": "鸡尾酒裙", "en": "cocktail dress" },
        { "zh": "伴娘礼服", "en": "bridesmaid dress" },
        { "zh": "婚纱", "en": "wedding dress" },
        { "zh": "沙滩裙", "en": "beach dress" },
        { "zh": "露肩连衣裙", "en": "off-shoulder dress" },
        { "zh": "单肩连衣裙", "en": "one-shoulder dress" },
        { "zh": "V领连衣裙", "en": "V-neck dress" },
        { "zh": "圆领连衣裙", "en": "crew neck dress" },
        { "zh": "高领连衣裙", "en": "turtleneck dress" },
        { "zh": "无袖连衣裙", "en": "sleeveless dress" },
        { "zh": "长袖连衣裙", "en": "long sleeve dress" },
        { "zh": "泡泡袖连衣裙", "en": "puff sleeve dress" },
        { "zh": "蕾丝连衣裙", "en": "lace dress" },
        { "zh": "丝绸连衣裙", "en": "silk dress" },
        { "zh": "雪纺连衣裙", "en": "chiffon dress" },
        { "zh": "印花连衣裙", "en": "printed dress" },
        { "zh": "条纹连衣裙", "en": "striped dress" },
        { "zh": "纯色连衣裙", "en": "solid color dress" },
        { "zh": "吊带裙", "en": "spaghetti strap dress" },
        { "zh": "背心裙", "en": "tank dress" },
        { "zh": "荷叶边连衣裙", "en": "ruffle dress" },
        { "zh": "叠穿连衣裙", "en": "layered dress" },
        { "zh": "露背连衣裙", "en": "backless dress" },
        { "zh": "开衩连衣裙", "en": "slit dress" },
        { "zh": "不对称连衣裙", "en": "asymmetrical dress" },
        { "zh": "鱼尾裙", "en": "mermaid-style dress" },
        { "zh": "公主线连衣裙", "en": "princess-seam dress" },
        { "zh": "复古连衣裙", "en": "vintage-style dress" },
        { "zh": "波西米亚风连衣裙", "en": "bohemian dress" },
        { "zh": "蓬蓬裙", "en": "tutu dress" },
        { "zh": "衬裙", "en": "petticoat dress" },
        { "zh": "抹胸连衣裙", "en": "strapless dress" },
        { "zh": "削肩连衣裙", "en": "halter-neck dress" },
        { "zh": "镂空连衣裙", "en": "cut-out dress" }
      ]
    },
    {
      "name": "内衣/贴身衣物 (Intimates & Underwear)",
      "tags": [
        { "zh": "文胸", "en": "bra" },
        { "zh": "无钢圈文胸", "en": "wire-free bra" },
        { "zh": "运动文胸", "en": "sports bra" },
        { "zh": "内裤", "en": "panties" },
        { "zh": "丁字裤", "en": "thong" },
        { "zh": "平角裤", "en": "boyshorts" },
        { "zh": "比基尼内裤", "en": "bikini briefs" },
        { "zh": "舒适内裤", "en": "comfortable underwear" },
        { "zh": "男士内裤", "en": "men's briefs" },
        { "zh": "平角内裤", "en": "boxer briefs" },
        { "zh": "四角内裤", "en": "boxer shorts" },
        { "zh": "蕾丝内衣", "en": "lace lingerie" },
        { "zh": "丝绸内衣", "en": "silk lingerie" },
        { "zh": "睡袍", "en": "robe" },
        { "zh": "睡衣套装", "en": "pajama set" },
        { "zh": "睡裙", "en": "nightgown" },
        { "zh": "吊带睡裙", "en": "chemise" },
        { "zh": "连体袜", "en": "bodystocking" },
        { "zh": "吊带袜", "en": "garter belt" },
        { "zh": "束身衣", "en": "corset" },
        { "zh": "塑身衣", "en": "shapewear" },
        { "zh": "保暖内衣", "en": "thermal underwear" },
        { "zh": "打底衫", "en": "base layer top" },
        { "zh": "打底裤", "en": "base layer bottom" },
        { "zh": "连体内衣", "en": "bodysuit (intimates)" },
        { "zh": "情趣内衣", "en": "erotic lingerie" },
        { "zh": "透明内衣", "en": "sheer lingerie" },
        { "zh": "网状内衣", "en": "fishnet lingerie" },
        { "zh": "性感内衣", "en": "sexy lingerie" },
        { "zh": "棉质内衣", "en": "cotton underwear" },
        { "zh": "调整型内衣", "en": "shaping bra" },
        { "zh": "聚拢型文胸", "en": "push-up bra" },
        { "zh": "无肩带文胸", "en": "strapless bra" },
        { "zh": "无痕内裤", "en": "seamless underwear" },
        { "zh": "生理裤", "en": "period underwear" },
        { "zh": "泳裤", "en": "swim briefs" },
        { "zh": "泳衣", "en": "swimsuit" },
        { "zh": "比基尼", "en": "bikini" },
        { "zh": "连体泳衣", "en": "one-piece swimsuit" },
        { "zh": "死库水", "en": "Japanese school swimsuit" },
        { "zh": "三角裤", "en": "briefs (men's)" },
        { "zh": "连裤袜", "en": "pantyhose" },
        { "zh": "渔网袜", "en": "fishnet tights/stockings" },
        { "zh": "情趣丝袜", "en": "erotic stockings" },
        { "zh": "乳贴", "en": "nipple covers" },
        { "zh": "硅胶胸贴", "en": "silicone pasties" }
      ]
    },
    {
      "name": "配饰 (Accessories)",
      "tags": [
        { "zh": "帽子", "en": "hat" },
        { "zh": "棒球帽", "en": "baseball cap" },
        { "zh": "毛线帽", "en": "beanie" },
        { "zh": "宽边帽", "en": "wide-brimmed hat" },
        { "zh": "鸭舌帽", "en": "flat cap" },
        { "zh": "草帽", "en": "straw hat" },
        { "zh": "渔夫帽", "en": "bucket hat" },
        { "zh": "贝雷帽", "en": "beret" },
        { "zh": "礼帽", "en": "fedora" },
        { "zh": "围巾", "en": "scarf" },
        { "zh": "羊绒围巾", "en": "cashmere scarf" },
        { "zh": "丝巾", "en": "silk scarf" },
        { "zh": "披肩", "en": "wrap" },
        { "zh": "手套", "en": "gloves" },
        { "zh": "皮手套", "en": "leather gloves" },
        { "zh": "针织手套", "en": "knitted gloves" },
        { "zh": "腰带", "en": "belt" },
        { "zh": "皮带", "en": "leather belt" },
        { "zh": "编织腰带", "en": "braided belt" },
        { "zh": "包袋", "en": "bag" },
        { "zh": "手提包", "en": "handbag" },
        { "zh": "斜挎包", "en": "crossbody bag" },
        { "zh": "背包", "en": "backpack" },
        { "zh": "旅行包", "en": "travel bag" },
        { "zh": "单肩包", "en": "shoulder bag" },
        { "zh": "钱包", "en": "wallet" },
        { "zh": "卡包", "en": "card holder" },
        { "zh": "首饰", "en": "jewelry" },
        { "zh": "项链", "en": "necklace" },
        { "zh": "耳环", "en": "earrings" },
        { "zh": "手镯", "en": "bracelet" },
        { "zh": "戒指", "en": "ring" },
        { "zh": "手表", "en": "watch" },
        { "zh": "领带", "en": "tie" },
        { "zh": "领结", "en": "bow tie" },
        { "zh": "袜子", "en": "socks" },
        { "zh": "短袜", "en": "ankle socks" },
        { "zh": "船袜", "en": "no-show socks" },
        { "zh": "高筒袜", "en": "knee-high socks" },
        { "zh": "连裤袜", "en": "tights" },
        { "zh": "墨镜", "en": "sunglasses" },
        { "zh": "眼镜", "en": "glasses" },
        { "zh": "发饰", "en": "hair accessory" },
        { "zh": "发夹", "en": "hair clip" },
        { "zh": "发箍", "en": "headband" },
        { "zh": "发圈", "en": "scrunchie" },
        { "zh": "手帕", "en": "handkerchief" },
        { "zh": "胸针", "en": "brooch" },
        { "zh": "胸花", "en": "lapel pin" },
        { "zh": "袖扣", "en": "cufflinks" },
        { "zh": "领带夹", "en": "tie clip" },
        { "zh": "怀表", "en": "pocket watch" },
        { "zh": "吊坠", "en": "pendant" },
        { "zh": "链条", "en": "chain" },
        { "zh": "脚链", "en": "anklet" },
        { "zh": "身体链", "en": "body chain" },
        { "zh": "纹身", "en": "tattoo" },
        { "zh": "身体彩绘", "en": "body paint" },
        { "zh": "穿孔饰品", "en": "piercing jewelry" },
        { "zh": "手链", "en": "charm bracelet" },
        { "zh": "护腕", "en": "wristband" },
        { "zh": "腕带", "en": "sweatband" },
        { "zh": "头巾", "en": "bandana" },
        { "zh": "手套 (时尚)", "en": "fashion gloves" },
        { "zh": "伞", "en": "umbrella" },
        { "zh": "扇子", "en": "fan" },
        { "zh": "面纱", "en": "veil" },
        { "zh": "假领", "en": "false collar" },
        { "zh": "可拆卸领子", "en": "detachable collar" },
        { "zh": "装饰性肩章", "en": "decorative epaulets" },
        { "zh": "丝带", "en": "ribbon" },
        { "zh": "羽毛装饰", "en": "feather embellishment" },
        { "zh": "口罩", "en": "face mask (fashion)" },
        { "zh": "眼镜链", "en": "glasses chain" },
        { "zh": "钥匙扣", "en": "keychain" },
        { "zh": "钱夹", "en": "money clip" },
        { "zh": "手帕方巾", "en": "pocket square" }
      ]
    },
    {
      "name": "鞋履 (Footwear)",
      "tags": [
        { "zh": "运动鞋", "en": "sneakers" },
        { "zh": "跑鞋", "en": "running shoes" },
        { "zh": "篮球鞋", "en": "basketball shoes" },
        { "zh": "休闲鞋", "en": "casual shoes" },
        { "zh": "板鞋", "en": "skate shoes" },
        { "zh": "帆布鞋", "en": "canvas shoes" },
        { "zh": "皮鞋", "en": "leather shoes" },
        { "zh": "正装皮鞋", "en": "dress shoes" },
        { "zh": "牛津鞋", "en": "Oxford shoes" },
        { "zh": "布洛克鞋", "en": "Brogue shoes" },
        { "zh": "乐福鞋", "en": "loafers" },
        { "zh": "船鞋", "en": "boat shoes" },
        { "zh": "德比鞋", "en": "Derby shoes" },
        { "zh": "孟克鞋", "en": "Monk strap shoes" },
        { "zh": "靴子", "en": "boots" },
        { "zh": "踝靴", "en": "ankle boots" },
        { "zh": "切尔西靴", "en": "Chelsea boots" },
        { "zh": "马丁靴", "en": "Doc Martens" },
        { "zh": "及膝靴", "en": "knee-high boots" },
        { "zh": "过膝靴", "en": "over-the-knee boots" },
        { "zh": "雪地靴", "en": "snow boots" },
        { "zh": "雨靴", "en": "rain boots" },
        { "zh": "工装靴", "en": "work boots" },
        { "zh": "凉鞋", "en": "sandals" },
        { "zh": "平底凉鞋", "en": "flat sandals" },
        { "zh": "坡跟凉鞋", "en": "wedge sandals" },
        { "zh": "高跟鞋", "en": "heels" },
        { "zh": "细高跟鞋", "en": "stiletto heels" },
        { "zh": "方跟鞋", "en": "block heels" },
        { "zh": "坡跟鞋", "en": "wedge heels" },
        { "zh": "芭蕾平底鞋", "en": "ballet flats" },
        { "zh": "拖鞋", "en": "slippers" },
        { "zh": "木屐", "en": "clogs" },
        { "zh": "洞洞鞋", "en": "Crocs" },
        { "zh": "水鞋", "en": "water shoes" },
        { "zh": "高尔夫鞋", "en": "golf shoes" },
        { "zh": "足球鞋", "en": "soccer cleats" },
        { "zh": "人字拖", "en": "flip-flops" },
        { "zh": "厚底鞋", "en": "platform shoes" },
        { "zh": "玛丽珍鞋", "en": "Mary Jane shoes" },
        { "zh": "绑带鞋", "en": "strappy shoes" },
        { "zh": "搭扣鞋", "en": "buckle shoes" },
        { "zh": "系带鞋", "en": "lace-up shoes" },
        { "zh": "搭便鞋", "en": "slip-on shoes" },
        { "zh": "透明鞋", "en": "transparent shoes" },
        { "zh": "发光鞋", "en": "glowing shoes" },
        { "zh": "定制鞋", "en": "customized shoes" },
        { "zh": "老爹鞋", "en": "chunky sneakers" },
        { "zh": "未来科技鞋", "en": "futuristic footwear" },
        { "zh": "穆勒鞋", "en": "mules" },
        { "zh": "渔夫鞋", "en": "espadrilles" },
        { "zh": "罗马凉鞋", "en": "gladiator sandals" },
        { "zh": "猫跟鞋", "en": "kitten heels" },
        { "zh": "运动凉鞋", "en": "sport sandals" },
        { "zh": "软底鞋", "en": "soft-soled shoes" }
      ]
    },
    {
      "name": "面料/材质 (Fabrics & Materials)",
      "tags": [
        { "zh": "棉", "en": "cotton" },
        { "zh": "有机棉", "en": "organic cotton" },
        { "zh": "亚麻", "en": "linen" },
        { "zh": "丝绸", "en": "silk" },
        { "zh": "羊毛", "en": "wool" },
        { "zh": "美利奴羊毛", "en": "merino wool" },
        { "zh": "羊绒", "en": "cashmere" },
        { "zh": "马海毛", "en": "mohair" },
        { "zh": "腈纶", "en": "acrylic" },
        { "zh": "涤纶", "en": "polyester" },
        { "zh": "尼龙", "en": "nylon" },
        { "zh": "氨纶/弹性纤维", "en": "spandex/elastane" },
        { "zh": "人造丝", "en": "rayon" },
        { "zh": "莫代尔", "en": "modal" },
        { "zh": "粘胶纤维", "en": "viscose" },
        { "zh": "竹纤维", "en": "bamboo fiber" },
        { "zh": "皮革", "en": "leather" },
        { "zh": "麂皮", "en": "suede" },
        { "zh": "PU皮", "en": "PU leather" },
        { "zh": "牛仔布", "en": "denim" },
        { "zh": "灯芯绒", "en": "corduroy" },
        { "zh": "法兰绒", "en": "flannel" },
        { "zh": "雪纺", "en": "chiffon" },
        { "zh": "蕾丝", "en": "lace" },
        { "zh": "网眼布", "en": "mesh" },
        { "zh": "薄纱", "en": "tulle" },
        { "zh": "天鹅绒", "en": "velvet" },
        { "zh": "缎面", "en": "satin" },
        { "zh": "针织面料", "en": "knit fabric" },
        { "zh": "梭织面料", "en": "woven fabric" },
        { "zh": "抓绒", "en": "fleece" },
        { "zh": "戈尔特斯 (Gore-Tex)", "en": "Gore-Tex" },
        { "zh": "摇粒绒", "en": "polar fleece" },
        { "zh": "毛呢", "en": "tweed" },
        { "zh": "粗花呢", "en": "bouclé" },
        { "zh": "环保面料", "en": "eco-friendly fabric" },
        { "zh": "回收材料", "en": "recycled material" },
        { "zh": "有机材料", "en": "organic material" },
        { "zh": "半透明面料", "en": "translucent fabric" },
        { "zh": "反光面料", "en": "reflective fabric" },
        { "zh": "防水面料", "en": "waterproof fabric" },
        { "zh": "防风面料", "en": "windproof fabric" },
        { "zh": "透气面料", "en": "breathable fabric" },
        { "zh": "吸湿排汗面料", "en": "moisture-wicking fabric" },
        { "zh": "抗菌面料", "en": "anti-bacterial fabric" },
        { "zh": "抗皱面料", "en": "wrinkle-resistant fabric" },
        { "zh": "弹性面料", "en": "stretch fabric" },
        { "zh": "垂坠感面料", "en": "drapey fabric" },
        { "zh": "硬挺面料", "en": "stiff fabric" },
        { "zh": "柔软面料", "en": "soft fabric" },
        { "zh": "厚重面料", "en": "heavy fabric" },
        { "zh": "轻薄面料", "en": "lightweight fabric" },
        { "zh": "纹理面料", "en": "textured fabric" },
        { "zh": "光滑面料", "en": "smooth fabric" },
        { "zh": "哑光面料", "en": "matte finish fabric" },
        { "zh": "光泽面料", "en": "shiny fabric" },
        { "zh": "混纺面料", "en": "blended fabric" },
        { "zh": "针线面料", "en": "crochet fabric" },
        { "zh": "锦纶", "en": "polyamide" },
        { "zh": "醋酸纤维", "en": "acetate" },
        { "zh": "马德拉斯棉布", "en": "madras cotton" },
        { "zh": "泡泡纱", "en": "seersucker" }
      ]
    },
    {
      "name": "图案/印花 (Patterns & Prints)",
      "tags": [
        { "zh": "纯色", "en": "solid color" },
        { "zh": "条纹", "en": "stripes" },
        { "zh": "细条纹", "en": "pin stripes" },
        { "zh": "粗条纹", "en": "broad stripes" },
        { "zh": "横条纹", "en": "horizontal stripes" },
        { "zh": "竖条纹", "en": "vertical stripes" },
        { "zh": "格纹", "en": "checks" },
        { "zh": "格子图案", "en": "plaid" },
        { "zh": "千鸟格", "en": "houndstooth" },
        { "zh": "苏格兰格子", "en": "tartan" },
        { "zh": "棋盘格", "en": "checkerboard" },
        { "zh": "波点", "en": "polka dots" },
        { "zh": "小波点", "en": "micro dots" },
        { "zh": "大波点", "en": "large dots" },
        { "zh": "花卉印花", "en": "floral print" },
        { "zh": "大花", "en": "large floral prints" },
        { "zh": "小碎花", "en": "small floral prints" },
        { "zh": "佩斯利花纹", "en": "paisley print" },
        { "zh": "几何图案", "en": "geometric pattern" },
        { "zh": "抽象图案", "en": "abstract pattern" },
        { "zh": "动物纹", "en": "animal print" },
        { "zh": "豹纹", "en": "leopard print" },
        { "zh": "斑马纹", "en": "zebra print" },
        { "zh": "蛇纹", "en": "snake print" },
        { "zh": "老虎纹", "en": "tiger print" },
        { "zh": "迷彩", "en": "camouflage" },
        { "zh": "涂鸦", "en": "graffiti print" },
        { "zh": "卡通图案", "en": "cartoon print" },
        { "zh": "照片印花", "en": "photographic print" },
        { "zh": "文字印花", "en": "typography print" },
        { "zh": "Logo图案", "en": "logo pattern" },
        { "zh": "渐变色", "en": "ombré / gradient" },
        { "zh": "扎染", "en": "tie-dye" },
        { "zh": "水洗色", "en": "washed out color" },
        { "zh": "褪色效果", "en": "faded effect" },
        { "zh": "破坏效果", "en": "distressed effect" },
        { "zh": "刺绣图案", "en": "embroidered pattern" },
        { "zh": "提花图案", "en": "jacquard pattern" },
        { "zh": "雕花", "en": "brocade" },
        { "zh": "民族风图案", "en": "ethnic pattern" },
        { "zh": "异域风情图案", "en": "exotic pattern" },
        { "zh": "日式图案", "en": "Japanese pattern" },
        { "zh": "中式图案", "en": "Chinese pattern" },
        { "zh": "数字印花", "en": "digital print" },
        { "zh": "闪光图案", "en": "glitter print" },
        { "zh": "夜光图案", "en": "glow-in-the-dark print" },
        { "zh": "亮片", "en": "sequins" },
        { "zh": "珠饰", "en": "beading" },
        { "zh": "贴花", "en": "appliqué" },
        { "zh": "烫印", "en": "foil print" },
        { "zh": "植绒", "en": "flocking" },
        { "zh": "印花", "en": "print" },
        { "zh": "豹纹印花", "en": "cheetah print" },
        { "zh": "斑点印花", "en": "dot print" },
        { "zh": "泼墨印花", "en": "splatter print" },
        { "zh": "手绘图案", "en": "hand-drawn pattern" },
        { "zh": "三维图案", "en": "3D pattern" },
        { "zh": "编织图案", "en": "knit pattern" }
      ]
    },
    {
      "name": "款式/廓形 (Style & Silhouette)",
      "tags": [
        { "zh": "修身", "en": "slim fit" },
        { "zh": "紧身", "en": "skinny fit" },
        { "zh": "标准版", "en": "regular fit" },
        { "zh": "直筒", "en": "straight fit" },
        { "zh": "宽松", "en": "loose fit" },
        { "zh": "超大号", "en": "oversized" },
        { "zh": "A字型", "en": "A-line" },
        { "zh": "H型", "en": "H-line" },
        { "zh": "X型", "en": "X-line" },
        { "zh": "沙漏型", "en": "hourglass silhouette" },
        { "zh": "箱型", "en": "box fit" },
        { "zh": "裹身式", "en": "wrap style" },
        { "zh": "层叠式", "en": "layered style" },
        { "zh": "拼接式", "en": "patchwork style" },
        { "zh": "不对称", "en": "asymmetrical" },
        { "zh": "结构感", "en": "structured" },
        { "zh": "垂坠感", "en": "draped" },
        { "zh": "褶皱", "en": "pleated" },
        { "zh": "荷叶边", "en": "ruffled" },
        { "zh": "波浪边", "en": "frilly" },
        { "zh": "流苏", "en": "fringe" },
        { "zh": "镂空", "en": "cut-out" },
        { "zh": "透视", "en": "sheer" },
        { "zh": "露背", "en": "backless" },
        { "zh": "露肩", "en": "off-shoulder" },
        { "zh": "单肩", "en": "one-shoulder" },
        { "zh": "高腰", "en": "high-waisted" },
        { "zh": "低腰", "en": "low-rise" },
        { "zh": "中腰", "en": "mid-rise" },
        { "zh": "系带", "en": "tie-waist" },
        { "zh": "收腰", "en": "cinched waist" },
        { "zh": "直筒袖", "en": "straight sleeve" },
        { "zh": "喇叭袖", "en": "bell sleeve" },
        { "zh": "泡泡袖", "en": "puff sleeve" },
        { "zh": "灯笼袖", "en": "lantern sleeve" },
        { "zh": "插肩袖", "en": "raglan sleeve" },
        { "zh": "落肩袖", "en": "drop shoulder" },
        { "zh": "无袖", "en": "sleeveless" },
        { "zh": "吊带", "en": "spaghetti strap" },
        { "zh": "衬衫领", "en": "shirt collar" },
        { "zh": "V领", "en": "V-neck" },
        { "zh": "圆领", "en": "crew neck" },
        { "zh": "高领", "en": "turtleneck" },
        { "zh": "方领", "en": "square neck" },
        { "zh": "U领", "en": "U-neck" },
        { "zh": "领口系带", "en": "tie-neck" },
        { "zh": "翻领", "en": "lapel collar" },
        { "zh": "立领", "en": "mandarin collar" },
        { "zh": "燕尾服领", "en": "shawl collar" },
        { "zh": "西装领", "en": "notched lapel" },
        { "zh": "长款", "en": "long length" },
        { "zh": "短款", "en": "short length" },
        { "zh": "及踝", "en": "ankle length" },
        { "zh": "迷你", "en": "mini length" },
        { "zh": "中长", "en": "midi length" },
        { "zh": "不规则下摆", "en": "asymmetrical hem" },
        { "zh": "开衩", "en": "slit" },
        { "zh": "荷叶边下摆", "en": "flounce hem" },
        { "zh": "纽扣门襟", "en": "button-front" },
        { "zh": "拉链门襟", "en": "zipper-front" },
        { "zh": "套头", "en": "pullover" },
        { "zh": "开襟", "en": "open-front" },
        { "zh": "单排扣", "en": "single-breasted" },
        { "zh": "双排扣", "en": "double-breasted" },
        { "zh": "有口袋", "en": "with pockets" },
        { "zh": "无口袋", "en": "without pockets" },
        { "zh": "装饰性纽扣", "en": "decorative buttons" },
        { "zh": "功能性纽扣", "en": "functional buttons" },
        { "zh": "金属扣", "en": "metal buckles" },
        { "zh": "铆钉", "en": "studs" },
        { "zh": "亮片", "en": "sequins" },
        { "zh": "珠饰", "en": "beads" },
        { "zh": "刺绣", "en": "embroidery" },
        { "zh": "流苏", "en": "tassels" },
        { "zh": "补丁", "en": "patches" },
        { "zh": "破洞", "en": "rips / tears" },
        { "zh": "磨边", "en": "frayed edges" },
        { "zh": "做旧", "en": "distressed look" },
        { "zh": "水洗", "en": "washed effect" },
        { "zh": "复古磨损", "en": "vintage faded" },
        { "zh": "手工制作", "en": "handmade details" },
        { "zh": "公主线裁剪", "en": "princess seam" },
        { "zh": "马鞍肩", "en": "saddle shoulder" },
        { "zh": "立体剪裁", "en": "3D tailoring" },
        { "zh": "裹胸式", "en": "bandeau style" }
      ]
    },
    {
      "name": "颜色 (Colors)",
      "tags": [
        { "zh": "黑色", "en": "black" },
        { "zh": "白色", "en": "white" },
        { "zh": "灰色", "en": "grey" },
        { "zh": "红色", "en": "red" },
        { "zh": "深红", "en": "crimson" },
        { "zh": "酒红", "en": "burgundy" },
        { "zh": "粉色", "en": "pink" },
        { "zh": "藕粉色", "en": "blush pink" },
        { "zh": "玫瑰色", "en": "rose pink" },
        { "zh": "蓝色", "en": "blue" },
        { "zh": "海军蓝", "en": "navy blue" },
        { "zh": "天蓝色", "en": "sky blue" },
        { "zh": "宝蓝色", "en": "royal blue" },
        { "zh": "绿色", "en": "green" },
        { "zh": "墨绿色", "en": "forest green" },
        { "zh": "军绿", "en": "army green" },
        { "zh": "黄色", "en": "yellow" },
        { "zh": "芥末黄", "en": "mustard yellow" },
        { "zh": "柠檬黄", "en": "lemon yellow" },
        { "zh": "橙色", "en": "orange" },
        { "zh": "米色", "en": "beige" },
        { "zh": "棕色", "en": "brown" },
        { "zh": "卡其色", "en": "khaki" },
        { "zh": "紫色", "en": "purple" },
        { "zh": "薰衣草紫", "en": "lavender" },
        { "zh": "金色", "en": "gold" },
        { "zh": "银色", "en": "silver" },
        { "zh": "彩色", "en": "multicolor" },
        { "zh": "霓虹色", "en": "neon colors" },
        { "zh": "马卡龙色", "en": "macaron colors" },
        { "zh": "大地色系", "en": "earth tones" },
        { "zh": "莫兰迪色系", "en": "Morandi colors" },
        { "zh": "柔和色调", "en": "pastel tones" },
        { "zh": "亮色系", "en": "bright colors" },
        { "zh": "深色系", "en": "dark colors" },
        { "zh": "中性色", "en": "neutral colors" },
        { "zh": "撞色", "en": "color block" },
        { "zh": "渐变色", "en": "gradient color" },
        { "zh": "荧光色", "en": "fluorescent colors" },
        { "zh": "金属色", "en": "metallic colors" },
        { "zh": "透明色", "en": "transparent colors" },
        { "zh": "普鲁士蓝", "en": "Prussian blue" },
        { "zh": "祖母绿", "en": "emerald green" },
        { "zh": "珊瑚色", "en": "coral" },
        { "zh": "焦糖色", "en": "caramel" }
      ]
    },
    {
      "name": "风格/主题 (Styles & Themes)",
      "tags": [
        { "zh": "简约风", "en": "minimalist style" },
        { "zh": "街头风", "en": "streetwear style" },
        { "zh": "运动风", "en": "sporty style" },
        { "zh": "复古", "en": "retro style" },
        { "zh": "波西米亚风", "en": "bohemian style" },
        { "zh": "朋克风", "en": "punk style" },
        { "zh": "摇滚风", "en": "rock style" },
        { "zh": "哥特风", "en": "gothic style" },
        { "zh": "休闲风", "en": "casual style" },
        { "zh": "优雅风", "en": "elegant style" },
        { "zh": "甜美风", "en": "sweet style" },
        { "zh": "都市风", "en": "urban style" },
        { "zh": "商务风", "en": "business style" },
        { "zh": "职场风", "en": "office wear style" },
        { "zh": "法式风情", "en": "French chic" },
        { "zh": "英伦风", "en": "British style" },
        { "zh": "日系风", "en": "Japanese style" },
        { "zh": "韩系风", "en": "Korean style" },
        { "zh": "美式休闲", "en": "American casual" },
        { "zh": "未来主义", "en": "futuristic style" },
        { "zh": "赛博朋克", "en": "cyberpunk fashion" },
        { "zh": "蒸汽朋克", "en": "steampunk fashion" },
        { "zh": "军装风", "en": "military style" },
        { "zh": "航海风", "en": "nautical style" },
        { "zh": "田园风", "en": "countryside style" },
        { "zh": "民族风", "en": "ethnic style" },
        { "zh": "异域风情", "en": "exotic style" },
        { "zh": "森林系", "en": "mori kei (forest style)" },
        { "zh": "洛丽塔", "en": "Lolita fashion" },
        { "zh": "Cosplay", "en": "cosplay" },
        { "zh": "舞台装", "en": "stage costume" },
        { "zh": "角色扮演", "en": "role-playing costume" },
        { "zh": "制服诱惑", "en": "uniform sexual appeal" },
        { "zh": "时尚前卫", "en": "avant-garde fashion" },
        { "zh": "高街时尚", "en": "high street fashion" },
        { "zh": "设计师品牌", "en": "designer brand" },
        { "zh": "奢侈品", "en": "luxury fashion" },
        { "zh": "可持续时尚", "en": "sustainable fashion" },
        { "zh": "无性别服饰", "en": "gender-neutral fashion" },
        { "zh": "潮牌", "en": "trendy brand" },
        { "zh": "经典款", "en": "classic style" },
        { "zh": "流行款", "en": "popular style" },
        { "zh": "定制款", "en": "custom-made" },
        { "zh": "二手衣物", "en": "secondhand clothing" },
        { "zh": "改造", "en": "upcycled" },
        { "zh": "手工", "en": "handmade" },
        { "zh": "学院风", "en": "preppy style" },
        { "zh": "芭蕾核心", "en": "balletcore" },
        { "zh": "老钱风", "en": "old money aesthetic" },
        { "zh": "静奢风", "en": "quiet luxury" },
        { "zh": "Y2K 风", "en": "Y2K fashion" },
        { "zh": "哥特萝莉", "en": "Gothic Lolita" },
        { "zh": "滑板风", "en": "skate style" },
        { "zh": "冲浪风", "en": "surf style" },
        { "zh": "工装风", "en": "utility style" },
        { "zh": "极简主义", "en": "minimalism" },
        { "zh": "可持续时尚", "en": "ethical fashion" },
        { "zh": "环保时尚", "en": "eco-fashion" },
        { "zh": "慢时尚", "en": "slow fashion" }
      ]
    }
  ]
});