tagData.push({
  "group": "摄影 (Photography)",
  "categories": [
    {
      "name": "人物 (People and Subjects)",
      "tags": [
        { "zh": "单人肖像", "en": "single portrait" },
        { "zh": "情侣拍摄", "en": "couple photography" },
        { "zh": "家庭合影", "en": "family portrait" },
        { "zh": "集体照", "en": "group photo" },
        { "zh": "新生儿", "en": "newborn" },
        { "zh": "儿童", "en": "child" },
        { "zh": "青少年", "en": "teenager" },
        { "zh": "青年", "en": "young adult" },
        { "zh": "成年人", "en": "adult" },
        { "zh": "中年", "en": "middle-aged person" },
        { "zh": "老年人", "en": "senior" },
        { "zh": "男性", "en": "male" },
        { "zh": "女性", "en": "female" },
        { "zh": "非二元性别", "en": "non-binary" },
        { "zh": "职业模特", "en": "professional model" },
        { "zh": "素人", "en": "non-professional subject" },
        { "zh": "名人/公众人物", "en": "celebrity/public figure" },
        { "zh": "艺术家", "en": "artist" },
        { "zh": "音乐家", "en": "musician" },
        { "zh": "舞者", "en": "dancer" },
        { "zh": "宇航员", "en": "astronaut" },
        { "zh": "运动员", "en": "athlete" },
        { "zh": "学生", "en": "student" },
        { "zh": "游客", "en": "tourist" },
        { "zh": "街头艺人", "en": "street performer" },
        { "zh": "流浪者", "en": "homeless person" },
        { "zh": "工人", "en": "worker" },
        { "zh": "医生/护士", "en": "doctor/nurse" },
        { "zh": "厨师", "en": "chef" },
        { "zh": "冒险家", "en": "adventurer" },
        { "zh": "时尚偶像", "en": "fashion icon" },
        { "zh": "宠物", "en": "pet" },
        { "zh": "野生动物", "en": "wild animal" },
        { "zh": "家畜", "en": "domestic animal" },
        { "zh": "植物（花卉/树木）", "en": "plant (flowers/trees)" },
        { "zh": "昆虫", "en": "insect" },
        { "zh": "鸟类", "en": "bird" },
        { "zh": "海洋生物", "en": "marine life" },
        { "zh": "交通工具", "en": "vehicle" },
        { "zh": "建筑", "en": "architecture" },
        { "zh": "城市景观", "en": "cityscape" },
        { "zh": "自然风光", "en": "natural landscape" },
        { "zh": "抽象形态", "en": "abstract form" },
        { "zh": "食物", "en": "food" },
        { "zh": "产品", "en": "product" },
        { "zh": "人造物品", "en": "man-made object" },
        { "zh": "遗迹", "en": "ruins" },
        { "zh": "肖像主体", "en": "portrait subject" },
        { "zh": "剪影主体", "en": "silhouette subject" }
      ]
    },
    {
      "name": "年龄/阶段 (Age/Life Stage)",
      "tags": [
        { "zh": "新生儿", "en": "newborn" },
        { "zh": "婴儿 (0-1岁)", "en": "infant (0-1 year)" },
        { "zh": "幼儿 (1-3岁)", "en": "toddler (1-3 years)" },
        { "zh": "学龄前儿童 (3-6岁)", "en": "preschooler (3-6 years)" },
        { "zh": "小学生 (6-12岁)", "en": "school-aged child (6-12 years)" },
        { "zh": "青少年/少年 (13-18岁)", "en": "teenager/adolescent (13-18 years)" },
        { "zh": "青年 (18-30岁)", "en": "young adult (18-30 years)" },
        { "zh": "壮年 (30-50岁)", "en": "mid-career adult (30-50 years)" },
        { "zh": "中年 (50-65岁)", "en": "middle-aged adult (50-65 years)" },
        { "zh": "老年 (65岁以上)", "en": "senior (65+ years)" },
        { "zh": "古稀之年 (70岁)", "en": "seventy-something" },
        { "zh": "耄耋之年 (80-90岁)", "en": "eighty-to-ninety-something" },
        { "zh": "百岁老人", "en": "centenarian" },
        { "zh": "童年", "en": "childhood" },
        { "zh": "青春期", "en": "adolescence" },
        { "zh": "退休生活", "en": "retirement life" },
        { "zh": "生命周期", "en": "life cycle" },
        { "zh": "代际关系", "en": "intergenerational bonds" }
      ]
    },
    {
      "name": "特征/情绪 (Characteristics/Emotions)",
      "tags": [
        { "zh": "微笑", "en": "smiling" },
        { "zh": "大笑", "en": "laughing" },
        { "zh": "严肃", "en": "serious" },
        { "zh": "沉思", "en": "pensive/contemplative" },
        { "zh": "闭眼", "en": "eyes closed" },
        { "zh": "直视镜头", "en": "direct gaze" },
        { "zh": "侧面", "en": "side profile" },
        { "zh": "特写面部", "en": "facial close-up" },
        { "zh": "高兴", "en": "happy" },
        { "zh": "悲伤", "en": "sad" },
        { "zh": "愤怒", "en": "angry" },
        { "zh": "惊讶", "en": "surprised" },
        { "zh": "平静", "en": "calm" },
        { "zh": "兴奋", "en": "excited" },
        { "zh": "好奇", "en": "curious" },
        { "zh": "宁静", "en": "serene" },
        { "zh": "自信", "en": "confident" },
        { "zh": "害羞", "en": "shy" },
        { "zh": "忧郁", "en": "melancholic" },
        { "zh": "渴望", "en": "longing" },
        { "zh": "疲惫", "en": "tired" },
        { "zh": "迷茫", "en": "confused" },
        { "zh": "勇敢", "en": "brave" },
        { "zh": "脆弱", "en": "vulnerable" },
        { "zh": "坚定", "en": "determined" },
        { "zh": "迷人", "en": "charming" },
        { "zh": "美丽", "en": "beautiful" },
        { "zh": "英俊", "en": "handsome" },
        { "zh": "独特面孔", "en": "distinctive face" },
        { "zh": "白皙皮肤", "en": "fair skin" },
        { "zh": "健康肤色", "en": "tanned skin" },
        { "zh": "深色皮肤", "en": "dark skin" },
        { "zh": "金发", "en": "blonde hair" },
        { "zh": "黑发", "en": "black hair" },
        { "zh": "棕发", "en": "brunette hair" },
        { "zh": "红发", "en": "red hair" },
        { "zh": "卷发", "en": "curly hair" },
        { "zh": "直发", "en": "straight hair" },
        { "zh": "短发", "en": "short hair" },
        { "zh": "长发", "en": "long hair" },
        { "zh": "脏辫", "en": "dreadlocks" },
        { "zh": "胡须", "en": "beard" },
        { "zh": "胡子", "en": "mustache" },
        { "zh": "雀斑", "en": "freckles" },
        { "zh": "皱纹", "en": "wrinkles" },
        { "zh": "纹身", "en": "tattoos" },
        { "zh": "穿孔", "en": "piercings" },
        { "zh": "疤痕", "en": "scar" },
        { "zh": "眼镜", "en": "glasses" },
        { "zh": "帽子", "en": "hat" },
        { "zh": "珠宝/配饰", "en": "jewelry/accessories" },
        { "zh": "时尚服装", "en": "fashionable attire" },
        { "zh": "休闲装", "en": "casual wear" },
        { "zh": "正装", "en": "formal wear" },
        { "zh": "民族服装", "en": "ethnic attire" },
        { "zh": "制服", "en": "uniform" },
        { "zh": "异域风情", "en": "exotic features" },
        { "zh": "运动型身材", "en": "athletic build" },
        { "zh": "纤细身材", "en": "slim build" },
        { "zh": "健壮身材", "en": "muscular build" },
        { "zh": "健康", "en": "healthy" },
        { "zh": "病态", "en": "sickly" },
        { "zh": "受伤", "en": "injured" },
        { "zh": "残疾", "en": "disabled" },
        { "zh": "特殊需要", "en": "special needs" }
      ]
    },
    {
      "name": "动作/姿态 (Actions/Poses)",
      "tags": [
        { "zh": "站立", "en": "standing" },
        { "zh": "坐姿", "en": "sitting" },
        { "zh": "行走", "en": "walking" },
        { "zh": "奔跑", "en": "running" },
        { "zh": "跳跃", "en": "jumping" },
        { "zh": "舞蹈", "en": "dancing" },
        { "zh": "睡觉", "en": "sleeping" },
        { "zh": "吃饭", "en": "eating" },
        { "zh": "说话", "en": "talking" },
        { "zh": "工作", "en": "working" },
        { "zh": "阅读", "en": "reading" },
        { "zh": "玩耍", "en": "playing" },
        { "zh": "摆姿势", "en": "posing" },
        { "zh": "自然姿态", "en": "natural posture" },
        { "zh": "互动", "en": "interacting" },
        { "zh": "拥抱", "en": "hugging" },
        { "zh": "亲吻", "en": "kissing" },
        { "zh": "举手", "en": "raising hand" },
        { "zh": "指点", "en": "pointing" },
        { "zh": "观察", "en": "observing" },
        { "zh": "思考", "en": "thinking" },
        { "zh": "冥想", "en": "meditating" },
        { "zh": "运动/锻炼", "en": "exercising" },
        { "zh": "烹饪", "en": "cooking" },
        { "zh": "驾驶", "en": "driving" },
        { "zh": "操作设备", "en": "operating equipment" },
        { "zh": "绘画/涂鸦", "en": "drawing/sketching" },
        { "zh": "演奏乐器", "en": "playing an instrument" },
        { "zh": "唱歌", "en": "singing" },
        { "zh": "拍摄", "en": "taking photo" },
        { "zh": "学习", "en": "studying" },
        { "zh": "写作", "en": "writing" },
        { "zh": "演讲", "en": "giving a speech" },
        { "zh": "购物", "en": "shopping" },
        { "zh": "旅行", "en": "traveling" },
        { "zh": "放松", "en": "relaxing" },
        { "zh": "庆祝", "en": "celebrating" },
        { "zh": "攀爬", "en": "climbing" },
        { "zh": "潜水", "en": "diving" },
        { "zh": "游泳", "en": "swimming" },
        { "zh": "跳水", "en": "diving (sport)" },
        { "zh": "滑雪", "en": "skiing" },
        { "zh": "冲浪", "en": "surfing" },
        { "zh": "瑜伽", "en": "doing yoga" },
        { "zh": "打坐", "en": "meditating" },
        { "zh": "等待", "en": "waiting" },
        { "zh": "探险", "en": "exploring" },
        { "zh": "攀岩", "en": "rock climbing" },
        { "zh": "跌倒", "en": "falling" },
        { "zh": "飞行", "en": "flying" },
        { "zh": "漂浮", "en": "floating" },
        { "zh": "动态捕捉", "en": "action shot / in motion" },
        { "zh": "静止姿态", "en": "static pose" },
        { "zh": "俯冲", "en": "diving down" },
        { "zh": "伸展", "en": "stretching" }
      ]
    },
    {
      "name": "主题/题材 (Themes/Genres)",
      "tags": [
        { "zh": "人像摄影", "en": "portrait photography" },
        { "zh": "风光摄影", "en": "landscape photography" },
        { "zh": "街头摄影", "en": "street photography" },
        { "zh": "野生动物摄影", "en": "wildlife photography" },
        { "zh": "自然摄影", "en": "nature photography" },
        { "zh": "建筑摄影", "en": "architectural photography" },
        { "zh": "美食摄影", "en": "food photography" },
        { "zh": "时尚摄影", "en": "fashion photography" },
        { "zh": "体育摄影", "en": "sports photography" },
        { "zh": "新闻摄影", "en": "photojournalism" },
        { "zh": "纪实摄影", "en": "documentary photography" },
        { "zh": "事件摄影", "en": "event photography" },
        { "zh": "产品摄影", "en": "product photography" },
        { "zh": "静物摄影", "en": "still life photography" },
        { "zh": "旅行摄影", "en": "travel photography" },
        { "zh": "微距摄影", "en": "macro photography" },
        { "zh": "天文摄影", "en": "astrophotography" },
        { "zh": "水下摄影", "en": "underwater photography" },
        { "zh": "婚礼摄影", "en": "wedding photography" },
        { "zh": "新生儿摄影", "en": "newborn photography" },
        { "zh": "家庭摄影", "en": "family photography" },
        { "zh": "演唱会摄影", "en": "concert photography" },
        { "zh": "航空摄影", "en": "aerial photography" },
        { "zh": "无人机摄影", "en": "drone photography" },
        { "zh": "水滴摄影", "en": "splash photography" },
        { "zh": "高速摄影", "en": "high-speed photography" },
        { "zh": "延时摄影", "en": "time-lapse photography" },
        { "zh": "红外摄影", "en": "infrared photography" },
        { "zh": "360度全景", "en": "360-degree panoramic" },
        { "zh": "艺术摄影 (纯艺)", "en": "fine art photography" },
        { "zh": "概念摄影", "en": "conceptual photography" },
        { "zh": "肖像写真", "en": "portraiture" },
        { "zh": "社论摄影", "en": "editorial photography" },
        { "zh": "商业广告摄影", "en": "commercial photography" },
        { "zh": "情感表达", "en": "emotional expression" },
        { "zh": "叙事性", "en": "narrative storytelling" },
        { "zh": "社会评论", "en": "social commentary" },
        { "zh": "环境肖像", "en": "environmental portrait" },
        { "zh": "水利工程", "en": "hydraulic engineering" },
        { "zh": "工业遗迹", "en": "industrial ruins" },
        { "zh": "城市探索", "en": "urban exploration" },
        { "zh": "废弃地摄影 (Urbex)", "en": "urbex photography" },
        { "zh": "微观世界", "en": "microscopic world" },
        { "zh": "宏观景象", "en": "macroscopic view" },
        { "zh": "节庆活动", "en": "festivities" },
        { "zh": "仪式", "en": "ceremony" },
        { "zh": "竞技", "en": "competition" },
        { "zh": "日常瞬间", "en": "everyday moments" },
        { "zh": "抽象艺术", "en": "abstract art" },
        { "zh": "超现实主义", "en": "surrealism" },
        { "zh": "幻想世界", "en": "fantasy world" },
        { "zh": "科幻场景", "en": "sci-fi scene" },
        { "zh": "末日废土", "en": "post-apocalyptic wasteland" },
        { "zh": "乌托邦", "en": "utopian vision" },
        { "zh": "反乌托邦", "en": "dystopian vision" }
      ]
    },
    {
      "name": "风格 (Style Aesthetics)",
      "tags": [
        { "zh": "写实", "en": "realistic" },
        { "zh": "超写实", "en": "hyperrealistic" },
        { "zh": "纪实", "en": "documentary style" },
        { "zh": "自然", "en": "naturalistic" },
        { "zh": "复古", "en": "vintage" },
        { "zh": "怀旧", "en": "retro" },
        { "zh": "经典", "en": "classic" },
        { "zh": "现代", "en": "modern" },
        { "zh": "当代", "en": "contemporary" },
        { "zh": "极简主义", "en": "minimalist" },
        { "zh": "印象派", "en": "impressionistic" },
        { "zh": "表现主义", "en": "expressionistic" },
        { "zh": "超现实", "en": "surreal" },
        { "zh": "抽象", "en": "abstract" },
        { "zh": "实验性", "en": "experimental" },
        { "zh": "前卫", "en": "avant-garde" },
        { "zh": "电影感", "en": "cinematic" },
        { "zh": "戏剧性", "en": "dramatic" },
        { "zh": "情绪化", "en": "moody" },
        { "zh": "空灵", "en": "ethereal" },
        { "zh": "梦幻", "en": "dreamy" },
        { "zh": "明亮且通风", "en": "bright and airy" },
        { "zh": "高调", "en": "high key" },
        { "zh": "低调", "en": "low key" },
        { "zh": "黑白", "en": "black and white" },
        { "zh": "单色", "en": "monochrome" },
        { "zh": "柔焦", "en": "soft focus" },
        { "zh": "锐利", "en": "sharp focus" },
        { "zh": "抓拍", "en": "candid" },
        { "zh": "摆拍", "en": "posed" },
        { "zh": "概念性", "en": "conceptual style" },
        { "zh": "波普艺术", "en": "pop art" },
        { "zh": "艺术装饰", "en": "Art Deco" },
        { "zh": "蒸汽朋克", "en": "steampunk" },
        { "zh": "赛博朋克", "en": "cyberpunk" },
        { "zh": "维多利亚时代", "en": "Victorian era" },
        { "zh": "哥特式", "en": "Gothic" },
        { "zh": "巴洛克", "en": "Baroque" },
        { "zh": "文艺复兴风格", "en": "Renaissance style" },
        { "zh": "Lo-Fi", "en": "Lo-Fi" },
        { "zh": "Hi-Fi", "en": "Hi-Fi" },
        { "zh": "暗黑系", "en": "dark aesthetic" },
        { "zh": "治愈系", "en": "healing aesthetic" },
        { "zh": "清新", "en": "fresh aesthetic" },
        { "zh": "浪漫", "en": "romantic" },
        { "zh": "史诗", "en": "epic" },
        { "zh": "超现实主义", "en": "surrealist" },
        { "zh": "极简主义", "en": "minimalist" },
        { "zh": "梦幻主义", "en": "dreamlike" },
        { "zh": "颗粒感", "en": "grainy" },
        { "zh": "模糊感", "en": "blurry" },
        { "zh": "高对比度", "en": "high contrast" },
        { "zh": "低对比度", "en": "low contrast" },
        { "zh": "扁平化设计", "en": "flat design" },
        { "zh": "故障艺术", "en": "glitch art" },
        { "zh": "像素艺术", "en": "pixel art" },
        { "zh": "涂鸦风格", "en": "graffiti style" },
        { "zh": "水墨", "en": "ink wash" },
        { "zh": "油画", "en": "oil painting style" },
        { "zh": "水彩", "en": "watercolor style" },
        { "zh": "素描", "en": "sketch style" },
        { "zh": "卡通", "en": "cartoon style" },
        { "zh": "动漫", "en": "anime style" }
      ]
    },
    {
      "name": "构图/美学原则 (Composition/Aesthetics Principles)",
      "tags": [
        { "zh": "三分法构图", "en": "rule of thirds" },
        { "zh": "引导线", "en": "leading lines" },
        { "zh": "对称构图", "en": "symmetry" },
        { "zh": "不对称构图", "en": "asymmetry" },
        { "zh": "黄金比例", "en": "golden ratio" },
        { "zh": "黄金螺旋", "en": "golden spiral" },
        { "zh": "框架构图", "en": "framing (composition)" },
        { "zh": "负空间", "en": "negative space" },
        { "zh": "平衡", "en": "balance" },
        { "zh": "视觉重量", "en": "visual weight" },
        { "zh": "重复图案", "en": "repetition/pattern" },
        { "zh": "纹理", "en": "texture" },
        { "zh": "色彩和谐", "en": "color harmony" },
        { "zh": "色彩对比", "en": "color contrast" },
        { "zh": "暖色调", "en": "warm tones" },
        { "zh": "冷色调", "en": "cool tones" },
        { "zh": "互补色", "en": "complementary colors" },
        { "zh": "类似色", "en": "analogous colors" },
        { "zh": "鲜艳色彩", "en": "vibrant colors" },
        { "zh": "柔和色彩", "en": "muted colors" },
        { "zh": "单色调", "en": "monochromatic palette" },
        { "zh": "留白", "en": "empty space" },
        { "zh": "动态平衡", "en": "dynamic balance" },
        { "zh": "节奏感", "en": "rhythm" },
        { "zh": "深度感", "en": "sense of depth" },
        { "zh": "视觉兴趣点", "en": "point of visual interest" },
        { "zh": "视觉流线", "en": "visual flow" },
        { "zh": "大小对比", "en": "scale contrast" },
        { "zh": "透视", "en": "perspective" },
        { "zh": "前景/中景/背景", "en": "foreground/midground/background" },
        { "zh": "前景虚化", "en": "foreground blur" },
        { "zh": "背景虚化", "en": "background blur (bokeh)" },
        { "zh": "散景", "en": "bokeh" },
        { "zh": "清晰度", "en": "sharpness" },
        { "zh": "颗粒感/噪点", "en": "grain/noise" },
        { "zh": "层次感", "en": "layering/depth" },
        { "zh": "影调", "en": "tonality" },
        { "zh": "光影对比", "en": "light and shadow contrast" },
        { "zh": "视觉冲击力", "en": "visual impact" },
        { "zh": "情感共鸣", "en": "emotional resonance" },
        { "zh": "叙事性构图", "en": "narrative composition" },
        { "zh": "秩序感", "en": "sense of order" },
        { "zh": "混乱感", "en": "sense of chaos" }
      ]
    },
    {
      "name": "图像质感 (Image Quality/Texture)",
      "tags": [
        { "zh": "高分辨率", "en": "high resolution" },
        { "zh": "低分辨率", "en": "low resolution" },
        { "zh": "锐利", "en": "sharp" },
        { "zh": "柔和", "en": "soft" },
        { "zh": "清晰", "en": "crisp" },
        { "zh": "模糊", "en": "blurry" },
        { "zh": "失焦", "en": "out of focus" },
        { "zh": "景深", "en": "depth of field" },
        { "zh": "浅景深", "en": "shallow depth of field" },
        { "zh": "深景深", "en": "deep depth of field" },
        { "zh": "散景", "en": "bokeh" },
        { "zh": "电影颗粒", "en": "film grain" },
        { "zh": "数字噪点", "en": "digital noise" },
        { "zh": "高对比度", "en": "high contrast" },
        { "zh": "低对比度", "en": "low contrast" },
        { "zh": "丰富细节", "en": "rich detail" },
        { "zh": "平滑", "en": "smooth" },
        { "zh": "粗糙", "en": "rough" },
        { "zh": "金属质感", "en": "metallic texture" },
        { "zh": "玻璃质感", "en": "glass texture" },
        { "zh": "皮肤质感", "en": "skin texture" },
        { "zh": "织物质感", "en": "fabric texture" },
        { "zh": "水面涟漪", "en": "water ripples" },
        { "zh": "雾蒙蒙", "en": "hazy" },
        { "zh": "光泽感", "en": "glossy" },
        { "zh": "哑光感", "en": "matte" },
        { "zh": "反射", "en": "reflective" },
        { "zh": "半透明", "en": "translucent" },
        { "zh": "透明", "en": "transparent" },
        { "zh": "湿润感", "en": "wet texture" },
        { "zh": "干燥感", "en": "dry texture" },
        { "zh": "磨损感", "en": "worn surface" },
        { "zh": "做旧感", "en": "distressed look" },
        { "zh": "完美无瑕", "en": "flawless finish" }
      ]
    },
    {
      "name": "滤镜/后期处理 (Filters/Post-Processing)",
      "tags": [
        { "zh": "黑白转换", "en": "black and white conversion" },
        { "zh": "复古色调", "en": "sepia tone" },
        { "zh": "暖色滤镜", "en": "warm filter" },
        { "zh": "冷色滤镜", "en": "cool filter" },
        { "zh": "电影 LUT", "en": "cinematic LUT" },
        { "zh": "哑光效果", "en": "matte effect" },
        { "zh": "局部色彩", "en": "selective color" },
        { "zh": "暗角", "en": "vignette" },
        { "zh": "HDR处理", "en": "HDR processing" },
        { "zh": "柔焦滤镜", "en": "soft focus filter" },
        { "zh": "锐化", "en": "sharpening" },
        { "zh": "降噪处理", "en": "noise reduction" },
        { "zh": "运动模糊", "en": "motion blur" },
        { "zh": "径向模糊", "en": "radial blur" },
        { "zh": "交叉冲洗", "en": "cross-processing" },
        { "zh": "分离色调", "en": "split toning" },
        { "zh": "奥顿效果", "en": "Orton effect" },
        { "zh": "辉光效果", "en": "glow effect" },
        { "zh": "漂白跳跃", "en": "bleach bypass" },
        { "zh": "中性密度滤镜(ND)", "en": "ND filter" },
        { "zh": "偏振镜(CPL)", "en": "CPL filter" },
        { "zh": "紫外线滤镜(UV)", "en": "UV filter" },
        { "zh": "渐变滤镜", "en": "graduated filter" },
        { "zh": "鱼眼校正/效果", "en": "fisheye correction/effect" },
        { "zh": "移轴效果", "en": "tilt-shift effect" },
        { "zh": "双重曝光", "en": "double exposure" },
        { "zh": "多重曝光", "en": "multiple exposure" },
        { "zh": "镜头光斑", "en": "lens flare" },
        { "zh": "色差校正", "en": "chromatic aberration correction" },
        { "zh": "畸变校正", "en": "distortion correction" },
        { "zh": "校色", "en": "color grading" },
        { "zh": "曲线调整", "en": "tone curve adjustment" },
        { "zh": "高饱和度", "en": "high saturation" },
        { "zh": "低饱和度", "en": "low saturation" },
        { "zh": "数字绘画感", "en": "digital painting effect" },
        { "zh": "胶片模拟", "en": "film simulation" },
        { "zh": "模拟胶片褪色", "en": "simulated film fade" },
        { "zh": "瑕疵/颗粒感", "en": "imperfections/grainy effect" },
        { "zh": "数字增强", "en": "digitally enhanced" },
        { "zh": "合成图像", "en": "composite image" },
        { "zh": "蒙版", "en": "masking" },
        { "zh": "克隆图章", "en": "clone stamp" },
        { "zh": "污垢和划痕效果", "en": "dirt and scratches effect" },
        { "zh": "漏光效果", "en": "light leak effect" },
        { "zh": "色彩分离", "en": "color separation" },
        { "zh": "Lomo效果", "en": "Lomo effect" }
      ]
    },
    {
      "name": "景别/构图视角 (Shot Types/Framing/Perspective)",
      "tags": [
        { "zh": "极特写 (局部)", "en": "extreme close-up (ECU)" },
        { "zh": "特写 (CU)", "en": "close-up (CU)" },
        { "zh": "大特写 (头部)", "en": "big close-up (BCU)" },
        { "zh": "中近景 (腰部以上)", "en": "medium close-up (MCU)" },
        { "zh": "中景 (膝盖以上)", "en": "medium shot (MS)" },
        { "zh": "中全景 (膝盖以下)", "en": "medium full shot (MFS)" },
        { "zh": "全景 (全身)", "en": "full shot (FS)" },
        { "zh": "远景 (环境)", "en": "long shot (LS)" },
        { "zh": "大远景 (广阔)", "en": "extreme long shot (ELS)" },
        { "zh": "广角镜头", "en": "wide-angle shot" },
        { "zh": "狭窄视角", "en": "tight shot" },
        { "zh": "特写细节", "en": "detail shot" },
        { "zh": "建立性镜头", "en": "establishing shot" },
        { "zh": "主观视角 (POV)", "en": "point of view (POV) shot" },
        { "zh": "过肩镜头", "en": "over-the-shoulder shot" },
        { "zh": "高角度/俯拍", "en": "high angle shot/overhead shot" },
        { "zh": "低角度/仰拍", "en": "low angle shot/undershot" },
        { "zh": "平视角度", "en": "eye-level shot" },
        { "zh": "鸟瞰", "en": "bird's eye view" },
        { "zh": "虫眼视角", "en": "worm's eye view" },
        { "zh": "倾斜构图 (Dutch angle)", "en": "Dutch angle" },
        { "zh": "水平视角", "en": "horizontal perspective" },
        { "zh": "垂直视角", "en": "vertical perspective" },
        { "zh": "中心构图", "en": "centered composition" },
        { "zh": "偏离中心构图", "en": "off-center composition" },
        { "zh": "对角线构图", "en": "diagonal composition" },
        { "zh": "开放式构图", "en": "open composition" },
        { "zh": "封闭式构图", "en": "closed composition" },
        { "zh": "剪影构图", "en": "silhouette composition" },
        { "zh": "框中框", "en": "frame within a frame" },
        { "zh": "并置", "en": "juxtaposition" },
        { "zh": "对称", "en": "symmetry" },
        { "zh": "多主体", "en": "multiple subjects" },
        { "zh": "孤独主体", "en": "isolated subject" },
        { "zh": "广阔景深", "en": "vast depth of field" },
        { "zh": "超广角", "en": "ultra wide-angle" },
        { "zh": "鱼眼镜头效果", "en": "fisheye lens effect" },
        { "zh": "长焦压缩", "en": "telephoto compression" },
        { "zh": "微距视角", "en": "macro perspective" }
      ]
    },
    {
      "name": "光影 (Lighting and Shadow)",
      "tags": [
        { "zh": "自然光", "en": "natural light" },
        { "zh": "人造光", "en": "artificial light" },
        { "zh": "影棚灯光", "en": "studio lighting" },
        { "zh": "环境光", "en": "ambient light" },
        { "zh": "硬光", "en": "hard light" },
        { "zh": "柔光", "en": "soft light" },
        { "zh": "散射光", "en": "diffused light" },
        { "zh": "直射光", "en": "direct light" },
        { "zh": "逆光", "en": "backlighting" },
        { "zh": "侧光", "en": "side lighting" },
        { "zh": "顺光", "en": "front lighting" },
        { "zh": "顶光", "en": "top lighting" },
        { "zh": "底光", "en": "bottom lighting" },
        { "zh": "轮廓光", "en": "rim light/hair light" },
        { "zh": "眼神光", "en": "catchlight" },
        { "zh": "伦勃朗光", "en": "Rembrandt lighting" },
        { "zh": "蝴蝶光", "en": "butterfly lighting" },
        { "zh": "分割光", "en": "split lighting" },
        { "zh": "环形光", "en": "loop lighting" },
        { "zh": "金光/黄金时段", "en": "golden light/golden hour" },
        { "zh": "蓝调/蓝色时段", "en": "blue hour" },
        { "zh": "日出", "en": "sunrise light" },
        { "zh": "日落", "en": "sunset light" },
        { "zh": "正午阳光", "en": "midday sun" },
        { "zh": "月光", "en": "moonlight" },
        { "zh": "星光", "en": "starlight" },
        { "zh": "城市灯光", "en": "city lights" },
        { "zh": "霓虹灯", "en": "neon lights" },
        { "zh": "车轨", "en": "light trails (from vehicles)" },
        { "zh": "火光", "en": "firelight" },
        { "zh": "烛光", "en": "candlelight" },
        { "zh": "闪光灯", "en": "flash photography" },
        { "zh": "曝光过度", "en": "overexposed" },
        { "zh": "曝光不足", "en": "underexposed" },
        { "zh": "高光", "en": "highlights" },
        { "zh": "阴影", "en": "shadows" },
        { "zh": "明暗对比", "en": "chiaroscuro" },
        { "zh": "硬阴影", "en": "harsh shadows" },
        { "zh": "柔和阴影", "en": "soft shadows" },
        { "zh": "拉长阴影", "en": "elongated shadows" },
        { "zh": "剪影", "en": "silhouette" },
        { "zh": "光斑", "en": "light leaks" },
        { "zh": "光晕", "en": "halo effect" },
        { "zh": "光线穿透", "en": "light filtering through" },
        { "zh": "丁达尔效应", "en": "Tyndall effect/crepuscular rays" },
        { "zh": "光画", "en": "light painting" },
        { "zh": "光线追踪", "en": "ray tracing (CGI term, but implies high photorealism)" },
        { "zh": "反射光", "en": "reflected light" },
        { "zh": "透射光", "en": "transmitted light" },
        { "zh": "光线充足", "en": "well-lit" },
        { "zh": "昏暗", "en": "dimly lit" },
        { "zh": "神秘光线", "en": "mysterious light" },
        { "zh": "梦幻光线", "en": "dreamy light" }
      ]
    },
    {
      "name": "年代 (Era/Time Period)",
      "tags": [
        { "zh": "当代", "en": "contemporary" },
        { "zh": "现代", "en": "modern era" },
        { "zh": "未来派", "en": "futuristic" },
        { "zh": "复古", "en": "vintage" },
        { "zh": "老式", "en": "antique" },
        { "zh": "蒸汽朋克时代", "en": "steampunk era" },
        { "zh": "赛博朋克时代", "en": "cyberpunk era" },
        { "zh": "维多利亚时代", "en": "Victorian era" },
        { "zh": "爱德华时代", "en": "Edwardian era" },
        { "zh": "20年代 (咆哮的)", "en": "1920s (Roaring Twenties)" },
        { "zh": "30年代 (大萧条)", "en": "1930s (Great Depression era)" },
        { "zh": "40年代 (二战)", "en": "1940s (WWII era)" },
        { "zh": "50年代 (黄金时代)", "en": "1950s (Golden Age)" },
        { "zh": "60年代 (嬉皮)", "en": "1960s (Hippie era)" },
        { "zh": "70年代 (迪斯科)", "en": "1970s (Disco era)" },
        { "zh": "80年代 (新浪潮)", "en": "1980s (New Wave era)" },
        { "zh": "90年代 (Y一代)", "en": "1990s (Gen Y era)" },
        { "zh": "千禧年 (2000年代)", "en": "2000s (Millennium)" },
        { "zh": "2010年代 (社交媒体)", "en": "2010s (Social Media Age)" },
        { "zh": "2020年代 (数字原生)", "en": "2020s (Digital Native Age)" },
        { "zh": "古时", "en": "ancient times" },
        { "zh": "中世纪", "en": "medieval period" },
        { "zh": "文艺复兴", "en": "Renaissance period" },
        { "zh": "工业革命", "en": "Industrial Revolution" },
        { "zh": "新石器时代", "en": "Neolithic period" },
        { "zh": "远古时代", "en": "primeval times" },
        { "zh": "后现代", "en": "postmodern" },
        { "zh": "赛博时代", "en": "cyber age" },
        { "zh": "太空时代", "en": "space age" },
        { "zh": "复古未来主义", "en": "retro-futuristic" },
        { "zh": "跨时代", "en": "trans-era" },
        { "zh": "特定年份", "en": "specific year (e.g., 1985)" }
      ]
    },
    {
      "name": "背景/环境 (Background/Environment)",
      "tags": [
        { "zh": "城市街景", "en": "urban street" },
        { "zh": "城市天际线", "en": "city skyline" },
        { "zh": "摩天大楼", "en": "skyscrapers" },
        { "zh": "小巷", "en": "alleyway" },
        { "zh": "工业区", "en": "industrial zone" },
        { "zh": "废弃建筑/遗址", "en": "abandoned building/ruins" },
        { "zh": "地铁站", "en": "subway station" },
        { "zh": "火车站", "en": "train station" },
        { "zh": "机场", "en": "airport" },
        { "zh": "咖啡馆", "en": "cafe" },
        { "zh": "酒吧/夜店", "en": "bar/nightclub" },
        { "zh": "博物馆/画廊", "en": "museum/art gallery" },
        { "zh": "图书馆", "en": "library" },
        { "zh": "购物中心", "en": "shopping mall" },
        { "zh": "体育场", "en": "sports stadium" },
        { "zh": "音乐厅", "en": "concert hall" },
        { "zh": "剧院", "en": "theatre" },
        { "zh": "办公室/工作场所", "en": "office/workplace" },
        { "zh": "家（室内）", "en": "home (indoor)" },
        { "zh": "厨房", "en": "kitchen" },
        { "zh": "卧室", "en": "bedroom" },
        { "zh": "客厅", "en": "living room" },
        { "zh": "阳台/露台", "en": "balcony/terrace" },
        { "zh": "农田", "en": "farmland" },
        { "zh": "森林/树林", "en": "forest/woods" },
        { "zh": "山脉/丘陵", "en": "mountains/hills" },
        { "zh": "海滩/海岸线", "en": "beach/coastline" },
        { "zh": "沙漠", "en": "desert" },
        { "zh": "湖泊/池塘", "en": "lake/pond" },
        { "zh": "河流/溪流", "en": "river/stream" },
        { "zh": "瀑布", "en": "waterfall" },
        { "zh": "冰川/雪地", "en": "glacier/snowy landscape" },
        { "zh": "草原/草地", "en": "grassland/meadow" },
        { "zh": "花园/公园", "en": "garden/park" },
        { "zh": "洞穴", "en": "cave" },
        { "zh": "水下世界", "en": "underwater world" },
        { "zh": "太空", "en": "outer space" },
        { "zh": "月球/行星表面", "en": "lunar/planetary surface" },
        { "zh": "云海", "en": "sea of clouds" },
        { "zh": "纯色背景", "en": "solid color background" },
        { "zh": "渐变背景", "en": "gradient background" },
        { "zh": "模糊背景", "en": "blurred background" },
        { "zh": "透明背景", "en": "transparent background" },
        { "zh": "工作室背景", "en": "studio background" },
        { "zh": "室外", "en": "outdoor" },
        { "zh": "室内", "en": "indoor" },
        { "zh": "白天", "en": "daytime" },
        { "zh": "夜晚", "en": "nighttime" },
        { "zh": "日出/日落", "en": "sunrise/sunset" },
        { "zh": "晴天", "en": "sunny weather" },
        { "zh": "阴天", "en": "cloudy weather" },
        { "zh": "雨天", "en": "rainy weather" },
        { "zh": "雪天", "en": "snowy weather" },
        { "zh": "雾天", "en": "foggy weather" },
        { "zh": "多风", "en": "windy" },
        { "zh": "暴风雨", "en": "stormy" },
        { "zh": "环境光效", "en": "ambient lighting effects" },
        { "zh": "自然景观", "en": "natural vista" },
        { "zh": "人文景观", "en": "cultural landscape" },
        { "zh": "废土景观", "en": "wasteland landscape" },
        { "zh": "超现实背景", "en": "surreal background" },
        { "zh": "幻想背景", "en": "fantasy background" },
        { "zh": "未来都市", "en": "futuristic city" },
        { "zh": "外星世界", "en": "alien world" },
        { "zh": "水面", "en": "water surface" },
        { "zh": "湿润的街道", "en": "wet street" },
        { "zh": "倒影", "en": "reflection" },
        { "zh": "沙尘暴", "en": "sandstorm" },
        { "zh": "暴雪", "en": "blizzard" },
        { "zh": "彩虹", "en": "rainbow" },
        { "zh": "闪电", "en": "lightning" },
        { "zh": "星轨", "en": "star trails" },
        { "zh": "银河系", "en": "Milky Way" },
        { "zh": "极光", "en": "aurora borealis" }
      ]
    },
    {
      "name": "拍摄方式/技巧 (Shooting Methods/Techniques)",
      "tags": [
        { "zh": "长曝光", "en": "long exposure" },
        { "zh": "短曝光", "en": "short exposure" },
        { "zh": "慢门", "en": "slow shutter speed" },
        { "zh": "高速快门", "en": "fast shutter speed" },
        { "zh": "追焦", "en": "panning shot" },
        { "zh": "包围曝光", "en": "exposure bracketing" },
        { "zh": "多重曝光", "en": "multiple exposure" },
        { "zh": "序列拍摄", "en": "sequence shot" },
        { "zh": "光绘", "en": "light painting" },
        { "zh": "HDR合成", "en": "HDR composite" },
        { "zh": "全景拼接", "en": "panoramic stitching" },
        { "zh": "延时摄影", "en": "time-lapse" },
        { "zh": "超延时", "en": "hyperlapse" },
        { "zh": "定格动画", "en": "stop motion" },
        { "zh": "高速连拍", "en": "high-speed burst" },
        { "zh": "手动对焦", "en": "manual focus" },
        { "zh": "自动对焦", "en": "autofocus" },
        { "zh": "景深合成", "en": "focus stacking/depth compositing" },
        { "zh": "自拍", "en": "self-portrait" },
        { "zh": "倒影拍摄", "en": "reflection photography" },
        { "zh": "雾中拍摄", "en": "fog photography" },
        { "zh": "雨中拍摄", "en": "rain photography" },
        { "zh": "水滴拍摄", "en": "water drop photography" },
        { "zh": "夜间摄影", "en": "night photography" },
        { "zh": "星空摄影", "en": "starry sky photography" },
        { "zh": "闪电捕捉", "en": "lightning capture" },
        { "zh": "运动模糊", "en": "motion blur" },
        { "zh": "虚化", "en": "defocusing" },
        { "zh": "清晰聚焦", "en": "sharp focus" },
        { "zh": "创意构图", "en": "creative composition" },
        { "zh": "抽象拍摄", "en": "abstract photography" },
        { "zh": "微距", "en": "macrophotography" },
        { "zh": "潜水摄影", "en": "underwater photography" },
        { "zh": "航空摄影", "en": "aerial photography" },
        { "zh": "无人机拍摄", "en": "drone shot" },
        { "zh": "光场摄影", "en": "light field photography" },
        { "zh": "红外摄影", "en": "infrared photography" },
        { "zh": "紫外摄影", "en": "ultraviolet photography" },
        { "zh": "超高速摄影", "en": "ultra-high-speed photography" },
        { "zh": "立体摄影", "en": "stereoscopic photography" },
        { "zh": "胶片摄影", "en": "film photography" },
        { "zh": "数码摄影", "en": "digital photography" }
      ]
    },
    {
      "name": "技术参数 (Technical Parameters)",
      "tags": [
        { "zh": "大光圈", "en": "wide aperture (low f-number)" },
        { "zh": "小光圈", "en": "narrow aperture (high f-number)" },
        { "zh": "快门优先", "en": "shutter priority" },
        { "zh": "光圈优先", "en": "aperture priority" },
        { "zh": "手动模式", "en": "manual mode" },
        { "zh": "高ISO", "en": "high ISO" },
        { "zh": "低ISO", "en": "low ISO" },
        { "zh": "曝光补偿", "en": "exposure compensation" },
        { "zh": "白平衡", "en": "white balance" },
        { "zh": "RGB色彩空间", "en": "RGB color space" },
        { "zh": "CMYK色彩空间", "en": "CMYK color space" },
        { "zh": "RAW格式", "en": "RAW format" },
        { "zh": "JPEG格式", "en": "JPEG format" },
        { "zh": "传感器尺寸", "en": "sensor size" },
        { "zh": "全画幅", "en": "full-frame" },
        { "zh": "APS-C画幅", "en": "APS-C" },
        { "zh": "微型三分之四画幅", "en": "micro four thirds" },
        { "zh": "中画幅", "en": "medium format" },
        { "zh": "像素", "en": "megapixel" },
        { "zh": "分辨率 (DPI/PPI)", "en": "resolution (DPI/PPI)" },
        { "zh": "焦距", "en": "focal length" },
        { "zh": "广角焦距", "en": "wide focal length" },
        { "zh": "标准焦距", "en": "standard focal length" },
        { "zh": "长焦距", "en": "telephoto focal length" },
        { "zh": "定焦镜头", "en": "prime lens" },
        { "zh": "变焦镜头", "en": "zoom lens" },
        { "zh": "微距镜头", "en": "macro lens" },
        { "zh": "鱼眼镜头", "en": "fisheye lens" },
        { "zh": "移轴镜头", "en": "tilt-shift lens" },
        { "zh": "自动对焦系统", "en": "autofocus system" },
        { "zh": "防抖系统", "en": "image stabilization" },
        { "zh": "测光模式", "en": "metering mode" },
        { "zh": "高速同步", "en": "high-speed sync" }
      ]
    },
    {
      "name": "器材 (Equipment)",
      "tags": [
        { "zh": "单反相机 (DSLR)", "en": "DSLR camera" },
        { "zh": "无反相机 (Mirrorless)", "en": "mirrorless camera" },
        { "zh": "数码傻瓜相机", "en": "point-and-shoot camera" },
        { "zh": "智能手机相机", "en": "smartphone camera" },
        { "zh": "胶片相机", "en": "film camera" },
        { "zh": "拍立得相机", "en": "instant camera" },
        { "zh": "运动相机", "en": "action camera" },
        { "zh": "无人机", "en": "drone" },
        { "zh": "GoPro", "en": "GoPro" },
        { "zh": "三脚架", "en": "tripod" },
        { "zh": "稳定器/云台", "en": "gimbal/stabilizer" },
        { "zh": "闪光灯", "en": "flash unit" },
        { "zh": "柔光箱", "en": "softbox" },
        { "zh": "反光板", "en": "reflector" },
        { "zh": "外置麦克风", "en": "external microphone" },
        { "zh": "摄影包", "en": "camera bag" },
        { "zh": "存储卡", "en": "memory card" },
        { "zh": "备用电池", "en": "spare battery" },
        { "zh": "滤镜套装", "en": "filter set" },
        { "zh": "快门线/遥控器", "en": "shutter release cable/remote" },
        { "zh": "清洁套装", "en": "cleaning kit" },
        { "zh": "监视器", "en": "external monitor" },
        { "zh": "灯架", "en": "light stand" },
        { "zh": "背景布", "en": "backdrop" },
        { "zh": "引闪器", "en": "flash trigger" },
        { "zh": "手持设备", "en": "handheld device" },
        { "zh": "电影灯", "en": "cinematic light" },
        { "zh": "LED面板灯", "en": "LED panel light" },
        { "zh": "环形灯", "en": "ring light" }
      ]
    },
    {
      "name": "用途/目的 (Usage/Purpose)",
      "tags": [
        { "zh": "商业用途", "en": "commercial use" },
        { "zh": "编辑用途", "en": "editorial use" },
        { "zh": "艺术展览", "en": "art exhibition" },
        { "zh": "个人收藏", "en": "personal collection" },
        { "zh": "产品目录", "en": "product catalog" },
        { "zh": "广告", "en": "advertisement" },
        { "zh": "杂志封面", "en": "magazine cover" },
        { "zh": "新闻报道", "en": "news report" },
        { "zh": "纪录片素材", "en": "documentary footage" },
        { "zh": "社交媒体内容", "en": "social media content" },
        { "zh": "网站配图", "en": "website imagery" },
        { "zh": "教育目的", "en": "educational purpose" },
        { "zh": "科研用途", "en": "scientific research" },
        { "zh": "证件照", "en": "ID photo" },
        { "zh": "宣传手册", "en": "brochure" },
        { "zh": "库存照片", "en": "stock photo" },
        { "zh": "照片墙", "en": "photo wall" },
        { "zh": "纪念品", "en": "souvenir" },
        { "zh": "时间记录", "en": "time documentation" },
        { "zh": "记录历史", "en": "historical record" },
        { "zh": "美学欣赏", "en": "aesthetic appreciation" },
        { "zh": "情绪传达", "en": "emotional conveyance" }
      ]
    }
  ]
});