tagData.push({
  "group": "室内设计 (Interior Design)",
  "categories": [
    {
      "name": "风格 (Style)",
      "tags": [
        { "zh": "现代主义", "en": "modernist" },
        { "zh": "极简主义", "en": "minimalist" },
        { "zh": "北欧风格", "en": "Scandinavian style" },
        { "zh": "工业风格", "en": "industrial style" },
        { "zh": "复古风格", "en": "retro style" },
        { "zh": "古典风格", "en": "classical style" },
        { "zh": "欧式风格", "en": "European style" },
        { "zh": "美式风格", "en": "American style" },
        { "zh": "法式风格", "en": "French style" },
        { "zh": "意式风格", "en": "Italian style" },
        { "zh": "中式风格", "en": "Chinese style" },
        { "zh": "新中式", "en": "new Chinese style" },
        { "zh": "日式风格", "en": "Japanese style" },
        { "zh": "侘寂风", "en": "wabi-sabi style" },
        { "zh": "地中海风格", "en": "Mediterranean style" },
        { "zh": "波西米亚风", "en": "Bohemian style" },
        { "zh": "田园风格", "en": "rustic style" },
        { "zh": "乡村风格", "en": "country style" },
        { "zh": "农舍风格", "en": "farmhouse style" },
        { "zh": "热带风格", "en": "tropical style" },
        { "zh": "海滨风格", "en": "coastal style" },
        { "zh": "艺术装饰风格", "en": "Art Deco style" },
        { "zh": "巴洛克风格", "en": "Baroque style" },
        { "zh": "洛可可风格", "en": "Rococo style" },
        { "zh": "维多利亚风格", "en": "Victorian style" },
        { "zh": "折衷风格", "en": "eclectic style" },
        { "zh": "过渡风格", "en": "transitional style" },
        { "zh": "奢华风格", "en": "luxury style" },
        { "zh": "高科技风格", "en": "high-tech style" },
        { "zh": "未来主义", "en": "futuristic style" },
        { "zh": "生物仿生设计", "en": "biophilic design" },
        { "zh": "智能家居风格", "en": "smart home style" },
        { "zh": "包豪斯风格", "en": "Bauhaus style" },
        { "zh": "解构主义", "en": "deconstructivist style" },
        { "zh": "格伦奇风格", "en": "grunch style" },
        { "zh": "蒸汽朋克风格", "en": "steampunk style" },
        { "zh": "赛博朋克风格", "en": "cyberpunk style" },
        { "zh": "孟菲斯风格", "en": "Memphis style" },
        { "zh": "可持续设计", "en": "sustainable design" },
        { "zh": "Loft风格", "en": "loft style" },
        { "zh": "禅宗风格", "en": "Zen style" },
        { "zh": "斯堪的纳维亚", "en": "Scandinavian" },
        { "zh": "都市现代", "en": "urban modern" },
        { "zh": "侘寂", "en": "wabi-sabi" },
        { "zh": "前卫", "en": "avant-garde" }
      ]
    },
    {
      "name": "空间 (Space)",
      "tags": [
        { "zh": "客厅", "en": "living room" },
        { "zh": "卧室", "en": "bedroom" },
        { "zh": "主卧", "en": "master bedroom" },
        { "zh": "儿童房", "en": "kids' room" },
        { "zh": "婴儿房", "en": "nursery" },
        { "zh": "厨房", "en": "kitchen" },
        { "zh": "餐厅", "en": "dining room" },
        { "zh": "卫生间", "en": "bathroom" },
        { "zh": "主卫", "en": "master bathroom" },
        { "zh": "客卫", "en": "guest bathroom" },
        { "zh": "书房", "en": "study room" },
        { "zh": "家庭办公室", "en": "home office" },
        { "zh": "玄关", "en": "entryway" },
        { "zh": "走廊", "en": "hallway" },
        { "zh": "衣帽间", "en": "walk-in closet" },
        { "zh": "洗衣房", "en": "laundry room" },
        { "zh": "储藏室", "en": "pantry" },
        { "zh": "地下室", "en": "basement" },
        { "zh": "阁楼", "en": "attic" },
        { "zh": "游戏室", "en": "game room" },
        { "zh": "家庭影院", "en": "home theater" },
        { "zh": "健身房", "en": "home gym" },
        { "zh": "阳台", "en": "balcony" },
        { "zh": "露台", "en": "terrace" },
        { "zh": "庭院", "en": "courtyard" },
        { "zh": "花园", "en": "garden" },
        { "zh": "公共区域", "en": "common area" },
        { "zh": "私人空间", "en": "private space" },
        { "zh": "开放式空间", "en": "open-concept space" },
        { "zh": "紧凑空间", "en": "compact space" },
        { "zh": "宽敞空间", "en": "spacious area" },
        { "zh": "多功能空间", "en": "multi-functional space" },
        { "zh": "商业空间", "en": "commercial space" },
        { "zh": "办公室大厅", "en": "office lobby" },
        { "zh": "会议室", "en": "conference room" },
        { "zh": "休息室", "en": "lounge area" },
        { "zh": "酒店客房", "en": "hotel room" },
        { "zh": "酒店大堂", "en": "hotel lobby" },
        { "zh": "餐厅（商业）", "en": "restaurant (commercial)" },
        { "zh": "咖啡馆", "en": "cafe" },
        { "zh": "零售店", "en": "retail store" },
        { "zh": "画廊", "en": "art gallery" },
        { "zh": "展览空间", "en": "exhibition space" },
        { "zh": "诊所", "en": "clinic" },
        { "zh": "健身中心", "en": "fitness center" },
        { "zh": "教育机构", "en": "educational institution" },
        { "zh": "工业厂房", "en": "industrial building" },
        { "zh": "高天花板", "en": "high ceilings" },
        { "zh": "带阁楼", "en": "with an attic" },
        { "zh": "过渡空间", "en": "transitional space" },
        { "zh": "私密区域", "en": "intimate area" },
        { "zh": "入口", "en": "entrance" }
      ]
    },
    {
      "name": "家装 (Home Decor/Design Elements)",
      "tags": [
        { "zh": "墙面设计", "en": "wall design" },
        { "zh": "漆面墙", "en": "painted wall" },
        { "zh": "壁纸", "en": "wallpaper" },
        { "zh": "护墙板", "en": "wainscoting" },
        { "zh": "艺术墙", "en": "feature wall" },
        { "zh": "裸砖墙", "en": "exposed brick wall" },
        { "zh": "木饰面墙", "en": "wood paneling" },
        { "zh": "石材墙", "en": "stone wall" },
        { "zh": "混凝土墙", "en": "concrete wall" },
        { "zh": "隔断墙", "en": "partition wall" },
        { "zh": "玻璃隔断", "en": "glass partition" },
        { "zh": "木格栅", "en": "wooden slats" },
        { "zh": "地面", "en": "flooring" },
        { "zh": "木地板", "en": "hardwood floor" },
        { "zh": "复合地板", "en": "laminate flooring" },
        { "zh": "瓷砖", "en": "tiles" },
        { "zh": "大理石地板", "en": "marble floor" },
        { "zh": "水泥地板", "en": "concrete floor" },
        { "zh": "地毯", "en": "carpet" },
        { "zh": "区域地毯", "en": "area rug" },
        { "zh": "水磨石地面", "en": "terrazzo flooring" },
        { "zh": "天花板设计", "en": "ceiling design" },
        { "zh": "石膏板吊顶", "en": "drywall ceiling" },
        { "zh": "集成吊顶", "en": "integrated ceiling" },
        { "zh": "裸露横梁", "en": "exposed beams" },
        { "zh": "下沉式天花板", "en": "recessed ceiling" },
        { "zh": "高顶天花板", "en": "vaulted ceiling" },
        { "zh": "天窗", "en": "skylight" },
        { "zh": "窗户", "en": "windows" },
        { "zh": "落地窗", "en": "floor-to-ceiling windows" },
        { "zh": "飘窗", "en": "bay window" },
        { "zh": "百叶窗", "en": "blinds" },
        { "zh": "窗帘", "en": "curtains" },
        { "zh": "罗马帘", "en": "Roman blinds" },
        { "zh": "门", "en": "doors" },
        { "zh": "木门", "en": "wooden door" },
        { "zh": "玻璃门", "en": "glass door" },
        { "zh": "推拉门", "en": "sliding door" },
        { "zh": "折叠门", "en": "folding door" },
        { "zh": "谷仓门", "en": "barn door" },
        { "zh": "拱形门", "en": "archway" },
        { "zh": "壁炉", "en": "fireplace" },
        { "zh": "定制柜体", "en": "custom cabinetry" },
        { "zh": "嵌入式书架", "en": "built-in bookshelves" },
        { "zh": "壁龛", "en": "niche" },
        { "zh": "厨房岛台", "en": "kitchen island" },
        { "zh": "吧台", "en": "bar counter" },
        { "zh": "楼梯", "en": "staircase" },
        { "zh": "扶手", "en": "handrail" },
        { "zh": "柱子", "en": "columns" },
        { "zh": "踢脚线", "en": "baseboards" },
        { "zh": "石膏线", "en": "crown molding" },
        { "zh": "镜面墙", "en": "mirror wall" },
        { "zh": "储物单元", "en": "storage unit" },
        { "zh": "开放式搁架", "en": "open shelving" },
        { "zh": "壁挂式电视", "en": "wall-mounted TV" },
        { "zh": "分体式空调", "en": "split air conditioner" },
        { "zh": "中央空调", "en": "central air conditioning" },
        { "zh": "通风系统", "en": "ventilation system" },
        { "zh": "智能开关", "en": "smart switch" }
      ]
    },
    {
      "name": "搭配 (Color/Material Palette)",
      "tags": [
        { "zh": "暖色调", "en": "warm tones" },
        { "zh": "冷色调", "en": "cool tones" },
        { "zh": "中性色调", "en": "neutral tones" },
        { "zh": "单色搭配", "en": "monochromatic palette" },
        { "zh": "对比色搭配", "en": "contrasting colors" },
        { "zh": "柔和色彩", "en": "pastel colors" },
        { "zh": "明亮跳色", "en": "bright accent colors" },
        { "zh": "深色系", "en": "dark color scheme" },
        { "zh": "浅色系", "en": "light color scheme" },
        { "zh": "大地色系", "en": "earthy tones" },
        { "zh": "白色主题", "en": "white theme" },
        { "zh": "灰色主题", "en": "gray theme" },
        { "zh": "黑色主题", "en": "black theme" },
        { "zh": "蓝色调", "en": "blue hues" },
        { "zh": "绿色调", "en": "green hues" },
        { "zh": "红色调", "en": "red hues" },
        { "zh": "黄色调", "en": "yellow hues" },
        { "zh": "粉色调", "en": "pink hues" },
        { "zh": "紫色调", "en": "purple hues" },
        { "zh": "橙色调", "en": "orange hues" },
        { "zh": "米色调", "en": "beige hues" },
        { "zh": "原木色", "en": "natural wood color" },
        { "zh": "金属光泽", "en": "metallic sheen" },
        { "zh": "哑光质感", "en": "matte finish" },
        { "zh": "高光质感", "en": "glossy finish" },
        { "zh": "绒面纹理", "en": "velvet texture" },
        { "zh": "粗糙纹理", "en": "rough texture" },
        { "zh": "光滑表面", "en": "smooth surface" },
        { "zh": "木材", "en": "wood" },
        { "zh": "橡木", "en": "oak" },
        { "zh": "胡桃木", "en": "walnut" },
        { "zh": "枫木", "en": "maple" },
        { "zh": "竹", "en": "bamboo" },
        { "zh": "金属", "en": "metal" },
        { "zh": "黄铜", "en": "brass" },
        { "zh": "不锈钢", "en": "stainless steel" },
        { "zh": "铸铁", "en": "cast iron" },
        { "zh": "玻璃", "en": "glass" },
        { "zh": "磨砂玻璃", "en": "frosted glass" },
        { "zh": "石材", "en": "stone" },
        { "zh": "大理石", "en": "marble" },
        { "zh": "花岗岩", "en": "granite" },
        { "zh": "板岩", "en": "slate" },
        { "zh": "水磨石", "en": "terrazzo" },
        { "zh": "混凝土", "en": "concrete" },
        { "zh": "陶瓷", "en": "ceramic" },
        { "zh": "黏土", "en": "terracotta" },
        { "zh": "织物", "en": "textile" },
        { "zh": "棉麻", "en": "linen" },
        { "zh": "羊毛", "en": "wool" },
        { "zh": "丝绸", "en": "silk" },
        { "zh": "皮革", "en": "leather" },
        { "zh": "藤编", "en": "rattan" },
        { "zh": "塑料", "en": "plastic" },
        { "zh": "毛皮", "en": "fur" },
        { "zh": "镜面", "en": "mirror finish" },
        { "zh": "有肌理感", "en": "textured feel" },
        { "zh": "天然材料", "en": "natural materials" },
        { "zh": "再生材料", "en": "recycled materials" },
        { "zh": "几何图案", "en": "geometric patterns" },
        { "zh": "花卉图案", "en": "floral patterns" },
        { "zh": "抽象图案", "en": "abstract patterns" }
      ]
    },
    {
      "name": "物品 (Objects/Furniture)",
      "tags": [
        { "zh": "沙发", "en": "sofa" },
        { "zh": "L形沙发", "en": "L-shaped sofa" },
        { "zh": "组合沙发", "en": "sectional sofa" },
        { "zh": "单人沙发", "en": "armchair" },
        { "zh": "躺椅", "en": "lounge chair" },
        { "zh": "凳子", "en": "stool" },
        { "zh": "吧凳", "en": "bar stool" },
        { "zh": "长凳", "en": "bench" },
        { "zh": "脚凳", "en": "ottoman" },
        { "zh": "豆袋", "en": "bean bag" },
        { "zh": "餐桌", "en": "dining table" },
        { "zh": "咖啡桌", "en": "coffee table" },
        { "zh": "边桌", "en": "side table" },
        { "zh": "控制台桌", "en": "console table" },
        { "zh": "办公桌", "en": "desk" },
        { "zh": "梳妆台", "en": "dressing table" },
        { "zh": "床", "en": "bed" },
        { "zh": "双人床", "en": "double bed" },
        { "zh": "大床", "en": "king size bed" },
        { "zh": "床头柜", "en": "nightstand" },
        { "zh": "床头板", "en": "headboard" },
        { "zh": "衣柜", "en": "wardrobe" },
        { "zh": "斗柜", "en": "chest of drawers" },
        { "zh": "书架", "en": "bookshelf" },
        { "zh": "储物柜", "en": "cabinet" },
        { "zh": "展示柜", "en": "display cabinet" },
        { "zh": "置物架", "en": "shelving unit" },
        { "zh": "电视柜", "en": "TV stand" },
        { "zh": "餐边柜", "en": "sideboard" },
        { "zh": "酒柜", "en": "wine cabinet" },
        { "zh": "鞋柜", "en": "shoe cabinet" },
        { "zh": "厨房橱柜", "en": "kitchen cabinets" },
        { "zh": "岛台", "en": "kitchen island" },
        { "zh": "餐具柜", "en": "buffet" },
        { "zh": "壁炉架", "en": "mantelpiece" },
        { "zh": "穿衣镜", "en": "full-length mirror" },
        { "zh": "落地灯", "en": "floor lamp" },
        { "zh": "台灯", "en": "table lamp" },
        { "zh": "吊灯", "en": "pendant light" },
        { "zh": "吸顶灯", "en": "ceiling light" },
        { "zh": "壁灯", "en": "wall sconce" },
        { "zh": "轨道灯", "en": "track lighting" },
        { "zh": "射灯", "en": "spotlight" },
        { "zh": "嵌入式灯具", "en": "recessed lighting" },
        { "zh": "装饰画", "en": "decorative painting" },
        { "zh": "艺术品", "en": "artwork" },
        { "zh": "雕塑", "en": "sculpture" },
        { "zh": "花瓶", "en": "vase" },
        { "zh": "盆栽植物", "en": "potted plant" },
        { "zh": "鲜花", "en": "fresh flowers" },
        { "zh": "装饰抱枕", "en": "throw pillows" },
        { "zh": "盖毯", "en": "throw blanket" },
        { "zh": "窗帘杆", "en": "curtain rod" },
        { "zh": "浴缸", "en": "bathtub" },
        { "zh": "淋浴房", "en": "shower enclosure" },
        { "zh": "马桶", "en": "toilet" },
        { "zh": "洗手盆", "en": "sink" },
        { "zh": "浴室柜", "en": "vanity" },
        { "zh": "冰箱", "en": "refrigerator" },
        { "zh": "烤箱", "en": "oven" },
        { "zh": "微波炉", "en": "microwave" },
        { "zh": "灶台", "en": "cooktop" },
        { "zh": "洗碗机", "en": "dishwasher" },
        { "zh": "洗衣机", "en": "washing machine" },
        { "zh": "烘干机", "en": "dryer" },
        { "zh": "排油烟机", "en": "range hood" },
        { "zh": "水龙头", "en": "faucet" },
        { "zh": "咖啡机", "en": "coffee maker" },
        { "zh": "电水壶", "en": "electric kettle" },
        { "zh": "吐司机", "en": "toaster" },
        { "zh": "搅拌机", "en": "blender" },
        { "zh": "餐具", "en": "dinnerware" },
        { "zh": "玻璃器皿", "en": "glassware" },
        { "zh": "碗碟", "en": "bowls and plates" },
        { "zh": "杯子", "en": "cups" },
        { "zh": "刀叉", "en": "cutlery" },
        { "zh": "茶具", "en": "tea set" },
        { "zh": "毛巾", "en": "towels" },
        { "zh": "浴袍", "en": "bathrobe" },
        { "zh": "香薰蜡烛", "en": "scented candles" },
        { "zh": "香薰机", "en": "diffuser" },
        { "zh": "时钟", "en": "clock" },
        { "zh": "镜子", "en": "mirror" },
        { "zh": "地垫", "en": "doormat" },
        { "zh": "垃圾桶", "en": "waste bin" },
        { "zh": "遥控器", "en": "remote control" },
        { "zh": "书籍", "en": "books" },
        { "zh": "杂志", "en": "magazines" },
        { "zh": "唱片", "en": "vinyl records" },
        { "zh": "小摆件", "en": "knick-knacks" },
        { "zh": "收藏品", "en": "collectibles" },
        { "zh": "智能音箱", "en": "smart speaker" },
        { "zh": "智能家居设备", "en": "smart home devices" },
        { "zh": "宠物床", "en": "pet bed" },
        { "zh": "琴", "en": "piano" },
        { "zh": "吉他", "en": "guitar" },
        { "zh": "健身器材", "en": "fitness equipment" },
        { "zh": "瑜伽垫", "en": "yoga mat" }
      ]
    },
    {
      "name": "景别 (Shot Type/Framing)",
      "tags": [
        { "zh": "全景", "en": "wide shot" },
        { "zh": "大全景", "en": "establishing shot" },
        { "zh": "中景", "en": "medium shot" },
        { "zh": "特写", "en": "close-up" },
        { "zh": "局部特写", "en": "extreme close-up" },
        { "zh": "室内全景", "en": "interior panoramic" },
        { "zh": "角落视图", "en": "corner view" },
        { "zh": "对角线视图", "en": "diagonal view" },
        { "zh": "门槛视图", "en": "doorway view" },
        { "zh": "窗户视图", "en": "window view" },
        { "zh": "俯视", "en": "overhead view" },
        { "zh": "鸟瞰图", "en": "bird's eye view" },
        { "zh": "仰视", "en": "low angle shot" },
        { "zh": "视线水平", "en": "eye-level shot" },
        { "zh": "焦点突出", "en": "focal point emphasis" },
        { "zh": "景深", "en": "depth of field" },
        { "zh": "背景虚化", "en": "blurred background" },
        { "zh": "清晰背景", "en": "sharp background" },
        { "zh": "空间感", "en": "sense of space" },
        { "zh": "细节呈现", "en": "detail presentation" },
        { "zh": "生活化场景", "en": "lived-in scene" },
        { "zh": "场景设定位", "en": "scene setting" },
        { "zh": "垂直构图", "en": "vertical composition" },
        { "zh": "水平构图", "en": "horizontal composition" },
        { "zh": "裁剪构图", "en": "cropped composition" },
        { "zh": "非对称构图", "en": "asymmetrical framing" },
        { "zh": "画中画构图", "en": "frame within a frame" },
        { "zh": "透视构图", "en": "perspective composition" }
      ]
    },
    {
      "name": "构图 (Composition)",
      "tags": [
        { "zh": "对称构图", "en": "symmetrical composition" },
        { "zh": "非对称构图", "en": "asymmetrical composition" },
        { "zh": "三分法构图", "en": "rule of thirds" },
        { "zh": "黄金比例", "en": "golden ratio" },
        { "zh": "中央构图", "en": "centered composition" },
        { "zh": "引导线", "en": "leading lines" },
        { "zh": "框架构图", "en": "framing (composition)" },
        { "zh": "视觉平衡", "en": "visual balance" },
        { "zh": "视觉节奏", "en": "visual rhythm" },
        { "zh": "层次感", "en": "layers" },
        { "zh": "重复元素", "en": "repetition" },
        { "zh": "对比构图", "en": "contrast composition" },
        { "zh": "聚焦点", "en": "focal point" },
        { "zh": "负空间", "en": "negative space" },
        { "zh": "几何构图", "en": "geometric composition" },
        { "zh": "对角线构图", "en": "diagonal composition" },
        { "zh": "曲线构图", "en": "curvilinear composition" },
        { "zh": "网格构图", "en": "grid composition" },
        { "zh": "三角形构图", "en": "triangular composition" },
        { "zh": "开放式构图", "en": "open composition" },
        { "zh": "封闭式构图", "en": "closed composition" },
        { "zh": "纵深感", "en": "sense of depth" },
        { "zh": "明暗对比", "en": "chiaroscuro" },
        { "zh": "影调构图", "en": "tonal composition" },
        { "zh": "色彩构图", "en": "color composition" },
        { "zh": "纹理构图", "en": "texture composition" },
        { "zh": "大小对比", "en": "scale contrast" },
        { "zh": "景深构图", "en": "depth of field composition" },
        { "zh": "前景", "en": "foreground" },
        { "zh": "中景", "en": "midground" },
        { "zh": "背景", "en": "background" }
      ]
    },
    {
      "name": "光照 (Lighting)",
      "tags": [
        { "zh": "充足自然光", "en": "abundant natural light" },
        { "zh": "柔和自然光", "en": "soft natural light" },
        { "zh": "直射阳光", "en": "direct sunlight" },
        { "zh": "侧面光", "en": "side light" },
        { "zh": "逆光", "en": "backlighting" },
        { "zh": "晴天光线", "en": "sunny daylight" },
        { "zh": "阴天光线", "en": "overcast light" },
        { "zh": "黎明光线", "en": "dawn light" },
        { "zh": "黄昏光线", "en": "dusk light" },
        { "zh": "日出光线", "en": "sunrise light" },
        { "zh": "日落光线", "en": "sunset light" },
        { "zh": "夜晚灯光", "en": "night lighting" },
        { "zh": "环境照明", "en": "ambient lighting" },
        { "zh": "任务照明", "en": "task lighting" },
        { "zh": "重点照明", "en": "accent lighting" },
        { "zh": "装饰照明", "en": "decorative lighting" },
        { "zh": "情绪照明", "en": "mood lighting" },
        { "zh": "隐藏式照明", "en": "cove lighting" },
        { "zh": "筒灯", "en": "downlight" },
        { "zh": "射灯", "en": "spotlight" },
        { "zh": "LED灯带", "en": "LED strip lights" },
        { "zh": "吊灯", "en": "pendant light" },
        { "zh": "吸顶灯", "en": "ceiling light" },
        { "zh": "壁灯", "en": "wall sconce" },
        { "zh": "落地灯", "en": "floor lamp" },
        { "zh": "台灯", "en": "table lamp" },
        { "zh": "轨道灯", "en": "track lighting" },
        { "zh": "暖白光", "en": "warm white light" },
        { "zh": "冷白光", "en": "cool white light" },
        { "zh": "中性光", "en": "neutral white light" },
        { "zh": "烛光", "en": "candlelight" },
        { "zh": "壁炉火光", "en": "fireplace glow" },
        { "zh": "光影对比", "en": "light and shadow contrast" },
        { "zh": "高光", "en": "highlights" },
        { "zh": "阴影", "en": "shadows" },
        { "zh": "戏剧性光照", "en": "dramatic lighting" },
        { "zh": "电影级光照", "en": "cinematic lighting" },
        { "zh": "柔光箱效果", "en": "softbox effect" },
        { "zh": "彩色灯光", "en": "colored lighting" },
        { "zh": "智能照明", "en": "smart lighting" },
        { "zh": "可调光", "en": "dimmable" },
        { "zh": "光束", "en": "light beam" },
        { "zh": "眩光", "en": "glare" },
        { "zh": "漫射", "en": "diffuse" }
      ]
    },
    {
      "name": "物品 (Decor & Accessories / Furnishing Details)",
      "tags": [
        { "zh": "艺术画", "en": "art prints" },
        { "zh": "油画", "en": "oil painting" },
        { "zh": "水彩画", "en": "watercolor painting" },
        { "zh": "雕塑", "en": "sculpture" },
        { "zh": "花瓶", "en": "vase" },
        { "zh": "陶瓷器物", "en": "ceramics" },
        { "zh": "装饰盘", "en": "decorative plate" },
        { "zh": "蜡烛", "en": "candles" },
        { "zh": "烛台", "en": "candle holder" },
        { "zh": "香薰扩散器", "en": "scent diffuser" },
        { "zh": "照片墙", "en": "gallery wall" },
        { "zh": "相框", "en": "photo frame" },
        { "zh": "纪念品", "en": "souvenirs" },
        { "zh": "小摆件", "en": "figurines" },
        { "zh": "靠垫", "en": "throw pillows" },
        { "zh": "抱枕", "en": "cushions" },
        { "zh": "盖毯", "en": "throw blanket" },
        { "zh": "床单", "en": "bed linens" },
        { "zh": "被子", "en": "duvet" },
        { "zh": "枕头", "en": "pillow" },
        { "zh": "桌布", "en": "tablecloth" },
        { "zh": "餐巾", "en": "napkins" },
        { "zh": "杯垫", "en": "coasters" },
        { "zh": "地毯", "en": "area rug" },
        { "zh": "门口垫", "en": "doormat" },
        { "zh": "毛巾", "en": "towels" },
        { "zh": "浴袍", "en": "bathrobe" },
        { "zh": "盆栽植物", "en": "potted plants" },
        { "zh": "鲜切花", "en": "fresh cut flowers" },
        { "zh": "干花", "en": "dried flowers" },
        { "zh": "绿植", "en": "greenery" },
        { "zh": "垂直花园", "en": "vertical garden" },
        { "zh": "餐具", "en": "dinnerware" },
        { "zh": "玻璃器皿", "en": "glassware" },
        { "zh": "咖啡具", "en": "coffee set" },
        { "zh": "茶具", "en": "tea set" },
        { "zh": "书籍", "en": "books" },
        { "zh": "杂志", "en": "magazines" },
        { "zh": "遥控器", "en": "remote controls" },
        { "zh": "唱片", "en": "vinyl records" },
        { "zh": "时钟", "en": "clock" },
        { "zh": "镜子", "en": "mirror" },
        { "zh": "全身镜", "en": "full-length mirror" },
        { "zh": "壁挂镜", "en": "wall mirror" },
        { "zh": "收纳盒", "en": "storage boxes" },
        { "zh": "杂志架", "en": "magazine rack" },
        { "zh": "报纸架", "en": "newspaper rack" },
        { "zh": "废物篓", "en": "waste bin" },
        { "zh": "衣架", "en": "coat rack" },
        { "zh": "挂钩", "en": "hooks" },
        { "zh": "窗帘", "en": "curtains" },
        { "zh": "百叶窗", "en": "blinds" },
        { "zh": "挂画", "en": "wall art" },
        { "zh": "屏风", "en": "folding screen" },
        { "zh": "地暖", "en": "underfloor heating" },
        { "zh": "香薰精油", "en": "essential oils" },
        { "zh": "文具", "en": "stationery" },
        { "zh": "游戏机", "en": "gaming console" },
        { "zh": "蓝牙音箱", "en": "bluetooth speaker" },
        { "zh": "智能显示屏", "en": "smart display" },
        { "zh": "无线充电器", "en": "wireless charger" },
        { "zh": "宠物用品", "en": "pet supplies" },
        { "zh": "装饰性托盘", "en": "decorative tray" },
        { "zh": "纺织品", "en": "textiles" },
        { "zh": "民族风装饰", "en": "ethnic decor" },
        { "zh": "工艺品", "en": "handicrafts" },
        { "zh": "纪念盘", "en": "commemorative plate" },
        { "zh": "地球仪", "en": "globe" }
      ]
    }
  ]
});