tagData.push({
  "group": "风景名胜 (Scenic Landmarks)",
  "categories": [
    {
      "name": "国内名胜 (Chinese Landmarks)",
      "tags": [
        { "zh": "万里长城", "en": "Great Wall of China" },
        { "zh": "故宫", "en": "Forbidden City" },
        { "zh": "天安门广场", "en": "Tiananmen Square" },
        { "zh": "颐和园", "en": "Summer Palace" },
        { "zh": "天坛", "en": "Temple of Heaven" },
        { "zh": "兵马俑", "en": "Terracotta Army" },
        { "zh": "秦始皇陵", "en": "Mausoleum of Qin Shi Huang" },
        { "zh": "华山", "en": "Mount Hua" },
        { "zh": "泰山", "en": "Mount Tai" },
        { "zh": "黄山", "en": "Mount Huang (Yellow Mountain)" },
        { "zh": "峨眉山", "en": "Mount Emei" },
        { "zh": "乐山大佛", "en": "Leshan Giant Buddha" },
        { "zh": "九寨沟", "en": "Jiuzhaigou Valley" },
        { "zh": "张家界国家森林公园", "en": "Zhangjiajie National Forest Park" },
        { "zh": "桂林山水", "en": "Guilin Landscapes" },
        { "zh": "漓江", "en": "Li River" },
        { "zh": "西湖", "en": "West Lake (Hangzhou)" },
        { "zh": "上海外滩", "en": "The Bund (Shanghai)" },
        { "zh": "东方明珠广播电视塔", "en": "Oriental Pearl TV Tower" },
        { "zh": "上海中心大厦", "en": "Shanghai Tower" },
        { "zh": "布达拉宫", "en": "Potala Palace" },
        { "zh": "拉萨大昭寺", "en": "Jokhang Temple (Lhasa)" },
        { "zh": "珠穆朗玛峰", "en": "Mount Everest (Qomolangma)" },
        { "zh": "青海湖", "en": "Qinghai Lake" },
        { "zh": "茶卡盐湖", "en": "Chaka Salt Lake" },
        { "zh": "龙门石窟", "en": "Longmen Grottoes" },
        { "zh": "敦煌莫高窟", "en": "Mogao Grottoes (Dunhuang)" },
        { "zh": "大雁塔", "en": "Giant Wild Goose Pagoda (Xi'an)" },
        { "zh": "小雁塔", "en": "Small Wild Goose Pagoda (Xi'an)" },
        { "zh": "西安城墙", "en": "Xi'an City Wall" },
        { "zh": "苏州园林", "en": "Suzhou Gardens" },
        { "zh": "拙政园", "en": "Humble Administrator's Garden" },
        { "zh": "留园", "en": "Lingering Garden" },
        { "zh": "周庄", "en": "Zhouzhuang Water Town" },
        { "zh": "乌镇", "en": "Wuzhen Water Town" },
        { "zh": "丽江古城", "en": "Lijiang Old Town" },
        { "zh": "玉龙雪山", "en": "Jade Dragon Snow Mountain" },
        { "zh": "香格里拉", "en": "Shangri-La" },
        { "zh": "虎跳峡", "en": "Tiger Leaping Gorge" },
        { "zh": "成都大熊猫繁育研究基地", "en": "Chengdu Research Base of Giant Panda Breeding" },
        { "zh": "三峡大坝", "en": "Three Gorges Dam" },
        { "zh": "张家界天门山", "en": "Tianmen Mountain (Zhangjiajie)" },
        { "zh": "凤凰古城", "en": "Fenghuang Ancient Town" },
        { "zh": "稻城亚丁", "en": "Daocheng Yading" },
        { "zh": "神农架", "en": "Shennongjia" },
        { "zh": "呼伦贝尔大草原", "en": "Hulunbuir Grasslands" },
        { "zh": "长白山", "en": "Changbai Mountain" },
        { "zh": "天池 (长白山)", "en": "Heaven Lake (Changbai Mountain)" },
        { "zh": "哈尔滨冰雪大世界", "en": "Harbin Ice and Snow World" },
        { "zh": "海南三亚", "en": "Sanya (Hainan Island)" },
        { "zh": "南山文化旅游区", "en": "Nanshan Cultural Tourism Zone" },
        { "zh": "大理古城", "en": "Dali Ancient City" },
        { "zh": "洱海", "en": "Erhai Lake" },
        { "zh": "崇圣寺三塔", "en": "Three Pagodas of Chongsheng Temple" },
        { "zh": "鼓浪屿", "en": "Gulangyu Island (Xiamen)" },
        { "zh": "厦门大学", "en": "Xiamen University" },
        { "zh": "武夷山", "en": "Mount Wuyi" },
        { "zh": "庐山", "en": "Mount Lu" },
        { "zh": "九华山", "en": "Mount Jiuhua" },
        { "zh": "普陀山", "en": "Mount Putuo" },
        { "zh": "五台山", "en": "Mount Wutai" },
        { "zh": "嵩山少林寺", "en": "Shaolin Temple (Mount Song)" },
        { "zh": "王府井", "en": "Wangfujing Street (Beijing)" },
        { "zh": "后海", "en": "Houhai Lake (Beijing)" },
        { "zh": "南锣鼓巷", "en": "Nanluoguxiang (Beijing)" },
        { "zh": "恭王府", "en": "Prince Gong's Mansion" },
        { "zh": "明十三陵", "en": "Ming Tombs" },
        { "zh": "承德避暑山庄", "en": "Chengde Mountain Resort" },
        { "zh": "平遥古城", "en": "Pingyao Ancient City" },
        { "zh": "五大连池", "en": "Wudalianchi Scenic Area" },
        { "zh": "锦里古街", "en": "Jinli Ancient Street (Chengdu)" },
        { "zh": "宽窄巷子", "en": "Kuanzhai Alley (Chengdu)" },
        { "zh": "都江堰", "en": "Dujiangyan Irrigation System" },
        { "zh": "青城山", "en": "Mount Qingcheng" },
        { "zh": "黄龙风景名胜区", "en": "Huanglong Scenic and Historic Interest Area" },
        { "zh": "若尔盖大草原", "en": "Ruoergai Grassland" },
        { "zh": "甘肃丹霞地貌", "en": "Zhangye Danxia Landform" },
        { "zh": "鸣沙山月牙泉", "en": "Mingsha Mountain and Crescent Spring" },
        { "zh": "甘南", "en": "Gannan (Gansu)" },
        { "zh": "扎尕那", "en": "Zhagana" },
        { "zh": "千户苗寨", "en": "Xijiang Qianhu Miao Village" },
        { "zh": "黄果树瀑布", "en": "Huangguoshu Waterfall" },
        { "zh": "黔东南", "en": "Southeast Guizhou" },
        { "zh": "梵净山", "en": "Fanjingshan" },
        { "zh": "庐山西海", "en": "Lushan West Sea" },
        { "zh": "景德镇", "en": "Jingdezhen" },
        { "zh": "婺源", "en": "Wuyuan" },
        { "zh": "龙虎山", "en": "Longhu Mountain" },
        { "zh": "武当山", "en": "Wudang Mountains" },
        { "zh": "神农架", "en": "Shennongjia" },
        { "zh": "恩施大峡谷", "en": "Enshi Grand Canyon" },
        { "zh": "曾侯乙墓", "en": "Tomb of Marquis Yi of Zeng" },
        { "zh": "湖北省博物馆", "en": "Hubei Provincial Museum" },
        { "zh": "东湖风景区", "en": "East Lake Scenic Area (Wuhan)" },
        { "zh": "炎帝陵", "en": "Mausoleum of Yan Emperor" },
        { "zh": "岳阳楼", "en": "Yueyang Tower" },
        { "zh": "张家界国家森林公园", "en": "Zhangjiajie National Forest Park" },
        { "zh": "天子山", "en": "Tianzi Mountain" },
        { "zh": "袁家界", "en": "Yuanjiajie" },
        { "zh": "金鞭溪", "en": "Golden Whip Stream" },
        { "zh": "橘子洲", "en": "Orange Isle (Changsha)" },
        { "zh": "韶山", "en": "Shaoshan" },
        { "zh": "井冈山", "en": "Jinggangshan" },
        { "zh": "南岳衡山", "en": "Mount Heng (Hunan)" },
        { "zh": "芙蓉镇", "en": "Furong Ancient Town" },
        { "zh": "德夯苗寨", "en": "Dehang Miao Village" },
        { "zh": "杨家界", "en": "Yangjiajie (Zhangjiajie)" },
        { "zh": "黄石寨", "en": "Huangshizhai (Zhangjiajie)" },
        { "zh": "十里画廊", "en": "Ten-Mile Gallery (Zhangjiajie)" },
        { "zh": "老君山", "en": "Mount Laojun (Luoyang)" },
        { "zh": "少林寺", "en": "Shaolin Temple" },
        { "zh": "开封清明上河园", "en": "Qingming Riverside Landscape Garden (Kaifeng)" },
        { "zh": "云台山", "en": "Mount Yuntai" },
        { "zh": "郭亮村", "en": "Guoliang Village" },
        { "zh": "红旗渠", "en": "Red Flag Canal" },
        { "zh": "白马寺", "en": "White Horse Temple" },
        { "zh": "洛阳牡丹园", "en": "Luoyang Peony Garden" },
        { "zh": "蓬莱阁", "en": "Penglai Pavilion" },
        { "zh": "崂山", "en": "Mount Laoshan" },
        { "zh": "青岛栈桥", "en": "Zhanqiao Pier (Qingdao)" },
        { "zh": "泰山", "en": "Mount Tai" },
        { "zh": "曲阜孔庙孔林孔府", "en": "Temple and Cemetery of Confucius and the Kong Family Mansion in Qufu" },
        { "zh": "威海刘公岛", "en": "Liugong Island (Weihai)" },
        { "zh": "荷泽牡丹园", "en": "Heze Peony Garden" },
        { "zh": "栈桥", "en": "Zhanqiao Pier (Qingdao)" },
        { "zh": "", "en": "" },
        { "zh": "大理三塔", "en": "Three Pagodas of Dali" },
        { "zh": "元阳梯田", "en": "Yuanyang Rice Terraces" },
        { "zh": "普者黑", "en": "Puzhehei" },
        { "zh": "东川红土地", "en": "Dongchuan Red Land" },
        { "zh": "禄劝轿子雪山", "en": "Jiaozishan (Luquan)" },
        { "zh": "怒江大峡谷", "en": "Nujiang Grand Canyon" },
        { "zh": "腾冲和顺古镇", "en": "Heshun Ancient Town (Tengchong)" },
        { "zh": "香格里拉普达措国家公园", "en": "Pudacuo National Park (Shangri-La)" },
        { "zh": "白水台", "en": "Baishuitai Terraces" },
        { "zh": "千岛湖", "en": "Qiandao Lake (Thousand Island Lake)" },
        { "zh": "西塘古镇", "en": "Xitang Water Town" },
        { "zh": "同里古镇", "en": "Tongli Water Town" },
        { "zh": "南浔古镇", "en": "Nanxun Ancient Town" },
        { "zh": "绍兴鲁迅故里", "en": "Former Residence of Lu Xun (Shaoxing)" },
        { "zh": "普陀山", "en": "Mount Putuo" },
        { "zh": "横店影视城", "en": "Hengdian World Studios" },
        { "zh": "雁荡山", "en": "Yandang Mountains" },
        { "zh": "楠溪江", "en": "Nanxi River" },
        { "zh": "浙西大峡谷", "en": "West Zhejiang Grand Canyon" },
        { "zh": "郭亮挂壁公路", "en": "Guoliang Tunnel Road" },
        { "zh": "南尖岩", "en": "Nanjianyan" },
        { "zh": "庆元廊桥", "en": "Qingyuan Covered Bridges" },
        { "zh": "舟山群岛", "en": "Zhoushan Archipelago" },
        { "zh": "东极岛", "en": "Dongji Island" },
        { "zh": "花鸟岛", "en": "Huaniao Island" },
        { "zh": "枸杞岛", "en": "Gouqi Island" },
        { "zh": "嵊泗列岛", "en": "Shengsi Islands" },
        { "zh": "神山圣湖 (冈仁波齐、玛旁雍错)", "en": "Holy Mountains and Lake (Mount Kailash, Lake Manasarovar)" },
        { "zh": "纳木错", "en": "Namtso Lake" },
        { "zh": "羊卓雍错", "en": "Yamdrok Lake" },
        { "zh": "林芝", "en": "Nyingchi" },
        { "zh": "雅鲁藏布大峡谷", "en": "Yarlung Tsangpo Grand Canyon" },
        { "zh": "米堆冰川", "en": "Midui Glacier" },
        { "zh": "然乌湖", "en": "Rawok Lake" },
        { "zh": "阿里古格王朝遗址", "en": "Ruins of Guge Kingdom (Ngari)" },
        { "zh": "普兰", "en": "Purang" },
        { "zh": "绒布寺", "en": "Rongbuk Monastery" },
        { "zh": "卡若拉冰川", "en": "Karola Glacier" },
        { "zh": "岗巴拉山口", "en": "Gampala Pass" },
        { "zh": "羊八井", "en": "Yangbajing Hot Springs" },
        { "zh": "哲蚌寺", "en": "Drepung Monastery" },
        { "zh": "色拉寺", "en": "Sera Monastery" },
        { "zh": "甘孜", "en": "Ganzi (Sichuan)" },
        { "zh": "理塘", "en": "Litang" },
        { "zh": "新都桥", "en": "Xinduqiao" },
        { "zh": "墨石公园", "en": "Moshi Park" },
        { "zh": "莲宝叶则", "en": "Lianbaoyeze" },
        { "zh": "色达", "en": "Seda Larung Gar Buddhist Academy" },
        { "zh": "阿坝", "en": "Aba (Sichuan)" },
        { "zh": "四姑娘山", "en": "Mount Siguniang" },
        { "zh": "毕棚沟", "en": "Bipenggou Valley" },
        { "zh": "九顶山", "en": "Jiuding Mountain" },
        { "zh": "峨眉山金顶", "en": "Golden Summit of Mount Emei" },
        { "zh": "三星堆遗址", "en": "Sanxingdui Museum" },
        { "zh": "海螺沟冰川", "en": "Hailuogou Glacier" },
        { "zh": "蜀南竹海", "en": "Southern Sichuan Bamboo Sea" },
        { "zh": "乐山", "en": "Leshan" },
        { "zh": "青城山", "en": "Mount Qingcheng" },
        { "zh": "都江堰", "en": "Dujiangyan" },
        { "zh": "大熊猫栖息地", "en": "Giant Panda Sanctuaries" },
        { "zh": "重庆洪崖洞", "en": "Hongyadong (Chongqing)" },
        { "zh": "长江索道", "en": "Yangtze River Cableway (Chongqing)" },
        { "zh": "解放碑", "en": "Jiefangbei (Chongqing)" },
        { "zh": "磁器口古镇", "en": "Ciqikou Ancient Town (Chongqing)" },
        { "zh": "武隆天生三桥", "en": "Wulong Karst National Geology Park (Three Natural Bridges)" },
        { "zh": "仙女山国家森林公园", "en": "Xiannü Mountain National Forest Park" },
        { "zh": "奉节白帝城", "en": "Baidi City (Fengjie)" },
        { "zh": "巫山小三峡", "en": "Wushan Small Three Gorges" },
        { "zh": "大足石刻", "en": "Dazu Rock Carvings" },
        { "zh": "阿勒泰", "en": "Altay (Xinjiang)" },
        { "zh": "喀纳斯湖", "en": "Kanas Lake" },
        { "zh": "禾木村", "en": "Hemu Village" },
        { "zh": "白哈巴村", "en": "Baihaba Village" },
        { "zh": "赛里木湖", "en": "Sayram Lake" },
        { "zh": "那拉提草原", "en": "Nalati Grassland" },
        { "zh": "伊犁河谷", "en": "Ili River Valley" },
        { "zh": "霍尔果斯口岸", "en": "Khorgos Port" },
        { "zh": "喀什老城", "en": "Kashgar Old City" },
        { "zh": "帕米尔高原", "en": "Pamir Mountains" },
        { "zh": "塔什库尔干", "en": "Tashkurgan" },
        { "zh": "卡拉库里湖", "en": "Karakul Lake" },
        { "zh": "天山天池", "en": "Heavenly Lake of Tianshan" },
        { "zh": "吐鲁番", "en": "Turpan" },
        { "zh": "火焰山", "en": "Flaming Mountains" },
        { "zh": "交河故城", "en": "Jiaohe Ancient City" },
        { "zh": "高昌故城", "en": "Gaochang Ancient City" },
        { "zh": "库木塔格沙漠", "en": "Kumtag Desert" },
        { "zh": "魔鬼城", "en": "Devil City (Urho Wind City)" },
        { "zh": "可可托海", "en": "Koktokay National Geopark" },
        { "zh": "独库公路", "en": "Duku Highway" },
        { "zh": "巴音布鲁克草原", "en": "Bayinbuluke Grassland" },
        { "zh": "库尔德宁", "en": "Kuerdening" },
        { "zh": "昭苏草原", "en": "Zhaosu Grassland" },
        { "zh": "琼库什台", "en": "Qiongkushitai" },
        { "zh": "特克斯八卦城", "en": "Tekes Eight Trigrams City" },
        { "zh": "喀拉峻草原", "en": "Kalaqun Grassland" },
        { "zh": "昭苏湿地公园", "en": "Zhaosu Wetland Park" },
        { "zh": "大峡谷风景区 (新疆)", "en": "Grand Canyon Scenic Area (Xinjiang)" },
        { "zh": "艾提尕尔清真寺", "en": "Id Kah Mosque (Kashgar)" },
        { "zh": "香妃墓", "en": "Abakh Khoja Mausoleum (Kashgar)" },
        { "zh": "石河子", "en": "Shihezi" },
        { "zh": "南山牧场", "en": "Nanshan Pasture (Urumqi)" },
        { "zh": "红山公园 (乌鲁木齐)", "en": "Red Hill Park (Urumqi)" },
        { "zh": "二道桥大巴扎", "en": "Erdaoqiao Grand Bazaar" },
        { "zh": "塔克拉玛干沙漠", "en": "Taklamakan Desert" },
        { "zh": "罗布泊", "en": "Lop Nur" },
        { "zh": "克拉玛依", "en": "Karamay" },
        { "zh": "交河故城", "en": "Jiaohe Ancient City" },
        { "zh": "苏公塔", "en": "Emin Minaret" },
        { "zh": "库车大峡谷", "en": "Kuche Grand Canyon" },
        { "zh": "克孜尔千佛洞", "en": "Kizil Caves" },
        { "zh": "吐鲁番葡萄沟", "en": "Grape Valley (Turpan)" },
        { "zh": "坎儿井", "en": "Karez Well (Turpan)" },
        { "zh": "罗布人村寨", "en": "Lop Nur People's Village" },
        { "zh": "塔里木胡杨林公园", "en": "Tarim Desert Poplar Forest Park" },
        { "zh": "阿拉尔", "en": "Aral" },
        { "zh": "石河子军垦博物馆", "en": "Shihezi Military Reclamation Museum" },
        { "zh": "北疆", "en": "Northern Xinjiang" },
        { "zh": "南疆", "en": "Southern Xinjiang" }
      ]
    },
    {
      "name": "亚洲名胜 (Asian Landmarks)",
      "tags": [
        { "zh": "富士山", "en": "Mount Fuji (Japan)" },
        { "zh": "东京塔", "en": "Tokyo Tower (Japan)" },
        { "zh": "东京晴空塔", "en": "Tokyo Skytree (Japan)" },
        { "zh": "涩谷交叉路口", "en": "Shibuya Crossing (Japan)" },
        { "zh": "浅草寺", "en": "Sensō-ji Temple (Japan)" },
        { "zh": "皇居", "en": "Imperial Palace (Japan)" },
        { "zh": "京都金阁寺", "en": "Kinkaku-ji (Golden Pavilion, Japan)" },
        { "zh": "伏见稻荷大社", "en": "Fushimi Inari-taisha (Japan)" },
        { "zh": "清水寺", "en": "Kiyomizu-dera (Japan)" },
        { "zh": "奈良公园", "en": "Nara Park (Japan)" },
        { "zh": "大阪城", "en": "Osaka Castle (Japan)" },
        { "zh": "广岛和平纪念公园", "en": "Hiroshima Peace Memorial Park (Japan)" },
        { "zh": "明治神宫", "en": "Meiji Jingu (Japan)" },
        { "zh": "箱根", "en": "Hakone (Japan)" },
        { "zh": "冲绳", "en": "Okinawa (Japan)" },
        { "zh": "北海道", "en": "Hokkaido (Japan)" },
        { "zh": "姬路城", "en": "Himeji Castle (Japan)" },
        { "zh": "严岛神社", "en": "Itsukushima Shrine (Japan)" },
        { "zh": "秋叶原", "en": "Akihabara (Japan)" },
        { "zh": "银座", "en": "Ginza (Japan)" },
        { "zh": "新宿御苑", "en": "Shinjuku Gyoen National Garden (Japan)" },
        { "zh": "六本木", "en": "Roppongi (Japan)" },
        { "zh": "筑地市场", "en": "Tsukiji Market (Japan)" },
        { "zh": "鎌倉大仏", "en": "Great Buddha of Kamakura (Japan)" },
        { "zh": "轻井泽", "en": "Karuizawa (Japan)" },
        { "zh": "高山", "en": "Takayama (Japan)" },
        { "zh": "白川乡", "en": "Shirakawa-go (Japan)" },
        { "zh": "洞爷湖", "en": "Lake Toya (Japan)" },
        { "zh": "富良野", "en": "Furano (Japan)" },
        { "zh": "首尔景福宫", "en": "Gyeongbokgung Palace (South Korea)" },
        { "zh": "南山公园", "en": "Namsan Park (South Korea)" },
        { "zh": "N首尔塔", "en": "N Seoul Tower (South Korea)" },
        { "zh": "明洞", "en": "Myeongdong (South Korea)" },
        { "zh": "东大门设计广场", "en": "Dongdaemun Design Plaza (DDP, South Korea)" },
        { "zh": "釜山海云台", "en": "Haeundae Beach (Busan, South Korea)" },
        { "zh": "济州岛", "en": "Jeju Island (South Korea)" },
        { "zh": "庆州仏国寺", "en": "Bulguksa Temple (Gyeongju, South Korea)" },
        { "zh": "DMZ 非军事区", "en": "Korean Demilitarized Zone (DMZ)" },
        { "zh": "清溪川", "en": "Cheonggyecheon Stream (South Korea)" },
        { "zh": "北村韩屋村", "en": "Bukchon Hanok Village (South Korea)" },
        { "zh": "梨花女子大学", "en": "Ewha Womans University (South Korea)" },
        { "zh": "乐天世界", "en": "Lotte World (South Korea)" },
        { "zh": "板门店", "en": "Panmunjom (South Korea)" },
        { "zh": "塔克西拉古城", "en": "Takht-i-Bahi (Pakistan)" },
        { "zh": "费萨尔清真寺", "en": "Faisal Mosque (Pakistan)" },
        { "zh": "莫卧儿花园", "en": "Shalimar Gardens (Pakistan)" },
        { "zh": "德里红堡", "en": "Red Fort (Delhi, India)" },
        { "zh": "泰姬陵", "en": "Taj Mahal (India)" },
        { "zh": "阿格拉堡", "en": "Agra Fort (India)" },
        { "zh": "斋浦尔风之宫殿", "en": "Hawa Mahal (Jaipur, India)" },
        { "zh": "孟买印度门", "en": "Gateway of India (Mumbai, India)" },
        { "zh": "瓦拉纳西恒河", "en": "Ganges River (Varanasi, India)" },
        { "zh": "阿姆利则金庙", "en": "Golden Temple (Amritsar, India)" },
        { "zh": "果阿海滩", "en": "Goa Beaches (India)" },
        { "zh": "新德里印度门", "en": "India Gate (New Delhi, India)" },
        { "zh": "甘地纪念馆", "en": "Raj Ghat (India)" },
        { "zh": "莲花寺", "en": "Lotus Temple (India)" },
        { "zh": "乌代浦城市宫殿", "en": "City Palace (Udaipur, India)" },
        { "zh": "克久拉霍寺庙", "en": "Khajuraho Temples (India)" },
        { "zh": "迈索尔宫殿", "en": "Mysore Palace (India)" },
        { "zh": "阿旃陀石窟", "en": "Ajanta Caves (India)" },
        { "zh": "埃洛拉石窟", "en": "Ellora Caves (India)" },
        { "zh": "清迈素帖寺", "en": "Wat Phra That Doi Suthep (Chiang Mai, Thailand)" },
        { "zh": "曼谷大皇宫", "en": "Grand Palace (Bangkok, Thailand)" },
        { "zh": "玉佛寺", "en": "Wat Phra Kaeo (Temple of the Emerald Buddha, Thailand)" },
        { "zh": "卧佛寺", "en": "Wat Pho (Temple of the Reclining Buddha, Thailand)" },
        { "zh": "黎明寺 (郑王庙)", "en": "Wat Arun (Temple of Dawn, Thailand)" },
        { "zh": "芭堤雅海滩", "en": "Pattaya Beach (Thailand)" },
        { "zh": "普吉岛", "en": "Phuket (Thailand)" },
        { "zh": "皮皮岛", "en": "Phi Phi Islands (Thailand)" },
        { "zh": "苏梅岛", "en": "Koh Samui (Thailand)" },
        { "zh": "茵他侬山", "en": "Doi Inthanon (Thailand)" },
        { "zh": "大城府", "en": "Ayutthaya Historical Park (Thailand)" },
        { "zh": "素可泰", "en": "Sukhothai Historical Park (Thailand)" },
        { "zh": "斯里兰卡狮子岩", "en": "Sigiriya (Sri Lanka)" },
        { "zh": "康提佛牙寺", "en": "Temple of the Sacred Tooth Relic (Kandy, Sri Lanka)" },
        { "zh": "马尔代夫", "en": "Maldives" },
        { "zh": "吴哥窟", "en": "Angkor Wat (Cambodia)" },
        { "zh": "巴戎寺", "en": "Bayon Temple (Cambodia)" },
        { "zh": "女王宫", "en": "Banteay Srei (Cambodia)" },
        { "zh": "塔普伦寺", "en": "Ta Prohm (Cambodia)" },
        { "zh": "金边皇宫", "en": "Royal Palace (Phnom Penh, Cambodia)" },
        { "zh": "越南下龙湾", "en": "Ha Long Bay (Vietnam)" },
        { "zh": "胡志明市圣母大教堂", "en": "Notre Dame Cathedral Basilica of Saigon (Vietnam)" },
        { "zh": "河内还剑湖", "en": "Hoan Kiem Lake (Hanoi, Vietnam)" },
        { "zh": "顺化皇城", "en": "Imperial City (Hue, Vietnam)" },
        { "zh": "会安古镇", "en": "Hoi An Ancient Town (Vietnam)" },
        { "zh": "美山圣地", "en": "My Son Sanctuary (Vietnam)" },
        { "zh": "芽庄", "en": "Nha Trang (Vietnam)" },
        { "zh": "岘港", "en": "Da Nang (Vietnam)" },
        { "zh": "沙巴梯田", "en": "Sapa Terraces (Vietnam)" },
        { "zh": "吉隆坡双子塔", "en": "Petronas Twin Towers (Kuala Lumpur, Malaysia)" },
        { "zh": "黑风洞", "en": "Batu Caves (Malaysia)" },
        { "zh": "马六甲红屋", "en": "Christ Church (Malacca, Malaysia)" },
        { "zh": "兰卡威", "en": "Langkawi (Malaysia)" },
        { "zh": "沙巴", "en": "Sabah (Malaysia)" },
        { "zh": "槟城乔治市", "en": "George Town (Penang, Malaysia)" },
        { "zh": "布城粉红清真寺", "en": "Putra Mosque (Putrajaya, Malaysia)" },
        { "zh": "苏丹阿都沙末大厦", "en": "Sultan Abdul Samad Building (Malaysia)" },
        { "zh": "新加坡滨海湾金沙酒店", "en": "Marina Bay Sands (Singapore)" },
        { "zh": "滨海湾花园", "en": "Gardens by the Bay (Singapore)" },
        { "zh": "鱼尾狮公园", "en": "Merlion Park (Singapore)" },
        { "zh": "圣淘沙岛", "en": "Sentosa Island (Singapore)" },
        { "zh": "新加坡动物园", "en": "Singapore Zoo" },
        { "zh": "牛车水", "en": "Chinatown (Singapore)" },
        { "zh": "小印度", "en": "Little India (Singapore)" },
        { "zh": "环球影城 (新加坡)", "en": "Universal Studios Singapore" },
        { "zh": "菲律宾长滩岛", "en": "Boracay Island (Philippines)" },
        { "zh": "马荣火山", "en": "Mayon Volcano (Philippines)" },
        { "zh": "巧克力山", "en": "Chocolate Hills (Philippines)" },
        { "zh": "宿务", "en": "Cebu (Philippines)" },
        { "zh": "黎刹公园", "en": "Rizal Park (Philippines)" },
        { "zh": "巴纳威梯田", "en": "Banaue Rice Terraces (Philippines)" },
        { "zh": "爱妮岛", "en": "El Nido (Philippines)" },
        { "zh": "科隆岛", "en": "Coron (Philippines)" },
        { "zh": "雅加达独立纪念碑", "en": "National Monument (Jakarta, Indonesia)" },
        { "zh": "巴厘岛", "en": "Bali (Indonesia)" },
        { "zh": "婆罗浮屠", "en": "Borobudur Temple (Indonesia)" },
        { "zh": "普兰巴南寺庙群", "en": "Prambanan Temple Compounds (Indonesia)" },
        { "zh": "科莫多国家公园", "en": "Komodo National Park (Indonesia)" },
        { "zh": "日惹", "en": "Yogyakarta (Indonesia)" },
        { "zh": "布罗莫火山", "en": "Mount Bromo (Indonesia)" },
        { "zh": "龙目岛", "en": "Lombok (Indonesia)" },
        { "zh": "乌布猴林", "en": "Ubud Monkey Forest (Indonesia)" },
        { "zh": "德格拉朗梯田", "en": "Tegalalang Rice Terrace (Indonesia)" },
        { "zh": "圣泉寺", "en": "Tirta Empul Temple (Indonesia)" },
        { "zh": "贝拉勒乌兰", "en": "Uluwatu Temple (Indonesia)" },
        { "zh": "阿布扎比大清真寺", "en": "Sheikh Zayed Grand Mosque (Abu Dhabi, UAE)" },
        { "zh": "迪拜哈利法塔", "en": "Burj Khalifa (Dubai, UAE)" },
        { "zh": "帆船酒店", "en": "Burj Al Arab (Dubai, UAE)" },
        { "zh": "朱美拉公共海滩", "en": "Jumeirah Public Beach (UAE)" },
        { "zh": "迪拜喷泉", "en": "Dubai Fountain (UAE)" },
        { "zh": "棕榈岛", "en": "Palm Jumeirah (UAE)" },
        { "zh": "伊朗伊斯法罕伊玛目广场", "en": "Naqsh-e Jahan Square (Isfahan, Iran)" },
        { "zh": "设拉子粉红清真寺", "en": "Nasir al-Mulk Mosque (Shiraz, Iran)" },
        { "zh": "波斯波利斯", "en": "Persepolis (Iran)" },
        { "zh": "耶斯尔古城", "en": "Yazd Ancient City (Iran)" },
        { "zh": "以色列耶路撒冷哭墙", "en": "Western Wall (Jerusalem, Israel)" },
        { "zh": "圣墓教堂", "en": "Church of the Holy Sepulchre (Israel)" },
        { "zh": "圆顶清真寺", "en": "Dome of the Rock (Israel)" },
        { "zh": "死海", "en": "Dead Sea (Israel/Jordan)" },
        { "zh": "马萨达", "en": "Masada (Israel)" },
        { "zh": "巴勒斯坦伯利恒主诞教堂", "en": "Church of the Nativity (Bethlehem, Palestine)" },
        { "zh": "约旦佩特拉古城", "en": "Petra (Jordan)" },
        { "zh": "瓦迪拉姆", "en": "Wadi Rum (Jordan)" },
        { "zh": "杰拉什古城", "en": "Jerash (Jordan)" },
        { "zh": "黎巴嫩贝鲁特鸽子岩", "en": "Pigeon Rocks (Beirut, Lebanon)" },
        { "zh": "巴勒贝克神庙", "en": "Baalbek (Lebanon)" },
        { "zh": "土耳其伊斯坦布尔蓝色清真寺", "en": "Blue Mosque (Istanbul, Turkey)" },
        { "zh": "圣索菲亚大教堂", "en": "Hagia Sophia (Turkey)" },
        { "zh": "托普卡帕宫", "en": "Topkapi Palace (Turkey)" },
        { "zh": "大巴扎", "en": "Grand Bazaar (Turkey)" },
        { "zh": "卡帕多奇亚", "en": "Cappadocia (Turkey)" },
        { "zh": "棉花堡", "en": "Pamukkale (Turkey)" },
        { "zh": "以弗所古城", "en": "Ephesus (Turkey)" },
        { "zh": "特洛伊古城", "en": "Troy (Turkey)" },
        { "zh": "安塔利亚", "en": "Antalya (Turkey)" },
        { "zh": "阿拉木图科克托贝山", "en": "Kok Tobe Mountain (Almaty, Kazakhstan)" },
        { "zh": "独立纪念碑", "en": "Independence Monument (Kazakhstan)" },
        { "zh": "努尔苏丹巴伊杰列克塔", "en": "Bayterek Tower (Nur-Sultan, Kazakhstan)" },
        { "zh": "比什凯克阿拉阿查国家公园", "en": "Ala-Archa National Park (Bishkek, Kyrgyzstan)" },
        { "zh": "伊塞克湖", "en": "Issyk-Kul Lake (Kyrgyzstan)" },
        { "zh": "塔什干哈斯特伊玛目广场", "en": "Hazrati Imam Complex (Tashkent, Uzbekistan)" },
        { "zh": "撒马尔罕雷吉斯坦广场", "en": "Registan Square (Samarkand, Uzbekistan)" },
        { "zh": "布哈拉老城", "en": "Historic Centre of Bukhara (Uzbekistan)" },
        { "zh": "希瓦古城", "en": "Itchan Kala (Khiva, Uzbekistan)" },
        { "zh": "孟加拉国孙德尔本斯", "en": "Sundarbans (Bangladesh)" },
        { "zh": "尼泊尔加德满都杜巴广场", "en": "Durbar Square (Kathmandu, Nepal)" },
        { "zh": "博大哈佛塔", "en": "Boudhanath Stupa (Nepal)" },
        { "zh": "斯瓦扬布纳特寺", "en": "Swayambhunath Temple (Monkey Temple, Nepal)" },
        { "zh": "费瓦湖", "en": "Phewa Lake (Nepal)" },
        { "zh": "帕坦杜巴广场", "en": "Patan Durbar Square (Nepal)" },
        { "zh": "不丹帕罗虎穴寺", "en": "Paro Taktsang (Tiger's Nest Monastery, Bhutan)" },
        { "zh": "廷布宗堡", "en": "Tashichho Dzong (Thimphu, Bhutan)" },
        { "zh": "蒙古乌兰巴托甘丹寺", "en": "Gandan Monastery (Ulaanbaatar, Mongolia)" },
        { "zh": "特勒吉国家公园", "en": "Gorkhi-Terelj National Park (Mongolia)" },
        { "zh": "戈壁沙漠", "en": "Gobi Desert (Mongolia)" },
        { "zh": "老挝琅勃拉邦光西瀑布", "en": "Kuang Si Falls (Luang Prabang, Laos)" },
        { "zh": "香通寺", "en": "Wat Xieng Thong (Luang Prabang, Laos)" },
        { "zh": "万荣", "en": "Vang Vieng (Laos)" },
        { "zh": "缅甸仰光大金塔", "en": "Shwedagon Pagoda (Yangon, Myanmar)" },
        { "zh": "曼德勒乌本桥", "en": "U Bein Bridge (Mandalay, Myanmar)" },
        { "zh": "蒲甘佛塔群", "en": "Bagan (Myanmar)" },
        { "zh": "因莱湖", "en": "Inle Lake (Myanmar)" },
        { "zh": "大金石", "en": "Kyaiktiyo Pagoda (Golden Rock, Myanmar)" },
        { "zh": "文莱斯里巴加湾市苏丹奥马尔阿里赛义夫丁清真寺", "en": "Sultan Omar Ali Saifuddien Mosque (Bandar Seri Begawan, Brunei)" },
        { "zh": "科威特塔", "en": "Kuwait Towers (Kuwait)" },
        { "zh": "卡塔尔多哈滨海大道", "en": "Corniche (Doha, Qatar)" },
        { "zh": "卡塔拉文化村", "en": "Katara Cultural Village (Qatar)" },
        { "zh": "阿曼马斯喀特苏丹卡布斯大清真寺", "en": "Sultan Qaboos Grand Mosque (Muscat, Oman)" },
        { "zh": "瓦迪沙布", "en": "Wadi Shab (Oman)" },
        { "zh": "也门萨那老城", "en": "Old City of Sana'a (Yemen)" },
        { "zh": "阿富汗巴米扬大佛遗址", "en": "Buddhas of Bamiyan (Afghanistan)" }
      ]
    },
    {
      "name": "欧洲名胜 (European Landmarks)",
      "tags": [
        { "zh": "埃菲尔铁塔", "en": "Eiffel Tower (Paris, France)" },
        { "zh": "卢浮宫", "en": "Louvre Museum (France)" },
        { "zh": "巴黎圣母院", "en": "Notre Dame Cathedral (Paris, France)" },
        { "zh": "凯旋门", "en": "Arc de Triomphe (Paris, France)" },
        { "zh": "凡尔赛宫", "en": "Palace of Versailles (France)" },
        { "zh": "香榭丽舍大街", "en": "Champs-Élysées (Paris, France)" },
        { "zh": "塞纳河", "en": "Seine River (France)" },
        { "zh": "圣米歇尔山", "en": "Mont Saint-Michel (France)" },
        { "zh": "普罗旺斯薰衣草田", "en": "Lavender Fields of Provence (France)" },
        { "zh": "尼斯蔚蓝海岸", "en": "French Riviera (Nice, France)" },
        { "zh": "勃朗峰", "en": "Mont Blanc (France)" },
        { "zh": "罗马斗兽场", "en": "Colosseum (Rome, Italy)" },
        { "zh": "特莱维喷泉", "en": "Trevi Fountain (Rome, Italy)" },
        { "zh": "罗马万神殿", "en": "Pantheon (Rome, Italy)" },
        { "zh": "圣彼得大教堂", "en": "St. Peter's Basilica (Vatican City)" },
        { "zh": "梵蒂冈博物馆", "en": "Vatican Museums" },
        { "zh": "比萨斜塔", "en": "Leaning Tower of Pisa (Italy)" },
        { "zh": "佛罗伦萨圣母百花大教堂", "en": "Florence Cathedral (Duomo, Italy)" },
        { "zh": "威尼斯大运河", "en": "Grand Canal (Venice, Italy)" },
        { "zh": "圣马可广场", "en": "St. Mark's Square (Venice, Italy)" },
        { "zh": "米兰大教堂", "en": "Milan Cathedral (Duomo, Italy)" },
        { "zh": "庞贝古城", "en": "Pompeii (Italy)" },
        { "zh": "卡普里岛蓝洞", "en": "Blue Grotto (Capri, Italy)" },
        { "zh": "科莫湖", "en": "Lake Como (Italy)" },
        { "zh": "五渔村", "en": "Cinque Terre (Italy)" },
        { "zh": "阿马尔菲海岸", "en": "Amalfi Coast (Italy)" },
        { "zh": "雅典卫城", "en": "Acropolis of Athens (Greece)" },
        { "zh": "帕特农神庙", "en": "Parthenon (Greece)" },
        { "zh": "圣托里尼岛", "en": "Santorini (Greece)" },
        { "zh": "米科诺斯岛", "en": "Mykonos (Greece)" },
        { "zh": "德尔菲遗址", "en": "Delphi (Greece)" },
        { "zh": "梅黛奥拉修道院", "en": "Meteora (Greece)" },
        { "zh": "克里特岛", "en": "Crete (Greece)" },
        { "zh": "大本钟", "en": "Big Ben (London, UK)" },
        { "zh": "伦敦塔桥", "en": "Tower Bridge (London, UK)" },
        { "zh": "白金汉宫", "en": "Buckingham Palace (UK)" },
        { "zh": "大英博物馆", "en": "British Museum (UK)" },
        { "zh": "威斯敏斯特教堂", "en": "Westminster Abbey (UK)" },
        { "zh": "巨石阵", "en": "Stonehenge (UK)" },
        { "zh": "苏格兰高地", "en": "Scottish Highlands (UK)" },
        { "zh": "爱丁堡城堡", "en": "Edinburgh Castle (UK)" },
        { "zh": "尼斯湖", "en": "Loch Ness (UK)" },
        { "zh": "温莎城堡", "en": "Windsor Castle (UK)" },
        { "zh": "巴斯罗马浴场", "en": "Roman Baths (Bath, UK)" },
        { "zh": "伦敦眼", "en": "London Eye (UK)" },
        { "zh": "国王十字车站 (9¾站台)", "en": "King's Cross Station (Platform 9¾, UK)" },
        { "zh": "格林威治皇家天文台", "en": "Royal Observatory Greenwich (UK)" },
        { "zh": "圣保罗大教堂", "en": "St Paul's Cathedral (UK)" },
        { "zh": "柏林勃兰登堡门", "en": "Brandenburg Gate (Berlin, Germany)" },
        { "zh": "柏林墙纪念碑", "en": "Berlin Wall Memorial (Germany)" },
        { "zh": "科隆大教堂", "en": "Cologne Cathedral (Germany)" },
        { "zh": "新天鹅堡", "en": "Neuschwanstein Castle (Germany)" },
        { "zh": "慕尼黑玛丽亚广场", "en": "Marienplatz (Munich, Germany)" },
        { "zh": "黑森林", "en": "Black Forest (Germany)" },
        { "zh": "国王湖", "en": "Königssee (Germany)" },
        { "zh": "莱茵河", "en": "Rhine River (Germany)" },
        { "zh": "巴伐利亚阿尔卑斯山", "en": "Bavarian Alps (Germany)" },
        { "zh": "德累斯顿圣母教堂", "en": "Frauenkirche (Dresden, Germany)" },
        { "zh": "汉堡仓库城", "en": "Speicherstadt (Hamburg, Germany)" },
        { "zh": "西班牙圣家族大教堂", "en": "Sagrada Família (Barcelona, Spain)" },
        { "zh": "巴特罗之家", "en": "Casa Batlló (Barcelona, Spain)" },
        { "zh": "古埃尔公园", "en": "Park Güell (Barcelona, Spain)" },
        { "zh": "阿兰布拉宫", "en": "Alhambra (Granada, Spain)" },
        { "zh": "马德里普拉多博物馆", "en": "Prado Museum (Madrid, Spain)" },
        { "zh": "塞维利亚大教堂", "en": "Seville Cathedral (Spain)" },
        { "zh": "直布罗陀巨岩", "en": "Rock of Gibraltar (UK/Spain)" },
        { "zh": "马略卡岛", "en": "Majorca (Spain)" },
        { "zh": "伊比萨岛", "en": "Ibiza (Spain)" },
        { "zh": "托莱多古城", "en": "Toledo (Spain)" },
        { "zh": "瓦伦西亚艺术科学城", "en": "City of Arts and Sciences (Valencia, Spain)" },
        { "zh": "葡萄牙里斯本贝伦塔", "en": "Belém Tower (Lisbon, Portugal)" },
        { "zh": "辛特拉佩纳宫", "en": "Pena Palace (Sintra, Portugal)" },
        { "zh": "杜罗河谷", "en": "Douro Valley (Portugal)" },
        { "zh": "阿尔加维海滩", "en": "Algarve Beaches (Portugal)" },
        { "zh": "波尔图历史中心", "en": "Historic Centre of Porto (Portugal)" },
        { "zh": "瑞士马特洪峰", "en": "Matterhorn (Switzerland)" },
        { "zh": "少女峰", "en": "Jungfraujoch (Switzerland)" },
        { "zh": "日内瓦湖", "en": "Lake Geneva (Switzerland)" },
        { "zh": "苏黎世湖", "en": "Lake Zurich (Switzerland)" },
        { "zh": "琉森湖", "en": "Lake Lucerne (Switzerland)" },
        { "zh": "因特拉肯", "en": "Interlaken (Switzerland)" },
        { "zh": "莱茵瀑布", "en": "Rhine Falls (Switzerland)" },
        { "zh": "采尔马特", "en": "Zermatt (Switzerland)" },
        { "zh": "奥地利维也纳美泉宫", "en": "Schönbrunn Palace (Vienna, Austria)" },
        { "zh": "圣斯蒂芬大教堂", "en": "St. Stephen's Cathedral (Vienna, Austria)" },
        { "zh": "哈尔施塔特", "en": "Hallstatt (Austria)" },
        { "zh": "萨尔茨堡老城", "en": "Historic Centre of the City of Salzburg (Austria)" },
        { "zh": "大钟山高山公路", "en": "Grossglockner High Alpine Road (Austria)" },
        { "zh": "匈牙利布达佩斯国会大厦", "en": "Hungarian Parliament Building (Budapest, Hungary)" },
        { "zh": "渔人堡", "en": "Fisherman's Bastion (Hungary)" },
        { "zh": "链子桥", "en": "Chain Bridge (Hungary)" },
        { "zh": "罗马尼亚布兰城堡 (吸血鬼城堡)", "en": "Bran Castle (Dracula's Castle, Romania)" },
        { "zh": "布加勒斯特人民宫", "en": "Palace of the Parliament (Bucharest, Romania)" },
        { "zh": "保加利亚里拉修道院", "en": "Rila Monastery (Bulgaria)" },
        { "zh": "圣亚历山大·涅夫斯基大教堂", "en": "Alexander Nevsky Cathedral (Bulgaria)" },
        { "zh": "俄罗斯莫斯科红场", "en": "Red Square (Moscow, Russia)" },
        { "zh": "圣瓦西里大教堂", "en": "St. Basil's Cathedral (Moscow, Russia)" },
        { "zh": "克里姆林宫", "en": "Moscow Kremlin (Russia)" },
        { "zh": "圣彼得堡冬宫博物馆", "en": "Hermitage Museum (St. Petersburg, Russia)" },
        { "zh": "滴血救世主教堂", "en": "Church of the Savior on Spilled Blood (St. Petersburg, Russia)" },
        { "zh": "贝加尔湖", "en": "Lake Baikal (Russia)" },
        { "zh": "冰岛蓝湖", "en": "Blue Lagoon (Iceland)" },
        { "zh": "黄金圈", "en": "Golden Circle (Iceland)" },
        { "zh": "斯科加瀑布", "en": "Skógafoss (Iceland)" },
        { "zh": "杰古沙龙冰河湖", "en": "Jökulsárlón Glacier Lagoon (Iceland)" },
        { "zh": "极光", "en": "Northern Lights (Iceland/Scandinavia)" },
        { "zh": "挪威峡湾", "en": "Norwegian Fjords (Norway)" },
        { "zh": "布吕根", "en": "Bryggen (Bergen, Norway)" },
        { "zh": "盖朗厄尔峡湾", "en": "Geirangerfjord (Norway)" },
        { "zh": "恶魔之舌", "en": "Trolltunga (Norway)" },
        { "zh": "丹麦哥本哈根小美人鱼雕像", "en": "The Little Mermaid (Copenhagen, Denmark)" },
        { "zh": "新港", "en": "Nyhavn (Copenhagen, Denmark)" },
        { "zh": "瑞典斯德哥尔摩老城", "en": "Gamla Stan (Stockholm, Sweden)" },
        { "zh": "瓦萨博物馆", "en": "Vasa Museum (Sweden)" },
        { "zh": "芬兰赫尔辛基大教堂", "en": "Helsinki Cathedral (Finland)" },
        { "zh": "罗瓦涅米圣诞老人村", "en": "Santa Claus Village (Rovaniemi, Finland)" },
        { "zh": "波兰克拉科夫瓦维尔城堡", "en": "Wawel Castle (Kraków, Poland)" },
        { "zh": "华沙老城", "en": "Old Town (Warsaw, Poland)" },
        { "zh": "维利奇卡盐矿", "en": "Wieliczka Salt Mine (Poland)" },
        { "zh": "捷克布拉格查理大桥", "en": "Charles Bridge (Prague, Czech Republic)" },
        { "zh": "布拉格城堡", "en": "Prague Castle (Czech Republic)" },
        { "zh": "老城广场", "en": "Old Town Square (Prague, Czech Republic)" },
        { "zh": "克鲁姆洛夫", "en": "Český Krumlov (Czech Republic)" },
        { "zh": "荷兰阿姆斯特丹风车村", "en": "Zaanse Schans (Netherlands)" },
        { "zh": "运河", "en": "Canals of Amsterdam (Netherlands)" },
        { "zh": "库肯霍夫公园", "en": "Keukenhof Gardens (Netherlands)" },
        { "zh": "比利时布鲁塞尔大广场", "en": "Grand Place (Brussels, Belgium)" },
        { "zh": "撒尿小童", "en": "Manneken Pis (Belgium)" },
        { "zh": "布鲁日老城", "en": "Historic Centre of Bruges (Belgium)" },
        { "zh": "爱尔兰都柏林圣三一学院", "en": "Trinity College Dublin (Ireland)" },
        { "zh": "莫赫悬崖", "en": "Cliffs of Moher (Ireland)" },
        { "zh": "巨人之路", "en": "Giant's Causeway (Northern Ireland, UK)" },
        { "zh": "克罗地亚杜布罗夫尼克老城墙", "en": "Walls of Dubrovnik (Croatia)" },
        { "zh": "十六湖国家公园", "en": "Plitvice Lakes National Park (Croatia)" },
        { "zh": "斯普利特戴克里先宫", "en": "Diocletian's Palace (Split, Croatia)" },
        { "zh": "斯洛文尼亚布莱德湖", "en": "Lake Bled (Slovenia)" },
        { "zh": "波斯托伊纳溶洞", "en": "Postojna Cave (Slovenia)" },
        { "zh": "马耳他瓦莱塔", "en": "Valletta (Malta)" },
        { "zh": "蓝窗 (已塌)", "en": "Azure Window (Malta, collapsed)" },
        { "zh": "塞浦路斯帕福斯古城", "en": "Paphos Archaeological Park (Cyprus)" },
        { "zh": "黎明女神海滩", "en": "Fig Tree Bay (Cyprus)" },
        { "zh": "摩纳哥亲王宫", "en": "Prince's Palace of Monaco (Monaco)" },
        { "zh": "圣马力诺蒙特蒂塔诺山", "en": "Monte Titano (San Marino)" },
        { "zh": "列支敦士登瓦杜兹城堡", "en": "Vaduz Castle (Liechtenstein)" },
        { "zh": "立陶宛维尔纽斯老城", "en": "Vilnius Old Town (Lithuania)" },
        { "zh": "十字架山", "en": "Hill of Crosses (Lithuania)" },
        { "zh": "拉脱维亚里加老城", "en": "Old Town of Riga (Latvia)" },
        { "zh": "爱沙尼亚塔林老城", "en": "Tallinn Old Town (Estonia)" },
        { "zh": "乌克兰基辅圣索菲亚大教堂", "en": "Saint Sophia Cathedral (Kyiv, Ukraine)" },
        { "zh": "切尔诺贝利", "en": "Chernobyl (Ukraine)" },
        { "zh": "白俄罗斯明斯克胜利广场", "en": "Victory Square (Minsk, Belarus)" },
        { "zh": "摩尔多瓦基希纳乌胜利门", "en": "Triumphal Arch (Chișinău, Moldova)" },
        { "zh": "格鲁吉亚第比利斯老城", "en": "Old Town of Tbilisi (Georgia)" },
        { "zh": "乌兹别克塔什干地震纪念碑", "en": "Earthquake Memorial (Tashkent, Uzbekistan)" },
        { "zh": "阿塞拜疆巴库老城", "en": "Old City (Baku, Azerbaijan)" },
        { "zh": "火焰塔", "en": "Flame Towers (Azerbaijan)" },
        { "zh": "冰岛蓝湖", "en": "Blue Lagoon (Iceland)" },
        { "zh": "斯洛伐克布拉迪斯拉发城堡", "en": "Bratislava Castle (Slovakia)" }
      ]
    },
    {
      "name": "北美洲名胜 (North American Landmarks)",
      "tags": [
        { "zh": "自由女神像", "en": "Statue of Liberty (New York, USA)" },
        { "zh": "时代广场", "en": "Times Square (New York, USA)" },
        { "zh": "帝国大厦", "en": "Empire State Building (New York, USA)" },
        { "zh": "中央公园", "en": "Central Park (New York, USA)" },
        { "zh": "金门大桥", "en": "Golden Gate Bridge (San Francisco, USA)" },
        { "zh": "渔人码头", "en": "Fisherman's Wharf (San Francisco, USA)" },
        { "zh": "阿尔卡特拉斯岛", "en": "Alcatraz Island (USA)" },
        { "zh": "好莱坞标志", "en": "Hollywood Sign (Los Angeles, USA)" },
        { "zh": "星光大道", "en": "Hollywood Walk of Fame (Los Angeles, USA)" },
        { "zh": "黄石国家公园", "en": "Yellowstone National Park (USA)" },
        { "zh": "大峡谷国家公园", "en": "Grand Canyon National Park (USA)" },
        { "zh": "优胜美地国家公园", "en": "Yosemite National Park (USA)" },
        { "zh": "拉什莫尔山国家纪念公园", "en": "Mount Rushmore National Memorial (USA)" },
        { "zh": "林肯纪念堂", "en": "Lincoln Memorial (Washington D.C., USA)" },
        { "zh": "华盛顿纪念碑", "en": "Washington Monument (Washington D.C., USA)" },
        { "zh": "白宫", "en": "White House (Washington D.C., USA)" },
        { "zh": "国会大厦", "en": "United States Capitol (Washington D.C., USA)" },
        { "zh": "拉斯维加斯大道", "en": "Las Vegas Strip (USA)" },
        { "zh": "尼亚加拉大瀑布", "en": "Niagara Falls (USA/Canada)" },
        { "zh": "芝加哥千禧公园", "en": "Millennium Park (Chicago, USA)" },
        { "zh": "太空针塔", "en": "Space Needle (Seattle, USA)" },
        { "zh": "波士顿自由之路", "en": "Freedom Trail (Boston, USA)" },
        { "zh": "迈阿密南海滩", "en": "South Beach (Miami, USA)" },
        { "zh": "奥兰多华特迪士尼世界度假区", "en": "Walt Disney World Resort (Orlando, USA)" },
        { "zh": "大烟山国家公园", "en": "Great Smoky Mountains National Park (USA)" },
        { "zh": "優勝美地国家公园", "en": "Yosemite National Park (USA)" },
        { "zh": "拱门国家公园", "en": "Arches National Park (USA)" },
        { "zh": "锡安国家公园", "en": "Zion National Park (USA)" },
        { "zh": "布莱斯峡谷国家公园", "en": "Bryce Canyon National Park (USA)" },
        { "zh": "纪念碑谷", "en": "Monument Valley (USA)" },
        { "zh": "死亡谷国家公园", "en": "Death Valley National Park (USA)" },
        { "zh": "红杉国家公园", "en": "Sequoia National Park (USA)" },
        { "zh": "冰川国家公园", "en": "Glacier National Park (USA)" },
        { "zh": "大提顿国家公园", "en": "Grand Teton National Park (USA)" },
        { "zh": "火山口湖国家公园", "en": "Crater Lake National Park (USA)" },
        { "zh": "夏威夷火山国家公园", "en": "Hawaii Volcanoes National Park (USA)" },
        { "zh": "茂宜岛", "en": "Maui (USA)" },
        { "zh": "欧胡岛珍珠港", "en": "Pearl Harbor (Oahu, USA)" },
        { "zh": "阿拉斯加迪纳利国家公园", "en": "Denali National Park (Alaska, USA)" },
        { "zh": "加拿大班夫国家公园", "en": "Banff National Park (Canada)" },
        { "zh": "路易斯湖", "en": "Lake Louise (Canada)" },
        { "zh": "贾斯珀国家公园", "en": "Jasper National Park (Canada)" },
        { "zh": "梦莲湖", "en": "Moraine Lake (Canada)" },
        { "zh": "落基山脉", "en": "Canadian Rockies (Canada)" },
        { "zh": "CN塔", "en": "CN Tower (Toronto, Canada)" },
        { "zh": "蒙特利尔圣约瑟夫大教堂", "en": "Saint Joseph's Oratory (Montreal, Canada)" },
        { "zh": "魁北克城老城区", "en": "Old Quebec (Canada)" },
        { "zh": "温哥华斯坦利公园", "en": "Stanley Park (Vancouver, Canada)" },
        { "zh": "墨西哥奇琴伊察玛雅遗址", "en": "Chichen Itza (Mexico)" },
        { "zh": "墨西哥城大都会主教座堂", "en": "Metropolitan Cathedral (Mexico City, Mexico)" },
        { "zh": "特奥蒂瓦坎", "en": "Teotihuacan (Mexico)" },
        { "zh": "坎昆海滩", "en": "Cancun Beaches (Mexico)" },
        { "zh": "图卢姆遗址", "en": "Tulum (Mexico)" },
        { "zh": "天使独立纪念柱", "en": "Angel of Independence (Mexico City, Mexico)" },
        { "zh": "古巴哈瓦那旧城", "en": "Old Havana (Cuba)" },
        { "zh": "百老汇大街", "en": "Broadway (New York, USA)" },
        { "zh": "自由钟", "en": "Liberty Bell (Philadelphia, USA)" },
        { "zh": "波托马克河", "en": "Potomac River (USA)" },
        { "zh": "科罗拉多大峡谷", "en": "Grand Canyon (USA)" },
        { "zh": "優勝美地国家公园", "en": "Yosemite National Park (USA)" },
        { "zh": "班夫国家公园", "en": "Banff National Park (Canada)" },
        { "zh": "洛矶山脉", "en": "Rocky Mountains (Canada/USA)" },
        { "zh": "冰原大道", "en": "Icefields Parkway (Canada)" },
        { "zh": "维多利亚布查特花园", "en": "Butchart Gardens (Victoria, Canada)" },
        { "zh": "墨西哥城国家人类学博物馆", "en": "National Museum of Anthropology (Mexico City, Mexico)" },
        { "zh": "奇琴伊察", "en": "Chichen Itza (Mexico)" },
        { "zh": "坎昆", "en": "Cancun (Mexico)" },
        { "zh": "圣胡安老城", "en": "Old San Juan (Puerto Rico)" },
        { "zh": "波多黎各雨林", "en": "El Yunque National Forest (Puerto Rico)" },
        { "zh": "洪都拉斯科潘玛雅遗址", "en": "Copán (Honduras)" },
        { "zh": "危地马拉蒂卡尔国家公园", "en": "Tikal National Park (Guatemala)" },
        { "zh": "安提瓜古城", "en": "Antigua Guatemala" },
        { "zh": "哥斯达黎加阿雷纳尔火山", "en": "Arenal Volcano (Costa Rica)" },
        { "zh": "蒙特维多云雾森林", "en": "Monteverde Cloud Forest (Costa Rica)" },
        { "zh": "巴拿马运河", "en": "Panama Canal (Panama)" },
        { "zh": "特拉华州大峡谷", "en": "Grand Canyon of Pennsylvania (USA)" },
        { "zh": "肖尼国家森林公园", "en": "Shawnee National Forest (Illinois, USA)" },
        { "zh": "路易斯安那州新奥尔良法国区", "en": "French Quarter (New Orleans, USA)" },
        { "zh": "德克萨斯州圣安东尼奥阿拉莫", "en": "The Alamo (San Antonio, USA)" }
      ]
    },
    {
      "name": "南美洲名胜 (South American Landmarks)",
      "tags": [
        { "zh": "里约热内卢基督像", "en": "Christ the Redeemer (Rio de Janeiro, Brazil)" },
        { "zh": "伊瓜苏大瀑布", "en": "Iguazu Falls (Brazil/Argentina)" },
        { "zh": "亚马逊雨林", "en": "Amazon Rainforest (Brazil/Peru/etc.)" },
        { "zh": "糖面包山", "en": "Sugarloaf Mountain (Rio de Janeiro, Brazil)" },
        { "zh": "科帕卡巴纳海滩", "en": "Copacabana Beach (Rio de Janeiro, Brazil)" },
        { "zh": "马丘比丘", "en": "Machu Picchu (Peru)" },
        { "zh": "库斯科", "en": "Cusco (Peru)" },
        { "zh": "的喀喀湖", "en": "Lake Titicaca (Peru/Bolivia)" },
        { "zh": "纳斯卡地画", "en": "Nazca Lines (Peru)" },
        { "zh": "盐湖 (乌尤尼盐沼)", "en": "Salar de Uyuni (Bolivia)" },
        { "zh": "拉巴斯女巫市场", "en": "Witches' Market (La Paz, Bolivia)" },
        { "zh": "布宜诺斯艾利斯科隆剧院", "en": "Teatro Colón (Buenos Aires, Argentina)" },
        { "zh": "雷科莱塔公墓", "en": "Recoleta Cemetery (Buenos Aires, Argentina)" },
        { "zh": "冰川国家公园 (阿根廷)", "en": "Los Glaciares National Park (Argentina)" },
        { "zh": "莫雷诺冰川", "en": "Perito Moreno Glacier (Argentina)" },
        { "zh": "火地岛国家公园", "en": "Tierra del Fuego National Park (Argentina)" },
        { "zh": "百内国家公园", "en": "Torres del Paine National Park (Chile)" },
        { "zh": "复活节岛", "en": "Easter Island (Chile)" },
        { "zh": "阿塔卡马沙漠", "en": "Atacama Desert (Chile)" },
        { "zh": "圣地亚哥", "en": "Santiago (Chile)" },
        { "zh": "加拉帕戈斯群岛", "en": "Galapagos Islands (Ecuador)" },
        { "zh": "基多老城", "en": "Historic Centre of Quito (Ecuador)" },
        { "zh": "哥伦比亚卡塔赫纳老城", "en": "Walled City of Cartagena (Colombia)" },
        { "zh": "麦德林", "en": "Medellin (Colombia)" },
        { "zh": "玻利维亚乌尤尼盐沼", "en": "Salar de Uyuni (Bolivia)" },
        { "zh": "圭亚那凯厄图尔瀑布", "en": "Kaieteur Falls (Guyana)" },
        { "zh": "委内瑞拉安赫尔瀑布", "en": "Angel Falls (Venezuela)" },
        { "zh": "罗赖马山", "en": "Mount Roraima (Venezuela)" },
        { "zh": "苏里南帕拉马里博内城", "en": "Historic Inner City of Paramaribo (Suriname)" },
        { "zh": "法属圭亚那库鲁航天中心", "en": "Guiana Space Centre (French Guiana)" },
        { "zh": "乌拉圭蒙得维的亚旧城", "en": "Ciudad Vieja (Montevideo, Uruguay)" },
        { "zh": "巴西里约热内卢贫民窟", "en": "Favelas of Rio de Janeiro (Brazil)" },
        { "zh": "萨尔瓦多历史中心", "en": "Historic Centre of Salvador de Bahia (Brazil)" },
        { "zh": "玛瑙斯亚马逊剧院", "en": "Manaus Opera House (Brazil)" },
        { "zh": "蓬塔阿雷纳斯", "en": "Punta Arenas (Chile)" }
      ]
    },
    {
      "name": "非洲名胜 (African Landmarks)",
      "tags": [
        { "zh": "吉萨金字塔", "en": "Pyramids of Giza (Egypt)" },
        { "zh": "狮身人面像", "en": "Great Sphinx of Giza (Egypt)" },
        { "zh": "卢克索神庙", "en": "Luxor Temple (Egypt)" },
        { "zh": "卡纳克神庙", "en": "Karnak Temple (Egypt)" },
        { "zh": "阿布辛贝神庙", "en": "Abu Simbel Temples (Egypt)" },
        { "zh": "尼罗河", "en": "Nile River (Egypt)" },
        { "zh": "开罗汗哈利利大市集", "en": "Khan el-Khalili (Cairo, Egypt)" },
        { "zh": "阿斯旺高坝", "en": "Aswan High Dam (Egypt)" },
        { "zh": "撒哈拉沙漠", "en": "Sahara Desert" },
        { "zh": "开普敦桌山", "en": "Table Mountain (Cape Town, South Africa)" },
        { "zh": "好望角", "en": "Cape of Good Hope (South Africa)" },
        { "zh": "克鲁格国家公园", "en": "Kruger National Park (South Africa)" },
        { "zh": "罗本岛", "en": "Robben Island (South Africa)" },
        { "zh": "花园大道", "en": "Garden Route (South Africa)" },
        { "zh": "维多利亚瀑布", "en": "Victoria Falls (Zambia/Zimbabwe)" },
        { "zh": "马赛马拉国家保护区", "en": "Maasai Mara National Reserve (Kenya)" },
        { "zh": "乞力马扎罗山", "en": "Mount Kilimanjaro (Tanzania)" },
        { "zh": "塞伦盖蒂国家公园", "en": "Serengeti National Park (Tanzania)" },
        { "zh": "恩戈罗恩戈罗火山口", "en": "Ngorongoro Crater (Tanzania)" },
        { "zh": "桑给巴尔石头城", "en": "Stone Town (Zanzibar, Tanzania)" },
        { "zh": "摩洛哥马拉喀什不眠广场", "en": "Jemaa el-Fnaa (Marrakech, Morocco)" },
        { "zh": "舍夫沙万", "en": "Chefchaouen (Morocco)" },
        { "zh": "菲斯古城", "en": "Fes el Bali (Morocco)" },
        { "zh": "卡萨布兰卡哈桑二世清真寺", "en": "Hassan II Mosque (Casablanca, Morocco)" },
        { "zh": "突尼斯迦太基遗址", "en": "Carthage (Tunisia)" },
        { "zh": "西迪布赛德", "en": "Sidi Bou Said (Tunisia)" },
        { "zh": "阿尔及利亚杰米拉古罗马遗址", "en": "Djémila (Algeria)" },
        { "zh": "埃塞俄比亚拉利贝拉岩石教堂", "en": "Rock-Hewn Churches of Lalibela (Ethiopia)" },
        { "zh": "达纳基勒凹地", "en": "Danakil Depression (Ethiopia)" },
        { "zh": "摩尔人王朝遗址", "en": "Fasil Ghebbi (Gonder, Ethiopia)" },
        { "zh": "马达加斯加猴面包树大道", "en": "Avenue of the Baobabs (Madagascar)" },
        { "zh": "石林", "en": "Tsingy de Bemaraha (Madagascar)" },
        { "zh": "毛里求斯七色土", "en": "Seven Coloured Earths (Mauritius)" },
        { "zh": "塞舌尔马埃岛", "en": "Mahé Island (Seychelles)" },
        { "zh": "博茨瓦纳奥卡万戈三角洲", "en": "Okavango Delta (Botswana)" },
        { "zh": "纳米比亚纳米布沙漠", "en": "Namib Desert (Namibia)" },
        { "zh": "死亡谷 (纳米比亚)", "en": "Deadvlei (Namibia)" },
        { "zh": "埃托沙国家公园", "en": "Etosha National Park (Namibia)" },
        { "zh": "津巴布韦大津巴布韦遗址", "en": "Great Zimbabwe (Zimbabwe)" },
        { "zh": "赞比亚南卢安瓦国家公园", "en": "South Luangwa National Park (Zambia)" },
        { "zh": "马拉维湖", "en": "Lake Malawi (Malawi)" },
        { "zh": "卢旺达火山国家公园", "en": "Volcanoes National Park (Rwanda)" },
        { "zh": "乌干达布温迪国家公园 (大猩猩)", "en": "Bwindi Impenetrable Forest (Uganda)" },
        { "zh": "刚果维龙加国家公园", "en": "Virunga National Park (DR Congo)" },
        { "zh": "尼日利亚阿布贾阿索岩", "en": "Aso Rock (Abuja, Nigeria)" },
        { "zh": "加纳埃尔米纳城堡", "en": "Elmina Castle (Ghana)" },
        { "zh": "塞内加尔戈雷岛", "en": "Gorée Island (Senegal)" },
        { "zh": "佛得角圣地亚哥岛 (老城)", "en": "Cidade Velha (Cape Verde)" }
      ]
    },
    {
      "name": "大洋洲名胜 (Oceanian Landmarks)",
      "tags": [
        { "zh": "悉尼歌剧院", "en": "Sydney Opera House (Australia)" },
        { "zh": "悉尼海港大桥", "en": "Sydney Harbour Bridge (Australia)" },
        { "zh": "邦迪海滩", "en": "Bondi Beach (Australia)" },
        { "zh": "大堡礁", "en": "Great Barrier Reef (Australia)" },
        { "zh": "艾尔斯岩 (乌鲁鲁)", "en": "Uluru (Ayers Rock, Australia)" },
        { "zh": "悉尼蓝山国家公园", "en": "Blue Mountains National Park (Australia)" },
        { "zh": "墨尔本大洋路十二门徒", "en": "Twelve Apostles (Great Ocean Road, Australia)" },
        { "zh": "黄金海岸", "en": "Gold Coast (Australia)" },
        { "zh": "袋鼠岛", "en": "Kangaroo Island (Australia)" },
        { "zh": "塔斯马尼亚摇篮山", "en": "Cradle Mountain (Tasmania, Australia)" },
        { "zh": "弗雷泽岛", "en": "Fraser Island (Australia)" },
        { "zh": "新西兰米尔福德峡湾", "en": "Milford Sound (New Zealand)" },
        { "zh": "皇后镇", "en": "Queenstown (New Zealand)" },
        { "zh": "奥克兰天空塔", "en": "Sky Tower (Auckland, New Zealand)" },
        { "zh": "罗托鲁瓦地热公园", "en": "Rotorua (New Zealand)" },
        { "zh": "霍比屯 (霍比特村)", "en": "Hobbiton Movie Set (New Zealand)" },
        { "zh": "南岛冰川", "en": "Franz Josef Glacier (New Zealand)" },
        { "zh": "库克山国家公园", "en": "Aoraki / Mount Cook National Park (New Zealand)" },
        { "zh": "瓦纳卡湖", "en": "Lake Wanaka (New Zealand)" },
        { "zh": "斐济主岛", "en": "Viti Levu (Fiji)" },
        { "zh": "塔希提岛", "en": "Tahiti (French Polynesia)" },
        { "zh": "博拉博拉岛", "en": "Bora Bora (French Polynesia)" },
        { "zh": "帕劳水母湖", "en": "Jellyfish Lake (Palau)" },
        { "zh": "瓦努阿图伊苏尔火山", "en": "Mount Yasur (Vanuatu)" },
        { "zh": "新喀里多尼亚泻湖", "en": "New Caledonia Lagoon" },
        { "zh": "美属萨摩亚国家公园", "en": "National Park of American Samoa" },
        { "zh": "复活节岛", "en": "Easter Island (Chile, technically Oceania)" }
      ]
    },
    {
      "name": "极地名胜 (Polar Landmarks)",
      "tags": [
        { "zh": "南极半岛", "en": "Antarctic Peninsula" },
        { "zh": "德雷克海峡", "en": "Drake Passage" },
        { "zh": "罗斯海", "en": "Ross Sea (Antarctica)" },
        { "zh": "企鹅栖息地", "en": "Penguin Colonies" },
        { "zh": "冰山", "en": "Icebergs" },
        { "zh": "北极圈", "en": "Arctic Circle" },
        { "zh": "斯瓦尔巴群岛", "en": "Svalbard (Arctic)" },
        { "zh": "格陵兰岛冰盖", "en": "Greenland Ice Sheet" },
        { "zh": "北极熊栖息地", "en": "Polar Bear Habitats" },
        { "zh": "极光", "en": "Aurora Borealis (Northern Lights)" },
        { "zh": "极光", "en": "Aurora Australis (Southern Lights)" },
        { "zh": "冰洞", "en": "Ice Caves" },
        { "zh": "冰川", "en": "Glaciers" }
      ]
    },
    {
      "name": "地标类型 (Landmark Type)",
      "tags": [
        { "zh": "山脉", "en": "Mountains" },
        { "zh": "湖泊", "en": "Lakes" },
        { "zh": "河流", "en": "Rivers" },
        { "zh": "峡谷", "en": "Canyons" },
        { "zh": "瀑布", "en": "Waterfalls" },
        { "zh": "沙漠", "en": "Deserts" },
        { "zh": "森林", "en": "Forests" },
        { "zh": "冰川", "en": "Glaciers" },
        { "zh": "海滩", "en": "Beaches" },
        { "zh": "岛屿", "en": "Islands" },
        { "zh": "火山", "en": "Volcanoes" },
        { "zh": "国家公园", "en": "National Parks" },
        { "zh": "世界遗产地", "en": "World Heritage Sites" },
        { "zh": "古城", "en": "Ancient Cities" },
        { "zh": "历史遗迹", "en": "Historical Sites" },
        { "zh": "宫殿", "en": "Palaces" },
        { "zh": "城堡", "en": "Castles" },
        { "zh": "寺庙", "en": "Temples" },
        { "zh": "清真寺", "en": "Mosques" },
        { "zh": "教堂", "en": "Churches" },
        { "zh": "桥", "en": "Bridges" },
        { "zh": "塔", "en": "Towers" },
        { "zh": "纪念碑", "en": "Monuments" },
        { "zh": "博物馆", "en": "Museums" },
        { "zh": "广场", "en": "Plazas/Squares" },
        { "zh": "花园", "en": "Gardens" },
        { "zh": "市场", "en": "Markets" },
        { "zh": "动物园", "en": "Zoos" },
        { "zh": "水族馆", "en": "Aquariums" },
        { "zh": "主题公园", "en": "Theme Parks" },
        { "zh": "观景台", "en": "Viewpoints" },
        { "zh": "天际线", "en": "Skyline" },
        { "zh": "地热景观", "en": "Geothermal Landscapes" },
        { "zh": "洞穴", "en": "Caves" },
        { "zh": "峡湾", "en": "Fjords" },
        { "zh": "梯田", "en": "Terraced Fields" },
        { "zh": "盐沼/盐湖", "en": "Salt Flats/Salt Lakes" },
        { "zh": "热带雨林", "en": "Tropical Rainforests" },
        { "zh": "珊瑚礁", "en": "Coral Reefs" },
        { "zh": "海岸线", "en": "Coastlines" },
        { "zh": "戈壁", "en": "Gobi" },
        { "zh": "平原", "en": "Plains" },
        { "zh": "盆地", "en": "Basins" },
        { "zh": "丘陵", "en": "Hills" },
        { "zh": "高原", "en": "Plateaus" },
        { "zh": "冲积扇", "en": "Alluvial Fans" },
        { "zh": "堰塞湖", "en": "Barrier Lakes" },
        { "zh": "丹霞地貌", "en": "Danxia Landform" },
        { "zh": "喀斯特地貌", "en": "Karst Topography" },
        { "zh": "石林", "en": "Stone Forests" },
        { "zh": "风蚀地貌", "en": "Wind-eroded Landforms" },
        { "zh": "雅丹地貌", "en": "Yardang Landform" },
        { "zh": "火山地貌", "en": "Volcanic Landscape" },
        { "zh": "冰蚀地貌", "en": "Glacial Erosion Landform" },
        { "zh": "冰碛湖", "en": "Moraine Lake" },
        { "zh": "火山湖", "en": "Volcanic Lake" },
        { "zh": "火山口", "en": "Volcanic Craters" },
        { "zh": "温泉", "en": "Hot Springs" },
        { "zh": "间歇泉", "en": "Geysers" },
        { "zh": "瀑布群", "en": "Waterfall Clusters" },
        { "zh": "梯级瀑布", "en": "Cascading Waterfalls" },
        { "zh": "高山草甸", "en": "Alpine Meadows" },
        { "zh": "高山湖泊", "en": "Alpine Lakes" },
        { "zh": "雪山", "en": "Snow-capped Mountains" },
        { "zh": "雪原", "en": "Snowfields" },
        { "zh": "热带雨林", "en": "Tropical Rainforests" },
        { "zh": "红树林", "en": "Mangrove Forests" },
        { "zh": "针叶林", "en": "Coniferous Forests" },
        { "zh": "阔叶林", "en": "Broadleaf Forests" },
        { "zh": "戈壁滩", "en": "Gobi Desert" },
        { "zh": "沙丘", "en": "Sand Dunes" },
        { "zh": "绿洲", "en": "Oasis" },
        { "zh": "海岸线", "en": "Coastline" },
        { "zh": "海岛", "en": "Islands" },
        { "zh": "海湾", "en": "Bays" },
        { "zh": "海峡", "en": "Straits" },
        { "zh": "海蚀洞", "en": "Sea Caves" },
        { "zh": "砂岩", "en": "Sandstone" },
        { "zh": "石灰岩", "en": "Limestone" },
        { "zh": "玄武岩", "en": "Basalt" },
        { "zh": "火山岩", "en": "Volcanic Rock" },
        { "zh": "花岗岩", "en": "Granite" },
        { "zh": "板岩", "en": "Slate" },
        { "zh": "钟乳石", "en": "Stalactites" },
        { "zh": "石笋", "en": "Stalagmites" },
        { "zh": "石柱", "en": "Columns (geology)" },
        { "zh": "地下河", "en": "Underground Rivers" },
        { "zh": "天坑", "en": "Doline/Sinkhole" },
        { "zh": "悬崖", "en": "Cliffs" },
        { "zh": "峡湾", "en": "Fjords" },
        { "zh": "冰碛物", "en": "Moraine" },
        { "zh": "冲积平原", "en": "Alluvial Plain" },
        { "zh": "冲击瀑布", "en": "Plunge Pool Waterfall" },
        { "zh": "水下洞穴", "en": "Underwater Caves" },
        { "zh": "珊瑚礁", "en": "Coral Reefs" },
        { "zh": "海蚀柱", "en": "Sea Stacks" },
        { "zh": "海蚀拱", "en": "Sea Arches" },
        { "zh": "潮汐湖", "en": "Tidal Lagoons" },
        { "zh": "沙滩", "en": "Sandy Beaches" },
        { "zh": "鹅卵石滩", "en": "Pebble Beaches" },
        { "zh": "黑沙滩", "en": "Black Sand Beaches" },
        { "zh": "红沙滩", "en": "Red Sand Beaches" },
        { "zh": "绿沙滩", "en": "Green Sand Beaches" },
        { "zh": "白沙滩", "en": "White Sand Beaches" },
        { "zh": "自然桥", "en": "Natural Bridges" },
        { "zh": "石柱", "en": "Pillars" },
        { "zh": "峡谷", "en": "Gorges" },
        { "zh": "悬空寺", "en": "Hanging Monasteries" },
        { "zh": "窟", "en": "Grottoes" },
        { "zh": "石窟寺", "en": "Cave Temples" },
        { "zh": "壁画", "en": "Murals" },
        { "zh": "石刻", "en": "Rock Carvings" },
        { "zh": "雕塑", "en": "Sculptures" },
        { "zh": "古村落", "en": "Ancient Villages" },
        { "zh": "水乡古镇", "en": "Water Towns" },
        { "zh": "梯田", "en": "Terraced Fields" },
        { "zh": "梯田景色", "en": "Rice Terraces Landscape" },
        { "zh": "高山湖泊", "en": "High Mountain Lakes" },
        { "zh": "堰塞湖", "en": "Landslide Dammed Lakes" },
        { "zh": "沼泽地", "en": "Swamplands" },
        { "zh": "湿地公园", "en": "Wetland Parks" },
        { "zh": "国家湿地公园", "en": "National Wetland Parks" },
        { "zh": "野牛", "en": "Bison (wildlife)" },
        { "zh": "麋鹿", "en": "Elk (wildlife)" },
        { "zh": "熊", "en": "Bears (wildlife)" },
        { "zh": "狼", "en": "Wolves (wildlife)" },
        { "zh": "狐狸", "en": "Foxes (wildlife)" },
        { "zh": "鸟类", "en": "Birds (wildlife)" },
        { "zh": "水生生物", "en": "Aquatic life" },
        { "zh": "海洋生物", "en": "Marine life" },
        { "zh": "稀有动物", "en": "Rare animals" },
        { "zh": "濒危物种", "en": "Endangered species" },
        { "zh": "生态系统", "en": "Ecosystems" },
        { "zh": "生物多样性", "en": "Biodiversity" },
        { "zh": "动植物群", "en": "Flora and fauna" }
      ]
    },
    {
      "name": "地质景观 (Geological Features)",
      "tags": [
        { "zh": "火山口", "en": "Volcano Crater" },
        { "zh": "地热喷泉", "en": "Geothermal Hot Spring" },
        { "zh": "熔岩地貌", "en": "Lava Fields" },
        { "zh": "岩溶地貌", "en": "Karst Landscape" },
        { "zh": "钟乳石洞", "en": "Stalactite Caves" },
        { "zh": "石灰岩洞", "en": "Limestone Caves" },
        { "zh": "火山湖", "en": "Crater Lake" },
        { "zh": "冰河世纪遗迹", "en": "Ice Age Relics" },
        { "zh": "风化岩石", "en": "Weathered Rocks" },
        { "zh": "侵蚀地貌", "en": "Erosion Landforms" },
        { "zh": "沉积岩", "en": "Sedimentary Rock Formations" },
        { "zh": "断裂带", "en": "Fault Lines" },
        { "zh": "地质公园", "en": "Geoparks" },
        { "zh": "石林", "en": "Stone Forest" },
        { "zh": "峡谷", "en": "Canyon" },
        { "zh": "丹霞地貌", "en": "Danxia Landform" },
        { "zh": "砂岩地貌", "en": "Red Sandstone Landform" },
        { "zh": "玄武岩柱", "en": "Basalt Columns" },
        { "zh": "火山锥", "en": "Volcanic Cone" },
        { "zh": "活火山", "en": "Active Volcano" },
        { "zh": "死火山", "en": "Extinct Volcano" },
        { "zh": "休眠火山", "en": "Dormant Volcano" },
        { "zh": "地裂缝", "en": "Earth Fissures" },
        { "zh": "岩洞 (海蚀洞)", "en": "Sea Caves" },
        { "zh": "海蚀柱", "en": "Sea Stacks" },
        { "zh": "海蚀拱", "en": "Sea Arches" },
        { "zh": "峡湾", "en": "Fjord" },
        { "zh": "冰碛物", "en": "Moraine" },
        { "zh": "冰斗", "en": "Cirque" },
        { "zh": "冰川谷", "en": "Glacial Valley" },
        { "zh": "U形谷", "en": "U-shaped Valley" },
        { "zh": "V形谷", "en": "V-shaped Valley" },
        { "zh": "裂谷", "en": "Rift Valley" },
        { "zh": "盐滩", "en": "Salt Pan" },
        { "zh": "盐岩", "en": "Salt Formations" },
        { "zh": "天然气排放", "en": "Methane Seeps" },
        { "zh": "温泉泉眼", "en": "Hot Spring Vents" },
        { "zh": "间歇泉", "en": "Geyser" },
        { "zh": "泥火山", "en": "Mud Volcano" },
        { "zh": "地下水", "en": "Underground Water Systems" }
      ]
    },
    {
      "name": "建筑风格 (Architectural Style)",
      "tags": [
        { "zh": "古典主义", "en": "Classical Architecture" },
        { "zh": "哥特式", "en": "Gothic Architecture" },
        { "zh": "文艺复兴", "en": "Renaissance Architecture" },
        { "zh": "巴洛克", "en": "Baroque Architecture" },
        { "zh": "新古典主义", "en": "Neoclassical Architecture" },
        { "zh": "维多利亚式", "en": "Victorian Architecture" },
        { "zh": "装饰艺术", "en": "Art Deco Architecture" },
        { "zh": "现代主义", "en": "Modernist Architecture" },
        { "zh": "后现代主义", "en": "Postmodern Architecture" },
        { "zh": "当代建筑", "en": "Contemporary Architecture" },
        { "zh": "罗马式", "en": "Romanesque Architecture" },
        { "zh": "拜占庭式", "en": "Byzantine Architecture" },
        { "zh": "伊斯兰建筑", "en": "Islamic Architecture" },
        { "zh": "亚洲传统建筑", "en": "Traditional Asian Architecture" },
        { "zh": "中国传统建筑", "en": "Traditional Chinese Architecture" },
        { "zh": "日本传统建筑", "en": "Traditional Japanese Architecture" },
        { "zh": "印度教寺庙建筑", "en": "Hindu Temple Architecture" },
        { "zh": "玛雅建筑", "en": "Mayan Architecture" },
        { "zh": "印加建筑", "en": "Incan Architecture" },
        { "zh": "阿兹特克建筑", "en": "Aztec Architecture" },
        { "zh": "殖民时期建筑", "en": "Colonial Architecture" },
        { "zh": "野兽派建筑", "en": "Brutalist Architecture" },
        { "zh": "解构主义建筑", "en": "Deconstructivist Architecture" },
        { "zh": "新艺术运动", "en": "Art Nouveau Architecture" },
        { "zh": "包豪斯", "en": "Bauhaus Architecture" },
        { "zh": "未来主义建筑", "en": "Futuristic Architecture" },
        { "zh": "可持续建筑", "en": "Sustainable Architecture" },
        { "zh": "绿色建筑", "en": "Green Architecture" },
        { "zh": "木结构", "en": "Timber Structure" },
        { "zh": "石结构", "en": "Stone Structure" },
        { "zh": "砖结构", "en": "Brick Architecture" },
        { "zh": "钢结构", "en": "Steel Architecture" },
        { "zh": "玻璃幕墙", "en": "Glass Facade" },
        { "zh": "混凝土建筑", "en": "Concrete Architecture" },
        { "zh": "土木建筑", "en": "Earthen Architecture" },
        { "zh": "竹建筑", "en": "Bamboo Architecture" },
        { "zh": "参数化设计", "en": "Parametric Design" },
        { "zh": "智能建筑", "en": "Smart Building" }
      ]
    },
    {
      "name": "气候/季节 (Climate/Season)",
      "tags": [
        { "zh": "春日", "en": "Spring" },
        { "zh": "夏日", "en": "Summer" },
        { "zh": "秋日", "en": "Autumn/Fall" },
        { "zh": "冬日", "en": "Winter" },
        { "zh": "晴朗的天空", "en": "Clear Skies" },
        { "zh": "多云", "en": "Cloudy" },
        { "zh": "阴天", "en": "Overcast" },
        { "zh": "下雨", "en": "Rainy" },
        { "zh": "下雪", "en": "Snowy" },
        { "zh": "雾蒙蒙", "en": "Foggy" },
        { "zh": "多风", "en": "Windy" },
        { "zh": "阳光明媚", "en": "Sunny" },
        { "zh": "暴风雨", "en": "Stormy" },
        { "zh": "雪光", "en": "Snow-light" },
        { "zh": "金色的光", "en": "Golden Hour Light" },
        { "zh": "蓝色时刻", "en": "Blue Hour Light" },
        { "zh": "黎明", "en": "Dawn" },
        { "zh": "黄昏", "en": "Dusk" },
        { "zh": "白天", "en": "Daytime" },
        { "zh": "夜晚", "en": "Nighttime" },
        { "zh": "星空", "en": "Starry Sky" },
        { "zh": "银河", "en": "Milky Way" },
        { "zh": "日出", "en": "Sunrise" },
        { "zh": "日落", "en": "Sunset" },
        { "zh": "严寒", "en": "Severe Cold" },
        { "zh": "酷热", "en": "Extreme Heat" },
        { "zh": "温和", "en": "Temperate" },
        { "zh": "热带", "en": "Tropical" },
        { "zh": "亚热带", "en": "Subtropical" },
        { "zh": "极地", "en": "Polar Climate" },
        { "zh": "干旱", "en": "Arid" },
        { "zh": "湿润", "en": "Humid" },
        { "zh": "季度性景观", "en": "Seasonal Landscape" },
        { "zh": "花海", "en": "Flower Fields" },
        { "zh": "红叶", "en": "Autumn Foliage" },
        { "zh": "冰冻", "en": "Frozen Landscape" }
      ]
    },
    {
      "name": "构图/视角 (Composition/Perspective)",
      "tags": [
        { "zh": "广角", "en": "Wide Angle" },
        { "zh": "特写", "en": "Close-up" },
        { "zh": "远景", "en": "Long Shot" },
        { "zh": "鸟瞰", "en": "Bird's Eye View" },
        { "zh": "仰视", "en": "Low Angle View" },
        { "zh": "全景", "en": "Panoramic" },
        { "zh": "对称", "en": "Symmetric Composition" },
        { "zh": "三分法", "en": "Rule of Thirds" },
        { "zh": "引导线", "en": "Leading Lines" },
        { "zh": "前景", "en": "Foreground" },
        { "zh": "中景", "en": "Midground" },
        { "zh": "背景", "en": "Background" },
        { "zh": "景深", "en": "Depth of Field" },
        { "zh": "模糊", "en": "Blurred" },
        { "zh": "清晰", "en": "Sharp Focus" },
        { "zh": "宏伟", "en": "Grand Scale" },
        { "zh": "细节", "en": "Detailed Shot" },
        { "zh": "航拍", "en": "Aerial Shot" },
        { "zh": "水下视角", "en": "Underwater Perspective" },
        { "zh": "倒影", "en": "Reflection" },
        { "zh": "日落剪影", "en": "Sunset Silhouette" },
        { "zh": "日出逆光", "en": "Sunrise Backlight" },
        { "zh": "高对比度", "en": "High Contrast" },
        { "zh": "低对比度", "en": "Low Contrast" },
        { "zh": "曝光过度", "en": "Overexposed" },
        { "zh": "曝光不足", "en": "Underexposed" },
        { "zh": "饱和度高", "en": "High Saturation" },
        { "zh": "饱和度低", "en": "Low Saturation" },
        { "zh": "黑白", "en": "Black and White" },
        { "zh": "复古色调", "en": "Vintage Tone" },
        { "zh": "电影感", "en": "Cinematic" },
        { "zh": "纪实摄影", "en": "Documentary Photography" },
        { "zh": "艺术摄影", "en": "Art Photography" },
        { "zh": "自然光", "en": "Natural Light" },
        { "zh": "人工照明", "en": "Artificial Lighting" },
        { "zh": "霞光", "en": "Alpenglow" },
        { "zh": "彩虹", "en": "Rainbow" },
        { "zh": "星轨", "en": "Star Trails" },
        { "zh": "光绘", "en": "Light Painting" },
        { "zh": "全景图", "en": "Panorama" },
        { "zh": "垂直构图", "en": "Vertical Composition" },
        { "zh": "水平构图", "en": "Horizontal Composition" },
        { "zh": "对角线构图", "en": "Diagonal Composition" },
        { "zh": "框架构图", "en": "Framing Composition" },
        { "zh": "黄金比例", "en": "Golden Ratio" },
        { "zh": "S形构图", "en": "S-Curve Composition" },
        { "zh": "圆形构图", "en": "Circular Composition" },
        { "zh": "三角形构图", "en": "Triangular Composition" },
        { "zh": "开放式构图", "en": "Open Composition" },
        { "zh": "封闭式构图", "en": "Closed Composition" },
        { "zh": "动态构图", "en": "Dynamic Composition" },
        { "zh": "静态构图", "en": "Static Composition" }
      ]
    },
    {
      "name": "氛围/情绪 (Atmosphere/Mood)",
      "tags": [
        { "zh": "宁静", "en": "Tranquil" },
        { "zh": "雄伟", "en": "Majestic" },
        { "zh": "神秘", "en": "Mysterious" },
        { "zh": "浪漫", "en": "Romantic" },
        { "zh": "活力", "en": "Vibrant" },
        { "zh": "荒凉", "en": "Desolate" },
        { "zh": "壮丽", "en": "Magnificent" },
        { "zh": "如画", "en": "Picturesque" },
        { "zh": "古老", "en": "Ancient" },
        { "zh": "现代", "en": "Modern" },
        { "zh": "未来", "en": "Futuristic" },
        { "zh": "史诗", "en": "Epic" },
        { "zh": "幽静", "en": "Secluded" },
        { "zh": "熙熙攘攘", "en": "Bustling" },
        { "zh": "和平", "en": "Peaceful" },
        { "zh": "戏剧性", "en": "Dramatic" },
        { "zh": "梦幻", "en": "Dreamlike" },
        { "zh": "超现实", "en": "Surreal" },
        { "zh": "田园", "en": "Pastoral" },
        { "zh": "都市", "en": "Urban" },
        { "zh": "自然", "en": "Natural" },
        { "zh": "工业", "en": "Industrial" },
        { "zh": "科幻", "en": "Sci-Fi" },
        { "zh": "奇幻", "en": "Fantasy" },
        { "zh": "超自然", "en": "Supernatural" },
        { "zh": "哥特式", "en": "Gothic" },
        { "zh": "蒸汽朋克", "en": "Steampunk" },
        { "zh": "卡通", "en": "Cartoony" },
        { "zh": "绘画风格", "en": "Painterly Style" },
        { "zh": "照片真实感", "en": "Photorealistic" },
        { "zh": "高细节", "en": "High Detail" },
        { "zh": "低细节", "en": "Low Detail" },
        { "zh": "抽象", "en": "Abstract" },
        { "zh": "概念艺术", "en": "Concept Art" },
        { "zh": "插画", "en": "Illustration" },
        { "zh": "素描", "en": "Sketch" },
        { "zh": "写实", "en": "Realistic" },
        { "zh": "超写实", "en": "Hyperrealistic" },
        { "zh": "怀旧", "en": "Nostalgic" },
        { "zh": "历史感", "en": "Historic Feel" },
        { "zh": "未来感", "en": "Futuristic Feel" },
        { "zh": "废弃", "en": "Abandoned" },
        { "zh": "被遗忘", "en": "Forgotten" },
        { "zh": "蓬勃发展", "en": "Flourishing" },
        { "zh": "生机盎然", "en": "Lush" },
        { "zh": "贫瘠", "en": "Barren" },
        { "zh": "茂盛", "en": "Dense" },
        { "zh": "稀疏", "en": "Sparse" },
        { "zh": "开阔", "en": "Open" },
        { "zh": "封闭", "en": "Enclosed" },
        { "zh": "自然", "en": "Wild" },
        { "zh": "平静", "en": "Calm" },
        { "zh": "动荡", "en": "Turbulent" },
        { "zh": "静止", "en": "Still" },
        { "zh": "流动", "en": "Flowing" },
        { "zh": "闪耀", "en": "Shimmering" },
        { "zh": "黑暗", "en": "Dark" }
      ]
    },
    {
      "name": "光照/色彩 (Lighting/Color)",
      "tags": [
        { "zh": "自然光", "en": "Natural Light" },
        { "zh": "柔和光", "en": "Soft Light" },
        { "zh": "硬光", "en": "Hard Light" },
        { "zh": "逆光", "en": "Backlight" },
        { "zh": "侧光", "en": "Side Light" },
        { "zh": "顶光", "en": "Top Light" },
        { "zh": "底光", "en": "Bottom Light" },
        { "zh": "散射光", "en": "Diffused Light" },
        { "zh": "聚光", "en": "Spotlight" },
        { "zh": "环境光", "en": "Ambient Light" },
        { "zh": "人造光", "en": "Artificial Light" },
        { "zh": "日出光", "en": "Sunrise Light" },
        { "zh": "日落光", "en": "Sunset Light" },
        { "zh": "月光", "en": "Moonlight" },
        { "zh": "星光", "en": "Starlight" },
        { "zh": "城市灯光", "en": "City Lights" },
        { "zh": "霓虹灯", "en": "Neon Lights" },
        { "zh": "节日灯光", "en": "Festive Lights" },
        { "zh": "暖色调", "en": "Warm Tones" },
        { "zh": "冷色调", "en": "Cool Tones" },
        { "zh": "单色", "en": "Monochromatic" },
        { "zh": "多色", "en": "Multicolor" },
        { "zh": "鲜艳色彩", "en": "Vivid Colors" },
        { "zh": "柔和色彩", "en": "Muted Colors" },
        { "zh": "高饱和度", "en": "High Saturation" },
        { "zh": "低饱和度", "en": "Low Saturation" },
        { "zh": "电影照明", "en": "Cinematic Lighting" },
        { "zh": "戏剧性照明", "en": "Dramatic Lighting" },
        { "zh": "梦幻照明", "en": "Dreamy Lighting" },
        { "zh": "阴影", "en": "Shadows" },
        { "zh": "光线透过云层", "en": "Sunlight Through Clouds" },
        { "zh": "丁达尔效应", "en": "Tyndall Effect (Godrays)" },
        { "zh": "色彩斑斓", "en": "Colorful" },
        { "zh": "明亮", "en": "Bright" },
        { "zh": "昏暗", "en": "Dim" },
        { "zh": "辉煌", "en": "Luminous" },
        { "zh": "闪烁", "en": "Glow" },
        { "zh": "发光", "en": "Radiant" },
        { "zh": "蓝紫色调", "en": "Purple-blue tones" },
        { "zh": "橙红色调", "en": "Orange-red tones" },
        { "zh": "金黄色调", "en": "Golden tones" },
        { "zh": "绿色调", "en": "Green tones" }
      ]
    }
  ]
});