tagData.push({
  "group": "视频词汇 (Video Generation)",
  "categories": [
    {
      "name": "视频类型 (Video Type)",
      "tags": [
        { "zh": "电影预告片", "en": "cinematic trailer" },
        { "zh": "广告片", "en": "commercial advertisement" },
        { "zh": "音乐录影带 (MV)", "en": "music video (MV)" },
        { "zh": "短片", "en": "short film" },
        { "zh": "纪录片风格", "en": "documentary style" },
        { "zh": "宣传片", "en": "promotional video" },
        { "zh": "时尚广告", "en": "fashion film" },
        { "zh": "旅游视频", "en": "travel vlog" },
        { "zh": "美食视频", "en": "food video" },
        { "zh": "产品介绍", "en": "product showcase" },
        { "zh": "教程视频", "en": "tutorial video" },
        { "zh": "个人Vlog", "en": "personal vlog" },
        { "zh": "科幻片", "en": "science fiction film" },
        { "zh": "奇幻片", "en": "fantasy film" },
        { "zh": "动作片", "en": "action film" },
        { "zh": "恐怖片", "en": "horror film" },
        { "zh": "喜剧片", "en": "comedy film" },
        { "zh": "剧情片", "en": "drama film" },
        { "zh": "浪漫爱情片", "en": "romantic film" },
        { "zh": "悬疑片", "en": "thriller film" },
        { "zh": "动画短片", "en": "animated short" },
        { "zh": "体育赛事集锦", "en": "sports highlight reel" },
        { "zh": "新闻报道", "en": "news report" },
        { "zh": "现场表演", "en": "live performance video" },
        { "zh": "混剪视频", "en": "montage video" },
        { "zh": "回忆录视频", "en": "memorial video" },
        { "zh": "概念艺术视频", "en": "concept art video" },
        { "zh": "延时摄影", "en": "timelapse video" },
        { "zh": "超延时摄影", "en": "hyperlapse video" },
        { "zh": "定格动画", "en": "stop-motion animation" },
        { "zh": "3D产品渲染", "en": "3D product render video" },
        { "zh": "建筑可视化", "en": "architectural visualization" },
        { "zh": "教育内容", "en": "educational content" },
        { "zh": "访谈", "en": "interview video" },
        { "zh": "直播回顾", "en": "livestream recap" },
        { "zh": "社交媒体短视频", "en": "social media short" },
        { "zh": "垂直视频", "en": "vertical video" },
        { "zh": "横向视频", "en": "horizontal video" },
        { "zh": "方形视频", "en": "square video" },
        { "zh": "多屏幕显示", "en": "multi-screen display" },
        { "zh": "分屏视频", "en": "split screen video" }
      ]
    },
    {
      "name": "运镜方式 (Camera Movement)",
      "tags": [
        { "zh": "固定镜头", "en": "static shot" },
        { "zh": "摇摄", "en": "pan" },
        { "zh": "俯仰", "en": "tilt" },
        { "zh": "推镜头", "en": "dolly in" },
        { "zh": "拉镜头", "en": "dolly out" },
        { "zh": "变焦", "en": "zoom" },
        { "zh": "手持拍摄", "en": "handheld footage" },
        { "zh": "斯坦尼康稳定", "en": "steadicam stabilization" },
        { "zh": "轨道拍摄", "en": "tracking shot" },
        { "zh": "升降", "en": "crane shot" },
        { "zh": "环绕拍摄", "en": "orbit shot" },
        { "zh": "旋转镜头", "en": "360 rotation" },
        { "zh": "推拉变焦", "en": "dolly zoom" },
        { "zh": "主观视角 (POV)", "en": "POV shot (point of view)" },
        { "zh": "无人机视角", "en": "drone shot" },
        { "zh": "航拍俯瞰", "en": "aerial overview" },
        { "zh": "低角度跟随", "en": "low angle follow" },
        { "zh": "高角度俯瞰", "en": "high angle overview" },
        { "zh": "快速平摇", "en": "whip pan" },
        { "zh": "慢速平摇", "en": "slow pan" },
        { "zh": "倾斜/荷兰角", "en": "dutch angle" },
        { "zh": "移轴效果", "en": "tilt-shift effect" },
        { "zh": "景深拉伸", "en": "rack focus" },
        { "zh": "超慢动作", "en": "ultra slow motion" },
        { "zh": "快动作", "en": "fast motion" },
        { "zh": "倒放镜头", "en": "reverse footage" },
        { "zh": "定格画面", "en": "freeze frame" },
        { "zh": "画面晃动 (有意)", "en": "camera shake (intentional)" },
        { "zh": "稳定拍摄", "en": "stabilized footage" },
        { "zh": "第一人称视角", "en": "first-person perspective" },
        { "zh": "第三人称跟随", "en": "third-person follow" },
        { "zh": "沉浸式体验", "en": "immersive camera" },
        { "zh": "运动模糊摄影", "en": "motion blur photography" },
        { "zh": "失真镜头", "en": "distorted lens" },
        { "zh": "鱼眼镜头", "en": "fisheye lens" },
        { "zh": "广角镜头", "en": "wide angle lens" },
        { "zh": "长焦镜头", "en": "telephoto lens" },
        { "zh": "微距镜头", "en": "macro lens" },
        { "zh": "自动对焦", "en": "autofocus in action" },
        { "zh": "手动对焦效果", "en": "manual focus pull" },
        { "zh": "画面聚焦", "en": "pinpoint focus" },
        { "zh": "画面追踪", "en": "subject tracking" },
        { "zh": "平稳滑行", "en": "smooth glide" },
        { "zh": "冲击式运镜", "en": "impactful camera movement" },
        { "zh": "动态推进", "en": "dynamic push-in" },
        { "zh": "电影感推拉", "en": "cinematic push-pull" },
        { "zh": "画面穿梭", "en": "fly-through shot" },
        { "zh": "3D相机路径", "en": "3D camera path" },
        { "zh": "环形运镜", "en": "circular camera movement" },
        { "zh": "多角度剪辑", "en": "multi-angle editing" },
        { "zh": "第一人称跑酷", "en": "first-person parkour" },
        { "zh": "冲刺镜头", "en": "sprint cam" },
        { "zh": "角色视角", "en": "character perspective" },
        { "zh": "环境扫视", "en": "environmental sweep" }
      ]
    },
    {
      "name": "镜头景别 (Shot Scale)",
      "tags": [
        { "zh": "特写", "en": "extreme close-up" },
        { "zh": "近景", "en": "close-up" },
        { "zh": "中景", "en": "medium shot" },
        { "zh": "半身景", "en": "medium close-up" },
        { "zh": "全景", "en": "full shot" },
        { "zh": "远景", "en": "long shot" },
        { "zh": "大全景", "en": "extreme long shot" },
        { "zh": "确立镜头", "en": "establishing shot" },
        { "zh": "过肩镜头", "en": "over-the-shoulder shot" },
        { "zh": "双人镜头", "en": "two-shot" },
        { "zh": "三人镜头", "en": "three-shot" },
        { "zh": "入镜/出镜", "en": "enter frame / exit frame" },
        { "zh": "遮蔽构图", "en": "occluded shot" },
        { "zh": "广阔视野", "en": "wide field of view" },
        { "zh": "细致特写", "en": "detailed close-up" },
        { "zh": "环境背景强调", "en": "environmental emphasis" },
        { "zh": "聚焦主体", "en": "subject focus" },
        { "zh": "前景模糊", "en": "foreground blur" },
        { "zh": "背景模糊虚化", "en": "background bokeh" },
        { "zh": "浅景深", "en": "shallow depth of field" },
        { "zh": "深景深", "en": "deep depth of field" },
        { "zh": "构图严谨", "en": "tight composition" },
        { "zh": "开放构图", "en": "open composition" },
        { "zh": "对称构图", "en": "symmetrical composition" },
        { "zh": "三分法构图", "en": "rule of thirds composition" },
        { "zh": "引导线构图", "en": "leading lines composition" },
        { "zh": "框架构图", "en": "frame within a frame" },
        { "zh": "留白构图", "en": "negative space composition" },
        { "zh": "对角线构图", "en": "diagonal line composition" },
        { "zh": "垂直构图", "en": "vertical composition" },
        { "zh": "水平构图", "en": "horizontal composition" },
        { "zh": "景物特写", "en": "object close-up" },
        { "zh": "面部特写", "en": "facial close-up" },
        { "zh": "剪影", "en": "silhouette shot" },
        { "zh": "倒影镜头", "en": "reflection shot" },
        { "zh": "透过窗户", "en": "through a window shot" },
        { "zh": "从缝隙中窥视", "en": "peeking through an opening" },
        { "zh": "窥视孔视角", "en": "keyhole perspective" },
        { "zh": "俯冲镜头", "en": "plunge shot" },
        { "zh": "仰视镜头", "en": "looking up shot" },
        { "zh": "高机位", "en": "high camera position" },
        { "zh": "低机位", "en": "low camera position" }
      ]
    },
    {
      "name": "转场效果 (Transitions)",
      "tags": [
        { "zh": "硬切", "en": "hard cut" },
        { "zh": "淡入淡出", "en": "fade in / fade out" },
        { "zh": "叠化", "en": "dissolve" },
        { "zh": "交叉淡化", "en": "crossfade" },
        { "zh": "划像", "en": "wipe transition" },
        { "zh": "推移", "en": "push transition" },
        { "zh": "闪白", "en": "flash cut" },
        { "zh": "闪黑", "en": "black flash transition" },
        { "zh": "叠影", "en": "superimposition" },
        { "zh": "匹配剪辑", "en": "match cut" },
        { "zh": "跳切", "en": "jump cut" },
        { "zh": "转场平摇", "en": "whip pan transition" },
        { "zh": "图层擦除", "en": "L-cut / J-cut" },
        { "zh": "音效转场", "en": "audio-driven transition" },
        { "zh": "镜头穿梭转场 (Swish Pan)", "en": "swish pan transition" },
        { "zh": "变焦转场", "en": "zoom transition" },
        { "zh": "光线转场", "en": "light leak transition" },
        { "zh": "粒子转场", "en": "particle transition" },
        { "zh": "故障艺术转场", "en": "glitch transition" },
        { "zh": "几何图形转场", "en": "geometric shape transition" },
        { "zh": "笔刷擦除转场", "en": "brush wipe transition" },
        { "zh": "故障信号转场", "en": "signal disruption transition" },
        { "zh": "画面撕裂转场", "en": "screen tear transition" },
        { "zh": "模糊转场", "en": "blur transition" },
        { "zh": "马赛克转场", "en": "mosaic transition" },
        { "zh": "扭曲转场", "en": "warp transition" },
        { "zh": "旋转转场", "en": "spin transition" },
        { "zh": "翻页转场", "en": "page turn transition" },
        { "zh": "快门转场", "en": "shutter transition" },
        { "zh": "胶片烧灼转场", "en": "film burn transition" },
        { "zh": "屏幕破碎转场", "en": "screen crack transition" },
        { "zh": "数字故障转场", "en": "digital glitch transition" },
        { "zh": "墨迹扩散转场", "en": "ink bleed transition" },
        { "zh": "水波纹转场", "en": "ripple effect transition" },
        { "zh": "波浪转场", "en": "wave dissolve" },
        { "zh": "分形转场", "en": "fractal transition" },
        { "zh": "RGB分离转场", "en": "RGB split transition" },
        { "zh": "像素化转场", "en": "pixelate transition" },
        { "zh": "光斑转场", "en": "light flare transition" },
        { "zh": "速度跳跃转场", "en": "speed ramp transition" },
        { "zh": "无缝转场", "en": "seamless transition" },
        { "zh": "声音驱动转场", "en": "sound-driven transition" },
        { "zh": "视觉叙事转场", "en": "visual storytelling transition" },
        { "zh": "蒙太奇转场", "en": "montage transition" },
        { "zh": "主题呼应转场", "en": "thematic transition" },
        { "zh": "情绪引导转场", "en": "emotion-guiding transition" }
      ]
    },
    {
      "name": "特效与VFX (Special Effects & VFX)",
      "tags": [
        { "zh": "电影感调色", "en": "cinematic color grading" },
        { "zh": "光线追踪渲染", "en": "ray tracing render" },
        { "zh": "体积照明", "en": "volumetric lighting" },
        { "zh": "后期烟雾", "en": "post-production smoke" },
        { "zh": "雨雪效果", "en": "rain and snow effects" },
        { "zh": "火焰爆炸", "en": "fire and explosion effects" },
        { "zh": "水花飞溅", "en": "water splash effects" },
        { "zh": "电光火石", "en": "electric arc effects" },
        { "zh": "魔法效果", "en": "magical effects" },
        { "zh": "能量冲击波", "en": "energy shockwave" },
        { "zh": "数字合成", "en": "digital compositing" },
        { "zh": "绿幕抠像", "en": "greenscreen compositing" },
        { "zh": "运动图形", "en": "motion graphics" },
        { "zh": "字幕动画", "en": "animated typography" },
        { "zh": "CG元素", "en": "CGI elements" },
        { "zh": "粒子系统", "en": "particle systems" },
        { "zh": "力场效果", "en": "force field effect" },
        { "zh": "全息投影", "en": "holographic projection" },
        { "zh": "慢动作", "en": "slow motion effect" },
        { "zh": "快动作", "en": "fast motion effect" },
        { "zh": "时间流逝", "en": "timewarp effect" },
        { "zh": "故障艺术", "en": "glitch art" },
        { "zh": "赛博朋克霓虹", "en": "cyberpunk neon effects" },
        { "zh": "复古VHS效果", "en": "retro VHS effect" },
        { "zh": "胶片颗粒", "en": "film grain" },
        { "zh": "色差", "en": "chromatic aberration" },
        { "zh": "镜头光晕", "en": "lens flare" },
        { "zh": "景深模拟", "en": "simulated depth of field" },
        { "zh": "模糊特效", "en": "blur effects" },
        { "zh": "锐化处理", "en": "sharpening effects" },
        { "zh": "扭曲特效", "en": "distortion effects" },
        { "zh": "像素化效果", "en": "pixelation effect" },
        { "zh": "马赛克效果", "en": "mosaic effect" },
        { "zh": "水下特效", "en": "underwater effects" },
        { "zh": "烟雾弥漫", "en": "haze effect" },
        { "zh": "破碎解体", "en": "shattering disintegration" },
        { "zh": "物体生成", "en": "object generation" },
        { "zh": "环境生成", "en": "environment generation" },
        { "zh": "UI/UX动画", "en": "UI/UX animation" },
        { "zh": "增强现实 (AR)", "en": "augmented reality (AR)" },
        { "zh": "虚拟现实 (VR)", "en": "virtual reality (VR)" },
        { "zh": "逼真模拟", "en": "realistic simulation" },
        { "zh": "卡通化渲染", "en": "toon shading" },
        { "zh": "手绘效果", "en": "hand-drawn effect" },
        { "zh": "水彩效果", "en": "watercolor effect" },
        { "zh": "油画效果", "en": "oil painting effect" },
        { "zh": "噪点纹理", "en": "noise texture" },
        { "zh": "视频叠加", "en": "video overlay" },
        { "zh": "边缘光", "en": "rim lighting effect" },
        { "zh": "屏幕内显示", "en": "screen within screen" },
        { "zh": "信息叠加显示 (HUD)", "en": "heads-up display (HUD) overlay" },
        { "zh": "扫描线", "en": "scanlines" },
        { "zh": "辉光边缘", "en": "glowing edges" },
        { "zh": "虚幻引擎渲染", "en": "Unreal Engine render" },
        { "zh": "Unity引擎渲染", "en": "Unity Engine render" },
        { "zh": "OC渲染器", "en": "Octane Render" },
        { "zh": "Redshift渲染器", "en": "Redshift Render" },
        { "zh": "V-Ray渲染器", "en": "V-Ray Render" },
        { "zh": "Houdini特效", "en": "Houdini VFX" },
        { "zh": "After Effects效果", "en": "After Effects driven" },
        { "zh": "Premiere Pro剪辑", "en": "Premiere Pro editing style" },
        { "zh": "DaVinci Resolve调色", "en": "DaVinci Resolve color grade" },
        { "zh": "真实感渲染", "en": "photorealistic rendering" },
        { "zh": "程式化渲染", "en": "stylized rendering" },
        { "zh": "像素艺术动画", "en": "pixel art animation" },
        { "zh": "体素艺术", "en": "voxel art" }
      ]
    },
    {
      "name": "动画表现 (Animation Style)",
      "tags": [
        { "zh": "2D动画", "en": "2D animation" },
        { "zh": "3D动画", "en": "3D animation" },
        { "zh": "逐帧动画", "en": "frame-by-frame animation" },
        { "zh": "骨骼动画", "en": "rigged character animation" },
        { "zh": "Q版动画", "en": "chibi animation" },
        { "zh": "手绘动画", "en": "hand-drawn animation" },
        { "zh": "插画风格动画", "en": "illustrated animation" },
        { "zh": "卡通动画", "en": "cartoon animation" },
        { "zh": "写实角色动画", "en": "realistic character animation" },
        { "zh": "布偶动画", "en": "puppet animation" },
        { "zh": "剪纸动画", "en": "paper cut-out animation" },
        { "zh": "水墨动画", "en": "ink wash animation" },
        { "zh": "粘土动画", "en": "claymation" },
        { "zh": "沙画动画", "en": "sand animation" },
        { "zh": "线稿动画", "en": "line art animation" },
        { "zh": "动态图形", "en": "motion graphics" },
        { "zh": "信息图动画", "en": "infographic animation" },
        { "zh": "UI界面动画", "en": "UI animation" },
        { "zh": "流程图动画", "en": "flowchart animation" },
        { "zh": "抽象动画", "en": "abstract animation" },
        { "zh": "角色绑定", "en": "character rigging" },
        { "zh": "表情动画", "en": "facial animation" },
        { "zh": "身体动作捕捉", "en": "motion capture (mocap)" },
        { "zh": "物理模拟动画", "en": "physics-based animation" },
        { "zh": "流体模拟动画", "en": "fluid simulation animation" },
        { "zh": "布料模拟动画", "en": "cloth simulation animation" },
        { "zh": "毛发模拟动画", "en": "hair simulation animation" },
        { "zh": "卡通渲染动画", "en": "cel-shaded animation" },
        { "zh": "卡通动作", "en": "cartoony action" },
        { "zh": "夸张动画", "en": "exaggerated animation" },
        { "zh": "平滑动画", "en": "smooth animation" },
        { "zh": "急促动画", "en": "jerky animation" },
        { "zh": "循环动画", "en": "looping animation" },
        { "zh": "无缝循环动画", "en": "seamless loop animation" },
        { "zh": "帧率高", "en": "high framerate" },
        { "zh": "帧率低", "en": "low framerate" },
        { "zh": "动画短片", "en": "animated short film" },
        { "zh": "场景动画", "en": "scene animation" },
        { "zh": "角色动画", "en": "character animation" },
        { "zh": "物体动画", "en": "object animation" },
        { "zh": "形态变换动画", "en": "morphing animation" },
        { "zh": "文字动画", "en": "text animation" },
        { "zh": "图标动画", "en": "icon animation" },
        { "zh": "标志揭示动画", "en": "logo reveal animation" },
        { "zh": "视差滚动动画", "en": "parallax scrolling animation" },
        { "zh": "光效动画", "en": "light effect animation" },
        { "zh": "能量动画", "en": "energy animation" },
        { "zh": "手绘特效动画", "en": "hand-drawn FX animation" },
        { "zh": "视觉效果动画", "en": "visual effects animation" },
        { "zh": "慢动作回放", "en": "slow-motion replay" },
        { "zh": "子弹时间", "en": "bullet time effect" },
        { "zh": "电影动画", "en": "cinematic animation" },
        { "zh": "游戏风格动画", "en": "game-style animation" },
        { "zh": "卡通人物", "en": "cartoon characters" },
        { "zh": "真实人物", "en": "realistic characters" },
        { "zh": "CG角色", "en": "CGI characters" },
        { "zh": "虚拟形象", "en": "avatar animation" },
        { "zh": "表情丰富", "en": "expressive animation" },
        { "zh": "无脸动画", "en": "faceless animation" },
        { "zh": "剪影动画", "en": "silhouette animation" },
        { "zh": "人物姿态", "en": "character poses" },
        { "zh": "姿态校正", "en": "pose correction" },
        { "zh": "姿态转换", "en": "pose transition" },
        { "zh": "流畅运动", "en": "fluid motion" },
        { "zh": "动态构图", "en": "dynamic composition" }
      ]
    },
    {
      "name": "视觉风格 (Visual Style)",
      "tags": [
        { "zh": "电影感", "en": "cinematic look" },
        { "zh": "高对比度", "en": "high contrast" },
        { "zh": "低对比度", "en": "low contrast" },
        { "zh": "黑白", "en": "black and white" },
        { "zh": "复古色彩", "en": "vintage color palette" },
        { "zh": "鲜艳色彩", "en": "vibrant colors" },
        { "zh": "柔和色彩", "en": "soft colors" },
        { "zh": "暗色系", "en": "dark color scheme" },
        { "zh": "未来主义光照", "en": "futuristic lighting" },
        { "zh": "梦幻滤镜", "en": "dreamy filter" },
        { "zh": "朋克风格", "en": "punk aesthetic" },
        { "zh": "蒸汽朋克", "en": "steampunk aesthetic" },
        { "zh": "赛博朋克", "en": "cyberpunk aesthetic" },
        { "zh": "废土风格", "en": "post-apocalyptic aesthetic" },
        { "zh": "复古未来主义", "en": "retro-futuristic" },
        { "zh": "霓虹灯光", "en": "neon lighting" },
        { "zh": "故障艺术", "en": "glitch art style" },
        { "zh": "蒸汽波美学", "en": "vaporwave aesthetic" },
        { "zh": "Low Poly (低多边形)", "en": "low poly style" },
        { "zh": "像素艺术", "en": "pixel art style" },
        { "zh": "水彩画风格", "en": "watercolor style" },
        { "zh": "油画风格", "en": "oil painting style" },
        { "zh": "素描风格", "en": "sketch style" },
        { "zh": "卡通风格", "en": "cartoon style" },
        { "zh": "写实风格", "en": "realistic style" },
        { "zh": "超写实", "en": "hyperrealistic" },
        { "zh": "概念艺术风格", "en": "concept art style" },
        { "zh": "插画风格", "en": "illustration style" },
        { "zh": "抽象风格", "en": "abstract style" },
        { "zh": "极简主义", "en": "minimalist style" },
        { "zh": "未来科技感", "en": "futuristic tech aesthetic" },
        { "zh": "有机形态", "en": "organic forms" },
        { "zh": "几何形态", "en": "geometric forms" },
        { "zh": "精致细节", "en": "intricate details" },
        { "zh": "干净清晰", "en": "clean and crisp" },
        { "zh": "粗糙质感", "en": "grungy texture" },
        { "zh": "闪耀光泽", "en": "glowing sheen" },
        { "zh": "磨砂质感", "en": "matte finish" },
        { "zh": "透明材质", "en": "transparent material" },
        { "zh": "半透明材质", "en": "translucent material" },
        { "zh": "反射表面", "en": "reflective surfaces" },
        { "zh": "折射效果", "en": "refractive effect" },
        { "zh": "光谱色散", "en": "chromatic dispersion" },
        { "zh": "扫描线效果", "en": "scanline effect" },
        { "zh": "模拟摄影", "en": "analog photography style" },
        { "zh": "8毫米胶片", "en": "8mm film look" },
        { "zh": "16毫米胶片", "en": "16mm film look" },
        { "zh": "电影胶片颗粒", "en": "cinematic film grain" },
        { "zh": "宽屏比例", "en": "widescreen aspect ratio" },
        { "zh": "影院比例", "en": "cinemascope ratio" },
        { "zh": "IMAX画幅", "en": "IMAX aspect ratio" },
        { "zh": "标准画幅", "en": "standard aspect ratio" },
        { "zh": "复古电视效果", "en": "retro TV effect" },
        { "zh": "VHS录像带效果", "en": "VHS tape effect" },
        { "zh": "手绘涂鸦", "en": "hand-drawn doodles" },
        { "zh": "矢量图形", "en": "vector graphics" },
        { "zh": "低保真", "en": "lo-fi" },
        { "zh": "高保真", "en": "hi-fi" },
        { "zh": "蒸汽朋克机械", "en": "steampunk machinery" },
        { "zh": "生物机械", "en": "biomechanical" },
        { "zh": "有机融合", "en": "organic blend" },
        { "zh": "数字艺术", "en": "digital art" },
        { "zh": "工业美学", "en": "industrial aesthetic" },
        { "zh": "超现实主义", "en": "surrealist" },
        { "zh": "梦幻般", "en": "dreamlike" },
        { "zh": "恐怖美学", "en": "horror aesthetic" },
        { "zh": "喜剧风格", "en": "comedic style" },
        { "zh": "黑暗风格", "en": "dark style" },
        { "zh": "光明风格", "en": "bright style" },
        { "zh": "冷色调", "en": "cool tones" },
        { "zh": "暖色调", "en": "warm tones" },
        { "zh": "对比鲜明", "en": "striking contrast" },
        { "zh": "单色", "en": "monochromatic" },
        { "zh": "双色调", "en": "duotone" },
        { "zh": "弥散光", "en": "diffuse lighting" },
        { "zh": "聚光灯", "en": "spotlight effect" },
        { "zh": "剪影照明", "en": "silhouette lighting" },
        { "zh": "高光强调", "en": "highlight emphasis" },
        { "zh": "暗部细节", "en": "shadow detail" },
        { "zh": "模糊背景", "en": "blurred background" },
        { "zh": "景深", "en": "depth of field" }
      ]
    },
    {
      "name": "情绪与主题 (Mood & Theme)",
      "tags": [
        { "zh": "史诗般", "en": "epic" },
        { "zh": "戏剧性", "en": "dramatic" },
        { "zh": "紧张刺激", "en": "tense and thrilling" },
        { "zh": "神秘莫测", "en": "mysterious" },
        { "zh": "宁静祥和", "en": "peaceful and serene" },
        { "zh": "幸福喜悦", "en": "joyful and happy" },
        { "zh": "悲伤沉重", "en": "sad and heavy" },
        { "zh": "感人至深", "en": "heartwarming" },
        { "zh": "励志积极", "en": "inspiring and positive" },
        { "zh": "未来科幻", "en": "futuristic and sci-fi" },
        { "zh": "复古怀旧", "en": "retro and nostalgic" },
        { "zh": "冒险探索", "en": "adventure and exploration" },
        { "zh": "悬疑惊悚", "en": "suspense and psychological thriller" },
        { "zh": "温馨浪漫", "en": "romantic and cozy" },
        { "zh": "活力四射", "en": "energetic and dynamic" },
        { "zh": "创意大胆", "en": "creative and bold" },
        { "zh": "艺术实验", "en": "artistic and experimental" },
        { "zh": "简洁明了", "en": "simple and clear" },
        { "zh": "复杂多变", "en": "complex and intricate" },
        { "zh": "黑暗幻想", "en": "dark fantasy" },
        { "zh": "光明希望", "en": "light and hope" },
        { "zh": "科技前沿", "en": "cutting-edge technology" },
        { "zh": "自然和谐", "en": "nature and harmony" },
        { "zh": "城市生活", "en": "urban life" },
        { "zh": "乡村风光", "en": "rural scenery" },
        { "zh": "梦境幻象", "en": "dream sequence" },
        { "zh": "超现实画面", "en": "surreal visuals" },
        { "zh": "成长与变化", "en": "growth and transformation" },
        { "zh": "冲突与解决", "en": "conflict and resolution" },
        { "zh": "希望与绝望", "en": "hope and despair" },
        { "zh": "记忆与回溯", "en": "memory and flashback" },
        { "zh": "时间旅行", "en": "time travel" },
        { "zh": "平行宇宙", "en": "parallel universes" },
        { "zh": "乌托邦", "en": "utopian" },
        { "zh": "反乌托邦", "en": "dystopian" },
        { "zh": "奇幻世界", "en": "fantastical world" },
        { "zh": "魔幻现实", "en": "magical realism" },
        { "zh": "神话传说", "en": "myth and legend" },
        { "zh": "历史重现", "en": "historical reenactment" },
        { "zh": "体育竞技", "en": "sports and competition" },
        { "zh": "自我发现", "en": "self-discovery" },
        { "zh": "庆祝与盛宴", "en": "celebration and feast" },
        { "zh": "末日", "en": "apocalyptic" }
      ]
    },
    {
      "name": "时间与场景 (Time & Setting)",
      "tags": [
        { "zh": "白天", "en": "daytime" },
        { "zh": "夜晚", "en": "nighttime" },
        { "zh": "黎明", "en": "dawn" },
        { "zh": "黄昏", "en": "dusk" },
        { "zh": "阳光明媚", "en": "sunny" },
        { "zh": "阴天", "en": "cloudy" },
        { "zh": "雨天", "en": "rainy" },
        { "zh": "雪天", "en": "snowy" },
        { "zh": "雾天", "en": "foggy" },
        { "zh": "风暴", "en": "stormy weather" },
        { "zh": "室内场景", "en": "indoor scene" },
        { "zh": "室外场景", "en": "outdoor scene" },
        { "zh": "城市街道", "en": "city street" },
        { "zh": "摩天大楼", "en": "skyscrapers" },
        { "zh": "公园", "en": "park" },
        { "zh": "森林", "en": "forest" },
        { "zh": "海滩", "en": "beach" },
        { "zh": "山脉", "en": "mountains" },
        { "zh": "沙漠", "en": "desert" },
        { "zh": "水下", "en": "underwater" },
        { "zh": "太空", "en": "outer space" },
        { "zh": "未来都市", "en": "futuristic city" },
        { "zh": "复古小镇", "en": "retro town" },
        { "zh": "历史建筑", "en": "historic building" },
        { "zh": "废墟", "en": "ruins" },
        { "zh": "实验室", "en": "laboratory" },
        { "zh": "工厂", "en": "factory" },
        { "zh": "学校", "en": "school" },
        { "zh": "医院", "en": "hospital" },
        { "zh": "咖啡馆", "en": "cafe" },
        { "zh": "酒吧", "en": "bar" },
        { "zh": "家庭客厅", "en": "living room" },
        { "zh": "卧室", "en": "bedroom" },
        { "zh": "厨房", "en": "kitchen" },
        { "zh": "办公室", "en": "office" },
        { "zh": "舞台", "en": "stage" },
        { "zh": "音乐厅", "en": "concert hall" },
        { "zh": "体育场", "en": "stadium" },
        { "zh": "图书馆", "en": "library" },
        { "zh": "博物馆", "en": "museum" },
        { "zh": "艺术画廊", "en": "art gallery" },
        { "zh": "地下城", "en": "dungeon" },
        { "zh": "宇宙飞船内部", "en": "spaceship interior" },
        { "zh": "外星景观", "en": "alien landscape" },
        { "zh": "丛林", "en": "jungle" },
        { "zh": "冰雪世界", "en": "icy landscape" },
        { "zh": "火星地表", "en": "Martian surface" },
        { "zh": "末日场景", "en": "apocalyptic scene" },
        { "zh": "赛车道", "en": "race track" },
        { "zh": "机场", "en": "airport" },
        { "zh": "火车站", "en": "train station" },
        { "zh": "港口", "en": "port" },
        { "zh": "市场", "en": "market" },
        { "zh": "寺庙", "en": "temple" },
        { "zh": "城堡", "en": "castle" },
        { "zh": "古遗址", "en": "ancient ruins" },
        { "zh": "洞穴", "en": "cave" },
        { "zh": "火山", "en": "volcano" },
        { "zh": "冰川", "en": "glacier" },
        { "zh": "极光", "en": "aurora borealis" },
        { "zh": "日出", "en": "sunrise" },
        { "zh": "日落", "en": "sunset" },
        { "zh": "午夜", "en": "midnight" },
        { "zh": "多变天气", "en": "variable weather" },
        { "zh": "季节变化", "en": "seasonal change" },
        { "zh": "清晨", "en": "early morning" },
        { "zh": "傍晚", "en": "late evening" },
        { "zh": "热带", "en": "tropical" },
        { "zh": "极地", "en": "polar" },
        { "zh": "草原", "en": "grassland" },
        { "zh": "农场", "en": "farm" },
        { "zh": "偏远地区", "en": "remote area" },
        { "zh": "地下世界", "en": "underground world" },
        { "zh": "天堂", "en": "heavenly setting" },
        { "zh": "地狱", "en": "hellish landscape" }
      ]
    },
    {
      "name": "光照与色彩 (Lighting & Color)",
      "tags": [
        { "zh": "自然光", "en": "natural lighting" },
        { "zh": "电影布光", "en": "cinematic lighting" },
        { "zh": "柔和光", "en": "soft lighting" },
        { "zh": "硬光", "en": "hard lighting" },
        { "zh": "伦勃朗光", "en": "Rembrandt lighting" },
        { "zh": "高调光", "en": "high-key lighting" },
        { "zh": "低调光", "en": "low-key lighting" },
        { "zh": "逆光", "en": "backlight" },
        { "zh": "侧光", "en": "side lighting" },
        { "zh": "顶光", "en": "top lighting" },
        { "zh": "底光", "en": "bottom lighting" },
        { "zh": "聚光灯", "en": "spotlight" },
        { "zh": "环境光", "en": "ambient light" },
        { "zh": "体积光", "en": "volumetric light" },
        { "zh": "丁达尔效应", "en": "God rays / crepuscular rays" },
        { "zh": "霓虹灯光", "en": "neon lighting" },
        { "zh": "LED灯光", "en": "LED lighting" },
        { "zh": "闪烁灯光", "en": "flickering lights" },
        { "zh": "反射光", "en": "reflected light" },
        { "zh": "漫反射光", "en": "diffuse light" },
        { "zh": "彩色灯光", "en": "colored lighting" },
        { "zh": "暖色调光", "en": "warm tone lighting" },
        { "zh": "冷色调光", "en": "cool tone lighting" },
        { "zh": "戏剧性阴影", "en": "dramatic shadows" },
        { "zh": "锐利阴影", "en": "sharp shadows" },
        { "zh": "柔和阴影", "en": "soft shadows" },
        { "zh": "光线穿透", "en": "light penetration" },
        { "zh": "辉光", "en": "bloom effect" },
        { "zh": "镜头光晕", "en": "lens flare" },
        { "zh": "光斑", "en": "bokeh (light pattern)" },
        { "zh": "高动态范围 (HDR)", "en": "HDR (High Dynamic Range)" },
        { "zh": "SDR (标准动态范围)", "en": "SDR (Standard Dynamic Range)" },
        { "zh": "Rec.709色彩", "en": "Rec.709 colors" },
        { "zh": "P3广色域", "en": "DCI-P3 wide gamut" },
        { "zh": "明亮", "en": "bright" },
        { "zh": "黑暗", "en": "dark" },
        { "zh": "高饱和度", "en": "high saturation" },
        { "zh": "低饱和度", "en": "low saturation" },
        { "zh": "去饱和", "en": "desaturated" },
        { "zh": "饱和度跳跃", "en": "color pop" },
        { "zh": "互补色", "en": "complementary colors" },
        { "zh": "相似色", "en": "analogous colors" },
        { "zh": "三原色", "en": "triadic colors" },
        { "zh": "单色", "en": "monochromatic" },
        { "zh": "双色调", "en": "duotone" },
        { "zh": "潘通色彩", "en": "Pantone colors" },
        { "zh": "CMYK色彩", "en": "CMYK colors" },
        { "zh": "RGB色彩", "en": "RGB colors" },
        { "zh": "金黄色", "en": "golden yellow" },
        { "zh": "深蓝色", "en": "deep blue" },
        { "zh": "翡翠绿", "en": "emerald green" },
        { "zh": "猩红色", "en": "scarlet red" },
        { "zh": "紫色", "en": "purple" },
        { "zh": "粉色", "en": "pink" },
        { "zh": "青色", "en": "cyan" },
        { "zh": "品红色", "en": "magenta" },
        { "zh": "黄昏色彩", "en": "twilight colors" },
        { "zh": "黎明色彩", "en": "dawn colors" },
        { "zh": "环境映射", "en": "environment mapping" },
        { "zh": "全局照明", "en": "global illumination" },
        { "zh": "焦散效应", "en": "caustic effects" },
        { "zh": "次表面散射", "en": "subsurface scattering" },
        { "zh": "屏幕空间反射", "en": "screen space reflections" },
        { "zh": "屏幕空间环境光遮蔽", "en": "SSAO (Screen Space Ambient Occlusion)" }
      ]
    },
    {
      "name": "人物与动作 (Characters & Actions)",
      "tags": [
        { "zh": "人物角色", "en": "character" },
        { "zh": "单人", "en": "solo person" },
        { "zh": "两人", "en": "two people" },
        { "zh": "人群", "en": "crowd" },
        { "zh": "特写面部", "en": "face close-up" },
        { "zh": "全身姿态", "en": "full body pose" },
        { "zh": "行走", "en": "walking" },
        { "zh": "奔跑", "en": "running" },
        { "zh": "跳跃", "en": "jumping" },
        { "zh": "攀爬", "en": "climbing" },
        { "zh": "打斗动作", "en": "fight sequence" },
        { "zh": "舞蹈", "en": "dancing" },
        { "zh": "对话交流", "en": "dialogue interaction" },
        { "zh": "思考", "en": "thinking" },
        { "zh": "哭泣", "en": "crying" },
        { "zh": "微笑", "en": "smiling" },
        { "zh": "大笑", "en": "laughing" },
        { "zh": "愤怒", "en": "angry" },
        { "zh": "恐惧", "en": "fearful" },
        { "zh": "惊讶", "en": "surprised" },
        { "zh": "沉思", "en": "contemplative" },
        { "zh": "胜利", "en": "victorious" },
        { "zh": "失败", "en": "defeated" },
        { "zh": "互动", "en": "interacting" },
        { "zh": "创造", "en": "creating" },
        { "zh": "探索", "en": "exploring" },
        { "zh": "学习", "en": "learning" },
        { "zh": "教学", "en": "teaching" },
        { "zh": "驾驶", "en": "driving" },
        { "zh": "驾驶舱", "en": "cockpit view" },
        { "zh": "骑行", "en": "riding" },
        { "zh": "演奏乐器", "en": "playing musical instrument" },
        { "zh": "运动", "en": "exercising" },
        { "zh": "吃饭", "en": "eating" },
        { "zh": "睡觉", "en": "sleeping" },
        { "zh": "工作", "en": "working" },
        { "zh": "放松", "en": "relaxing" },
        { "zh": "战斗姿态", "en": "combat stance" },
        { "zh": "英雄姿态", "en": "heroic pose" },
        { "zh": "反派角色", "en": "villain character" },
        { "zh": "普通人", "en": "ordinary person" },
        { "zh": "奇幻生物", "en": "fantasy creature" },
        { "zh": "机器人", "en": "robot" },
        { "zh": "人工智能 (AI)", "en": "AI (Artificial Intelligence)" },
        { "zh": "超能力", "en": "superpowers" },
        { "zh": "特殊能力", "en": "special abilities" },
        { "zh": "服饰细节", "en": "costume details" },
        { "zh": "装备道具", "en": "prop equipment" },
        { "zh": "角色弧光", "en": "character arc" },
        { "zh": "心理描写", "en": "psychological portrayal" },
        { "zh": "内心独白", "en": "inner monologue" },
        { "zh": "身体语言", "en": "body language" },
        { "zh": "表情丰富", "en": "expressive face" },
        { "zh": "眼神戏", "en": "eye acting" },
        { "zh": "手势", "en": "hand gestures" },
        { "zh": "群演", "en": "extras / background actors" },
        { "zh": "观众", "en": "audience" },
        { "zh": "互动式表演", "en": "interactive performance" },
        { "zh": "比耶 (V字手势)", "en": "V sign (peace sign)" },
        { "zh": "轻抚头发", "en": "hair flip / stroking hair" },
        { "zh": "做鬼脸", "en": "making a funny face / grimace" },
        { "zh": "耍酷", "en": "acting cool / showing off" },
        { "zh": "嘴唇吹头发", "en": "blowing hair off lips" },
        { "zh": "打招呼 (挥手)", "en": "waving hello / waving goodbye" },
        { "zh": "摇头晃脑 (思考/得意)", "en": "shaking head (thinking/proud)" },
        { "zh": "吐舌头", "en": "sticking tongue out" },
        { "zh": "鼓掌", "en": "clapping hands" },
        { "zh": "指向", "en": "pointing" },
        { "zh": "竖大拇指", "en": "thumbs up" },
        { "zh": "倒大拇指", "en": "thumbs down" },
        { "zh": "耸肩", "en": "shrugging shoulders" },
        { "zh": "敬礼", "en": "saluting" },
        { "zh": "打字", "en": "typing" },
        { "zh": "书写", "en": "writing" },
        { "zh": "绘图", "en": "drawing" },
        { "zh": "拿着物品", "en": "holding an object" },
        { "zh": "摆姿势", "en": "posing" },
        { "zh": "坐着", "en": "sitting" },
        { "zh": "躺着", "en": "lying down" },
        { "zh": "跪着", "en": "kneeling" },
        { "zh": "蹲着", "en": "crouching" },
        { "zh": "跌倒/摔跤", "en": "falling / tripping" },
        { "zh": "跳舞 (特定舞步)", "en": "dancing (specific moves)" },
        { "zh": "唱歌", "en": "singing" },
        { "zh": "低语", "en": "whispering" },
        { "zh": "喊叫", "en": "shouting" },
        { "zh": "耳语", "en": "ear whispering" },
        { "zh": "窃笑", "en": "giggling" },
        { "zh": "咧嘴笑", "en": "grinning" },
        { "zh": "皱眉", "en": "frowning" },
        { "zh": "噘嘴", "en": "pouting" },
        { "zh": "眨眼", "en": "winking" },
        { "zh": "点头", "en": "nodding" },
        { "zh": "摇手 (拒绝)", "en": "shaking hand (refusal)" },
        { "zh": "捂嘴", "en": "covering mouth" },
        { "zh": "挠头", "en": "scratching head" },
        { "zh": "抱臂", "en": "crossing arms" },
        { "zh": "双手叉腰", "en": "hands on hips" },
        { "zh": "抱膝", "en": "hugging knees" },
        { "zh": "思考状", "en": "pondering pose" },
        { "zh": "困倦/打哈欠", "en": "drowsy / yawning" },
        { "zh": "发呆", "en": "daydreaming / zoning out" },
        { "zh": "动物：奔跑", "en": "animal: running" },
        { "zh": "动物：跳跃", "en": "animal: jumping" },
        { "zh": "动物：飞翔", "en": "animal: flying" },
        { "zh": "动物：游泳", "en": "animal: swimming" },
        { "zh": "动物：捕食", "en": "animal: hunting / preying" },
        { "zh": "动物：嬉戏", "en": "animal: playing" },
        { "zh": "动物：呼唤", "en": "animal: calling / vocalizing" },
        { "zh": "动物：进食", "en": "animal: eating" },
        { "zh": "动物：睡觉", "en": "animal: sleeping" },
        { "zh": "动物：警惕", "en": "animal: alert / watchful" },
        { "zh": "动物：咆哮/嘶吼", "en": "animal: roaring / snarling" },
        { "zh": "动物：摇尾巴", "en": "animal: wagging tail" },
        { "zh": "动物：舔舐", "en": "animal: licking" },
        { "zh": "动物：嗅探", "en": "animal: sniffing" },
        { "zh": "动物：踱步", "en": "animal: pacing" },
        { "zh": "动物：梳理毛发", "en": "animal: grooming" }
      ]
    },
    {
      "name": "静态画面动态化 (Static to Dynamic)",
      "tags": [
        { "zh": "画面元素轻微闪烁", "en": "subtle flickering elements" },
        { "zh": "画面元素缓慢移动", "en": "slow moving elements" },
        { "zh": "背景视差滚动", "en": "background parallax scroll" },
        { "zh": "前景元素位移", "en": "foreground element shift" },
        { "zh": "局部放大/缩小动画", "en": "localized zoom in/out animation" },
        { "zh": "Ken Burns效果 (推拉摇移)", "en": "Ken Burns effect (pan/zoom)" },
        { "zh": "光线/阴影动态变化", "en": "dynamic light/shadow changes" },
        { "zh": "景深动画", "en": "animated depth of field" },
        { "zh": "烟雾/粒子效果添加", "en": "smoke/particle effects added" },
        { "zh": "水面波纹动画", "en": "animated water ripples" },
        { "zh": "云朵缓慢漂移", "en": "slow cloud drift" },
        { "zh": "火焰跳动效果", "en": "flickering flame effect" },
        { "zh": "雨滴/雪花飘落", "en": "falling rain/snowflakes" },
        { "zh": "风吹草动/树叶摇曳", "en": "wind blowing grass/leaves swaying" },
        { "zh": "人物头发/衣物飘动", "en": "character hair/clothing flapping" },
        { "zh": "呼吸动画 (人物/动物)", "en": "breathing animation (human/animal)" },
        { "zh": "眼睛眨动动画", "en": "blinking eye animation" },
        { "zh": "嘴巴微动 (呼吸/低语)", "en": "subtle mouth movement (breathing/whisper)" },
        { "zh": "面部表情细微调整", "en": "subtle facial expression adjustments" },
        { "zh": "环境光反射变化", "en": "environmental light reflection change" },
        { "zh": "屏幕叠加层动画", "en": "screen overlay animation" },
        { "zh": "数字故障/信号干扰", "en": "digital glitch / signal interference" },
        { "zh": "模糊效果动态化", "en": "dynamic blur effect" },
        { "zh": "锐化效果动态化", "en": "dynamic sharpening effect" },
        { "zh": "色彩渐变/循环动画", "en": "color gradient / loop animation" },
        { "zh": "辉光/发光效果", "en": "bloom / glow effect" },
        { "zh": "焦点切换动画", "en": "focus shift animation" },
        { "zh": "前景/背景元素的循环动画", "en": "looping animation for foreground/background elements" },
        { "zh": "2.5D效果 (伪3D动画)", "en": "2.5D effect (pseudo 3D animation)" },
        { "zh": "物体缩放/旋转动画", "en": "object scale/rotation animation" },
        { "zh": "局部扭曲效果", "en": "localized distortion effect" },
        { "zh": "波浪形动画", "en": "wavy animation" },
        { "zh": "流光溢彩", "en": "shimmering effect / light streaks" },
        { "zh": "光效动画 (如灯光闪烁)", "en": "lighting animation (e.g., flickering lights)" },
        { "zh": "纹理动画", "en": "texture animation" },
        { "zh": "画面噪点/胶片颗粒增加", "en": "added film grain / screen noise" },
        { "zh": "模拟摄像头抖动", "en": "simulated camera shake" },
        { "zh": "赛博朋克线框叠加", "en": "cyberpunk wireframe overlay" },
        { "zh": "扫描线效果", "en": "scanline effect" },
        { "zh": "VHS失真效果", "en": "VHS distortion effect" },
        { "zh": "水彩画墨迹扩散", "en": "watercolor ink bleed" },
        { "zh": "像素化过渡", "en": "pixelation transition" },
        { "zh": "霓虹灯呼吸效果", "en": "neon breathing effect" },
        { "zh": "能量波动", "en": "energy pulsating" },
        { "zh": "环境雾气/蒸汽效果", "en": "environmental mist/steam effect" },
        { "zh": "倒影动态变化", "en": "dynamic reflection changes" },
        { "zh": "地面湿润反光", "en": "wet ground reflections" },
        { "zh": "屏幕裂纹/破碎动画", "en": "screen crack / shattering animation" },
        { "zh": "粒子爆炸/碎屑飞溅", "en": "particle burst / debris scattering" }
      ]
    },
    {
      "name": "剪辑技巧与节奏 (Editing Techniques & Pacing)",
      "tags": [
        { "zh": "快节奏剪辑", "en": "fast-paced editing" },
        { "zh": "慢节奏剪辑", "en": "slow-paced editing" },
        { "zh": "中速节奏", "en": "medium pacing" },
        { "zh": "蒙太奇", "en": "montage editing" },
        { "zh": "平行剪辑", "en": "parallel editing" },
        { "zh": "交叉剪辑", "en": "cross-cutting" },
        { "zh": "J-Cut (音先入)", "en": "J-cut (audio leading)" },
        { "zh": "L-Cut (音后出)", "en": "L-cut (audio lingering)" },
        { "zh": "匹配剪辑 (动作衔接)", "en": "match on action" },
        { "zh": "匹配剪辑 (视觉衔接)", "en": "match cut (visual)" },
        { "zh": "跳切", "en": "jump cut" },
        { "zh": "省略剪辑", "en": "ellipsis (editing)" },
        { "zh": "扩展时间", "en": "expanded time" },
        { "zh": "压缩时间", "en": "compressed time" },
        { "zh": "闪回", "en": "flashback" },
        { "zh": "闪进", "en": "flashforward" },
        { "zh": "节奏升降", "en": "pacing shift" },
        { "zh": "视觉音乐性", "en": "visual musicality" },
        { "zh": "剪辑点", "en": "cut points" },
        { "zh": "节奏感", "en": "rhythmic editing" },
        { "zh": "情绪剪辑", "en": "emotional editing" },
        { "zh": "叙事剪辑", "en": "narrative editing" },
        { "zh": "概念剪辑", "en": "conceptual editing" },
        { "zh": "声音设计驱动", "en": "sound design driven" },
        { "zh": "音乐驱动", "en": "music driven" },
        { "zh": "视觉节拍", "en": "visual beats" },
        { "zh": "重复剪辑", "en": "repetition editing" },
        { "zh": "冲突剪辑", "en": "conflict editing" },
        { "zh": "反转剪辑", "en": "reverse editing" },
        { "zh": "非线性剪辑", "en": "non-linear editing" },
        { "zh": "倒叙", "en": "anachrony" },
        { "zh": "画外音", "en": "voiceover (VO)" },
        { "zh": "旁白", "en": "narration" },
        { "zh": "对白剪辑", "en": "dialogue editing" },
        { "zh": "环境音", "en": "ambient sound" },
        { "zh": "音效", "en": "sound effects (SFX)" },
        { "zh": "配乐", "en": "musical score" },
        { "zh": "声画分离", "en": "audio-visual separation" },
        { "zh": "音画同步", "en": "audio-visual synchronization" },
        { "zh": "混音", "en": "audio mixing" },
        { "zh": "高潮迭起", "en": "climax building" },
        { "zh": "悬念营造", "en": "suspense building" },
        { "zh": "过渡衔接", "en": "smooth transitions" },
        { "zh": "故事板", "en": "storyboard visualization" },
        { "zh": "预演", "en": "pre-visualization (pre-vis)" },
        { "zh": "电影语言运用", "en": "cinematic language usage" },
        { "zh": "叙事清晰", "en": "clear narrative flow" },
        { "zh": "信息密度高", "en": "high information density" },
        { "zh": "节奏感强", "en": "strong sense of rhythm" },
        { "zh": "视觉冲击力", "en": "strong visual impact" },
        { "zh": "内聚焦", "en": "internal focus" },
        { "zh": "外聚焦", "en": "external focus" },
        { "zh": "视角变化", "en": "perspective shift" },
        { "zh": "情绪曲线", "en": "emotional arc" },
        { "zh": "叙事结构", "en": "narrative structure" }
      ]
    },
    {
      "name": "渲染与画质 (Rendering & Quality)",
      "tags": [
        { "zh": "4K分辨率", "en": "4K resolution" },
        { "zh": "8K分辨率", "en": "8K resolution" },
        { "zh": "全高清 (1080p)", "en": "Full HD (1080p)" },
        { "zh": "超高清 (UHD)", "en": "Ultra HD (UHD)" },
        { "zh": "60fps帧率", "en": "60fps framerate" },
        { "zh": "24fps电影感", "en": "24fps cinematic look" },
        { "zh": "30fps标准", "en": "30fps standard" },
        { "zh": "真实感渲染", "en": "photorealistic rendering" },
        { "zh": "物理渲染 (PBR)", "en": "PBR (Physically Based Rendering)" },
        { "zh": "电影级画质", "en": "cinematic quality" },
        { "zh": "高质量", "en": "high quality" },
        { "zh": "画质清晰", "en": "sharp image quality" },
        { "zh": "细节丰富", "en": "rich in detail" },
        { "zh": "高保真", "en": "high fidelity" },
        { "zh": "低保真", "en": "low fidelity" },
        { "zh": "纹理细腻", "en": "fine textures" },
        { "zh": "光影逼真", "en": "realistic lighting and shadows" },
        { "zh": "抗锯齿", "en": "anti-aliasing" },
        { "zh": "平滑边沿", "en": "smooth edges" },
        { "zh": "噪点控制", "en": "noise control" },
        { "zh": "无损压缩", "en": "lossless compression" },
        { "zh": "有损压缩", "en": "lossy compression" },
        { "zh": "色彩深度", "en": "color depth" },
        { "zh": "色彩精确", "en": "color accurate" },
        { "zh": "色彩失真", "en": "color distortion" },
        { "zh": "色彩溢出", "en": "color bleeding" },
        { "zh": "动态范围广", "en": "wide dynamic range" },
        { "zh": "比特率高", "en": "high bitrate" },
        { "zh": "比特率低", "en": "low bitrate" },
        { "zh": "编码效率高", "en": "high encoding efficiency" },
        { "zh": "格式优化", "en": "format optimized" },
        { "zh": "输出优化", "en": "output optimized" },
        { "zh": "专业级", "en": "professional grade" },
        { "zh": "电影制片厂标准", "en": "studio standard" },
        { "zh": "广播级", "en": "broadcast quality" },
        { "zh": "Web优化", "en": "web optimized" },
        { "zh": "移动设备优化", "en": "mobile optimized" },
        { "zh": "流媒体优化", "en": "streaming optimized" },
        { "zh": "实时渲染", "en": "real-time rendering" },
        { "zh": "离线渲染", "en": "offline rendering" },
        { "zh": "云渲染", "en": "cloud rendering" },
        { "zh": "GPU渲染", "en": "GPU rendering" },
        { "zh": "CPU渲染", "en": "CPU rendering" },
        { "zh": "路径追踪渲染", "en": "path tracing rendering" },
        { "zh": "体积渲染", "en": "volume rendering" },
        { "zh": "全局光照", "en": "global illumination" },
        { "zh": "环境光遮蔽", "en": "ambient occlusion" },
        { "zh": "屏幕空间反射", "en": "screen space reflection" },
        { "zh": "焦散", "en": "caustics" },
        { "zh": "次表面散射", "en": "subsurface scattering" },
        { "zh": "运动模糊渲染", "en": "motion blur rendering" },
        { "zh": "景深渲染", "en": "depth of field rendering" },
        { "zh": "噪声着色器", "en": "noise shader" },
        { "zh": "边缘检测", "en": "edge detection" },
        { "zh": "轮廓线", "en": "outline rendering" },
        { "zh": "卡通着色器", "en": "toon shader" }
      ]
    }
  ]
});